syntax = "proto3";
import "erp.proto";
package manufacturing;

// Go 包路径配置，指定生成的 Go 代码存放位置
option go_package = "ttpos-bmp/app/ttpos-erp/api/manufacturing";


message BomInfo {
  string item_code = 1;      // 商品编码
  string bom_name = 2;      // 名称
  string uom = 3;      // 单位
  string company = 4;      // 公司
  double  quantity = 5;      // 数量
  bool is_active = 6;      // 是否激活
  bool is_default = 7;      // 是否默认
  repeated BomItem items = 8;      // 物品列表，列表查询服务不返回该字段，详情查询服务返回该字段
}

message BomItem {
  string item_code = 1;      // 物品编码
  double rate = 2;      // 物品价格
  double qty = 3;      // 物品数量
  string uom = 4;      // 物品单位
}


message GetBomListReq {
  string company_abbr = 1;      // 公司简称，必填
  string branch = 2;      // 分支名称，可选
  string item_code = 3;      // 物品编码，可选
  bool is_active = 4;    //是否激活 ，可选
  bool is_default = 5; //是否默认，可选
  string sub_company_abbr = 6; // 门店公司简称，可选。  sub_company_abbr(门店公司简称) ,会过滤  permission rule 下的物品，黑名单优先级高。
}

message GetBomListResp {
  repeated BomInfo bom_list = 1; // 物品列表
}

message GetBomReq {
  string bom_name = 1; // BOM名称，必填
}

message GetBomResp {
  BomInfo bom_info = 1; // BOM信息
}


message SaveBomReq {
  string item_code = 1 ; //商品编码，必填
  string company_abbr = 2; //公司简称，必填
  double quantity = 3; //数量，必填
  string uom = 4; //单位，可选
  bool is_active = 5;    //是否激活 ，可选
  bool is_default = 6; //是否默认，可选
  repeated BomItem items = 7; //物品列表，必填
}

message SaveBomResp {
  string bom_name = 1; //BOM名称
}

service BomService {
  // 获取BOM列表
  // 输入条件如果未包含company 则会返回全量数据，如需要只显示无company 约束的数据，需要自行过滤结果中 company 为空的数据
  // 参数：查询条件
  // 返回：BOM列表
  rpc GetBomList(GetBomListReq) returns (erp.ResponseInfo);

  // 获取单个BOM
  // 参数：BOM名称
  // 返回：BOM详情
  rpc GetBom(GetBomReq) returns (erp.ResponseInfo);

  // 保存BOM
  // 参数：BOM信息
  // 返回：操作结果
  rpc SaveBom(SaveBomReq) returns (erp.ResponseInfo);
}
