syntax = "proto3";
import "erp.proto";
package manufacturing;

// Go 包路径配置，指定生成的 Go 代码存放位置
option go_package = "ttpos-bmp/app/ttpos-erp/api/manufacturing";


message BomInfo {
  string item_code = 1;      // 商品编码
  string uom = 2;      // 单位
  string company = 3;      // 公司
  float  quantity = 4;      // 数量
  bool is_active = 5;      // 是否激活
  bool is_default = 6;      // 是否默认
  repeated BomItem items = 7;      // 物品列表
}

message BomItem {
  string item_code = 1;      // 物品编码
  float rate = 2;      // 物品名称
  float qty = 3;      // 物品数量
  string uom = 4;      // 物品单位
}


message GetBomListReq {
  string company_abbr = 1;      // 公司简称，必填
  string branch = 2;      // 分支名称，可选
  string item_code = 3;      // 物品编码，可选
  string item_name = 4;      // 物品名称，可选，模糊查询
}


message GetBomListResp {
  repeated BomInfo bom_list = 1; // 物品列表
}

service BomService {
  // 获取BOM列表
  // 参数：查询条件
  // 返回：BOM列表
  rpc GetBomList(GetBomListReq) returns (erp.ResponseInfo);
}
