// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package crm

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// CrmServiceClient is the client API for CrmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrmServiceClient interface {
	// 获取联系人列表
	// 参数：查询条件
	// 返回：联系人列表
	GetContactList(ctx context.Context, in *GetContactListReq, opts ...grpc.CallOption) (*GetContactListResp, error)
	// 根据名称获取联系人详情
	// 参数：联系人名称
	// 返回：联系人详细信息
	GetContact(ctx context.Context, in *GetContactReq, opts ...grpc.CallOption) (*GetContactResp, error)
	// 创建新联系人
	// 参数：联系人信息
	// 返回：创建结果
	CreateContact(ctx context.Context, in *CreateContactReq, opts ...grpc.CallOption) (*CreateContactResp, error)
	// 更新联系人信息
	// 参数：联系人名称和更新数据
	// 返回：更新结果
	UpdateContact(ctx context.Context, in *UpdateContactReq, opts ...grpc.CallOption) (*UpdateContactResp, error)
	// 删除联系人
	// 参数：联系人名称
	// 返回：删除结果
	DeleteContact(ctx context.Context, in *DeleteContactReq, opts ...grpc.CallOption) (*DeleteContactResp, error)
	// 获取地址列表
	// 参数：查询条件
	// 返回：地址列表
	GetAddressList(ctx context.Context, in *GetAddressListReq, opts ...grpc.CallOption) (*GetAddressListResp, error)
	// 根据名称获取地址详情
	// 参数：地址名称
	// 返回：地址详细信息
	GetAddress(ctx context.Context, in *GetAddressReq, opts ...grpc.CallOption) (*GetAddressResp, error)
	// 创建新地址
	// 参数：地址信息
	// 返回：创建结果
	CreateAddress(ctx context.Context, in *CreateAddressReq, opts ...grpc.CallOption) (*CreateAddressResp, error)
	// 更新地址信息
	// 参数：地址名称和更新数据
	// 返回：更新结果
	UpdateAddress(ctx context.Context, in *UpdateAddressReq, opts ...grpc.CallOption) (*UpdateAddressResp, error)
	// 删除地址
	// 参数：地址名称
	// 返回：删除结果
	DeleteAddress(ctx context.Context, in *DeleteAddressReq, opts ...grpc.CallOption) (*DeleteAddressResp, error)
}

type crmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrmServiceClient(cc grpc.ClientConnInterface) CrmServiceClient {
	return &crmServiceClient{cc}
}

func (c *crmServiceClient) GetContactList(ctx context.Context, in *GetContactListReq, opts ...grpc.CallOption) (*GetContactListResp, error) {
	out := new(GetContactListResp)
	err := c.cc.Invoke(ctx, "/crm.CrmService/GetContactList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crmServiceClient) GetContact(ctx context.Context, in *GetContactReq, opts ...grpc.CallOption) (*GetContactResp, error) {
	out := new(GetContactResp)
	err := c.cc.Invoke(ctx, "/crm.CrmService/GetContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crmServiceClient) CreateContact(ctx context.Context, in *CreateContactReq, opts ...grpc.CallOption) (*CreateContactResp, error) {
	out := new(CreateContactResp)
	err := c.cc.Invoke(ctx, "/crm.CrmService/CreateContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crmServiceClient) UpdateContact(ctx context.Context, in *UpdateContactReq, opts ...grpc.CallOption) (*UpdateContactResp, error) {
	out := new(UpdateContactResp)
	err := c.cc.Invoke(ctx, "/crm.CrmService/UpdateContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crmServiceClient) DeleteContact(ctx context.Context, in *DeleteContactReq, opts ...grpc.CallOption) (*DeleteContactResp, error) {
	out := new(DeleteContactResp)
	err := c.cc.Invoke(ctx, "/crm.CrmService/DeleteContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crmServiceClient) GetAddressList(ctx context.Context, in *GetAddressListReq, opts ...grpc.CallOption) (*GetAddressListResp, error) {
	out := new(GetAddressListResp)
	err := c.cc.Invoke(ctx, "/crm.CrmService/GetAddressList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crmServiceClient) GetAddress(ctx context.Context, in *GetAddressReq, opts ...grpc.CallOption) (*GetAddressResp, error) {
	out := new(GetAddressResp)
	err := c.cc.Invoke(ctx, "/crm.CrmService/GetAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crmServiceClient) CreateAddress(ctx context.Context, in *CreateAddressReq, opts ...grpc.CallOption) (*CreateAddressResp, error) {
	out := new(CreateAddressResp)
	err := c.cc.Invoke(ctx, "/crm.CrmService/CreateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crmServiceClient) UpdateAddress(ctx context.Context, in *UpdateAddressReq, opts ...grpc.CallOption) (*UpdateAddressResp, error) {
	out := new(UpdateAddressResp)
	err := c.cc.Invoke(ctx, "/crm.CrmService/UpdateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crmServiceClient) DeleteAddress(ctx context.Context, in *DeleteAddressReq, opts ...grpc.CallOption) (*DeleteAddressResp, error) {
	out := new(DeleteAddressResp)
	err := c.cc.Invoke(ctx, "/crm.CrmService/DeleteAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrmServiceServer is the server API for CrmService service.
// All implementations must embed UnimplementedCrmServiceServer
// for forward compatibility
type CrmServiceServer interface {
	// 获取联系人列表
	// 参数：查询条件
	// 返回：联系人列表
	GetContactList(context.Context, *GetContactListReq) (*GetContactListResp, error)
	// 根据名称获取联系人详情
	// 参数：联系人名称
	// 返回：联系人详细信息
	GetContact(context.Context, *GetContactReq) (*GetContactResp, error)
	// 创建新联系人
	// 参数：联系人信息
	// 返回：创建结果
	CreateContact(context.Context, *CreateContactReq) (*CreateContactResp, error)
	// 更新联系人信息
	// 参数：联系人名称和更新数据
	// 返回：更新结果
	UpdateContact(context.Context, *UpdateContactReq) (*UpdateContactResp, error)
	// 删除联系人
	// 参数：联系人名称
	// 返回：删除结果
	DeleteContact(context.Context, *DeleteContactReq) (*DeleteContactResp, error)
	// 获取地址列表
	// 参数：查询条件
	// 返回：地址列表
	GetAddressList(context.Context, *GetAddressListReq) (*GetAddressListResp, error)
	// 根据名称获取地址详情
	// 参数：地址名称
	// 返回：地址详细信息
	GetAddress(context.Context, *GetAddressReq) (*GetAddressResp, error)
	// 创建新地址
	// 参数：地址信息
	// 返回：创建结果
	CreateAddress(context.Context, *CreateAddressReq) (*CreateAddressResp, error)
	// 更新地址信息
	// 参数：地址名称和更新数据
	// 返回：更新结果
	UpdateAddress(context.Context, *UpdateAddressReq) (*UpdateAddressResp, error)
	// 删除地址
	// 参数：地址名称
	// 返回：删除结果
	DeleteAddress(context.Context, *DeleteAddressReq) (*DeleteAddressResp, error)
	mustEmbedUnimplementedCrmServiceServer()
}

// UnimplementedCrmServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCrmServiceServer struct {
}

func (UnimplementedCrmServiceServer) GetContactList(context.Context, *GetContactListReq) (*GetContactListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContactList not implemented")
}
func (UnimplementedCrmServiceServer) GetContact(context.Context, *GetContactReq) (*GetContactResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContact not implemented")
}
func (UnimplementedCrmServiceServer) CreateContact(context.Context, *CreateContactReq) (*CreateContactResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContact not implemented")
}
func (UnimplementedCrmServiceServer) UpdateContact(context.Context, *UpdateContactReq) (*UpdateContactResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateContact not implemented")
}
func (UnimplementedCrmServiceServer) DeleteContact(context.Context, *DeleteContactReq) (*DeleteContactResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContact not implemented")
}
func (UnimplementedCrmServiceServer) GetAddressList(context.Context, *GetAddressListReq) (*GetAddressListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressList not implemented")
}
func (UnimplementedCrmServiceServer) GetAddress(context.Context, *GetAddressReq) (*GetAddressResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddress not implemented")
}
func (UnimplementedCrmServiceServer) CreateAddress(context.Context, *CreateAddressReq) (*CreateAddressResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAddress not implemented")
}
func (UnimplementedCrmServiceServer) UpdateAddress(context.Context, *UpdateAddressReq) (*UpdateAddressResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAddress not implemented")
}
func (UnimplementedCrmServiceServer) DeleteAddress(context.Context, *DeleteAddressReq) (*DeleteAddressResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAddress not implemented")
}
func (UnimplementedCrmServiceServer) mustEmbedUnimplementedCrmServiceServer() {}

// UnsafeCrmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrmServiceServer will
// result in compilation errors.
type UnsafeCrmServiceServer interface {
	mustEmbedUnimplementedCrmServiceServer()
}

func RegisterCrmServiceServer(s *grpc.Server, srv CrmServiceServer) {
	s.RegisterService(&_CrmService_serviceDesc, srv)
}

func _CrmService_GetContactList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmServiceServer).GetContactList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crm.CrmService/GetContactList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmServiceServer).GetContactList(ctx, req.(*GetContactListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrmService_GetContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmServiceServer).GetContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crm.CrmService/GetContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmServiceServer).GetContact(ctx, req.(*GetContactReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrmService_CreateContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContactReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmServiceServer).CreateContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crm.CrmService/CreateContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmServiceServer).CreateContact(ctx, req.(*CreateContactReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrmService_UpdateContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContactReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmServiceServer).UpdateContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crm.CrmService/UpdateContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmServiceServer).UpdateContact(ctx, req.(*UpdateContactReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrmService_DeleteContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContactReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmServiceServer).DeleteContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crm.CrmService/DeleteContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmServiceServer).DeleteContact(ctx, req.(*DeleteContactReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrmService_GetAddressList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmServiceServer).GetAddressList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crm.CrmService/GetAddressList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmServiceServer).GetAddressList(ctx, req.(*GetAddressListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrmService_GetAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmServiceServer).GetAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crm.CrmService/GetAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmServiceServer).GetAddress(ctx, req.(*GetAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrmService_CreateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmServiceServer).CreateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crm.CrmService/CreateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmServiceServer).CreateAddress(ctx, req.(*CreateAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrmService_UpdateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmServiceServer).UpdateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crm.CrmService/UpdateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmServiceServer).UpdateAddress(ctx, req.(*UpdateAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrmService_DeleteAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmServiceServer).DeleteAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crm.CrmService/DeleteAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmServiceServer).DeleteAddress(ctx, req.(*DeleteAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CrmService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crm.CrmService",
	HandlerType: (*CrmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContactList",
			Handler:    _CrmService_GetContactList_Handler,
		},
		{
			MethodName: "GetContact",
			Handler:    _CrmService_GetContact_Handler,
		},
		{
			MethodName: "CreateContact",
			Handler:    _CrmService_CreateContact_Handler,
		},
		{
			MethodName: "UpdateContact",
			Handler:    _CrmService_UpdateContact_Handler,
		},
		{
			MethodName: "DeleteContact",
			Handler:    _CrmService_DeleteContact_Handler,
		},
		{
			MethodName: "GetAddressList",
			Handler:    _CrmService_GetAddressList_Handler,
		},
		{
			MethodName: "GetAddress",
			Handler:    _CrmService_GetAddress_Handler,
		},
		{
			MethodName: "CreateAddress",
			Handler:    _CrmService_CreateAddress_Handler,
		},
		{
			MethodName: "UpdateAddress",
			Handler:    _CrmService_UpdateAddress_Handler,
		},
		{
			MethodName: "DeleteAddress",
			Handler:    _CrmService_DeleteAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crm/crm.proto",
}
