syntax = "proto3";
import "erp.proto";

package selling;

option go_package = "ttpos-bmp/app/ttpos-erp/api/selling";

// PosProfileReq 查询Pos Profile请求消息
message PosProfileReq {
  // Pos Profile名称
  string name = 1;
  string company = 2; // 公司名称
  string company_abbr = 3; // 公司缩写, 必填
}

// PosProfile 查询Pos Profile响应消息
message PosProfile {
  // Pos Profile名称
  string name = 1;
  string company = 2; // 公司名称
  string branch = 3; // 分店名称
  string warehouse = 4; // 仓库名称
  string cashier = 5; // 收银员
}

message PosProfileListResp {
  // Pos Profile名称
  repeated PosProfile profile_list = 1;
}

message CreatePaymentAccountReq {
  string company_abbr = 1; // 公司缩写, 必填
  string payment_type = 2; // 支付类型，必填 Cash/Balance/Free Meal/Wechat Pay/Alipay/QR PromptPay
  string branch = 3; // 分店名称,可选
  string payment_source = 4; // 支付来源,可选 2= lianlianpay
}

message OpenPosEntryReq {
  string pos_profile_name = 1; // Pos Profile名称,必填
  string cashier_email = 2; // 收银员邮箱,必填
  string company_abbr = 3; // 公司缩写,必填
  int64 period_start_date = 5; // 周期开始时间,必填
  repeated OpenPosEntryDetail open_pos_entry_detail = 6; // 开帐详情,必填
  string branch = 7; // 分店名称,可选
}

message OpenPosEntryInfo {
  string open_pos_entry_name = 1; // 开帐的Pos Profile名称
  string pos_profile_name = 2; // Pos Profile名称
  string cashier_email = 3; // 收银员邮箱,必填
  string company_abbr = 4; // 公司缩写,必填
  string branch = 5; // 分店名称,可选
  repeated OpenPosEntryDetail open_pos_entry_detail = 6; // 开帐详情
}

message OpenPosEntryDetail {
  string mode_of_payment = 1; // 支付方式
  double opening_amount = 2; // 开帐金额
}

message OpenPosEntryResp {
  OpenPosEntryInfo open_pos_entry_info = 1;
}

message ClosePosEntryReq {
  string pos_open_entry_name = 1; // 开帐名称,必填
  int64 period_end_date = 2; // 结账时间,必填
  repeated ClosePosEntryDetail close_pos_entry_detail = 3; // 关帐详情,必填
}

message ClosePosEntryDetail {
  string mode_of_payment = 1; // 支付方式,必填
  double opening_amount = 2; // 开帐金额,必填
  double closing_amount = 3; // 关帐金额,必填
}

message ClosePosEntryInfo {
  string close_pos_entry_name = 1; // 关帐的Pos Profile名称
  string pos_profile_name = 2; // Pos Profile名称
  int64 period_end_date = 3; // 周期结束时间,必填
  repeated ClosePosEntryDetail close_pos_entry_detail = 4; // 关帐详情
}

message ClosePosEntryResp {
  ClosePosEntryInfo close_pos_entry_info = 1;
}

// SavePosInvoiceReq 保存POS发票请求消息
message SavePosInvoiceReq {
  string order_no = 1; // 订单号,必填 传ttpos的订单号
  string open_pos_entry_name = 2;                    // POS开帐名称,必填
  string company_abbr = 3;                        // 公司缩写,必填
  int64 posting_datetime = 4;                        // 过账日期时间 格式为时间戳，必填， 传交易时间过来
  int32 update_stock = 5;                         // 是否更新库存 必填，默认选1 0=不更新 1=更新
  string currency = 6;                            // 货币 标准缩写例如 CNY/THB/USD 必填
  string price_list_currency = 7;                 // 价格表货币 标准缩写例如 CNY/THB/USD 必填
  string branch = 8;                              // 分店 可选
  string customer_uuid = 9;                       // 客户,可选
  repeated PosInvoiceItem items = 10;             // 商品项目列表 必填
  repeated PosInvoiceItem material_items = 11;             // 原材料项目列表 必填
  repeated PosInvoiceTax taxes = 12;              // 税费列表 必填
  repeated PosInvoicePayment payments = 13;       // 付款列表 必填
  string amended_products_invoice_name = 14; // 反结账后，重新结账时填写原商品发票名称
  string amended_material_invoice_name = 15; // 反结账后，重新结账时填写原材料发票名称
}

// SavePosInvoiceResp 保存POS发票响应消息
message SavePosInvoiceResp {
  string products_invoice_name = 1; // 商品发票名称
  string material_invoice_name = 2; // 原材料发票名称
  string async_record_id = 3; // 异步记录ID
}

// PosInvoiceItem POS发票商品项目
message PosInvoiceItem {
  string item_code = 1;  // 商品编码，必填
  double qty = 2;         // 数量，必填
  double rate = 3;       // 单价，必填
  double amount = 4;     // 金额，必填
  string uom = 5; // 单位, 可选
  string description = 6;     // 描述, 可选。 如果是套餐内的商品，填写内容 “Sales in package:{套餐名称}”
  bool is_free_item = 7; // 是否免单商品, 可选, 默认false
}

// PosInvoiceTax POS发票税费
message PosInvoiceTax {
  double rate = 1;            // 税率，必填 费用填0
  double tax_amount = 2;      // 税费金额，必填
  string description = 3;     // 描述, 必填.例如 Tax/Service Fee/Payment Processing Fee/Delivery Fee
}

// PosInvoicePayment POS发票付款
message PosInvoicePayment {
  string mode_of_payment = 1; // 支付方式，必填 仅支持  Cash/Balance/Free Meal/LianlianPay-WeChat Pay/LianlianPay-Alipay/LianlianPay-QR PromptPay， 使用lianlianpay时，请加上前缀
  double amount = 2;          // 金额，必填
}

// ReturnPosInvoiceReq 退款POS发票请求消息
message ReturnPosInvoiceReq {
  string order_no = 1; // 退款订单号,必填 传ttpos的退款订单号
  string open_pos_entry_name = 2;                    // POS开帐名称,必填
  int64 posting_datetime = 3;                        // 过账日期时间 格式为时间戳，必填， 传交易时间过来
  string company_abbr = 4;                        // 公司缩写,必填
  string invoice_name = 5;                         // 销售发票
  repeated PosInvoiceItem items = 6;             // 商品项目列表 必填
  repeated PosInvoiceTax taxes = 7;              // 税费列表 必填
  repeated PosInvoicePayment payments = 8;       // 付款列表 必填
  int64 invoice_type = 9; // 发票类型 1=商品发票 2=原材料发票 异步模式下必填
}

// ReturnPosInvoiceResp 退款POS发票响应消息
message ReturnPosInvoiceResp {
  string invoice_name = 1; // 商品发票名称
  string async_record_id = 2; // 异步记录ID
}

// CancelPosInvoiceReq 取消POS发票请求消息，反结账时调用
message CancelPosInvoiceReq {
  string products_invoice_name = 1;                         // 商品销售发票，必填
  string material_invoice_name = 2;                         // 材料销售发票，必填
  string order_no = 3; // 订单号，传ttpos的订单号,异步模式下必填
  string open_pos_entry_name = 4; // POS开帐名称,异步模式下必填
}

message CancelPosInvoiceResp {
  string products_invoice_name = 1; // 商品发票名称
  string material_invoice_name = 2; // 材料发票名称
  string async_record_id = 3; // 异步记录ID
}


message ModeOfPayment {
  string name = 1; // 支付方式名称
}

message GetModeOfPaymentListReq {
  string company_abbr = 1; // 公司缩写,可选
  string branch = 2; // 分支名称,可选
}

message GetModeOfPaymentListResp {
  repeated ModeOfPayment mode_of_payment_list = 1; // 支付方式列表
}

// SellingService 服务定义
service SellingService {
  // 查询Pos Profile
  rpc GetPosProfileList (PosProfileReq) returns (erp.ResponseInfo);
  // 在erpnext 新增支付账号
  rpc CreatePaymentAccount (CreatePaymentAccountReq) returns (erp.ResponseInfo);
  //Pos 开帐
  rpc OpenPosEntry (OpenPosEntryReq) returns (erp.ResponseInfo);

  //Pos 关帐
  rpc ClosePosEntry (ClosePosEntryReq) returns (erp.ResponseInfo);

  //保存 Pos Invoice
  rpc SavePosInvoice (SavePosInvoiceReq) returns (erp.ResponseInfo);

  // 退款 Pos Invoice
  rpc ReturnPosInvoice (ReturnPosInvoiceReq) returns (erp.ResponseInfo);

  // 取消 Pos Invoice
  rpc CancelPosInvoice (CancelPosInvoiceReq) returns (erp.ResponseInfo);

  //获取支付方式
  rpc GetModeOfPaymentList (GetModeOfPaymentListReq) returns (erp.ResponseInfo);
}
