syntax = "proto3";
import "erp.proto";

package selling;

option go_package = "ttpos-bmp/app/ttpos-erp/api/selling";


// PosProfileReq 查询Pos Profile请求消息
message PosProfileReq {
  // Pos Profile名称
  string name = 1;
  string company = 2; // 公司名称
  string company_abbr = 3; // 公司缩写, 必填

}

// PosProfile 查询Pos Profile响应消息
message PosProfile {
  // Pos Profile名称
  string name = 1;
  string company = 2; // 公司名称
  string branch = 3; // 分店名称
  string warehouse = 4; // 仓库名称
}

message PosProfileListResp {
  // Pos Profile名称
  repeated PosProfile profile_list = 1;

}

message CreatePaymentAccountReq {
  string company_abbr = 1; // 公司缩写, 必填
  string payment_type = 2; // 支付类型，必填 Cash/Balance/Wechat Pay/Alipay
  string branch = 3; // 分店名称,可选
  string payment_source = 4; // 支付来源,可选 2= lianlianpay
}


message OpenPosEntryReq {
  string pos_profile_name = 1; // Pos Profile名称,必填
  string cashier_email = 2; // 收银员邮箱,必填
  string company_abbr = 3; // 公司缩写,必填
  int64 period_start_date = 5; // 周期开始时间,必填
  repeated OpenPosEntryDetail open_pos_entry_detail = 6; // 开帐详情,必填
  string branch = 7; // 分店名称,可选
}

message OpenPosEntryInfo {
  string open_pos_entry_name = 1; // 开帐的Pos Profile名称
  string pos_profile_name = 2; // Pos Profile名称
  string cashier_email = 3; // 收银员邮箱,必填
  string company_abbr = 4; // 公司缩写,必填
  string branch = 5; // 分店名称,可选
  repeated OpenPosEntryDetail open_pos_entry_detail = 6; // 开帐详情
}

message OpenPosEntryDetail {
  string mode_of_payment = 1; // 支付方式
  double opening_amount = 2; // 开帐金额
}

message OpenPosEntryResp {
  OpenPosEntryInfo open_pos_entry_info = 1;
}

message ClosePosEntryReq {
  string pos_profile_name = 1; // Pos Profile名称,必填
  string pos_open_entry_name = 2; // 开帐名称,必填
  int64 period_end_date = 3; // 结账时间,必填
  repeated ClosePosEntryDetail close_pos_entry_detail = 4; // 关帐详情,必填
}


message ClosePosEntryDetail {
  string mode_of_payment = 1; // 支付方式
  double opening_amount = 2; // 开帐金额
  double closing_amount = 3; // 关帐金额
}

message ClosePosEntryInfo {
  string close_pos_entry_name = 1; // 关帐的Pos Profile名称
  string pos_profile_name = 2; // Pos Profile名称
  int64 period_end_date = 3; // 周期结束时间,必填
  repeated ClosePosEntryDetail close_pos_entry_detail = 4; // 关帐详情
}

message ClosePosEntryResp {
  ClosePosEntryInfo close_pos_entry_info = 1;
}

// SellingService 服务定义
service SellingService {
  // 查询Pos Profile
  rpc GetPosProfileList (PosProfileReq) returns (erp.ResponseInfo);
  // 在erpnext 新增支付账号
  rpc CreatePaymentAccount (CreatePaymentAccountReq) returns (erp.ResponseInfo);
  //Pos 开帐
  rpc OpenPosEntry (OpenPosEntryReq) returns (erp.ResponseInfo);

  //Pos 关帐
  rpc ClosePosEntry (ClosePosEntryReq) returns (erp.ResponseInfo);
}
