/*
 * 厨显项目
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package resp

// CategoryProductInfo - 分类成品信息
type CategoryProductInfo struct {

	// 订单编号
	OrderNo string `json:"orderNo"`

	// 成品ID
	Id string `json:"id"`

	// 商品名
	Name string `json:"name"`

	// 商品描述
	Description string `json:"description"`

	// 商品数量
	Num int32 `json:"num"`

	// 送厨时间
	CreateTime int32 `json:"createTime"`
}
