/*
 * 厨显项目
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package resp

// CallList - 呼叫列表
type CallList struct {

	// 列表
	List []CallInfo `json:"list"`

	// 总页数
	TotalPage int32 `json:"totalPage"`

	// 页码
	PageNum int32 `json:"pageNum"`

	// 每页数量
	PageSize int32 `json:"pageSize"`
}
