/*
 * 厨显项目
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package resp

// Captcha - 验证码信息
type Captcha struct {

	// 验证码的base64图片
	Base64 string `json:"base64"`

	// 验证码签名，用于验证用户提交的验证码是否正确
	Sign string `json:"sign"`
}
