syntax = "proto3";
package api;
option go_package = "takeout/api";

message Address {
  string addressName = 1;
  string address = 2;
  string lat = 3;
  string lng = 4;
}

message Location {
  string addressName = 1; // 地址名称
  string address = 2;  // 详细地址
  string lat = 3;      // 纬度
  string lng = 4;      // 经度
  string contactName = 5; // 联系人
  string contactPhone = 6; // 联系电话
}

message ResponseInfo {
  string code = 1;
  string message = 2;
}

message EstimatePriceReq {
  string providerName = 1; // 外送渠道：skootar、grab
  repeated Address address = 2;
}

message EstimatePriceResp {
  ResponseInfo responseInfo = 1;
  float normalPrice = 2;
  float netPrice = 3;
  float discount = 4;
  float distance = 5;
  int32 tripDuration = 6;
}

message CreateOrderReq {
  string providerName = 1;           // 外送渠道：skootar、grab
  Location customer_location = 2;    // 客户位置信息
  Location merchant_location = 3;    // 商家位置信息
  string remark = 4;                 // 备注
  string callback_url = 5;           // 客户端回调地址
}

message CreateOrderResp {
  ResponseInfo responseInfo = 1;
  string order_id = 2;               // 订单ID
  int32 status = 3;                 // 0 - Canceled 已取消; 1 - New 新订单; 2 - Under review 正在审核中; 3 - Mission created 审核通过; 4 - Matching 正在匹配司机; 5 - Assigned 已分配司机; 6 - OTW to pickup 正在前往取货; 7 - OTW to delivery 正在前往送货; 8 - Pending 等待修改; 9 - Completed 已完成; 1 -  Invoice Created 已生成发票; 1 -  Paid 已支付服务费;
}

message ConfirmOrderReq {
  string providerName = 1;           // 外送渠道：skootar、grab
  string orderId = 2;  // 外送渠道订单ID
}

message ConfirmOrderResp {
  ResponseInfo responseInfo = 1;
}

message GetDriverLocationReq {
  string providerName = 1;           // 外送渠道：skootar、grab
  string orderId = 2;      // 外送渠道订单ID
}

message GetDriverLocationResp {
  ResponseInfo responseInfo = 1;           // 外送渠道：skootar、grab
  float lat = 2;      // 纬度
  float lng = 3;      // 经度
}

service TakeoutService {
  rpc EstimatePrice (EstimatePriceReq) returns (EstimatePriceResp) {}
  rpc CreateOrder (CreateOrderReq) returns (CreateOrderResp) {}
  rpc ConfirmOrder (ConfirmOrderReq) returns (ConfirmOrderResp) {}
  rpc GetDriverLocation(GetDriverLocationReq) returns (GetDriverLocationResp) {}
}