services:

  php:
    container_name: "saas-php-${APP_ID}"
    image: hitosea2020/php-fpm:1.0.6
    volumes:
      - ./docker:/var/docker
      - ./docker/php/conf.d/docker-vars.ini:/usr/local/etc/php/conf.d/docker-vars.ini
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - ./docker/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/supervisor/supervisor.conf:/etc/supervisor/conf.d/php.conf
      - ./docker/certificate:/var/certificate
      - ./admin/:/var/www
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-proxy
    networks:
      saas-network:
        ipv4_address: 10.0.0.10
      
  nginx:
    container_name: "saas-nginx-${APP_ID}"
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-}:80"
      - "${NGINX_SSL_PORT:-}:443"
    volumes:
      - ./docker/sysctl/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx:/etc/nginx/conf.d
      - ./admin/public:/var/www/public
    links:
      - php
      - golang
    depends_on:
      - php
      - golang
    restart: unless-stopped
    networks:
      saas-network:
        ipv4_address: 10.0.0.11
      bmp-network:

  db:
    container_name: "saas-db-${APP_ID}"
    image: "mysql:8.0"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d/
      - ./docker/mysql/repassword.sh:/etc/mysql/repassword.sh
      - ./docker/mysql/permissions.sh:/etc/mysql/permissions.sh
      - ./docker/mysql/create_saas.sh:/etc/mysql/create_saas.sh
      # - ./docker/mysql/init.d:/docker-entrypoint-initdb.d/
    ports:
      - "${DB_PORT_OPEN:-}:3306"
    environment:
      # 兼容旧的脚本
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DB_DATABASE}"
      MARIADB_USER: "${DB_USERNAME}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      MARIADB_PREFIX: "${DB_PREFIX}"
      MARIADB_HOST: "${DB_HOST}"
      MARIADB_PORT: "${DB_PORT}"
      # 兼容旧的脚本
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      TZ: "Asia/Bangkok"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    networks:
      saas-network:
        ipv4_address: 10.0.0.12
  
  redis-proxy:
    container_name: "saas-redis-proxy-${APP_ID}"
    image: hitosea2020/redis-proxy:latest
    volumes:
      - .env:/var/.env
    restart: always
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    networks:
      saas-network:
        ipv4_address: 10.0.0.17
    
  golang:
    container_name: "saas-golang-${APP_ID}"
    build:
      dockerfile: main/Dockerfile-dev
    image: ttpos-server-go
    volumes:
      - ./main/i18n:/var/www/i18n
      - .env:/var/.env
      - ./docker/certificate:/var/certificate
      - ./admin/public:/var/www/public
    restart: always
    networks:
      saas-network:
        ipv4_address: 10.0.0.18

networks:
  saas-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
  
  bmp-network:
    external: true
    name: ttpos-bmp_bmp-network