// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: setup/setup.proto

package setup

import (
	context "context"
	api "ttpos-bmp/app/ttpos-erp/api"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SetupService_InitShop_FullMethodName                = "/setup.SetupService/InitShop"
	SetupService_CreatePosUser_FullMethodName           = "/setup.SetupService/CreatePosUser"
	SetupService_CreateDefaultPosProfile_FullMethodName = "/setup.SetupService/CreateDefaultPosProfile"
)

// SetupServiceClient is the client API for SetupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SetupServiceClient interface {
	// 初始化店铺
	// 返回：初始化结果
	InitShop(ctx context.Context, in *InitShopReq, opts ...grpc.CallOption) (*api.ResponseInfo, error)
	// 创建.pos用户
	// 参数：用户邮箱
	// 返回：创建结果
	CreatePosUser(ctx context.Context, in *CreatePosUserReq, opts ...grpc.CallOption) (*api.ResponseInfo, error)
	// 创建默认pos profile
	CreateDefaultPosProfile(ctx context.Context, in *CreateDefaultPosProfileReq, opts ...grpc.CallOption) (*api.ResponseInfo, error)
}

type setupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSetupServiceClient(cc grpc.ClientConnInterface) SetupServiceClient {
	return &setupServiceClient{cc}
}

func (c *setupServiceClient) InitShop(ctx context.Context, in *InitShopReq, opts ...grpc.CallOption) (*api.ResponseInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.ResponseInfo)
	err := c.cc.Invoke(ctx, SetupService_InitShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setupServiceClient) CreatePosUser(ctx context.Context, in *CreatePosUserReq, opts ...grpc.CallOption) (*api.ResponseInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.ResponseInfo)
	err := c.cc.Invoke(ctx, SetupService_CreatePosUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setupServiceClient) CreateDefaultPosProfile(ctx context.Context, in *CreateDefaultPosProfileReq, opts ...grpc.CallOption) (*api.ResponseInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.ResponseInfo)
	err := c.cc.Invoke(ctx, SetupService_CreateDefaultPosProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SetupServiceServer is the server API for SetupService service.
// All implementations must embed UnimplementedSetupServiceServer
// for forward compatibility.
type SetupServiceServer interface {
	// 初始化店铺
	// 返回：初始化结果
	InitShop(context.Context, *InitShopReq) (*api.ResponseInfo, error)
	// 创建.pos用户
	// 参数：用户邮箱
	// 返回：创建结果
	CreatePosUser(context.Context, *CreatePosUserReq) (*api.ResponseInfo, error)
	// 创建默认pos profile
	CreateDefaultPosProfile(context.Context, *CreateDefaultPosProfileReq) (*api.ResponseInfo, error)
	mustEmbedUnimplementedSetupServiceServer()
}

// UnimplementedSetupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSetupServiceServer struct{}

func (UnimplementedSetupServiceServer) InitShop(context.Context, *InitShopReq) (*api.ResponseInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitShop not implemented")
}
func (UnimplementedSetupServiceServer) CreatePosUser(context.Context, *CreatePosUserReq) (*api.ResponseInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePosUser not implemented")
}
func (UnimplementedSetupServiceServer) CreateDefaultPosProfile(context.Context, *CreateDefaultPosProfileReq) (*api.ResponseInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDefaultPosProfile not implemented")
}
func (UnimplementedSetupServiceServer) mustEmbedUnimplementedSetupServiceServer() {}
func (UnimplementedSetupServiceServer) testEmbeddedByValue()                      {}

// UnsafeSetupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SetupServiceServer will
// result in compilation errors.
type UnsafeSetupServiceServer interface {
	mustEmbedUnimplementedSetupServiceServer()
}

func RegisterSetupServiceServer(s grpc.ServiceRegistrar, srv SetupServiceServer) {
	// If the following call pancis, it indicates UnimplementedSetupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SetupService_ServiceDesc, srv)
}

func _SetupService_InitShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitShopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetupServiceServer).InitShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetupService_InitShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetupServiceServer).InitShop(ctx, req.(*InitShopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetupService_CreatePosUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePosUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetupServiceServer).CreatePosUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetupService_CreatePosUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetupServiceServer).CreatePosUser(ctx, req.(*CreatePosUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetupService_CreateDefaultPosProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDefaultPosProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetupServiceServer).CreateDefaultPosProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetupService_CreateDefaultPosProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetupServiceServer).CreateDefaultPosProfile(ctx, req.(*CreateDefaultPosProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SetupService_ServiceDesc is the grpc.ServiceDesc for SetupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SetupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "setup.SetupService",
	HandlerType: (*SetupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitShop",
			Handler:    _SetupService_InitShop_Handler,
		},
		{
			MethodName: "CreatePosUser",
			Handler:    _SetupService_CreatePosUser_Handler,
		},
		{
			MethodName: "CreateDefaultPosProfile",
			Handler:    _SetupService_CreateDefaultPosProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "setup/setup.proto",
}
