zend_extension=opcache.so
; opcache settings
opcache.enable=1
; OPcache 内存消耗，以 MB 为单位。
opcache.memory_consumption=1024
; 用于储存 interned 字符串的内存。
opcache.interned_strings_buffer=64
; OPcache 可以缓存的文件数。
opcache.max_accelerated_files=100000
; 开启缓存校验器（启用这个可以保证 opcache 会检查脚本在修改后是否更新了）
opcache.validate_timestamps=0
; 多长时间检查一次文件改动，单位是秒。
opcache.revalidate_freq=2
; 启用快速关闭功能。
opcache.fast_shutdown=1
; 在 CLI 模式下启用 OPcache。
opcache.enable_cli=1
; 保存注释信息
opcache.save_comments=1
; 如果置为1，则每次调用file_exist() is_file() is_readable()函数时，
opcache.enable_file_override=1
; 文件更新保护机制
opcache.file_update_protection=0
; 如果opcache处于非active状态，当N秒后opcache将自动重启
opcache.force_restart_timeout=28800
; JIT 模式
opcache.jit_buffer_size=1024m
opcache.jit=function