# 使用官方Go语言镜像作为基础镜像
FROM golang:1.23 AS builder


#注意 context 要设置为上级目录,因为要拷贝别的模块的文件
#复制ttpos-bmp 模块 api
WORKDIR /ttpos-bmp
COPY  ttpos-bmp/go.mod ttpos-bmp/go.sum  ./
COPY  ttpos-bmp/app/ttpos-takeout/api  app/ttpos-takeout/api
COPY  ttpos-bmp/app/ttpos-erp/api  app/ttpos-erp/api
COPY  ttpos-bmp/app/ttpos-shop/api  app/ttpos-shop/api
COPY  ttpos-bmp/app/ttpos-manager/api  app/ttpos-manager/api
COPY  ttpos-bmp/app/ttpos-message/api  app/ttpos-message/api
COPY  ttpos-bmp/app/ttpos-websocket/api  app/ttpos-websocket/api

# 复制ttpos-api 模块
WORKDIR /ttpos-api
COPY  ttpos-api/  ./

# 设置工作目录
WORKDIR /app

# 复制go.mod和go.sum文件
COPY main/go.mod main/go.sum ./
# 设置代理
ENV GOPROXY=https://goproxy.cn,direct

# 检查依赖是否已下载，如果没有则下载
RUN if [ ! -f main ] || [ ! -x main ]; then \
        echo "下载Go依赖..."; \
        go mod download; \
    else \
        echo "发现已存在的Go依赖，跳过下载"; \
    fi

# 复制源代码
COPY main .

# 检查是否已经存在编译好的main文件，如果不存在则编译
RUN if [ ! -f main ] || [ ! -x main ]; then \
        echo "编译Go程序..."; \
        go build -o main ./main.go; \
    else \
        echo "发现已存在的main可执行文件，跳过编译"; \
    fi

# 添加执行权限
RUN chmod +x main

# 使用轻量级的镜像来运行应用
FROM ubuntu:latest

# 安装 ca-certificates 和 curl
RUN apt-get update && apt-get install -y ca-certificates curl golang

RUN apt-get clean && apt-get autoclean && apt-get autoremove --yes \
&& rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN apt-get clean && apt-get autoclean && apt-get autoremove --yes \
&& rm -rf /var/lib/{apt,dpkg,cache,log}/

# 设置工作目录
WORKDIR /var/www

# 复制编译好的二进制文件到新镜像
COPY --from=builder /app/main .

# 暴露应用运行的端口
EXPOSE 8080

# 运行应用
CMD ["./main"]