/*
 * 厨显项目
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package resp

// ServedProductHistory - 上菜历史
type ServedProductHistory struct {
	List []HistoryProductionOrder `json:"list"`

	// 总页数
	TotalPage int32 `json:"totalPage"`

	// 页码
	PageNum int32 `json:"pageNum"`

	// 每页大小
	PageSize int32 `json:"pageSize"`
}
