// 消息中心服务 Protobuf 定义文件
// 用于定义消息发送相关的 gRPC 服务接口和消息结构

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: message/message.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Message_SendMessage_FullMethodName      = "/message.Message/SendMessage"
	Message_GetMessageStatus_FullMethodName = "/message.Message/GetMessageStatus"
	Message_ResendMessage_FullMethodName    = "/message.Message/ResendMessage"
)

// MessageClient is the client API for Message service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 消息服务接口定义
// 提供消息发送、查询、重发等相关的 gRPC 服务方法
type MessageClient interface {
	// 发送消息
	// 接收消息发送请求，创建消息记录并提交到消息队列
	// 参数：消息发送请求参数
	// 返回：发送结果
	SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
	// 查询消息状态
	// 根据消息UUID查询消息的发送状态和详细信息
	// 参数：消息UUID
	// 返回：消息详细信息
	GetMessageStatus(ctx context.Context, in *GetMessageStatusReq, opts ...grpc.CallOption) (*GetMessageStatusResp, error)
	// 重发消息
	// 针对发送失败的消息，支持重新发送
	// 参数：消息UUID
	// 返回：重发结果
	ResendMessage(ctx context.Context, in *ResendMessageReq, opts ...grpc.CallOption) (*ResendMessageResp, error)
}

type messageClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageClient(cc grpc.ClientConnInterface) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResp)
	err := c.cc.Invoke(ctx, Message_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetMessageStatus(ctx context.Context, in *GetMessageStatusReq, opts ...grpc.CallOption) (*GetMessageStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageStatusResp)
	err := c.cc.Invoke(ctx, Message_GetMessageStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) ResendMessage(ctx context.Context, in *ResendMessageReq, opts ...grpc.CallOption) (*ResendMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResendMessageResp)
	err := c.cc.Invoke(ctx, Message_ResendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServer is the server API for Message service.
// All implementations must embed UnimplementedMessageServer
// for forward compatibility.
//
// 消息服务接口定义
// 提供消息发送、查询、重发等相关的 gRPC 服务方法
type MessageServer interface {
	// 发送消息
	// 接收消息发送请求，创建消息记录并提交到消息队列
	// 参数：消息发送请求参数
	// 返回：发送结果
	SendMessage(context.Context, *SendMessageReq) (*SendMessageResp, error)
	// 查询消息状态
	// 根据消息UUID查询消息的发送状态和详细信息
	// 参数：消息UUID
	// 返回：消息详细信息
	GetMessageStatus(context.Context, *GetMessageStatusReq) (*GetMessageStatusResp, error)
	// 重发消息
	// 针对发送失败的消息，支持重新发送
	// 参数：消息UUID
	// 返回：重发结果
	ResendMessage(context.Context, *ResendMessageReq) (*ResendMessageResp, error)
	mustEmbedUnimplementedMessageServer()
}

// UnimplementedMessageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageServer struct{}

func (UnimplementedMessageServer) SendMessage(context.Context, *SendMessageReq) (*SendMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMessageServer) GetMessageStatus(context.Context, *GetMessageStatusReq) (*GetMessageStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessageStatus not implemented")
}
func (UnimplementedMessageServer) ResendMessage(context.Context, *ResendMessageReq) (*ResendMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResendMessage not implemented")
}
func (UnimplementedMessageServer) mustEmbedUnimplementedMessageServer() {}
func (UnimplementedMessageServer) testEmbeddedByValue()                 {}

// UnsafeMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServer will
// result in compilation errors.
type UnsafeMessageServer interface {
	mustEmbedUnimplementedMessageServer()
}

func RegisterMessageServer(s grpc.ServiceRegistrar, srv MessageServer) {
	// If the following call pancis, it indicates UnimplementedMessageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Message_ServiceDesc, srv)
}

func _Message_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SendMessage(ctx, req.(*SendMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetMessageStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetMessageStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_GetMessageStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetMessageStatus(ctx, req.(*GetMessageStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_ResendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).ResendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_ResendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).ResendMessage(ctx, req.(*ResendMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Message_ServiceDesc is the grpc.ServiceDesc for Message service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Message_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Message_SendMessage_Handler,
		},
		{
			MethodName: "GetMessageStatus",
			Handler:    _Message_GetMessageStatus_Handler,
		},
		{
			MethodName: "ResendMessage",
			Handler:    _Message_ResendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message/message.proto",
}
