version: '3'
#中台中间件
services:
  nacos:
    image: nacos/nacos-server:v3.1.1
    container_name: "bmp-nacos-${APP_ID}"
    #    env_file:
    #      - ../.env
    environment:
      - MODE=standalone
      - NACOS_AUTH_TOKEN="${NACOS_AUTH_TOKEN}"
      - NACOS_AUTH_IDENTITY_KEY="${NACOS_AUTH_IDENTITY_KEY}"
      - NACOS_AUTH_IDENTITY_VALUE="${NACOS_AUTH_IDENTITY_VALUE}"
      - JVM_XMX=512m
      - JVM_XMS=256m
    ports:
      - "${NACOS_CONSOLE_PORT:-18080}:8080"
      - "${NACOS_SERVER_PORT:-8848}:8848"
      - "${NACOS_GRPC_PORT:-9848}:9848"
    networks:
      bmp-mid-network:
        ipv4_address: 10.0.11.10

  #以下是rocketmq 服务
  namesrv:
    image: apache/rocketmq:5.3.4
    container_name: "bmp-rmqnamesrv-${APP_ID}"
    ports:
      - "9876:9876"
    networks:
      bmp-mid-network:
        ipv4_address: 10.0.11.40
    command: sh mqnamesrv
    environment:
      - JVM_OPTS="-Xms256m -Xmx1g -Xss256k -XX:+UseG1GC -XX:MaxDirectMemorySize=1g"

  broker:
    image: apache/rocketmq:5.3.4
    container_name: "bmp-rmqbroker-${APP_ID}"
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      - NAMESRV_ADDR=namesrv:9876
      - JVM_OPTS="-Xms256m -Xmx1g -Xss256k -XX:+UseG1GC -XX:MaxDirectMemorySize=1g"
    depends_on:
      - namesrv
    networks:
      bmp-mid-network:
        ipv4_address: 10.0.11.41
    command: sh mqbroker -c /opt/rocketmq/conf/broker-dev.conf
    volumes:
      - ../docker/rocketmq/conf/broker-dev.conf:/opt/rocketmq/conf/broker-dev.conf
      # 添加持久化存储，挂载到宿主机有足够空间的目录
      # - ../docker/rocketmq/data:/home/rocketmq/store

  # mq-proxy:
  #   image: apache/rocketmq:5.3.4
  #   container_name: "bmp-rmqproxy-${APP_ID}"
  #   networks:
  #     bmp-mid-network:
  #       ipv4_address: 10.0.11.42
  #   depends_on:
  #     - broker
  #     - namesrv
  #   ports:
  #     - "28080:8080"
  #     - "28081:8081"
  #   restart: on-failure
  #   environment:
  #     - NAMESRV_ADDR=namesrv:9876
  #     - JVM_OPTS="-Xms256m -Xmx1g -Xss256k -XX:+UseG1GC -XX:MaxDirectMemorySize=1g"
  #   command: sh mqproxy
  mq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: "bmp-dashboard-${APP_ID}"
    networks:
      bmp-mid-network:
    depends_on:
      - namesrv
    ports:
      # 修改了映射端口号
      - "8082:8082"
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876 -Xms256m -Xmx512m
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.11.0
    container_name: "bmp-jaeger-${APP_ID}"
    networks:
      bmp-mid-network:
        ipv4_address: 10.0.11.43
    ports:
      - "16686:16686"
      - "4318:4318"
      - "4317:4317"

networks:
  bmp-mid-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.11.0/24
          gateway: 10.0.11.1