services:
  #中台服务模块
  bmp-takeout:
    container_name: "ttpos-bmp-takeout-${APP_ID}"
    image: hub.hitosea.com/ttpos-server/ttpos-server-takeout:${IMAGE_VERSION}
    environment:
      GRPC_ENDPOINTS: "${GRPC_ENDPOINTS}:14032"  #生产环境调成服务IP
      SW_AGENT_NAME: "ttpos-bmp-takeout"
      SW_AGENT_REPORTER_GRPC_BACKEND_SERVICE: "${SW_AGENT_REPORTER_GRPC_BACKEND_SERVICE:-127.0.0.1:11800}"
      SW_AGENT_REPORTER_GRPC_CHECK_INTERVAL: "${SW_AGENT_REPORTER_GRPC_CHECK_INTERVAL:-20}"
    volumes:
      - ./app/ttpos-takeout/manifest/config:/app/config  #生产环境根据需要调整
    restart: always
    ports:
      - "14031:14031"
      - "14032:14032"
    networks:
      bmp-network:
        ipv4_address: 10.0.10.40

  # 门店管理服务 (预留)
  bmp-shop:
    container_name: "ttpos-bmp-shop-${APP_ID}"
    image: hub.hitosea.com/ttpos-server/ttpos-server-shop:${IMAGE_VERSION}
    environment:
      GRPC_ENDPOINTS: "${GRPC_ENDPOINTS}:14012"  #生产环境调成服务IP
      SW_AGENT_NAME: "ttpos-bmp-shop"
      SW_AGENT_REPORTER_GRPC_BACKEND_SERVICE: "${SW_AGENT_REPORTER_GRPC_BACKEND_SERVICE:-127.0.0.1:11800}"
      SW_AGENT_REPORTER_GRPC_CHECK_INTERVAL: "${SW_AGENT_REPORTER_GRPC_CHECK_INTERVAL:-20}"
    volumes:
      - ./app/ttpos-shop/manifest/config:/app/config  #生产环境根据需要调整
    restart: always
    ports:
      - "14011:14011"
      - "14012:14012"
    networks:
      bmp-network:
        ipv4_address: 10.0.10.41

  #erp管理模块
  bmp-erp:
    container_name: "ttpos-bmp-erp-${APP_ID}"
    image: hub.hitosea.com/ttpos-server/ttpos-server-erp:${IMAGE_VERSION}
    environment:
      GRPC_ENDPOINTS: "${GRPC_ENDPOINTS}:14022"  #生产环境调成服务IP
      SW_AGENT_NAME: "ttpos-bmp-erp"
      SW_AGENT_REPORTER_GRPC_BACKEND_SERVICE: "${SW_AGENT_REPORTER_GRPC_BACKEND_SERVICE:-127.0.0.1:11800}"
      SW_AGENT_REPORTER_GRPC_CHECK_INTERVAL: "${SW_AGENT_REPORTER_GRPC_CHECK_INTERVAL:-20}"
    volumes:
      - ./app/ttpos-erp/manifest/config:/app/config  #生产环境根据需要调整
    restart: always
    ports:
      - "14021:14021"
      - "14022:14022"
    networks:
      bmp-network:
        ipv4_address: 10.0.10.42

  #云平台管理模块
  bmp-manager:
    container_name: "ttpos-bmp-manager-${APP_ID}"
    image: hub.hitosea.com/ttpos-server/ttpos-server-manager:${IMAGE_VERSION}
    environment:
      GRPC_ENDPOINTS: "${GRPC_ENDPOINTS}:14002"  #生产环境调成服务IP
      SW_AGENT_NAME: "ttpos-bmp-manager"
      SW_AGENT_REPORTER_GRPC_BACKEND_SERVICE: "${SW_AGENT_REPORTER_GRPC_BACKEND_SERVICE:-127.0.0.1:11800}"
      SW_AGENT_REPORTER_GRPC_CHECK_INTERVAL: "${SW_AGENT_REPORTER_GRPC_CHECK_INTERVAL:-20}"
    volumes:
      - ./app/ttpos-manager/manifest/config:/app/config  #生产环境根据需要调整
    restart: always
    ports:
      - "14001:14001"
      - "14002:14002"
    networks:
      bmp-network:
        ipv4_address: 10.0.10.43

networks:
  bmp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24
          gateway: 10.0.10.1