package fixture

import (
	"fmt"
	"strconv"
	"testing"
	"time"

	"github.com/golang-jwt/jwt/v5"
)

// JWTConfig holds configuration for JWT token generation.
type JWTConfig struct {
	Secret    string
	ExpiresAt time.Time
	Issuer    string
}

// DefaultJWTConfig returns a default JWT configuration for testing.
func DefaultJWTConfig() JWTConfig {
	return JWTConfig{
		Secret:    getEnv("JWT_SECRET", "test-secret-key-for-integration-tests"),
		ExpiresAt: time.Now().Add(24 * time.Hour),
		Issuer:    "ttpos-test",
	}
}

// TestClaims matches the server's auth.Claims structure exactly so that
// the server's JWT middleware can parse tokens generated by tests.
type TestClaims struct {
	Source         string `json:"source"`           // Terminal type: "cashier", "shop", etc.
	CompanyUUID    uint64 `json:"company_uuid"`     // Company identifier (uint64, not string)
	StaffUUID      uint64 `json:"staff_uuid"`       // Staff identifier (uint64, not string)
	DeviceId       string `json:"device_id"`        // Device serial number for device binding check
	IsRefreshToken bool   `json:"is_refresh_token"` // Must be false for access tokens
	jwt.RegisteredClaims
}

// GenerateToken generates a JWT token from the given claims.
func GenerateToken(tb testing.TB, claims TestClaims, secret string) string {
	tb.Helper()

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	tokenString, err := token.SignedString([]byte(secret))
	if err != nil {
		tb.Fatalf("failed to sign token: %v", err)
	}

	return tokenString
}

// GenerateStaffToken generates a JWT token for a cashier staff member.
// companyUUID and staffUUID are numeric strings (as returned by GenerateCompanyUUID or
// formatted staff.UUID). Pass an optional deviceId as the last argument for device binding.
func GenerateStaffToken(tb testing.TB, companyUUID, staffUUID, username string, roleID int64, deviceId ...string) string {
	tb.Helper()

	companyUUIDInt, _ := strconv.ParseUint(companyUUID, 10, 64)
	staffUUIDInt, _ := strconv.ParseUint(staffUUID, 10, 64)

	devId := ""
	if len(deviceId) > 0 {
		devId = deviceId[0]
	}

	config := DefaultJWTConfig()
	claims := TestClaims{
		Source:      "cashier",
		CompanyUUID: companyUUIDInt,
		StaffUUID:   staffUUIDInt,
		DeviceId:    devId,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(config.ExpiresAt),
			IssuedAt:  jwt.NewNumericDate(time.Now()),
			Issuer:    config.Issuer,
		},
	}

	return GenerateToken(tb, claims, config.Secret)
}

// GenerateAdminToken generates a JWT token with admin privileges.
func GenerateAdminToken(tb testing.TB, companyUUID string) string {
	tb.Helper()

	return GenerateStaffToken(tb, companyUUID, "0", "admin", 1)
}

// ParseToken parses a JWT token and returns the claims.
func ParseToken(tb testing.TB, tokenString, secret string) *TestClaims {
	tb.Helper()

	token, err := jwt.ParseWithClaims(tokenString, &TestClaims{}, func(token *jwt.Token) (interface{}, error) {
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
		}
		return []byte(secret), nil
	})

	if err != nil {
		tb.Fatalf("failed to parse token: %v", err)
	}

	if claims, ok := token.Claims.(*TestClaims); ok && token.Valid {
		return claims
	}

	tb.Fatalf("invalid token")
	return nil
}
