
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    pbentity:
      link: "mysql:$DB_USERNAME:$DB_PASSWORD@tcp($DB_HOST:$DB_PORT_OPEN)/takeout"
      path: "manifest/protobuf/pbentity"
      removePrefix: "takeout_"
      #tables: "order,products"
      package: "ttpos-bmp/app/ttpos-takeout/api/pbentity"
    pb:
      api: "api"
      ctrl: "internal/controller/rpc"
    dao:
      - link: "mysql:$DB_USERNAME:$DB_PASSWORD@tcp($DB_HOST:$DB_PORT_OPEN)/takeout"
        descriptionTag: true
        removePrefix: "takeout_"
        tablesEx: "schema_migrations"


  run:
    path: "./bin"
    extra: ""
    args: "all"
    watchPaths:
      - api/*.go
      - internal/*.go
  build:
    path: "./bin"
    system: linux
    arch: amd64
  docker:
    build: >-
      -a amd64 -s linux -p temp -ew
    tagName: ttpos-bmp-takeout
    tagPrefixes:
      - hub.hitosea.com

#注意db的格式跟link的不一样 用容器内网ip 端口
migrate-db-link: mysql://$DB_USERNAME:$DB_PASSWORD@tcp($DB_HOST:$DB_PORT)/takeout
migrate-db-link-open: mysql://$DB_USERNAME:$DB_PASSWORD@tcp($DB_HOST:$DB_PORT_OPEN)/takeout