// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: buying/buying.proto

package buying

import (
	reflect "reflect"
	sync "sync"
	api "ttpos-bmp/app/ttpos-erp/api"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSupplierListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyAbbr   string                 `protobuf:"bytes,1,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司缩写编码,必填"` // 公司缩写编码,必填
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupplierListReq) Reset() {
	*x = GetSupplierListReq{}
	mi := &file_buying_buying_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupplierListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupplierListReq) ProtoMessage() {}

func (x *GetSupplierListReq) ProtoReflect() protoreflect.Message {
	mi := &file_buying_buying_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupplierListReq.ProtoReflect.Descriptor instead.
func (*GetSupplierListReq) Descriptor() ([]byte, []int) {
	return file_buying_buying_proto_rawDescGZIP(), []int{0}
}

func (x *GetSupplierListReq) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

type GetSupplierListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupplierList  []*SupplierInfo        `protobuf:"bytes,1,rep,name=supplier_list,json=supplierList,proto3" json:"supplier_list,omitempty" dc:"供应商列表"` // 供应商列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupplierListResp) Reset() {
	*x = GetSupplierListResp{}
	mi := &file_buying_buying_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupplierListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupplierListResp) ProtoMessage() {}

func (x *GetSupplierListResp) ProtoReflect() protoreflect.Message {
	mi := &file_buying_buying_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupplierListResp.ProtoReflect.Descriptor instead.
func (*GetSupplierListResp) Descriptor() ([]byte, []int) {
	return file_buying_buying_proto_rawDescGZIP(), []int{1}
}

func (x *GetSupplierListResp) GetSupplierList() []*SupplierInfo {
	if x != nil {
		return x.SupplierList
	}
	return nil
}

type SupplierInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SupplierName      string                 `protobuf:"bytes,1,opt,name=supplier_name,json=supplierName,proto3" json:"supplier_name,omitempty" dc:"供应商名称"`                  // 供应商名称
	RepresentsCompany string                 `protobuf:"bytes,2,opt,name=represents_company,json=representsCompany,proto3" json:"represents_company,omitempty" dc:"供应商代表公司"` // 供应商代表公司
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SupplierInfo) Reset() {
	*x = SupplierInfo{}
	mi := &file_buying_buying_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplierInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplierInfo) ProtoMessage() {}

func (x *SupplierInfo) ProtoReflect() protoreflect.Message {
	mi := &file_buying_buying_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplierInfo.ProtoReflect.Descriptor instead.
func (*SupplierInfo) Descriptor() ([]byte, []int) {
	return file_buying_buying_proto_rawDescGZIP(), []int{2}
}

func (x *SupplierInfo) GetSupplierName() string {
	if x != nil {
		return x.SupplierName
	}
	return ""
}

func (x *SupplierInfo) GetRepresentsCompany() string {
	if x != nil {
		return x.RepresentsCompany
	}
	return ""
}

type GetPurchaseOrderReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PurchaseOrderName string                 `protobuf:"bytes,1,opt,name=purchase_order_name,json=purchaseOrderName,proto3" json:"purchase_order_name,omitempty" dc:"采购订单名称"` // 采购订单名称
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetPurchaseOrderReq) Reset() {
	*x = GetPurchaseOrderReq{}
	mi := &file_buying_buying_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchaseOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchaseOrderReq) ProtoMessage() {}

func (x *GetPurchaseOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_buying_buying_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchaseOrderReq.ProtoReflect.Descriptor instead.
func (*GetPurchaseOrderReq) Descriptor() ([]byte, []int) {
	return file_buying_buying_proto_rawDescGZIP(), []int{3}
}

func (x *GetPurchaseOrderReq) GetPurchaseOrderName() string {
	if x != nil {
		return x.PurchaseOrderName
	}
	return ""
}

type GetPurchaseOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseOrder *PurchaseOrderInfo     `protobuf:"bytes,1,opt,name=purchase_order,json=purchaseOrder,proto3" json:"purchase_order,omitempty" dc:"采购订单信息"` // 采购订单信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchaseOrderResp) Reset() {
	*x = GetPurchaseOrderResp{}
	mi := &file_buying_buying_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchaseOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchaseOrderResp) ProtoMessage() {}

func (x *GetPurchaseOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_buying_buying_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchaseOrderResp.ProtoReflect.Descriptor instead.
func (*GetPurchaseOrderResp) Descriptor() ([]byte, []int) {
	return file_buying_buying_proto_rawDescGZIP(), []int{4}
}

func (x *GetPurchaseOrderResp) GetPurchaseOrder() *PurchaseOrderInfo {
	if x != nil {
		return x.PurchaseOrder
	}
	return nil
}

type PurchaseOrderInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PurchaseOrderName string                 `protobuf:"bytes,1,opt,name=purchase_order_name,json=purchaseOrderName,proto3" json:"purchase_order_name,omitempty" dc:"采购订单名称"` // 采购订单名称
	SupplierName      string                 `protobuf:"bytes,2,opt,name=supplier_name,json=supplierName,proto3" json:"supplier_name,omitempty" dc:"供应商名称"`                   // 供应商名称
	PerReceived       float64                `protobuf:"fixed64,3,opt,name=per_received,json=perReceived,proto3" json:"per_received,omitempty" dc:"已接收比例"`                    // 已接收比例
	ScheduleDate      string                 `protobuf:"bytes,4,opt,name=schedule_date,json=scheduleDate,proto3" json:"schedule_date,omitempty" dc:"计划到货日期"`                  // 计划到货日期
	Items             []*PurchaseOrderItem   `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty" dc:"采购订单物品列表"`                                                  // 采购订单物品列表
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PurchaseOrderInfo) Reset() {
	*x = PurchaseOrderInfo{}
	mi := &file_buying_buying_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseOrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseOrderInfo) ProtoMessage() {}

func (x *PurchaseOrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_buying_buying_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseOrderInfo.ProtoReflect.Descriptor instead.
func (*PurchaseOrderInfo) Descriptor() ([]byte, []int) {
	return file_buying_buying_proto_rawDescGZIP(), []int{5}
}

func (x *PurchaseOrderInfo) GetPurchaseOrderName() string {
	if x != nil {
		return x.PurchaseOrderName
	}
	return ""
}

func (x *PurchaseOrderInfo) GetSupplierName() string {
	if x != nil {
		return x.SupplierName
	}
	return ""
}

func (x *PurchaseOrderInfo) GetPerReceived() float64 {
	if x != nil {
		return x.PerReceived
	}
	return 0
}

func (x *PurchaseOrderInfo) GetScheduleDate() string {
	if x != nil {
		return x.ScheduleDate
	}
	return ""
}

func (x *PurchaseOrderInfo) GetItems() []*PurchaseOrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PurchaseOrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemCode      string                 `protobuf:"bytes,1,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty" dc:"物品编码,必填"` // 物品编码,必填
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty" dc:"物品名称"`    // 物品名称
	StockUom      string                 `protobuf:"bytes,3,opt,name=stock_uom,json=stockUom,proto3" json:"stock_uom,omitempty" dc:"物品单位"`    // 物品单位
	Qty           float64                `protobuf:"fixed64,4,opt,name=qty,proto3" json:"qty,omitempty" dc:"物品数量,必填"`                         // 物品数量,必填
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseOrderItem) Reset() {
	*x = PurchaseOrderItem{}
	mi := &file_buying_buying_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseOrderItem) ProtoMessage() {}

func (x *PurchaseOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_buying_buying_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseOrderItem.ProtoReflect.Descriptor instead.
func (*PurchaseOrderItem) Descriptor() ([]byte, []int) {
	return file_buying_buying_proto_rawDescGZIP(), []int{6}
}

func (x *PurchaseOrderItem) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *PurchaseOrderItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *PurchaseOrderItem) GetStockUom() string {
	if x != nil {
		return x.StockUom
	}
	return ""
}

func (x *PurchaseOrderItem) GetQty() float64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type SavePurchaseReceiptReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PurchaseOrderName string                 `protobuf:"bytes,1,opt,name=purchase_order_name,json=purchaseOrderName,proto3" json:"purchase_order_name,omitempty" dc:"采购订单名称,必填"` // 采购订单名称,必填
	Items             []*PurchaseOrderItem   `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" dc:"采购订单物品列表,必填"`                                                  // 采购订单物品列表,必填
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SavePurchaseReceiptReq) Reset() {
	*x = SavePurchaseReceiptReq{}
	mi := &file_buying_buying_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePurchaseReceiptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePurchaseReceiptReq) ProtoMessage() {}

func (x *SavePurchaseReceiptReq) ProtoReflect() protoreflect.Message {
	mi := &file_buying_buying_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePurchaseReceiptReq.ProtoReflect.Descriptor instead.
func (*SavePurchaseReceiptReq) Descriptor() ([]byte, []int) {
	return file_buying_buying_proto_rawDescGZIP(), []int{7}
}

func (x *SavePurchaseReceiptReq) GetPurchaseOrderName() string {
	if x != nil {
		return x.PurchaseOrderName
	}
	return ""
}

func (x *SavePurchaseReceiptReq) GetItems() []*PurchaseOrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SavePurchaseReceiptResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseOrder *PurchaseOrderInfo     `protobuf:"bytes,1,opt,name=purchase_order,json=purchaseOrder,proto3" json:"purchase_order,omitempty" dc:"采购订单信息"` // 采购订单信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavePurchaseReceiptResp) Reset() {
	*x = SavePurchaseReceiptResp{}
	mi := &file_buying_buying_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePurchaseReceiptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePurchaseReceiptResp) ProtoMessage() {}

func (x *SavePurchaseReceiptResp) ProtoReflect() protoreflect.Message {
	mi := &file_buying_buying_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePurchaseReceiptResp.ProtoReflect.Descriptor instead.
func (*SavePurchaseReceiptResp) Descriptor() ([]byte, []int) {
	return file_buying_buying_proto_rawDescGZIP(), []int{8}
}

func (x *SavePurchaseReceiptResp) GetPurchaseOrder() *PurchaseOrderInfo {
	if x != nil {
		return x.PurchaseOrder
	}
	return nil
}

var File_buying_buying_proto protoreflect.FileDescriptor

const file_buying_buying_proto_rawDesc = "" +
	"\n" +
	"\x13buying/buying.proto\x12\x06buying\x1a\terp.proto\"7\n" +
	"\x12GetSupplierListReq\x12!\n" +
	"\fcompany_abbr\x18\x01 \x01(\tR\vcompanyAbbr\"P\n" +
	"\x13GetSupplierListResp\x129\n" +
	"\rsupplier_list\x18\x01 \x03(\v2\x14.buying.SupplierInfoR\fsupplierList\"b\n" +
	"\fSupplierInfo\x12#\n" +
	"\rsupplier_name\x18\x01 \x01(\tR\fsupplierName\x12-\n" +
	"\x12represents_company\x18\x02 \x01(\tR\x11representsCompany\"E\n" +
	"\x13GetPurchaseOrderReq\x12.\n" +
	"\x13purchase_order_name\x18\x01 \x01(\tR\x11purchaseOrderName\"X\n" +
	"\x14GetPurchaseOrderResp\x12@\n" +
	"\x0epurchase_order\x18\x01 \x01(\v2\x19.buying.PurchaseOrderInfoR\rpurchaseOrder\"\xe1\x01\n" +
	"\x11PurchaseOrderInfo\x12.\n" +
	"\x13purchase_order_name\x18\x01 \x01(\tR\x11purchaseOrderName\x12#\n" +
	"\rsupplier_name\x18\x02 \x01(\tR\fsupplierName\x12!\n" +
	"\fper_received\x18\x03 \x01(\x01R\vperReceived\x12#\n" +
	"\rschedule_date\x18\x04 \x01(\tR\fscheduleDate\x12/\n" +
	"\x05items\x18\x05 \x03(\v2\x19.buying.PurchaseOrderItemR\x05items\"|\n" +
	"\x11PurchaseOrderItem\x12\x1b\n" +
	"\titem_code\x18\x01 \x01(\tR\bitemCode\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x1b\n" +
	"\tstock_uom\x18\x03 \x01(\tR\bstockUom\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\x01R\x03qty\"y\n" +
	"\x16SavePurchaseReceiptReq\x12.\n" +
	"\x13purchase_order_name\x18\x01 \x01(\tR\x11purchaseOrderName\x12/\n" +
	"\x05items\x18\x02 \x03(\v2\x19.buying.PurchaseOrderItemR\x05items\"[\n" +
	"\x17SavePurchaseReceiptResp\x12@\n" +
	"\x0epurchase_order\x18\x01 \x01(\v2\x19.buying.PurchaseOrderInfoR\rpurchaseOrder2\xdf\x01\n" +
	"\rBuyingService\x12@\n" +
	"\x0fGetSupplierList\x12\x1a.buying.GetSupplierListReq\x1a\x11.erp.ResponseInfo\x12B\n" +
	"\x10GetPurchaseOrder\x12\x1b.buying.GetPurchaseOrderReq\x1a\x11.erp.ResponseInfo\x12H\n" +
	"\x13SavePurchaseReceipt\x12\x1e.buying.SavePurchaseReceiptReq\x1a\x11.erp.ResponseInfoB$Z\"ttpos-bmp/app/ttpos-erp/api/buyingb\x06proto3"

var (
	file_buying_buying_proto_rawDescOnce sync.Once
	file_buying_buying_proto_rawDescData []byte
)

func file_buying_buying_proto_rawDescGZIP() []byte {
	file_buying_buying_proto_rawDescOnce.Do(func() {
		file_buying_buying_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_buying_buying_proto_rawDesc), len(file_buying_buying_proto_rawDesc)))
	})
	return file_buying_buying_proto_rawDescData
}

var file_buying_buying_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_buying_buying_proto_goTypes = []any{
	(*GetSupplierListReq)(nil),      // 0: buying.GetSupplierListReq
	(*GetSupplierListResp)(nil),     // 1: buying.GetSupplierListResp
	(*SupplierInfo)(nil),            // 2: buying.SupplierInfo
	(*GetPurchaseOrderReq)(nil),     // 3: buying.GetPurchaseOrderReq
	(*GetPurchaseOrderResp)(nil),    // 4: buying.GetPurchaseOrderResp
	(*PurchaseOrderInfo)(nil),       // 5: buying.PurchaseOrderInfo
	(*PurchaseOrderItem)(nil),       // 6: buying.PurchaseOrderItem
	(*SavePurchaseReceiptReq)(nil),  // 7: buying.SavePurchaseReceiptReq
	(*SavePurchaseReceiptResp)(nil), // 8: buying.SavePurchaseReceiptResp
	(*api.ResponseInfo)(nil),        // 9: erp.ResponseInfo
}
var file_buying_buying_proto_depIdxs = []int32{
	2, // 0: buying.GetSupplierListResp.supplier_list:type_name -> buying.SupplierInfo
	5, // 1: buying.GetPurchaseOrderResp.purchase_order:type_name -> buying.PurchaseOrderInfo
	6, // 2: buying.PurchaseOrderInfo.items:type_name -> buying.PurchaseOrderItem
	6, // 3: buying.SavePurchaseReceiptReq.items:type_name -> buying.PurchaseOrderItem
	5, // 4: buying.SavePurchaseReceiptResp.purchase_order:type_name -> buying.PurchaseOrderInfo
	0, // 5: buying.BuyingService.GetSupplierList:input_type -> buying.GetSupplierListReq
	3, // 6: buying.BuyingService.GetPurchaseOrder:input_type -> buying.GetPurchaseOrderReq
	7, // 7: buying.BuyingService.SavePurchaseReceipt:input_type -> buying.SavePurchaseReceiptReq
	9, // 8: buying.BuyingService.GetSupplierList:output_type -> erp.ResponseInfo
	9, // 9: buying.BuyingService.GetPurchaseOrder:output_type -> erp.ResponseInfo
	9, // 10: buying.BuyingService.SavePurchaseReceipt:output_type -> erp.ResponseInfo
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_buying_buying_proto_init() }
func file_buying_buying_proto_init() {
	if File_buying_buying_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_buying_buying_proto_rawDesc), len(file_buying_buying_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_buying_buying_proto_goTypes,
		DependencyIndexes: file_buying_buying_proto_depIdxs,
		MessageInfos:      file_buying_buying_proto_msgTypes,
	}.Build()
	File_buying_buying_proto = out.File
	file_buying_buying_proto_goTypes = nil
	file_buying_buying_proto_depIdxs = nil
}
