user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}

stream {
    log_format custom '$remote_addr [$time_local] '
                            'protocol:$protocol '
                            'status:$status '
                            'bytes_sent:$bytes_sent '
                            'bytes_received:$bytes_received '
                            'upstream:"$upstream_addr" '
                            'connect_time:$upstream_connect_time '
                            'session_time:$session_time';
    #mysql-router的ip和端口
   upstream database_servers {
        zone database_servers 64k;
        server 192.168.30.109:6446 max_fails=1 fail_timeout=3s;
        server 192.168.30.208:6446 max_fails=1 fail_timeout=3s backup;
        server 192.168.30.77:6446 max_fails=1 fail_timeout=3s backup;
    }
    # 配置健康检查
    server {
        listen 6446;
        proxy_pass database_servers;
        proxy_next_upstream on;
        access_log /var/log/nginx/access.log custom;
    }
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}