ALTER TABLE `ttpos_member_card_type` CHANGE COLUMN `expire` `period` INT(11) NOT NULL DEFAULT 0 COMMENT '有效期限,单位:月, 0为永久有效';
ALTER TABLE `ttpos_member_card_type` CHANGE COLUMN `describe` `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '使用须知';
ALTER TABLE `ttpos_member_card_type` ADD COLUMN `count` INT(11) NOT NULL DEFAULT 0 COMMENT '数量';
ALTER TABLE `ttpos_member_card_type` ADD COLUMN `gift_value` decimal(12,2) NOT NULL DEFAULT 0 COMMENT '赠送额';
ALTER TABLE `ttpos_member_card_type` ADD COLUMN `card_opening_gift` tinyint(1) NOT NULL DEFAULT 0 COMMENT '开卡赠送,0-否 1-是';
ALTER TABLE `ttpos_member_card_type` DROP COLUMN `open_point`;
ALTER TABLE `ttpos_member_card_type` DROP COLUMN `open_point_num`;
ALTER TABLE `ttpos_member_card_type` DROP COLUMN `open_money`;
ALTER TABLE `ttpos_member_card_type` DROP COLUMN `open_money_num`;
ALTER TABLE `ttpos_member` CHANGE COLUMN `gift_balance` `gift_account_balance` DECIMAL(12, 2) NOT NULL DEFAULT 0 COMMENT '赠送账户余额';
ALTER TABLE `ttpos_member_level` CHANGE COLUMN `upgrade_point` `upgrade_points` INT(11) DEFAULT 0 COMMENT '升级条件，累计积分';
ALTER TABLE `ttpos_member_level` CHANGE COLUMN `open_point` `open_points` TINYINT(3) DEFAULT 0 COMMENT '是否开放累计积分升级，0-否 1-是';
ALTER TABLE `ttpos_member_card_log` CHANGE COLUMN `expire` `period` INT(11) DEFAULT 0 COMMENT '有效期限,单位:月, 0为永久有效';
ALTER TABLE `ttpos_member_point_log` CHANGE COLUMN `describe` `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '变动描述';
ALTER TABLE `ttpos_member_balance_log` CHANGE COLUMN `describe` `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '变动描述';
