[www]
user = www-data
group = www-data
listen = 127.0.0.1:9000
listen.mode = 0666
pm = Static
pm.max_children = 50
pm.start_servers = 50
pm.min_spare_servers = 50
pm.max_spare_servers = 50
pm.process_idle_timeout = 10s;
pm.max_requests = 65535
request_terminate_timeout = 60s
catch_workers_output = yes
clear_env = no