//go:build integration

package statistics_test

import (
	"database/sql"
	"sync/atomic"
	"testing"
	"time"

	"ttpos-server-go/tests/fixture"
)

// --- P0: Test Business Mode Exclusion (Fix A) ---

// Test_P0_Shop_Statistics_Business_TestMode_CreateTimeDrift verifies that
// ExcludeTestBusinessByBillSQL correctly traces back to sale_bill.create_time
// (not statistics_sale.create_time) when filtering test business periods.
//
// This is the critical regression test for the "create_time drift" bug:
// When SaveSale() recreates statistics records, GORM auto-sets create_time to now(),
// causing statistics_sale.create_time to drift away from the original order's creation time.
//
// Timeline:
//
//	1800000000 ──[A:created@005000]── 1800010000 ═══TEST═══ 1800020000 ──[B:finish@025000]── 1800100000
//	                                  [B:created@015000]     [A:stats.create_time drifted]
//	                                  [A:finish@015000]      [B:stats.create_time drifted]
//
// Expected:
//
//	Bill A (sale_bill.create_time in normal period) → INCLUDED
//	Bill B (sale_bill.create_time in test period)   → EXCLUDED
func Test_P0_Shop_Statistics_Business_TestMode_CreateTimeDrift(t *testing.T) {
	companyUUID := fixture.GenerateCompanyUUID(t)
	db := fixture.NewTestTenantFull(t, companyUUID)

	now := time.Now().Unix()
	testStart := int64(1800010000)
	testEnd := int64(1800020000)

	// Seed test business period
	tbmExec(t, db,
		`INSERT INTO ttpos_business_status_period (uuid, start_time, end_time, create_time, update_time, delete_time)
		 VALUES (?, ?, ?, ?, ?, 0)`,
		tbmNextID(), testStart, testEnd, now, now)

	// Bill A: created in NORMAL period (before test), finished during test
	// → statistics should INCLUDE this order
	billA := tbmNextID()
	tbmExec(t, db,
		`INSERT INTO ttpos_sale_bill (uuid, status, finish_time, create_time, update_time, delete_time)
		 VALUES (?, 1, ?, ?, ?, 0)`,
		billA, 1800015000, 1800005000, now)

	tbmExec(t, db,
		`INSERT INTO ttpos_statistics_sale
		 (uuid, sale_bill_uuid, sale_order_uuid, payment_amount, complete_time, create_time, update_time, delete_time)
		 VALUES (?, ?, ?, 100.0000, ?, ?, ?, 0)`,
		tbmNextID(), billA, tbmNextID(),
		1800015000, // complete_time
		1800015000, // create_time — DRIFTED to test period (the bug scenario)
		now)

	// Bill B: created in TEST period, finished after test
	// → statistics should EXCLUDE this order
	billB := tbmNextID()
	tbmExec(t, db,
		`INSERT INTO ttpos_sale_bill (uuid, status, finish_time, create_time, update_time, delete_time)
		 VALUES (?, 1, ?, ?, ?, 0)`,
		billB, 1800025000, 1800015000, now)

	tbmExec(t, db,
		`INSERT INTO ttpos_statistics_sale
		 (uuid, sale_bill_uuid, sale_order_uuid, payment_amount, complete_time, create_time, update_time, delete_time)
		 VALUES (?, ?, ?, 200.0000, ?, ?, ?, 0)`,
		tbmNextID(), billB, tbmNextID(),
		1800025000, // complete_time
		1800025000, // create_time — DRIFTED to normal period (would fool the old code)
		now)

	// --- SQL-level assertion: directly test ExcludeTestBusinessByBillSQL logic ---
	// This is the exact SQL generated by ExcludeTestBusinessByBillSQL("ss.sale_bill_uuid")
	excludeSQL := `
		SELECT ss.sale_bill_uuid, ss.payment_amount
		FROM ttpos_statistics_sale ss
		WHERE ss.delete_time = 0
		AND NOT EXISTS (
			SELECT 1 FROM ttpos_sale_bill _sb
			JOIN ttpos_business_status_period bsp ON bsp.delete_time = 0
			AND _sb.create_time >= bsp.start_time
			AND (bsp.end_time = 0 OR _sb.create_time <= bsp.end_time)
			WHERE _sb.uuid = ss.sale_bill_uuid AND _sb.delete_time = 0
		)
		ORDER BY ss.payment_amount`

	rows, err := db.Query(excludeSQL)
	if err != nil {
		t.Fatalf("query failed: %v", err)
	}
	defer rows.Close()

	type result struct {
		billUUID      int64
		paymentAmount float64
	}
	var results []result
	for rows.Next() {
		var r result
		if err := rows.Scan(&r.billUUID, &r.paymentAmount); err != nil {
			t.Fatalf("scan failed: %v", err)
		}
		results = append(results, r)
	}

	// Only Bill A (100.00, normal period) should pass the filter
	if len(results) != 1 {
		t.Fatalf("expected 1 row (only normal-period order), got %d rows", len(results))
	}
	if results[0].billUUID != billA {
		t.Errorf("expected bill_uuid=%d (Bill A), got %d", billA, results[0].billUUID)
	}
	if results[0].paymentAmount != 100.0 {
		t.Errorf("expected payment_amount=100.00 (Bill A), got %.4f", results[0].paymentAmount)
	}
	t.Logf("PASS: Bill A (normal, 100.00) included, Bill B (test, 200.00) excluded")

	// --- Verify the inverse: old-style filtering (using stats.create_time) would give WRONG results ---
	oldStyleSQL := `
		SELECT ss.sale_bill_uuid, ss.payment_amount
		FROM ttpos_statistics_sale ss
		WHERE ss.delete_time = 0
		AND NOT EXISTS (
			SELECT 1 FROM (SELECT start_time, end_time FROM ttpos_business_status_period WHERE delete_time = 0) bsp
			WHERE ss.create_time >= bsp.start_time
			AND (bsp.end_time = 0 OR ss.create_time <= bsp.end_time)
		)
		ORDER BY ss.payment_amount`

	rows2, err := db.Query(oldStyleSQL)
	if err != nil {
		t.Fatalf("old-style query failed: %v", err)
	}
	defer rows2.Close()

	var oldResults []result
	for rows2.Next() {
		var r result
		if err := rows2.Scan(&r.billUUID, &r.paymentAmount); err != nil {
			t.Fatalf("scan failed: %v", err)
		}
		oldResults = append(oldResults, r)
	}

	// Old-style filtering incorrectly includes Bill B (200, test period with drifted stats.create_time)
	// and excludes Bill A (100, normal period with drifted stats.create_time into test period)
	if len(oldResults) != 1 || oldResults[0].billUUID != billB {
		t.Logf("old-style results (expected WRONG): %+v", oldResults)
	}
	t.Logf("Confirmed: old-style filtering would return Bill B (test period) instead of Bill A (normal period)")
}

// Test_P0_Shop_Statistics_Business_TestMode_NoTestPeriod verifies that when no
// test business periods exist, ExcludeTestBusinessByBillSQL does not exclude any records.
func Test_P0_Shop_Statistics_Business_TestMode_NoTestPeriod(t *testing.T) {
	companyUUID := fixture.GenerateCompanyUUID(t)
	db := fixture.NewTestTenantFull(t, companyUUID)
	now := time.Now().Unix()

	// No business_status_period records — all orders should be counted
	billA := tbmNextID()
	tbmExec(t, db,
		`INSERT INTO ttpos_sale_bill (uuid, status, finish_time, create_time, update_time, delete_time)
		 VALUES (?, 1, ?, ?, ?, 0)`,
		billA, 1800015000, 1800005000, now)
	tbmExec(t, db,
		`INSERT INTO ttpos_statistics_sale
		 (uuid, sale_bill_uuid, sale_order_uuid, payment_amount, complete_time, create_time, update_time, delete_time)
		 VALUES (?, ?, ?, 100.0000, ?, ?, ?, 0)`,
		tbmNextID(), billA, tbmNextID(), 1800015000, 1800005000, now)

	billB := tbmNextID()
	tbmExec(t, db,
		`INSERT INTO ttpos_sale_bill (uuid, status, finish_time, create_time, update_time, delete_time)
		 VALUES (?, 1, ?, ?, ?, 0)`,
		billB, 1800025000, 1800015000, now)
	tbmExec(t, db,
		`INSERT INTO ttpos_statistics_sale
		 (uuid, sale_bill_uuid, sale_order_uuid, payment_amount, complete_time, create_time, update_time, delete_time)
		 VALUES (?, ?, ?, 200.0000, ?, ?, ?, 0)`,
		tbmNextID(), billB, tbmNextID(), 1800025000, 1800015000, now)

	// Without test periods, ExcludeTestBusinessByBillSQL should pass all records
	query := `
		SELECT COUNT(*), COALESCE(SUM(ss.payment_amount), 0)
		FROM ttpos_statistics_sale ss
		WHERE ss.delete_time = 0
		AND NOT EXISTS (
			SELECT 1 FROM ttpos_sale_bill _sb
			JOIN ttpos_business_status_period bsp ON bsp.delete_time = 0
			AND _sb.create_time >= bsp.start_time
			AND (bsp.end_time = 0 OR _sb.create_time <= bsp.end_time)
			WHERE _sb.uuid = ss.sale_bill_uuid AND _sb.delete_time = 0
		)`

	var count int
	var total float64
	if err := db.QueryRow(query).Scan(&count, &total); err != nil {
		t.Fatalf("query failed: %v", err)
	}

	if count != 2 {
		t.Errorf("expected 2 rows (all orders), got %d", count)
	}
	if total != 300.0 {
		t.Errorf("expected total=300.00 (100+200), got %.4f", total)
	}
	t.Logf("PASS: no test period → all %d orders included, total=%.2f", count, total)
}

// Test_P0_Shop_Statistics_Business_TestMode_APISmoke verifies the statistics business API
// still returns success (code=0) with test business period data present.
// Route: GET /shop/statistics/business
func Test_P0_Shop_Statistics_Business_TestMode_APISmoke(t *testing.T) {
	companyUUID := fixture.GenerateCompanyUUID(t)
	db := fixture.NewTestTenantFull(t, companyUUID)
	companyUUIDInt := mustParseInt64(companyUUID)

	fixture.SeedCompany(t, db, fixture.WithCompanyUUID(companyUUIDInt))
	fixture.SeedCompanySetting(t, db, fixture.WithCompanySettingCompanyUUID(companyUUIDInt))
	staff := fixture.SeedStaff(t, db,
		fixture.WithStaffCompanyUUID(companyUUIDInt),
		fixture.WithStaffIsSuper(1),
	)
	fixture.SetupWireMock(t)

	now := time.Now().Unix()

	// Seed a test business period and statistics data
	tbmExec(t, db,
		`INSERT INTO ttpos_business_status_period (uuid, start_time, end_time, create_time, update_time, delete_time)
		 VALUES (?, ?, ?, ?, ?, 0)`,
		tbmNextID(), 1800010000, 1800020000, now, now)

	bill := tbmNextID()
	tbmExec(t, db,
		`INSERT INTO ttpos_sale_bill (uuid, status, finish_time, create_time, update_time, delete_time)
		 VALUES (?, 1, ?, ?, ?, 0)`,
		bill, 1800015000, 1800005000, now)
	tbmExec(t, db,
		`INSERT INTO ttpos_statistics_sale
		 (uuid, sale_bill_uuid, sale_order_uuid, payment_amount, complete_time, create_time, update_time, delete_time)
		 VALUES (?, ?, ?, 100.0000, ?, ?, ?, 0)`,
		tbmNextID(), bill, tbmNextID(), 1800015000, 1800015000, now)

	// API should still respond successfully
	token := fixture.GenerateShopToken(t, companyUUID, mustParseString(staff.UUID))
	fixture.NewHTTPClient().WithToken(token).WithHeaders(versionHeaders).
		Get(t, pathStatsBusiness+"?start_time=1700000000&end_time=1900000000").
		AssertOK(t).AssertSuccess(t)
}

// --- Helpers ---

var tbmIDSeq int64

func tbmNextID() int64 {
	return time.Now().UnixNano()/int64(time.Millisecond)<<16 | atomic.AddInt64(&tbmIDSeq, 1)
}

func tbmExec(t *testing.T, db *sql.DB, query string, args ...any) {
	t.Helper()
	if _, err := db.Exec(query, args...); err != nil {
		t.Fatalf("SQL exec failed: %v\nquery: %s\nargs: %v", err, query, args)
	}
}
