// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-takeout/internal/dao/internal"
)

// jobDao is the data access object for the table takeout_job.
// You can define custom methods on it to extend its functionality as needed.
type jobDao struct {
	*internal.JobDao
}

var (
	// Job is a globally accessible object for table takeout_job operations.
	Job = jobDao{internal.NewJobDao()}
)

// Add your custom methods and functionality below.
