// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-takeout/internal/dao/internal"
)

// orderItemDao is the data access object for the table takeout_order_item.
// You can define custom methods on it to extend its functionality as needed.
type orderItemDao struct {
	*internal.OrderItemDao
}

var (
	// OrderItem is a globally accessible object for table takeout_order_item operations.
	OrderItem = orderItemDao{internal.NewOrderItemDao()}
)

// Add your custom methods and functionality below.
