
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    pbentity:
        link: "mysql:$DB_USERNAME:$DB_PASSWORD@tcp($DB_HOST:$DB_PORT_OPEN)/shop"
        path: "manifest/protobuf/shop"
        removePrefix: "ttpos_"
        #tables: "order,products"
        package: "ttpos-bmp/app/ttpos-shop/api/shop"
    pb:
        api: "api"
        ctrl: "internal/controller/rpc"
    dao:
      - link: "mysql:$DB_USERNAME:$DB_PASSWORD@tcp($DB_HOST:$DB_PORT_OPEN)/shop"
        descriptionTag: true
        removePrefix: "ttpos_"

  run:
    path: "./bin"
    extra: ""
    args: "all"
    watchPaths:
      - api/*.go
      - internal/*.go
  build:
    path: "./bin"
    system: linux
    arch: amd64
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - hub.hitosea.com/ttpos-bmp-shop

#注意db的格式跟link的不一样 用容器内网ip 端口
# shop 项目不做自动迁移，通过 php 那边做
#migrate-db-link: mysql://$DB_USERNAME:$DB_PASSWORD@tcp($DB_HOST:$DB_PORT)/shop
#migrate-db-link-open: mysql://$DB_USERNAME:$DB_PASSWORD@tcp($DB_HOST:$DB_PORT_OPEN)/shop