// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-manager/internal/dao/internal"
)

// webSocketMsgDao is the data access object for the table ttpos_web_socket_msg.
// You can define custom methods on it to extend its functionality as needed.
type webSocketMsgDao struct {
	*internal.WebSocketMsgDao
}

var (
	// WebSocketMsg is a globally accessible object for table ttpos_web_socket_msg operations.
	WebSocketMsg = webSocketMsgDao{internal.NewWebSocketMsgDao()}
)

// Add your custom methods and functionality below.
