// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: menu/menu.proto

package menu

import (
	reflect "reflect"
	sync "sync"
	takeout "ttpos-bmp/app/ttpos-takeout/api/takeout"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMenuSnapshotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty" dc:"渠道名称: grab,lineman"` // 渠道名称: grab,lineman
	ShopUuid      string                 `protobuf:"bytes,2,opt,name=shop_uuid,json=shopUuid,proto3" json:"shop_uuid,omitempty" dc:"店铺 UUID"`                        // 店铺 UUID
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty" dc:"请求 ID,可选"`                    // 请求 ID,可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuSnapshotReq) Reset() {
	*x = GetMenuSnapshotReq{}
	mi := &file_menu_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuSnapshotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuSnapshotReq) ProtoMessage() {}

func (x *GetMenuSnapshotReq) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuSnapshotReq.ProtoReflect.Descriptor instead.
func (*GetMenuSnapshotReq) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{0}
}

func (x *GetMenuSnapshotReq) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *GetMenuSnapshotReq) GetShopUuid() string {
	if x != nil {
		return x.ShopUuid
	}
	return ""
}

func (x *GetMenuSnapshotReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetMenuSnapshotResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuData      string                 `protobuf:"bytes,2,opt,name=menu_data,json=menuData,proto3" json:"menu_data,omitempty" dc:"Provider 侧原始菜单 JSON"`                     // Provider 侧原始菜单 JSON
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" dc:"快照更新时间"`                              // 快照更新时间
	SyncState     string                 `protobuf:"bytes,4,opt,name=sync_state,json=syncState,proto3" json:"sync_state,omitempty" dc:"同步状态  QUEUED/PROCESSING/SUCCESS/FAIL"` // 同步状态  QUEUED/PROCESSING/SUCCESS/FAIL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuSnapshotResp) Reset() {
	*x = GetMenuSnapshotResp{}
	mi := &file_menu_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuSnapshotResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuSnapshotResp) ProtoMessage() {}

func (x *GetMenuSnapshotResp) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuSnapshotResp.ProtoReflect.Descriptor instead.
func (*GetMenuSnapshotResp) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{1}
}

func (x *GetMenuSnapshotResp) GetMenuData() string {
	if x != nil {
		return x.MenuData
	}
	return ""
}

func (x *GetMenuSnapshotResp) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *GetMenuSnapshotResp) GetSyncState() string {
	if x != nil {
		return x.SyncState
	}
	return ""
}

type SaveMenuSnapshotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty" dc:"渠道名称: grab,lineman"` // 渠道名称: grab,lineman
	ShopUuid      string                 `protobuf:"bytes,2,opt,name=shop_uuid,json=shopUuid,proto3" json:"shop_uuid,omitempty" dc:"店铺 UUID"`                        // 店铺 UUID
	MenuData      string                 `protobuf:"bytes,3,opt,name=menu_data,json=menuData,proto3" json:"menu_data,omitempty" dc:"菜单数据 JSON 字符串"`                  // 菜单数据 JSON 字符串
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty" dc:"请求 ID"`                       // 请求 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMenuSnapshotReq) Reset() {
	*x = SaveMenuSnapshotReq{}
	mi := &file_menu_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMenuSnapshotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMenuSnapshotReq) ProtoMessage() {}

func (x *SaveMenuSnapshotReq) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMenuSnapshotReq.ProtoReflect.Descriptor instead.
func (*SaveMenuSnapshotReq) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{2}
}

func (x *SaveMenuSnapshotReq) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *SaveMenuSnapshotReq) GetShopUuid() string {
	if x != nil {
		return x.ShopUuid
	}
	return ""
}

func (x *SaveMenuSnapshotReq) GetMenuData() string {
	if x != nil {
		return x.MenuData
	}
	return ""
}

func (x *SaveMenuSnapshotReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type SaveMenuSnapshotResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMenuSnapshotResp) Reset() {
	*x = SaveMenuSnapshotResp{}
	mi := &file_menu_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMenuSnapshotResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMenuSnapshotResp) ProtoMessage() {}

func (x *SaveMenuSnapshotResp) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMenuSnapshotResp.ProtoReflect.Descriptor instead.
func (*SaveMenuSnapshotResp) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{3}
}

// 高级定价配置
type AdvancedPricing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty" dc:"定价键 (格式: serviceType.orderType.channel)"` // 定价键 (格式: serviceType.orderType.channel)
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty" dc:"价格 (minor unit，单位：分)"`               // 价格 (minor unit，单位：分)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvancedPricing) Reset() {
	*x = AdvancedPricing{}
	mi := &file_menu_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvancedPricing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvancedPricing) ProtoMessage() {}

func (x *AdvancedPricing) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvancedPricing.ProtoReflect.Descriptor instead.
func (*AdvancedPricing) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{4}
}

func (x *AdvancedPricing) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AdvancedPricing) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// 购买能力配置
type Purchasability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty" dc:"购买能力键 (格式: serviceType.orderType.channel)"` // 购买能力键 (格式: serviceType.orderType.channel)
	Purchasable   bool                   `protobuf:"varint,2,opt,name=purchasable,proto3" json:"purchasable,omitempty" dc:"是否可购买"`                    // 是否可购买
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Purchasability) Reset() {
	*x = Purchasability{}
	mi := &file_menu_menu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Purchasability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Purchasability) ProtoMessage() {}

func (x *Purchasability) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Purchasability.ProtoReflect.Descriptor instead.
func (*Purchasability) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{5}
}

func (x *Purchasability) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Purchasability) GetPurchasable() bool {
	if x != nil {
		return x.Purchasable
	}
	return false
}

// 更新菜单项请求
type UpdateMenuItemReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MerchantId       string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty" dc:"Grab MerchantID (必填)"`                                               // Grab MerchantID (必填)
	ItemId           string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty" dc:"商品ID (partner item id, 必填)"`                                                     // 商品ID (partner item id, 必填)
	Price            *int64                 `protobuf:"varint,3,opt,name=price,proto3,oneof" json:"price,omitempty" dc:"价格 (minor unit，单位：分)"`                                                                    // 价格 (minor unit，单位：分)
	AvailableStatus  *string                `protobuf:"bytes,4,opt,name=available_status,json=availableStatus,proto3,oneof" json:"available_status,omitempty" dc:"可用状态: AVAILABLE, UNAVAILABLE, UNAVAILABLEHIDE"` // 可用状态: AVAILABLE, UNAVAILABLE, UNAVAILABLEHIDE
	MaxStock         *int64                 `protobuf:"varint,5,opt,name=max_stock,json=maxStock,proto3,oneof" json:"max_stock,omitempty" dc:"库存数量"`                                                              // 库存数量
	AdvancedPricings []*AdvancedPricing     `protobuf:"bytes,6,rep,name=advanced_pricings,json=advancedPricings,proto3" json:"advanced_pricings,omitempty" dc:"高级定价配置"`                                           // 高级定价配置
	Purchasabilities []*Purchasability      `protobuf:"bytes,7,rep,name=purchasabilities,proto3" json:"purchasabilities,omitempty" dc:"购买能力配置"`                                                                   // 购买能力配置
	RequestId        string                 `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty" dc:"请求 ID (可选，用于追踪)"`                                                       // 请求 ID (可选，用于追踪)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateMenuItemReq) Reset() {
	*x = UpdateMenuItemReq{}
	mi := &file_menu_menu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemReq) ProtoMessage() {}

func (x *UpdateMenuItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemReq.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemReq) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMenuItemReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UpdateMenuItemReq) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *UpdateMenuItemReq) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateMenuItemReq) GetAvailableStatus() string {
	if x != nil && x.AvailableStatus != nil {
		return *x.AvailableStatus
	}
	return ""
}

func (x *UpdateMenuItemReq) GetMaxStock() int64 {
	if x != nil && x.MaxStock != nil {
		return *x.MaxStock
	}
	return 0
}

func (x *UpdateMenuItemReq) GetAdvancedPricings() []*AdvancedPricing {
	if x != nil {
		return x.AdvancedPricings
	}
	return nil
}

func (x *UpdateMenuItemReq) GetPurchasabilities() []*Purchasability {
	if x != nil {
		return x.Purchasabilities
	}
	return nil
}

func (x *UpdateMenuItemReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// 更新菜单项响应
type UpdateMenuItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty" dc:"商户ID"`       // 商户ID
	RecordId      string                 `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty" dc:"记录ID (ItemID)"`    // 记录ID (ItemID)
	RecordType    string                 `protobuf:"bytes,3,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty" dc:"记录类型: ITEM"` // 记录类型: ITEM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuItemResp) Reset() {
	*x = UpdateMenuItemResp{}
	mi := &file_menu_menu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemResp) ProtoMessage() {}

func (x *UpdateMenuItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemResp.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemResp) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMenuItemResp) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UpdateMenuItemResp) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *UpdateMenuItemResp) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

// 更新菜单修饰符请求
type UpdateMenuModifierReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MerchantId       string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty" dc:"Grab MerchantID (必填)"`                              // Grab MerchantID (必填)
	ModifierId       string                 `protobuf:"bytes,2,opt,name=modifier_id,json=modifierId,proto3" json:"modifier_id,omitempty" dc:"修饰符ID (partner modifier id, 必填)"`                   // 修饰符ID (partner modifier id, 必填)
	ModifierName     string                 `protobuf:"bytes,3,opt,name=modifier_name,json=modifierName,proto3" json:"modifier_name,omitempty" dc:"修饰符名称 (用于定位记录, 必填)"`                          // 修饰符名称 (用于定位记录, 必填)
	Price            *int64                 `protobuf:"varint,4,opt,name=price,proto3,oneof" json:"price,omitempty" dc:"价格 (minor unit，单位：分)"`                                                   // 价格 (minor unit，单位：分)
	AvailableStatus  *string                `protobuf:"bytes,5,opt,name=available_status,json=availableStatus,proto3,oneof" json:"available_status,omitempty" dc:"可用状态: AVAILABLE, UNAVAILABLE"` // 可用状态: AVAILABLE, UNAVAILABLE
	IsFree           *bool                  `protobuf:"varint,6,opt,name=is_free,json=isFree,proto3,oneof" json:"is_free,omitempty" dc:"是否免费"`                                                   // 是否免费
	AdvancedPricings []*AdvancedPricing     `protobuf:"bytes,7,rep,name=advanced_pricings,json=advancedPricings,proto3" json:"advanced_pricings,omitempty" dc:"高级定价配置"`                          // 高级定价配置
	RequestId        string                 `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty" dc:"请求 ID (可选，用于追踪)"`                                      // 请求 ID (可选，用于追踪)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateMenuModifierReq) Reset() {
	*x = UpdateMenuModifierReq{}
	mi := &file_menu_menu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuModifierReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuModifierReq) ProtoMessage() {}

func (x *UpdateMenuModifierReq) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuModifierReq.ProtoReflect.Descriptor instead.
func (*UpdateMenuModifierReq) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMenuModifierReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UpdateMenuModifierReq) GetModifierId() string {
	if x != nil {
		return x.ModifierId
	}
	return ""
}

func (x *UpdateMenuModifierReq) GetModifierName() string {
	if x != nil {
		return x.ModifierName
	}
	return ""
}

func (x *UpdateMenuModifierReq) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateMenuModifierReq) GetAvailableStatus() string {
	if x != nil && x.AvailableStatus != nil {
		return *x.AvailableStatus
	}
	return ""
}

func (x *UpdateMenuModifierReq) GetIsFree() bool {
	if x != nil && x.IsFree != nil {
		return *x.IsFree
	}
	return false
}

func (x *UpdateMenuModifierReq) GetAdvancedPricings() []*AdvancedPricing {
	if x != nil {
		return x.AdvancedPricings
	}
	return nil
}

func (x *UpdateMenuModifierReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// 更新菜单修饰符响应
type UpdateMenuModifierResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty" dc:"商户ID"`           // 商户ID
	RecordId      string                 `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty" dc:"记录ID (ModifierID)"`    // 记录ID (ModifierID)
	RecordType    string                 `protobuf:"bytes,3,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty" dc:"记录类型: MODIFIER"` // 记录类型: MODIFIER
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuModifierResp) Reset() {
	*x = UpdateMenuModifierResp{}
	mi := &file_menu_menu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuModifierResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuModifierResp) ProtoMessage() {}

func (x *UpdateMenuModifierResp) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuModifierResp.ProtoReflect.Descriptor instead.
func (*UpdateMenuModifierResp) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMenuModifierResp) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UpdateMenuModifierResp) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *UpdateMenuModifierResp) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

// 菜单实体 (用于批量更新)
type MenuEntity struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" dc:"菜单项ID或修饰符ID (partner item id 或 partner modifier id, 必填)"`                                                                                 // 菜单项ID或修饰符ID (partner item id 或 partner modifier id, 必填)
	Price            *int64                 `protobuf:"varint,2,opt,name=price,proto3,oneof" json:"price,omitempty" dc:"价格 (minor unit，单位：分)"`                                                                                                       // 价格 (minor unit，单位：分)
	AvailableStatus  *string                `protobuf:"bytes,3,opt,name=available_status,json=availableStatus,proto3,oneof" json:"available_status,omitempty" dc:"可用状态: AVAILABLE, UNAVAILABLE, UNAVAILABLEHIDE (商品), AVAILABLE, UNAVAILABLE (修饰符)"` // 可用状态: AVAILABLE, UNAVAILABLE, UNAVAILABLEHIDE (商品), AVAILABLE, UNAVAILABLE (修饰符)
	MaxStock         *int64                 `protobuf:"varint,4,opt,name=max_stock,json=maxStock,proto3,oneof" json:"max_stock,omitempty" dc:"库存数量 (仅商品支持)"`                                                                                         // 库存数量 (仅商品支持)
	AdvancedPricings []*AdvancedPricing     `protobuf:"bytes,5,rep,name=advanced_pricings,json=advancedPricings,proto3" json:"advanced_pricings,omitempty" dc:"高级定价配置"`                                                                              // 高级定价配置
	Purchasabilities []*Purchasability      `protobuf:"bytes,6,rep,name=purchasabilities,proto3" json:"purchasabilities,omitempty" dc:"购买能力配置 (仅商品支持)"`                                                                                              // 购买能力配置 (仅商品支持)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MenuEntity) Reset() {
	*x = MenuEntity{}
	mi := &file_menu_menu_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuEntity) ProtoMessage() {}

func (x *MenuEntity) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuEntity.ProtoReflect.Descriptor instead.
func (*MenuEntity) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{10}
}

func (x *MenuEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuEntity) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *MenuEntity) GetAvailableStatus() string {
	if x != nil && x.AvailableStatus != nil {
		return *x.AvailableStatus
	}
	return ""
}

func (x *MenuEntity) GetMaxStock() int64 {
	if x != nil && x.MaxStock != nil {
		return *x.MaxStock
	}
	return 0
}

func (x *MenuEntity) GetAdvancedPricings() []*AdvancedPricing {
	if x != nil {
		return x.AdvancedPricings
	}
	return nil
}

func (x *MenuEntity) GetPurchasabilities() []*Purchasability {
	if x != nil {
		return x.Purchasabilities
	}
	return nil
}

// 批量更新菜单请求
type BatchUpdateMenuReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty" dc:"Grab MerchantID (必填)"`   // Grab MerchantID (必填)
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty" dc:"字段类型: ITEM (商品) (必填)"`                               // 字段类型: ITEM (商品) (必填)
	MenuEntities  []*MenuEntity          `protobuf:"bytes,3,rep,name=menu_entities,json=menuEntities,proto3" json:"menu_entities,omitempty" dc:"菜单实体列表 (1-200 个)"` // 菜单实体列表 (1-200 个)
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty" dc:"请求 ID (可选，用于追踪)"`           // 请求 ID (可选，用于追踪)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateMenuReq) Reset() {
	*x = BatchUpdateMenuReq{}
	mi := &file_menu_menu_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateMenuReq) ProtoMessage() {}

func (x *BatchUpdateMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateMenuReq.ProtoReflect.Descriptor instead.
func (*BatchUpdateMenuReq) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{11}
}

func (x *BatchUpdateMenuReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *BatchUpdateMenuReq) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *BatchUpdateMenuReq) GetMenuEntities() []*MenuEntity {
	if x != nil {
		return x.MenuEntities
	}
	return nil
}

func (x *BatchUpdateMenuReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// 菜单实体错误信息
type MenuEntityError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" dc:"菜单项ID或修饰符ID"`                                  // 菜单项ID或修饰符ID
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty" dc:"错误代码"`          // 错误代码
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty" dc:"错误消息"` // 错误消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuEntityError) Reset() {
	*x = MenuEntityError{}
	mi := &file_menu_menu_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuEntityError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuEntityError) ProtoMessage() {}

func (x *MenuEntityError) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuEntityError.ProtoReflect.Descriptor instead.
func (*MenuEntityError) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{12}
}

func (x *MenuEntityError) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuEntityError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *MenuEntityError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 批量更新菜单响应
type BatchUpdateMenuResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty" dc:"商户ID"`       // 商户ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty" dc:"更新状态: success, partial_success, fail"` // 更新状态: success, partial_success, fail
	Errors        []*MenuEntityError     `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty" dc:"错误列表 (仅在 partial_success 或 fail 时返回)"` // 错误列表 (仅在 partial_success 或 fail 时返回)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateMenuResp) Reset() {
	*x = BatchUpdateMenuResp{}
	mi := &file_menu_menu_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateMenuResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateMenuResp) ProtoMessage() {}

func (x *BatchUpdateMenuResp) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateMenuResp.ProtoReflect.Descriptor instead.
func (*BatchUpdateMenuResp) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{13}
}

func (x *BatchUpdateMenuResp) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *BatchUpdateMenuResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BatchUpdateMenuResp) GetErrors() []*MenuEntityError {
	if x != nil {
		return x.Errors
	}
	return nil
}

// 通知菜单更新请求
type NotifyMenuUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopUuid      string                 `protobuf:"bytes,1,opt,name=shop_uuid,json=shopUuid,proto3" json:"shop_uuid,omitempty" dc:"店铺 UUID (必填)"`                         // 店铺 UUID (必填)
	ProviderName  string                 `protobuf:"bytes,2,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty" dc:"平台名称: grab, lineman (必填)"` // 平台名称: grab, lineman (必填)
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty" dc:"请求 ID (可选，用于追踪)"`                   // 请求 ID (可选，用于追踪)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyMenuUpdateReq) Reset() {
	*x = NotifyMenuUpdateReq{}
	mi := &file_menu_menu_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyMenuUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyMenuUpdateReq) ProtoMessage() {}

func (x *NotifyMenuUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyMenuUpdateReq.ProtoReflect.Descriptor instead.
func (*NotifyMenuUpdateReq) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{14}
}

func (x *NotifyMenuUpdateReq) GetShopUuid() string {
	if x != nil {
		return x.ShopUuid
	}
	return ""
}

func (x *NotifyMenuUpdateReq) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *NotifyMenuUpdateReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_menu_menu_proto protoreflect.FileDescriptor

const file_menu_menu_proto_rawDesc = "" +
	"\n" +
	"\x0fmenu/menu.proto\x12\x04menu\x1a\x11takeout_api.proto\"u\n" +
	"\x12GetMenuSnapshotReq\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x1b\n" +
	"\tshop_uuid\x18\x02 \x01(\tR\bshopUuid\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"p\n" +
	"\x13GetMenuSnapshotResp\x12\x1b\n" +
	"\tmenu_data\x18\x02 \x01(\tR\bmenuData\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"sync_state\x18\x04 \x01(\tR\tsyncState\"\x93\x01\n" +
	"\x13SaveMenuSnapshotReq\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x1b\n" +
	"\tshop_uuid\x18\x02 \x01(\tR\bshopUuid\x12\x1b\n" +
	"\tmenu_data\x18\x03 \x01(\tR\bmenuData\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\x16\n" +
	"\x14SaveMenuSnapshotResp\"9\n" +
	"\x0fAdvancedPricing\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\"D\n" +
	"\x0ePurchasability\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\vpurchasable\x18\x02 \x01(\bR\vpurchasable\"\x8c\x03\n" +
	"\x11UpdateMenuItemReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x19\n" +
	"\x05price\x18\x03 \x01(\x03H\x00R\x05price\x88\x01\x01\x12.\n" +
	"\x10available_status\x18\x04 \x01(\tH\x01R\x0favailableStatus\x88\x01\x01\x12 \n" +
	"\tmax_stock\x18\x05 \x01(\x03H\x02R\bmaxStock\x88\x01\x01\x12B\n" +
	"\x11advanced_pricings\x18\x06 \x03(\v2\x15.menu.AdvancedPricingR\x10advancedPricings\x12@\n" +
	"\x10purchasabilities\x18\a \x03(\v2\x14.menu.PurchasabilityR\x10purchasabilities\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestIdB\b\n" +
	"\x06_priceB\x13\n" +
	"\x11_available_statusB\f\n" +
	"\n" +
	"_max_stock\"s\n" +
	"\x12UpdateMenuItemResp\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\x12\x1f\n" +
	"\vrecord_type\x18\x03 \x01(\tR\n" +
	"recordType\"\xf5\x02\n" +
	"\x15UpdateMenuModifierReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vmodifier_id\x18\x02 \x01(\tR\n" +
	"modifierId\x12#\n" +
	"\rmodifier_name\x18\x03 \x01(\tR\fmodifierName\x12\x19\n" +
	"\x05price\x18\x04 \x01(\x03H\x00R\x05price\x88\x01\x01\x12.\n" +
	"\x10available_status\x18\x05 \x01(\tH\x01R\x0favailableStatus\x88\x01\x01\x12\x1c\n" +
	"\ais_free\x18\x06 \x01(\bH\x02R\x06isFree\x88\x01\x01\x12B\n" +
	"\x11advanced_pricings\x18\a \x03(\v2\x15.menu.AdvancedPricingR\x10advancedPricings\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestIdB\b\n" +
	"\x06_priceB\x13\n" +
	"\x11_available_statusB\n" +
	"\n" +
	"\b_is_free\"w\n" +
	"\x16UpdateMenuModifierResp\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\x12\x1f\n" +
	"\vrecord_type\x18\x03 \x01(\tR\n" +
	"recordType\"\xbc\x02\n" +
	"\n" +
	"MenuEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05price\x18\x02 \x01(\x03H\x00R\x05price\x88\x01\x01\x12.\n" +
	"\x10available_status\x18\x03 \x01(\tH\x01R\x0favailableStatus\x88\x01\x01\x12 \n" +
	"\tmax_stock\x18\x04 \x01(\x03H\x02R\bmaxStock\x88\x01\x01\x12B\n" +
	"\x11advanced_pricings\x18\x05 \x03(\v2\x15.menu.AdvancedPricingR\x10advancedPricings\x12@\n" +
	"\x10purchasabilities\x18\x06 \x03(\v2\x14.menu.PurchasabilityR\x10purchasabilitiesB\b\n" +
	"\x06_priceB\x13\n" +
	"\x11_available_statusB\f\n" +
	"\n" +
	"_max_stock\"\xa1\x01\n" +
	"\x12BatchUpdateMenuReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x125\n" +
	"\rmenu_entities\x18\x03 \x03(\v2\x10.menu.MenuEntityR\fmenuEntities\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"e\n" +
	"\x0fMenuEntityError\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"}\n" +
	"\x13BatchUpdateMenuResp\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12-\n" +
	"\x06errors\x18\x03 \x03(\v2\x15.menu.MenuEntityErrorR\x06errors\"v\n" +
	"\x13NotifyMenuUpdateReq\x12\x1b\n" +
	"\tshop_uuid\x18\x01 \x01(\tR\bshopUuid\x12#\n" +
	"\rprovider_name\x18\x02 \x01(\tR\fproviderName\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId2\xb3\x03\n" +
	"\vMenuService\x12C\n" +
	"\x0fGetMenuSnapshot\x12\x18.menu.GetMenuSnapshotReq\x1a\x14.takeout.ApiResponse\"\x00\x12E\n" +
	"\x10SaveMenuSnapshot\x12\x19.menu.SaveMenuSnapshotReq\x1a\x14.takeout.ApiResponse\"\x00\x12A\n" +
	"\x0eUpdateMenuItem\x12\x17.menu.UpdateMenuItemReq\x1a\x14.takeout.ApiResponse\"\x00\x12I\n" +
	"\x12UpdateMenuModifier\x12\x1b.menu.UpdateMenuModifierReq\x1a\x14.takeout.ApiResponse\"\x00\x12C\n" +
	"\x0fBatchUpdateMenu\x12\x18.menu.BatchUpdateMenuReq\x1a\x14.takeout.ApiResponse\"\x00\x12E\n" +
	"\x10NotifyMenuUpdate\x12\x19.menu.NotifyMenuUpdateReq\x1a\x14.takeout.ApiResponse\"\x00B&Z$ttpos-bmp/app/ttpos-takeout/api/menub\x06proto3"

var (
	file_menu_menu_proto_rawDescOnce sync.Once
	file_menu_menu_proto_rawDescData []byte
)

func file_menu_menu_proto_rawDescGZIP() []byte {
	file_menu_menu_proto_rawDescOnce.Do(func() {
		file_menu_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_menu_menu_proto_rawDesc), len(file_menu_menu_proto_rawDesc)))
	})
	return file_menu_menu_proto_rawDescData
}

var file_menu_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_menu_menu_proto_goTypes = []any{
	(*GetMenuSnapshotReq)(nil),     // 0: menu.GetMenuSnapshotReq
	(*GetMenuSnapshotResp)(nil),    // 1: menu.GetMenuSnapshotResp
	(*SaveMenuSnapshotReq)(nil),    // 2: menu.SaveMenuSnapshotReq
	(*SaveMenuSnapshotResp)(nil),   // 3: menu.SaveMenuSnapshotResp
	(*AdvancedPricing)(nil),        // 4: menu.AdvancedPricing
	(*Purchasability)(nil),         // 5: menu.Purchasability
	(*UpdateMenuItemReq)(nil),      // 6: menu.UpdateMenuItemReq
	(*UpdateMenuItemResp)(nil),     // 7: menu.UpdateMenuItemResp
	(*UpdateMenuModifierReq)(nil),  // 8: menu.UpdateMenuModifierReq
	(*UpdateMenuModifierResp)(nil), // 9: menu.UpdateMenuModifierResp
	(*MenuEntity)(nil),             // 10: menu.MenuEntity
	(*BatchUpdateMenuReq)(nil),     // 11: menu.BatchUpdateMenuReq
	(*MenuEntityError)(nil),        // 12: menu.MenuEntityError
	(*BatchUpdateMenuResp)(nil),    // 13: menu.BatchUpdateMenuResp
	(*NotifyMenuUpdateReq)(nil),    // 14: menu.NotifyMenuUpdateReq
	(*takeout.ApiResponse)(nil),    // 15: takeout.ApiResponse
}
var file_menu_menu_proto_depIdxs = []int32{
	4,  // 0: menu.UpdateMenuItemReq.advanced_pricings:type_name -> menu.AdvancedPricing
	5,  // 1: menu.UpdateMenuItemReq.purchasabilities:type_name -> menu.Purchasability
	4,  // 2: menu.UpdateMenuModifierReq.advanced_pricings:type_name -> menu.AdvancedPricing
	4,  // 3: menu.MenuEntity.advanced_pricings:type_name -> menu.AdvancedPricing
	5,  // 4: menu.MenuEntity.purchasabilities:type_name -> menu.Purchasability
	10, // 5: menu.BatchUpdateMenuReq.menu_entities:type_name -> menu.MenuEntity
	12, // 6: menu.BatchUpdateMenuResp.errors:type_name -> menu.MenuEntityError
	0,  // 7: menu.MenuService.GetMenuSnapshot:input_type -> menu.GetMenuSnapshotReq
	2,  // 8: menu.MenuService.SaveMenuSnapshot:input_type -> menu.SaveMenuSnapshotReq
	6,  // 9: menu.MenuService.UpdateMenuItem:input_type -> menu.UpdateMenuItemReq
	8,  // 10: menu.MenuService.UpdateMenuModifier:input_type -> menu.UpdateMenuModifierReq
	11, // 11: menu.MenuService.BatchUpdateMenu:input_type -> menu.BatchUpdateMenuReq
	14, // 12: menu.MenuService.NotifyMenuUpdate:input_type -> menu.NotifyMenuUpdateReq
	15, // 13: menu.MenuService.GetMenuSnapshot:output_type -> takeout.ApiResponse
	15, // 14: menu.MenuService.SaveMenuSnapshot:output_type -> takeout.ApiResponse
	15, // 15: menu.MenuService.UpdateMenuItem:output_type -> takeout.ApiResponse
	15, // 16: menu.MenuService.UpdateMenuModifier:output_type -> takeout.ApiResponse
	15, // 17: menu.MenuService.BatchUpdateMenu:output_type -> takeout.ApiResponse
	15, // 18: menu.MenuService.NotifyMenuUpdate:output_type -> takeout.ApiResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_menu_menu_proto_init() }
func file_menu_menu_proto_init() {
	if File_menu_menu_proto != nil {
		return
	}
	file_menu_menu_proto_msgTypes[6].OneofWrappers = []any{}
	file_menu_menu_proto_msgTypes[8].OneofWrappers = []any{}
	file_menu_menu_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_menu_menu_proto_rawDesc), len(file_menu_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_menu_menu_proto_goTypes,
		DependencyIndexes: file_menu_menu_proto_depIdxs,
		MessageInfos:      file_menu_menu_proto_msgTypes,
	}.Build()
	File_menu_menu_proto = out.File
	file_menu_menu_proto_goTypes = nil
	file_menu_menu_proto_depIdxs = nil
}
