// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: menu/menu.proto

package menu

import (
	reflect "reflect"
	sync "sync"
	takeout "ttpos-bmp/app/ttpos-takeout/api/takeout"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMenuSnapshotReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty" dc:"渠道名称: grab,lineman"` // 渠道名称: grab,lineman
	ShopUuid     string `protobuf:"bytes,2,opt,name=shop_uuid,json=shopUuid,proto3" json:"shop_uuid,omitempty" dc:"店铺 UUID"`                        // 店铺 UUID
	RequestId    string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty" dc:"请求 ID,可选"`                    // 请求 ID,可选
}

func (x *GetMenuSnapshotReq) Reset() {
	*x = GetMenuSnapshotReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_menu_menu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuSnapshotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuSnapshotReq) ProtoMessage() {}

func (x *GetMenuSnapshotReq) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuSnapshotReq.ProtoReflect.Descriptor instead.
func (*GetMenuSnapshotReq) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{0}
}

func (x *GetMenuSnapshotReq) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *GetMenuSnapshotReq) GetShopUuid() string {
	if x != nil {
		return x.ShopUuid
	}
	return ""
}

func (x *GetMenuSnapshotReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetMenuSnapshotResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content   string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty" dc:"Provider 侧原始菜单 JSON"`                                       // Provider 侧原始菜单 JSON
	UpdatedAt int64  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" dc:"快照更新时间"`                              // 快照更新时间
	SyncState string `protobuf:"bytes,4,opt,name=sync_state,json=syncState,proto3" json:"sync_state,omitempty" dc:"同步状态  QUEUED/PROCESSING/SUCCESS/FAIL"` // 同步状态  QUEUED/PROCESSING/SUCCESS/FAIL
}

func (x *GetMenuSnapshotResp) Reset() {
	*x = GetMenuSnapshotResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_menu_menu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuSnapshotResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuSnapshotResp) ProtoMessage() {}

func (x *GetMenuSnapshotResp) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuSnapshotResp.ProtoReflect.Descriptor instead.
func (*GetMenuSnapshotResp) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{1}
}

func (x *GetMenuSnapshotResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetMenuSnapshotResp) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *GetMenuSnapshotResp) GetSyncState() string {
	if x != nil {
		return x.SyncState
	}
	return ""
}

type SaveMenuSnapshotReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty" dc:"渠道名称: grab,lineman"` // 渠道名称: grab,lineman
	ShopUuid     string `protobuf:"bytes,2,opt,name=shop_uuid,json=shopUuid,proto3" json:"shop_uuid,omitempty" dc:"店铺 UUID"`                        // 店铺 UUID
	MenuData     string `protobuf:"bytes,3,opt,name=menu_data,json=menuData,proto3" json:"menu_data,omitempty" dc:"菜单数据 JSON 字符串"`                  // 菜单数据 JSON 字符串
	RequestId    string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty" dc:"请求 ID"`                       // 请求 ID
}

func (x *SaveMenuSnapshotReq) Reset() {
	*x = SaveMenuSnapshotReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_menu_menu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMenuSnapshotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMenuSnapshotReq) ProtoMessage() {}

func (x *SaveMenuSnapshotReq) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMenuSnapshotReq.ProtoReflect.Descriptor instead.
func (*SaveMenuSnapshotReq) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{2}
}

func (x *SaveMenuSnapshotReq) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *SaveMenuSnapshotReq) GetShopUuid() string {
	if x != nil {
		return x.ShopUuid
	}
	return ""
}

func (x *SaveMenuSnapshotReq) GetMenuData() string {
	if x != nil {
		return x.MenuData
	}
	return ""
}

func (x *SaveMenuSnapshotReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type SaveMenuSnapshotResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveMenuSnapshotResp) Reset() {
	*x = SaveMenuSnapshotResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_menu_menu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMenuSnapshotResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMenuSnapshotResp) ProtoMessage() {}

func (x *SaveMenuSnapshotResp) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMenuSnapshotResp.ProtoReflect.Descriptor instead.
func (*SaveMenuSnapshotResp) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{3}
}

var File_menu_menu_proto protoreflect.FileDescriptor

var file_menu_menu_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x65, 0x6e, 0x75, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6d, 0x65, 0x6e, 0x75, 0x1a, 0x11, 0x74, 0x61, 0x6b, 0x65, 0x6f, 0x75, 0x74,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x6e, 0x75, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x55, 0x75,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x22, 0x6d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x53, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x79, 0x6e, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x22, 0x93, 0x01, 0x0a, 0x13, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65,
	0x6e, 0x75, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d,
	0x65, 0x6e, 0x75, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65,
	0x6e, 0x75, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x32, 0x99,
	0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x6e, 0x75, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x12, 0x18, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x74, 0x61,
	0x6b, 0x65, 0x6f, 0x75, 0x74, 0x2e, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x10, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x19, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x53,
	0x61, 0x76, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x14, 0x2e, 0x74, 0x61, 0x6b, 0x65, 0x6f, 0x75, 0x74, 0x2e, 0x41, 0x70, 0x69,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x26, 0x5a, 0x24, 0x74, 0x74,
	0x70, 0x6f, 0x73, 0x2d, 0x62, 0x6d, 0x70, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x74, 0x74, 0x70, 0x6f,
	0x73, 0x2d, 0x74, 0x61, 0x6b, 0x65, 0x6f, 0x75, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65,
	0x6e, 0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_menu_menu_proto_rawDescOnce sync.Once
	file_menu_menu_proto_rawDescData = file_menu_menu_proto_rawDesc
)

func file_menu_menu_proto_rawDescGZIP() []byte {
	file_menu_menu_proto_rawDescOnce.Do(func() {
		file_menu_menu_proto_rawDescData = protoimpl.X.CompressGZIP(file_menu_menu_proto_rawDescData)
	})
	return file_menu_menu_proto_rawDescData
}

var file_menu_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_menu_menu_proto_goTypes = []any{
	(*GetMenuSnapshotReq)(nil),   // 0: menu.GetMenuSnapshotReq
	(*GetMenuSnapshotResp)(nil),  // 1: menu.GetMenuSnapshotResp
	(*SaveMenuSnapshotReq)(nil),  // 2: menu.SaveMenuSnapshotReq
	(*SaveMenuSnapshotResp)(nil), // 3: menu.SaveMenuSnapshotResp
	(*takeout.ApiResponse)(nil),  // 4: takeout.ApiResponse
}
var file_menu_menu_proto_depIdxs = []int32{
	0, // 0: menu.MenuService.GetMenuSnapshot:input_type -> menu.GetMenuSnapshotReq
	2, // 1: menu.MenuService.SaveMenuSnapshot:input_type -> menu.SaveMenuSnapshotReq
	4, // 2: menu.MenuService.GetMenuSnapshot:output_type -> takeout.ApiResponse
	4, // 3: menu.MenuService.SaveMenuSnapshot:output_type -> takeout.ApiResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_menu_menu_proto_init() }
func file_menu_menu_proto_init() {
	if File_menu_menu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_menu_menu_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetMenuSnapshotReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_menu_menu_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetMenuSnapshotResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_menu_menu_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SaveMenuSnapshotReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_menu_menu_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SaveMenuSnapshotResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_menu_menu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_menu_menu_proto_goTypes,
		DependencyIndexes: file_menu_menu_proto_depIdxs,
		MessageInfos:      file_menu_menu_proto_msgTypes,
	}.Build()
	File_menu_menu_proto = out.File
	file_menu_menu_proto_rawDesc = nil
	file_menu_menu_proto_goTypes = nil
	file_menu_menu_proto_depIdxs = nil
}
