// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: takeout_api.proto

package takeout

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty" dc:"响应数据，根据实际情况定义"` // 响应数据，根据实际情况定义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponse) Reset() {
	*x = ApiResponse{}
	mi := &file_takeout_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponse) ProtoMessage() {}

func (x *ApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_takeout_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponse.ProtoReflect.Descriptor instead.
func (*ApiResponse) Descriptor() ([]byte, []int) {
	return file_takeout_api_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ApiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponse) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_takeout_api_proto protoreflect.FileDescriptor

const file_takeout_api_proto_rawDesc = "" +
	"\n" +
	"\x11takeout_api.proto\x12\atakeout\x1a\x19google/protobuf/any.proto\"e\n" +
	"\vApiResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04dataB)Z'ttpos-bmp/app/ttpos-takeout/api/takeoutb\x06proto3"

var (
	file_takeout_api_proto_rawDescOnce sync.Once
	file_takeout_api_proto_rawDescData []byte
)

func file_takeout_api_proto_rawDescGZIP() []byte {
	file_takeout_api_proto_rawDescOnce.Do(func() {
		file_takeout_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takeout_api_proto_rawDesc), len(file_takeout_api_proto_rawDesc)))
	})
	return file_takeout_api_proto_rawDescData
}

var file_takeout_api_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_takeout_api_proto_goTypes = []any{
	(*ApiResponse)(nil), // 0: takeout.ApiResponse
	(*anypb.Any)(nil),   // 1: google.protobuf.Any
}
var file_takeout_api_proto_depIdxs = []int32{
	1, // 0: takeout.ApiResponse.data:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_takeout_api_proto_init() }
func file_takeout_api_proto_init() {
	if File_takeout_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takeout_api_proto_rawDesc), len(file_takeout_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takeout_api_proto_goTypes,
		DependencyIndexes: file_takeout_api_proto_depIdxs,
		MessageInfos:      file_takeout_api_proto_msgTypes,
	}.Build()
	File_takeout_api_proto = out.File
	file_takeout_api_proto_goTypes = nil
	file_takeout_api_proto_depIdxs = nil
}
