// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: item/item.proto

package item

import (
	reflect "reflect"
	sync "sync"
	api "ttpos-bmp/app/ttpos-erp/api"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemGroup int32

const (
	ItemGroup_Others      ItemGroup = 0 // 其他
	ItemGroup_RawMaterial ItemGroup = 1 // 原材料
	ItemGroup_Products    ItemGroup = 2 // 商品
)

// Enum value maps for ItemGroup.
var (
	ItemGroup_name = map[int32]string{
		0: "Others",
		1: "RawMaterial",
		2: "Products",
	}
	ItemGroup_value = map[string]int32{
		"Others":      0,
		"RawMaterial": 1,
		"Products":    2,
	}
)

func (x ItemGroup) Enum() *ItemGroup {
	p := new(ItemGroup)
	*p = x
	return p
}

func (x ItemGroup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemGroup) Descriptor() protoreflect.EnumDescriptor {
	return file_item_item_proto_enumTypes[0].Descriptor()
}

func (ItemGroup) Type() protoreflect.EnumType {
	return &file_item_item_proto_enumTypes[0]
}

func (x ItemGroup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemGroup.Descriptor instead.
func (ItemGroup) EnumDescriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{0}
}

type GetItemListReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemGroup      ItemGroup              `protobuf:"varint,1,opt,name=item_group,json=itemGroup,proto3,enum=item.ItemGroup" json:"item_group,omitempty" dc:"物品分组，可选  Products 商品/Raw Material 原材料"` // 物品分组，可选  Products 商品/Raw Material 原材料
	ItemName       string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty" dc:"商品名称模糊查询，可选，如: %商品名称%"`                                         // 商品名称模糊查询，可选，如: %商品名称%
	Branch         string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                                                                           // 分支名称，可选
	CompanyAbbr    string                 `protobuf:"bytes,4,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司简称，可选"`                                              // 公司简称，可选
	ItemCode       string                 `protobuf:"bytes,5,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty" dc:"物品编码，可选"`                                                       // 物品编码，可选
	ItemCodePrefix string                 `protobuf:"bytes,6,opt,name=item_code_prefix,json=itemCodePrefix,proto3" json:"item_code_prefix,omitempty" dc:"物品编码前缀，可选"`                                 // 物品编码前缀，可选
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetItemListReq) Reset() {
	*x = GetItemListReq{}
	mi := &file_item_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemListReq) ProtoMessage() {}

func (x *GetItemListReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemListReq.ProtoReflect.Descriptor instead.
func (*GetItemListReq) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{0}
}

func (x *GetItemListReq) GetItemGroup() ItemGroup {
	if x != nil {
		return x.ItemGroup
	}
	return ItemGroup_Others
}

func (x *GetItemListReq) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *GetItemListReq) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetItemListReq) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *GetItemListReq) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *GetItemListReq) GetItemCodePrefix() string {
	if x != nil {
		return x.ItemCodePrefix
	}
	return ""
}

type GetItemListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemList      []*ItemInfo            `protobuf:"bytes,1,rep,name=item_list,json=itemList,proto3" json:"item_list,omitempty" dc:"物品列表"` // 物品列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemListResp) Reset() {
	*x = GetItemListResp{}
	mi := &file_item_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemListResp) ProtoMessage() {}

func (x *GetItemListResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemListResp.ProtoReflect.Descriptor instead.
func (*GetItemListResp) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemListResp) GetItemList() []*ItemInfo {
	if x != nil {
		return x.ItemList
	}
	return nil
}

type ItemInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ItemName          string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty" dc:"物品名称，必填"`                                                      // 物品名称，必填
	ItemGroup         ItemGroup              `protobuf:"varint,2,opt,name=item_group,json=itemGroup,proto3,enum=item.ItemGroup" json:"item_group,omitempty" dc:"物品分组，必填 Products 商品/Raw Material 原材料"` // 物品分组，必填 Products 商品/Raw Material 原材料
	StockUom          string                 `protobuf:"bytes,3,opt,name=stock_uom,json=stockUom,proto3" json:"stock_uom,omitempty" dc:"库存单位，必填 ttpos 传英文过来"`                                          // 库存单位，必填 ttpos 传英文过来
	ItemCode          string                 `protobuf:"bytes,4,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty" dc:"物品编码，可选"`                                                      // 物品编码，可选
	ValuationRate     float32                `protobuf:"fixed32,5,opt,name=valuation_rate,json=valuationRate,proto3" json:"valuation_rate,omitempty" dc:"估值率，可选, 原材料必填"`                               // 估值率，可选, 原材料必填
	Barcode           string                 `protobuf:"bytes,6,opt,name=barcode,proto3" json:"barcode,omitempty" dc:"条码，可选"`                                                                          // 条码，可选
	OpeningStock      float32                `protobuf:"fixed32,7,opt,name=opening_stock,json=openingStock,proto3" json:"opening_stock,omitempty" dc:"期初库存，可选"`                                        // 期初库存，可选
	IsStockItem       bool                   `protobuf:"varint,8,opt,name=is_stock_item,json=isStockItem,proto3" json:"is_stock_item,omitempty" dc:"是否库存物品，可选"`                                        // 是否库存物品，可选
	TemplateItemCode  string                 `protobuf:"bytes,9,opt,name=template_item_code,json=templateItemCode,proto3" json:"template_item_code,omitempty" dc:"模版物品编码，可选， 多规格商品时必填，传原始物品编码"`        // 模版物品编码，可选， 多规格商品时必填，传原始物品编码
	Branch            string                 `protobuf:"bytes,10,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                                                                         // 分支名称，可选
	CompanyAbbr       string                 `protobuf:"bytes,11,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司简称，可选"`                                            // 公司简称，可选
	Company           string                 `protobuf:"bytes,12,opt,name=company,proto3" json:"company,omitempty" dc:"公司名称，可选"`                                                                       // 公司名称，可选
	ItemSpecification string                 `protobuf:"bytes,13,opt,name=item_specification,json=itemSpecification,proto3" json:"item_specification,omitempty" dc:"物品规格，可选 ttpos 传英文过来 多规格商品时必填"`     // 物品规格，可选 ttpos 传英文过来 多规格商品时必填
	Uoms              []*UomDetail           `protobuf:"bytes,14,rep,name=uoms,proto3" json:"uoms,omitempty" dc:"单位列表，可选"`                                                                             // 单位列表，可选
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	mi := &file_item_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{2}
}

func (x *ItemInfo) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ItemInfo) GetItemGroup() ItemGroup {
	if x != nil {
		return x.ItemGroup
	}
	return ItemGroup_Others
}

func (x *ItemInfo) GetStockUom() string {
	if x != nil {
		return x.StockUom
	}
	return ""
}

func (x *ItemInfo) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *ItemInfo) GetValuationRate() float32 {
	if x != nil {
		return x.ValuationRate
	}
	return 0
}

func (x *ItemInfo) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *ItemInfo) GetOpeningStock() float32 {
	if x != nil {
		return x.OpeningStock
	}
	return 0
}

func (x *ItemInfo) GetIsStockItem() bool {
	if x != nil {
		return x.IsStockItem
	}
	return false
}

func (x *ItemInfo) GetTemplateItemCode() string {
	if x != nil {
		return x.TemplateItemCode
	}
	return ""
}

func (x *ItemInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ItemInfo) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *ItemInfo) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *ItemInfo) GetItemSpecification() string {
	if x != nil {
		return x.ItemSpecification
	}
	return ""
}

func (x *ItemInfo) GetUoms() []*UomDetail {
	if x != nil {
		return x.Uoms
	}
	return nil
}

type UomDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uom              string                 `protobuf:"bytes,1,opt,name=uom,proto3" json:"uom,omitempty" dc:"单位名称，必填"`                                                          // 单位名称，必填
	ConversionFactor float32                `protobuf:"fixed32,2,opt,name=conversion_factor,json=conversionFactor,proto3" json:"conversion_factor,omitempty" dc:"转换比率，相对于基准单位"` // 转换比率，相对于基准单位
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UomDetail) Reset() {
	*x = UomDetail{}
	mi := &file_item_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UomDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UomDetail) ProtoMessage() {}

func (x *UomDetail) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UomDetail.ProtoReflect.Descriptor instead.
func (*UomDetail) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{3}
}

func (x *UomDetail) GetUom() string {
	if x != nil {
		return x.Uom
	}
	return ""
}

func (x *UomDetail) GetConversionFactor() float32 {
	if x != nil {
		return x.ConversionFactor
	}
	return 0
}

type GetItemGroupListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`       // 分支名称，可选
	ItemGroup     string                 `protobuf:"bytes,2,opt,name=ItemGroup,proto3" json:"ItemGroup,omitempty" dc:"物品分组，可选"` // 物品分组，可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemGroupListReq) Reset() {
	*x = GetItemGroupListReq{}
	mi := &file_item_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemGroupListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemGroupListReq) ProtoMessage() {}

func (x *GetItemGroupListReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemGroupListReq.ProtoReflect.Descriptor instead.
func (*GetItemGroupListReq) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{4}
}

func (x *GetItemGroupListReq) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetItemGroupListReq) GetItemGroup() string {
	if x != nil {
		return x.ItemGroup
	}
	return ""
}

type GetItemGroupListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`       // 分支名称，可选
	ItemGroup     string                 `protobuf:"bytes,2,opt,name=ItemGroup,proto3" json:"ItemGroup,omitempty" dc:"物品分组，可选"` // 物品分组，可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemGroupListResp) Reset() {
	*x = GetItemGroupListResp{}
	mi := &file_item_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemGroupListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemGroupListResp) ProtoMessage() {}

func (x *GetItemGroupListResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemGroupListResp.ProtoReflect.Descriptor instead.
func (*GetItemGroupListResp) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{5}
}

func (x *GetItemGroupListResp) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetItemGroupListResp) GetItemGroup() string {
	if x != nil {
		return x.ItemGroup
	}
	return ""
}

type GetUomListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                              // 分支名称，可选
	CompanyAbbr   string                 `protobuf:"bytes,2,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司简称，可选"` // 公司简称，可选
	UomName       string                 `protobuf:"bytes,3,opt,name=uom_name,json=uomName,proto3" json:"uom_name,omitempty" dc:"单位名称，可选"`             // 单位名称，可选
	AliasName     string                 `protobuf:"bytes,4,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty" dc:"单位别名，可选"`       // 单位别名，可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUomListReq) Reset() {
	*x = GetUomListReq{}
	mi := &file_item_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUomListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUomListReq) ProtoMessage() {}

func (x *GetUomListReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUomListReq.ProtoReflect.Descriptor instead.
func (*GetUomListReq) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{6}
}

func (x *GetUomListReq) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetUomListReq) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *GetUomListReq) GetUomName() string {
	if x != nil {
		return x.UomName
	}
	return ""
}

func (x *GetUomListReq) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

type GetUomListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UomList       []*UomInfo             `protobuf:"bytes,1,rep,name=uom_list,json=uomList,proto3" json:"uom_list,omitempty" dc:"单位列表"` //单位列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUomListResp) Reset() {
	*x = GetUomListResp{}
	mi := &file_item_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUomListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUomListResp) ProtoMessage() {}

func (x *GetUomListResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUomListResp.ProtoReflect.Descriptor instead.
func (*GetUomListResp) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{7}
}

func (x *GetUomListResp) GetUomList() []*UomInfo {
	if x != nil {
		return x.UomList
	}
	return nil
}

type UomInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UomName           string                 `protobuf:"bytes,1,opt,name=uom_name,json=uomName,proto3" json:"uom_name,omitempty" dc:"单位名称，必填"`                                    // 单位名称，必填
	Branch            string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                                                     // 分支名称，可选
	CompanyAbbr       string                 `protobuf:"bytes,3,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司简称，可选"`                        // 公司简称，可选
	Company           string                 `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty" dc:"公司名称，可选"`                                                   // 公司名称，可选
	AliasName         string                 `protobuf:"bytes,5,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty" dc:"单位别名，可选"`                              // 单位别名，可选
	MustBeWholeNumber bool                   `protobuf:"varint,6,opt,name=must_be_whole_number,json=mustBeWholeNumber,proto3" json:"must_be_whole_number,omitempty" dc:"是否必须为整数"` // 是否必须为整数
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UomInfo) Reset() {
	*x = UomInfo{}
	mi := &file_item_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UomInfo) ProtoMessage() {}

func (x *UomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UomInfo.ProtoReflect.Descriptor instead.
func (*UomInfo) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{8}
}

func (x *UomInfo) GetUomName() string {
	if x != nil {
		return x.UomName
	}
	return ""
}

func (x *UomInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *UomInfo) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *UomInfo) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *UomInfo) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

func (x *UomInfo) GetMustBeWholeNumber() bool {
	if x != nil {
		return x.MustBeWholeNumber
	}
	return false
}

type GetAttributeListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                                    // 分支名称，可选
	CompanyAbbr   string                 `protobuf:"bytes,2,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司简称，可选"`       // 公司简称，可选
	AttributeName string                 `protobuf:"bytes,3,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty" dc:"属性名称，可选"` // 属性名称，可选
	AliasName     string                 `protobuf:"bytes,4,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty" dc:"属性别名，可选"`             // 属性别名，可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributeListReq) Reset() {
	*x = GetAttributeListReq{}
	mi := &file_item_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeListReq) ProtoMessage() {}

func (x *GetAttributeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeListReq.ProtoReflect.Descriptor instead.
func (*GetAttributeListReq) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{9}
}

func (x *GetAttributeListReq) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetAttributeListReq) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *GetAttributeListReq) GetAttributeName() string {
	if x != nil {
		return x.AttributeName
	}
	return ""
}

func (x *GetAttributeListReq) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

type AttributeInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AttributeName      string                 `protobuf:"bytes,1,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty" dc:"属性名称，必填"`                // 属性名称，必填
	Branch             string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                                                   // 分支名称，可选
	Company            string                 `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty" dc:"公司名称，可选"`                                                 // 公司名称，可选
	CompanyAbbr        string                 `protobuf:"bytes,4,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司简称，可选"`                      // 公司简称，可选
	AliasName          string                 `protobuf:"bytes,5,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty" dc:"属性别名，可选"`                            // 属性别名，可选
	AttributeValueList []*AttributeValueInfo  `protobuf:"bytes,6,rep,name=attribute_value_list,json=attributeValueList,proto3" json:"attribute_value_list,omitempty" dc:"属性值列表"` // 属性值列表
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AttributeInfo) Reset() {
	*x = AttributeInfo{}
	mi := &file_item_item_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeInfo) ProtoMessage() {}

func (x *AttributeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeInfo.ProtoReflect.Descriptor instead.
func (*AttributeInfo) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{10}
}

func (x *AttributeInfo) GetAttributeName() string {
	if x != nil {
		return x.AttributeName
	}
	return ""
}

func (x *AttributeInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *AttributeInfo) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *AttributeInfo) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *AttributeInfo) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

func (x *AttributeInfo) GetAttributeValueList() []*AttributeValueInfo {
	if x != nil {
		return x.AttributeValueList
	}
	return nil
}

type AttributeValueInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AttributeValue string                 `protobuf:"bytes,1,opt,name=attribute_value,json=attributeValue,proto3" json:"attribute_value,omitempty" dc:"属性值，必填"` // 属性值，必填
	Abbr           string                 `protobuf:"bytes,2,opt,name=abbr,proto3" json:"abbr,omitempty" dc:"属性缩写，必填"`                                          // 属性缩写，必填
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AttributeValueInfo) Reset() {
	*x = AttributeValueInfo{}
	mi := &file_item_item_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValueInfo) ProtoMessage() {}

func (x *AttributeValueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValueInfo.ProtoReflect.Descriptor instead.
func (*AttributeValueInfo) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{11}
}

func (x *AttributeValueInfo) GetAttributeValue() string {
	if x != nil {
		return x.AttributeValue
	}
	return ""
}

func (x *AttributeValueInfo) GetAbbr() string {
	if x != nil {
		return x.Abbr
	}
	return ""
}

type GetAttributeListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttributeList []*AttributeInfo       `protobuf:"bytes,1,rep,name=attribute_list,json=attributeList,proto3" json:"attribute_list,omitempty" dc:"属性列表"` // 属性列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributeListResp) Reset() {
	*x = GetAttributeListResp{}
	mi := &file_item_item_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeListResp) ProtoMessage() {}

func (x *GetAttributeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeListResp.ProtoReflect.Descriptor instead.
func (*GetAttributeListResp) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{12}
}

func (x *GetAttributeListResp) GetAttributeList() []*AttributeInfo {
	if x != nil {
		return x.AttributeList
	}
	return nil
}

var File_item_item_proto protoreflect.FileDescriptor

const file_item_item_proto_rawDesc = "" +
	"\n" +
	"\x0fitem/item.proto\x12\x04item\x1a\terp.proto\"\xdf\x01\n" +
	"\x0eGetItemListReq\x12.\n" +
	"\n" +
	"item_group\x18\x01 \x01(\x0e2\x0f.item.ItemGroupR\titemGroup\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12!\n" +
	"\fcompany_abbr\x18\x04 \x01(\tR\vcompanyAbbr\x12\x1b\n" +
	"\titem_code\x18\x05 \x01(\tR\bitemCode\x12(\n" +
	"\x10item_code_prefix\x18\x06 \x01(\tR\x0eitemCodePrefix\">\n" +
	"\x0fGetItemListResp\x12+\n" +
	"\titem_list\x18\x01 \x03(\v2\x0e.item.ItemInfoR\bitemList\"\xf2\x03\n" +
	"\bItemInfo\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12.\n" +
	"\n" +
	"item_group\x18\x02 \x01(\x0e2\x0f.item.ItemGroupR\titemGroup\x12\x1b\n" +
	"\tstock_uom\x18\x03 \x01(\tR\bstockUom\x12\x1b\n" +
	"\titem_code\x18\x04 \x01(\tR\bitemCode\x12%\n" +
	"\x0evaluation_rate\x18\x05 \x01(\x02R\rvaluationRate\x12\x18\n" +
	"\abarcode\x18\x06 \x01(\tR\abarcode\x12#\n" +
	"\ropening_stock\x18\a \x01(\x02R\fopeningStock\x12\"\n" +
	"\ris_stock_item\x18\b \x01(\bR\visStockItem\x12,\n" +
	"\x12template_item_code\x18\t \x01(\tR\x10templateItemCode\x12\x16\n" +
	"\x06branch\x18\n" +
	" \x01(\tR\x06branch\x12!\n" +
	"\fcompany_abbr\x18\v \x01(\tR\vcompanyAbbr\x12\x18\n" +
	"\acompany\x18\f \x01(\tR\acompany\x12-\n" +
	"\x12item_specification\x18\r \x01(\tR\x11itemSpecification\x12#\n" +
	"\x04uoms\x18\x0e \x03(\v2\x0f.item.UomDetailR\x04uoms\"J\n" +
	"\tUomDetail\x12\x10\n" +
	"\x03uom\x18\x01 \x01(\tR\x03uom\x12+\n" +
	"\x11conversion_factor\x18\x02 \x01(\x02R\x10conversionFactor\"K\n" +
	"\x13GetItemGroupListReq\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\x12\x1c\n" +
	"\tItemGroup\x18\x02 \x01(\tR\tItemGroup\"L\n" +
	"\x14GetItemGroupListResp\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\x12\x1c\n" +
	"\tItemGroup\x18\x02 \x01(\tR\tItemGroup\"\x84\x01\n" +
	"\rGetUomListReq\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\x12!\n" +
	"\fcompany_abbr\x18\x02 \x01(\tR\vcompanyAbbr\x12\x19\n" +
	"\buom_name\x18\x03 \x01(\tR\auomName\x12\x1d\n" +
	"\n" +
	"alias_name\x18\x04 \x01(\tR\taliasName\":\n" +
	"\x0eGetUomListResp\x12(\n" +
	"\buom_list\x18\x01 \x03(\v2\r.item.UomInfoR\auomList\"\xc9\x01\n" +
	"\aUomInfo\x12\x19\n" +
	"\buom_name\x18\x01 \x01(\tR\auomName\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12!\n" +
	"\fcompany_abbr\x18\x03 \x01(\tR\vcompanyAbbr\x12\x18\n" +
	"\acompany\x18\x04 \x01(\tR\acompany\x12\x1d\n" +
	"\n" +
	"alias_name\x18\x05 \x01(\tR\taliasName\x12/\n" +
	"\x14must_be_whole_number\x18\x06 \x01(\bR\x11mustBeWholeNumber\"\x96\x01\n" +
	"\x13GetAttributeListReq\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\x12!\n" +
	"\fcompany_abbr\x18\x02 \x01(\tR\vcompanyAbbr\x12%\n" +
	"\x0eattribute_name\x18\x03 \x01(\tR\rattributeName\x12\x1d\n" +
	"\n" +
	"alias_name\x18\x04 \x01(\tR\taliasName\"\xf6\x01\n" +
	"\rAttributeInfo\x12%\n" +
	"\x0eattribute_name\x18\x01 \x01(\tR\rattributeName\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x18\n" +
	"\acompany\x18\x03 \x01(\tR\acompany\x12!\n" +
	"\fcompany_abbr\x18\x04 \x01(\tR\vcompanyAbbr\x12\x1d\n" +
	"\n" +
	"alias_name\x18\x05 \x01(\tR\taliasName\x12J\n" +
	"\x14attribute_value_list\x18\x06 \x03(\v2\x18.item.AttributeValueInfoR\x12attributeValueList\"Q\n" +
	"\x12AttributeValueInfo\x12'\n" +
	"\x0fattribute_value\x18\x01 \x01(\tR\x0eattributeValue\x12\x12\n" +
	"\x04abbr\x18\x02 \x01(\tR\x04abbr\"R\n" +
	"\x14GetAttributeListResp\x12:\n" +
	"\x0eattribute_list\x18\x01 \x03(\v2\x13.item.AttributeInfoR\rattributeList*6\n" +
	"\tItemGroup\x12\n" +
	"\n" +
	"\x06Others\x10\x00\x12\x0f\n" +
	"\vRawMaterial\x10\x01\x12\f\n" +
	"\bProducts\x10\x022\xd2\x02\n" +
	"\vItemService\x126\n" +
	"\vGetItemList\x12\x14.item.GetItemListReq\x1a\x11.erp.ResponseInfo\x124\n" +
	"\n" +
	"GetUomList\x12\x13.item.GetUomListReq\x1a\x11.erp.ResponseInfo\x12+\n" +
	"\aSaveUom\x12\r.item.UomInfo\x1a\x11.erp.ResponseInfo\x12@\n" +
	"\x10GetAttributeList\x12\x19.item.GetAttributeListReq\x1a\x11.erp.ResponseInfo\x127\n" +
	"\rSaveAttribute\x12\x13.item.AttributeInfo\x1a\x11.erp.ResponseInfo\x12-\n" +
	"\bSaveItem\x12\x0e.item.ItemInfo\x1a\x11.erp.ResponseInfoB\"Z ttpos-bmp/app/ttpos-erp/api/itemb\x06proto3"

var (
	file_item_item_proto_rawDescOnce sync.Once
	file_item_item_proto_rawDescData []byte
)

func file_item_item_proto_rawDescGZIP() []byte {
	file_item_item_proto_rawDescOnce.Do(func() {
		file_item_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_item_proto_rawDesc), len(file_item_item_proto_rawDesc)))
	})
	return file_item_item_proto_rawDescData
}

var file_item_item_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_item_item_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_item_item_proto_goTypes = []any{
	(ItemGroup)(0),               // 0: item.ItemGroup
	(*GetItemListReq)(nil),       // 1: item.GetItemListReq
	(*GetItemListResp)(nil),      // 2: item.GetItemListResp
	(*ItemInfo)(nil),             // 3: item.ItemInfo
	(*UomDetail)(nil),            // 4: item.UomDetail
	(*GetItemGroupListReq)(nil),  // 5: item.GetItemGroupListReq
	(*GetItemGroupListResp)(nil), // 6: item.GetItemGroupListResp
	(*GetUomListReq)(nil),        // 7: item.GetUomListReq
	(*GetUomListResp)(nil),       // 8: item.GetUomListResp
	(*UomInfo)(nil),              // 9: item.UomInfo
	(*GetAttributeListReq)(nil),  // 10: item.GetAttributeListReq
	(*AttributeInfo)(nil),        // 11: item.AttributeInfo
	(*AttributeValueInfo)(nil),   // 12: item.AttributeValueInfo
	(*GetAttributeListResp)(nil), // 13: item.GetAttributeListResp
	(*api.ResponseInfo)(nil),     // 14: erp.ResponseInfo
}
var file_item_item_proto_depIdxs = []int32{
	0,  // 0: item.GetItemListReq.item_group:type_name -> item.ItemGroup
	3,  // 1: item.GetItemListResp.item_list:type_name -> item.ItemInfo
	0,  // 2: item.ItemInfo.item_group:type_name -> item.ItemGroup
	4,  // 3: item.ItemInfo.uoms:type_name -> item.UomDetail
	9,  // 4: item.GetUomListResp.uom_list:type_name -> item.UomInfo
	12, // 5: item.AttributeInfo.attribute_value_list:type_name -> item.AttributeValueInfo
	11, // 6: item.GetAttributeListResp.attribute_list:type_name -> item.AttributeInfo
	1,  // 7: item.ItemService.GetItemList:input_type -> item.GetItemListReq
	7,  // 8: item.ItemService.GetUomList:input_type -> item.GetUomListReq
	9,  // 9: item.ItemService.SaveUom:input_type -> item.UomInfo
	10, // 10: item.ItemService.GetAttributeList:input_type -> item.GetAttributeListReq
	11, // 11: item.ItemService.SaveAttribute:input_type -> item.AttributeInfo
	3,  // 12: item.ItemService.SaveItem:input_type -> item.ItemInfo
	14, // 13: item.ItemService.GetItemList:output_type -> erp.ResponseInfo
	14, // 14: item.ItemService.GetUomList:output_type -> erp.ResponseInfo
	14, // 15: item.ItemService.SaveUom:output_type -> erp.ResponseInfo
	14, // 16: item.ItemService.GetAttributeList:output_type -> erp.ResponseInfo
	14, // 17: item.ItemService.SaveAttribute:output_type -> erp.ResponseInfo
	14, // 18: item.ItemService.SaveItem:output_type -> erp.ResponseInfo
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_item_item_proto_init() }
func file_item_item_proto_init() {
	if File_item_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_item_proto_rawDesc), len(file_item_item_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_item_item_proto_goTypes,
		DependencyIndexes: file_item_item_proto_depIdxs,
		EnumInfos:         file_item_item_proto_enumTypes,
		MessageInfos:      file_item_item_proto_msgTypes,
	}.Build()
	File_item_item_proto = out.File
	file_item_item_proto_goTypes = nil
	file_item_item_proto_depIdxs = nil
}
