// ItemGroup 服务 Protobuf 定义文件
// 用于定义物品分组相关的 gRPC 服务接口和消息结构

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: item/item_group.proto

package item

import (
	reflect "reflect"
	sync "sync"
	api "ttpos-bmp/app/ttpos-erp/api"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取物品分组列表请求消息
type GetItemGroupListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Branch          string `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                                              // 分支名称，可选
	CompanyAbbr     string `protobuf:"bytes,2,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司缩写，可选"`                 // 公司缩写，可选
	ParentItemGroup string `protobuf:"bytes,3,opt,name=parent_item_group,json=parentItemGroup,proto3" json:"parent_item_group,omitempty" dc:"分组名称查询，可选"` // 分组名称查询，可选
}

func (x *GetItemGroupListReq) Reset() {
	*x = GetItemGroupListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemGroupListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemGroupListReq) ProtoMessage() {}

func (x *GetItemGroupListReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemGroupListReq.ProtoReflect.Descriptor instead.
func (*GetItemGroupListReq) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{0}
}

func (x *GetItemGroupListReq) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetItemGroupListReq) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *GetItemGroupListReq) GetParentItemGroup() string {
	if x != nil {
		return x.ParentItemGroup
	}
	return ""
}

// 获取物品分组列表响应消息
type GetItemGroupListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemGroupList []*ItemGroupInfo `protobuf:"bytes,1,rep,name=item_group_list,json=itemGroupList,proto3" json:"item_group_list,omitempty" dc:"物品分组列表"` // 物品分组列表
}

func (x *GetItemGroupListResp) Reset() {
	*x = GetItemGroupListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemGroupListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemGroupListResp) ProtoMessage() {}

func (x *GetItemGroupListResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemGroupListResp.ProtoReflect.Descriptor instead.
func (*GetItemGroupListResp) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemGroupListResp) GetItemGroupList() []*ItemGroupInfo {
	if x != nil {
		return x.ItemGroupList
	}
	return nil
}

// 获取单个物品分组请求消息
type GetItemGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupCode string `protobuf:"bytes,1,opt,name=group_code,json=groupCode,proto3" json:"group_code,omitempty" dc:"分组代码，必填"` // 分组代码，必填
}

func (x *GetItemGroupReq) Reset() {
	*x = GetItemGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemGroupReq) ProtoMessage() {}

func (x *GetItemGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemGroupReq.ProtoReflect.Descriptor instead.
func (*GetItemGroupReq) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{2}
}

func (x *GetItemGroupReq) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

type GetItemGroupResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemGroupInfo *ItemGroupInfo `protobuf:"bytes,1,opt,name=item_group_info,json=itemGroupInfo,proto3" json:"item_group_info,omitempty" dc:"物品分组信息，必填"` // 物品分组信息，必填
}

func (x *GetItemGroupResp) Reset() {
	*x = GetItemGroupResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemGroupResp) ProtoMessage() {}

func (x *GetItemGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemGroupResp.ProtoReflect.Descriptor instead.
func (*GetItemGroupResp) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{3}
}

func (x *GetItemGroupResp) GetItemGroupInfo() *ItemGroupInfo {
	if x != nil {
		return x.ItemGroupInfo
	}
	return nil
}

// 保存物品分组请求消息
type SaveItemGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemGroupInfo *ItemGroupInfo `protobuf:"bytes,1,opt,name=item_group_info,json=itemGroupInfo,proto3" json:"item_group_info,omitempty" dc:"物品分组信息，必填"` // 物品分组信息，必填
}

func (x *SaveItemGroupReq) Reset() {
	*x = SaveItemGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveItemGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveItemGroupReq) ProtoMessage() {}

func (x *SaveItemGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveItemGroupReq.ProtoReflect.Descriptor instead.
func (*SaveItemGroupReq) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{4}
}

func (x *SaveItemGroupReq) GetItemGroupInfo() *ItemGroupInfo {
	if x != nil {
		return x.ItemGroupInfo
	}
	return nil
}

type SaveItemGroupResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemGroupInfo *ItemGroupInfo `protobuf:"bytes,1,opt,name=item_group_info,json=itemGroupInfo,proto3" json:"item_group_info,omitempty" dc:"物品分组信息，必填"` // 物品分组信息，必填
}

func (x *SaveItemGroupResp) Reset() {
	*x = SaveItemGroupResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveItemGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveItemGroupResp) ProtoMessage() {}

func (x *SaveItemGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveItemGroupResp.ProtoReflect.Descriptor instead.
func (*SaveItemGroupResp) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{5}
}

func (x *SaveItemGroupResp) GetItemGroupInfo() *ItemGroupInfo {
	if x != nil {
		return x.ItemGroupInfo
	}
	return nil
}

// 删除物品分组请求消息
type DeleteItemGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemGroupName string `protobuf:"bytes,1,opt,name=item_group_name,json=itemGroupName,proto3" json:"item_group_name,omitempty" dc:"分组名，必填"` // 分组名，必填
}

func (x *DeleteItemGroupReq) Reset() {
	*x = DeleteItemGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteItemGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemGroupReq) ProtoMessage() {}

func (x *DeleteItemGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemGroupReq.ProtoReflect.Descriptor instead.
func (*DeleteItemGroupReq) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteItemGroupReq) GetItemGroupName() string {
	if x != nil {
		return x.ItemGroupName
	}
	return ""
}

// 物品分组信息消息
type ItemGroupInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemGroupName   string `protobuf:"bytes,1,opt,name=item_group_name,json=itemGroupName,proto3" json:"item_group_name,omitempty" dc:"分组名称，必填"`       // 分组名称，必填
	ParentItemGroup string `protobuf:"bytes,2,opt,name=parent_item_group,json=parentItemGroup,proto3" json:"parent_item_group,omitempty" dc:"父级分组，可选"` // 父级分组，可选
	CompanyAbbr     string `protobuf:"bytes,3,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司缩写，可选"`               // 公司缩写，可选
	IsGroup         bool   `protobuf:"varint,4,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty" dc:"是否为分组，可选"`                         // 是否为分组，可选
	Branch          string `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                                            // 分支名称，可选
	AliasName       string `protobuf:"bytes,6,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty" dc:"别名，可选"`                       // 别名，可选
}

func (x *ItemGroupInfo) Reset() {
	*x = ItemGroupInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemGroupInfo) ProtoMessage() {}

func (x *ItemGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemGroupInfo.ProtoReflect.Descriptor instead.
func (*ItemGroupInfo) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{7}
}

func (x *ItemGroupInfo) GetItemGroupName() string {
	if x != nil {
		return x.ItemGroupName
	}
	return ""
}

func (x *ItemGroupInfo) GetParentItemGroup() string {
	if x != nil {
		return x.ParentItemGroup
	}
	return ""
}

func (x *ItemGroupInfo) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *ItemGroupInfo) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

func (x *ItemGroupInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ItemGroupInfo) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

type AttributeGroupInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AliasName         string               `protobuf:"bytes,1,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty" dc:"别名，必填"`                               // 别名，必填
	CompanyAbbr       string               `protobuf:"bytes,2,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司缩写，可选"`                       // 公司缩写，可选
	Branch            string               `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                                                    // 分支名称，可选
	GroupName         string               `protobuf:"bytes,4,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty" dc:"分组名称，修改时必填"`                          // 分组名称，修改时必填
	AttributeItemList []*AttributeItemInfo `protobuf:"bytes,5,rep,name=attribute_item_list,json=attributeItemList,proto3" json:"attribute_item_list,omitempty" dc:"属性物品列表，必填"` // 属性物品列表，必填
}

func (x *AttributeGroupInfo) Reset() {
	*x = AttributeGroupInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeGroupInfo) ProtoMessage() {}

func (x *AttributeGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeGroupInfo.ProtoReflect.Descriptor instead.
func (*AttributeGroupInfo) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{8}
}

func (x *AttributeGroupInfo) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

func (x *AttributeGroupInfo) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *AttributeGroupInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *AttributeGroupInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *AttributeGroupInfo) GetAttributeItemList() []*AttributeItemInfo {
	if x != nil {
		return x.AttributeItemList
	}
	return nil
}

type AttributeItemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AliasName string `protobuf:"bytes,1,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty" dc:"物品别名，必填"` // 物品别名，必填
	ItemCode  string `protobuf:"bytes,2,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty" dc:"物品编码，创建时必填"` // 物品编码，创建时必填
}

func (x *AttributeItemInfo) Reset() {
	*x = AttributeItemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeItemInfo) ProtoMessage() {}

func (x *AttributeItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeItemInfo.ProtoReflect.Descriptor instead.
func (*AttributeItemInfo) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{9}
}

func (x *AttributeItemInfo) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

func (x *AttributeItemInfo) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

type SaveAttributeGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttributeGroupInfo *AttributeGroupInfo `protobuf:"bytes,1,opt,name=attribute_group_info,json=attributeGroupInfo,proto3" json:"attribute_group_info,omitempty" dc:"属性分组信息，必填"` // 属性分组信息，必填
}

func (x *SaveAttributeGroupReq) Reset() {
	*x = SaveAttributeGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveAttributeGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAttributeGroupReq) ProtoMessage() {}

func (x *SaveAttributeGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAttributeGroupReq.ProtoReflect.Descriptor instead.
func (*SaveAttributeGroupReq) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{10}
}

func (x *SaveAttributeGroupReq) GetAttributeGroupInfo() *AttributeGroupInfo {
	if x != nil {
		return x.AttributeGroupInfo
	}
	return nil
}

type DeleteAttributeGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty" dc:"分组名称，必填"` // 分组名称，必填
}

func (x *DeleteAttributeGroupReq) Reset() {
	*x = DeleteAttributeGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAttributeGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttributeGroupReq) ProtoMessage() {}

func (x *DeleteAttributeGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttributeGroupReq.ProtoReflect.Descriptor instead.
func (*DeleteAttributeGroupReq) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAttributeGroupReq) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type SaveAttributeGroupResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttributeGroupInfo *AttributeGroupInfo `protobuf:"bytes,1,opt,name=attribute_group_info,json=attributeGroupInfo,proto3" json:"attribute_group_info,omitempty" dc:"属性分组信息，必填"` // 属性分组信息，必填
}

func (x *SaveAttributeGroupResp) Reset() {
	*x = SaveAttributeGroupResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveAttributeGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAttributeGroupResp) ProtoMessage() {}

func (x *SaveAttributeGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAttributeGroupResp.ProtoReflect.Descriptor instead.
func (*SaveAttributeGroupResp) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{12}
}

func (x *SaveAttributeGroupResp) GetAttributeGroupInfo() *AttributeGroupInfo {
	if x != nil {
		return x.AttributeGroupInfo
	}
	return nil
}

type AddonGroupInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// string alias_name = 1; // 别名，必填
	CompanyAbbr   string           `protobuf:"bytes,1,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"string alias_name = 1; // 别名，必填公司缩写，可选"` // 公司缩写，可选
	Branch        string           `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                                                             // 分支名称，可选
	GroupName     string           `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty" dc:"分组名称，修改时必填"`                                   // 分组名称，修改时必填
	AddonItemList []*AddonItemInfo `protobuf:"bytes,4,rep,name=addon_item_list,json=addonItemList,proto3" json:"addon_item_list,omitempty" dc:"加料物品列表，必填"`                      // 加料物品列表，必填
}

func (x *AddonGroupInfo) Reset() {
	*x = AddonGroupInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddonGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddonGroupInfo) ProtoMessage() {}

func (x *AddonGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddonGroupInfo.ProtoReflect.Descriptor instead.
func (*AddonGroupInfo) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{13}
}

func (x *AddonGroupInfo) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *AddonGroupInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *AddonGroupInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *AddonGroupInfo) GetAddonItemList() []*AddonItemInfo {
	if x != nil {
		return x.AddonItemList
	}
	return nil
}

type AddonItemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemCode  string `protobuf:"bytes,1,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty" dc:"物品编码，必填"`    // 物品编码，必填
	AliasName string `protobuf:"bytes,2,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty" dc:"物品别名，必填"` // 物品别名，必填
}

func (x *AddonItemInfo) Reset() {
	*x = AddonItemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddonItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddonItemInfo) ProtoMessage() {}

func (x *AddonItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddonItemInfo.ProtoReflect.Descriptor instead.
func (*AddonItemInfo) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{14}
}

func (x *AddonItemInfo) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *AddonItemInfo) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

type SaveAddonGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddonGroupInfo *AddonGroupInfo `protobuf:"bytes,1,opt,name=addon_group_info,json=addonGroupInfo,proto3" json:"addon_group_info,omitempty" dc:"加料分组信息，必填"` // 加料分组信息，必填
}

func (x *SaveAddonGroupReq) Reset() {
	*x = SaveAddonGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveAddonGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAddonGroupReq) ProtoMessage() {}

func (x *SaveAddonGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAddonGroupReq.ProtoReflect.Descriptor instead.
func (*SaveAddonGroupReq) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{15}
}

func (x *SaveAddonGroupReq) GetAddonGroupInfo() *AddonGroupInfo {
	if x != nil {
		return x.AddonGroupInfo
	}
	return nil
}

type SaveAddonGroupResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddonGroupInfo *AddonGroupInfo `protobuf:"bytes,1,opt,name=addon_group_info,json=addonGroupInfo,proto3" json:"addon_group_info,omitempty" dc:"加料分组信息，必填"` // 加料分组信息，必填
}

func (x *SaveAddonGroupResp) Reset() {
	*x = SaveAddonGroupResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_item_group_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveAddonGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAddonGroupResp) ProtoMessage() {}

func (x *SaveAddonGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_group_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAddonGroupResp.ProtoReflect.Descriptor instead.
func (*SaveAddonGroupResp) Descriptor() ([]byte, []int) {
	return file_item_item_group_proto_rawDescGZIP(), []int{16}
}

func (x *SaveAddonGroupResp) GetAddonGroupInfo() *AddonGroupInfo {
	if x != nil {
		return x.AddonGroupInfo
	}
	return nil
}

var File_item_item_group_proto protoreflect.FileDescriptor

var file_item_item_group_proto_rawDesc = []byte{
	0x0a, 0x15, 0x69, 0x74, 0x65, 0x6d, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x1a, 0x09, 0x65,
	0x72, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x5f, 0x61, 0x62, 0x62, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x41, 0x62, 0x62, 0x72, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x53, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b,
	0x0a, 0x0f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x69, 0x74,
	0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x1d,
	0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x4f, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x3b, 0x0a, 0x0f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x74, 0x65,
	0x6d, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0d, 0x69, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x4f,
	0x0a, 0x10, 0x53, 0x61, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x71, 0x12, 0x3b, 0x0a, 0x0f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x74,
	0x65, 0x6d, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0d, 0x69, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x50, 0x0a, 0x11, 0x53, 0x61, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x69, 0x74, 0x65, 0x6d, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0d, 0x69, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x3c, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x74, 0x65, 0x6d, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x69, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0xd8, 0x01, 0x0a, 0x0d, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x74, 0x65, 0x6d,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x5f, 0x61, 0x62, 0x62, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x41, 0x62, 0x62, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x61,
	0x6c, 0x69, 0x61, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xd6, 0x01, 0x0a, 0x12, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x61, 0x62, 0x62, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x41,
	0x62, 0x62, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x47, 0x0a, 0x13, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x11, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x11, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x6c, 0x69, 0x61,
	0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6c,
	0x69, 0x61, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x63, 0x0a, 0x15, 0x53, 0x61, 0x76, 0x65, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x4a, 0x0a,
	0x14, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x74,
	0x65, 0x6d, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x12, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x38, 0x0a, 0x17, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x64, 0x0a, 0x16, 0x53, 0x61, 0x76, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4a, 0x0a,
	0x14, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x74,
	0x65, 0x6d, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x12, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xa7, 0x01, 0x0a, 0x0e, 0x41, 0x64,
	0x64, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x61, 0x62, 0x62, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x41, 0x62, 0x62, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0f, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x5f,
	0x69, 0x74, 0x65, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x53, 0x0a, 0x11, 0x53, 0x61, 0x76, 0x65, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x3e, 0x0a, 0x10, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x54, 0x0a, 0x12, 0x53, 0x61, 0x76, 0x65, 0x41, 0x64, 0x64,
	0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3e, 0x0a, 0x10, 0x61,
	0x64, 0x64, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x41, 0x64, 0x64,
	0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x61, 0x64, 0x64,
	0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0xd8, 0x03, 0x0a, 0x10,
	0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x40, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x11, 0x2e, 0x65, 0x72, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x38, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x15, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x65, 0x72, 0x70, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3a, 0x0a, 0x0d,
	0x53, 0x61, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x16, 0x2e,
	0x69, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x65, 0x72, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3e, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x18, 0x2e, 0x69, 0x74,
	0x65, 0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x65, 0x72, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x44, 0x0a, 0x12, 0x53, 0x61, 0x76, 0x65,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1b,
	0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x65, 0x72,
	0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x48,
	0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1d, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x65, 0x72, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3c, 0x0a, 0x0e, 0x53, 0x61, 0x76, 0x65,
	0x41, 0x64, 0x64, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x17, 0x2e, 0x69, 0x74, 0x65,
	0x6d, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x65, 0x72, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x22, 0x5a, 0x20, 0x74, 0x74, 0x70, 0x6f, 0x73, 0x2d,
	0x62, 0x6d, 0x70, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x74, 0x74, 0x70, 0x6f, 0x73, 0x2d, 0x65, 0x72,
	0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_item_item_group_proto_rawDescOnce sync.Once
	file_item_item_group_proto_rawDescData = file_item_item_group_proto_rawDesc
)

func file_item_item_group_proto_rawDescGZIP() []byte {
	file_item_item_group_proto_rawDescOnce.Do(func() {
		file_item_item_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_item_item_group_proto_rawDescData)
	})
	return file_item_item_group_proto_rawDescData
}

var file_item_item_group_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_item_item_group_proto_goTypes = []interface{}{
	(*GetItemGroupListReq)(nil),     // 0: item.GetItemGroupListReq
	(*GetItemGroupListResp)(nil),    // 1: item.GetItemGroupListResp
	(*GetItemGroupReq)(nil),         // 2: item.GetItemGroupReq
	(*GetItemGroupResp)(nil),        // 3: item.GetItemGroupResp
	(*SaveItemGroupReq)(nil),        // 4: item.SaveItemGroupReq
	(*SaveItemGroupResp)(nil),       // 5: item.SaveItemGroupResp
	(*DeleteItemGroupReq)(nil),      // 6: item.DeleteItemGroupReq
	(*ItemGroupInfo)(nil),           // 7: item.ItemGroupInfo
	(*AttributeGroupInfo)(nil),      // 8: item.AttributeGroupInfo
	(*AttributeItemInfo)(nil),       // 9: item.AttributeItemInfo
	(*SaveAttributeGroupReq)(nil),   // 10: item.SaveAttributeGroupReq
	(*DeleteAttributeGroupReq)(nil), // 11: item.DeleteAttributeGroupReq
	(*SaveAttributeGroupResp)(nil),  // 12: item.SaveAttributeGroupResp
	(*AddonGroupInfo)(nil),          // 13: item.AddonGroupInfo
	(*AddonItemInfo)(nil),           // 14: item.AddonItemInfo
	(*SaveAddonGroupReq)(nil),       // 15: item.SaveAddonGroupReq
	(*SaveAddonGroupResp)(nil),      // 16: item.SaveAddonGroupResp
	(*api.ResponseInfo)(nil),        // 17: erp.ResponseInfo
}
var file_item_item_group_proto_depIdxs = []int32{
	7,  // 0: item.GetItemGroupListResp.item_group_list:type_name -> item.ItemGroupInfo
	7,  // 1: item.GetItemGroupResp.item_group_info:type_name -> item.ItemGroupInfo
	7,  // 2: item.SaveItemGroupReq.item_group_info:type_name -> item.ItemGroupInfo
	7,  // 3: item.SaveItemGroupResp.item_group_info:type_name -> item.ItemGroupInfo
	9,  // 4: item.AttributeGroupInfo.attribute_item_list:type_name -> item.AttributeItemInfo
	8,  // 5: item.SaveAttributeGroupReq.attribute_group_info:type_name -> item.AttributeGroupInfo
	8,  // 6: item.SaveAttributeGroupResp.attribute_group_info:type_name -> item.AttributeGroupInfo
	14, // 7: item.AddonGroupInfo.addon_item_list:type_name -> item.AddonItemInfo
	13, // 8: item.SaveAddonGroupReq.addon_group_info:type_name -> item.AddonGroupInfo
	13, // 9: item.SaveAddonGroupResp.addon_group_info:type_name -> item.AddonGroupInfo
	0,  // 10: item.ItemGroupService.GetItemGroupList:input_type -> item.GetItemGroupListReq
	2,  // 11: item.ItemGroupService.GetItemGroup:input_type -> item.GetItemGroupReq
	4,  // 12: item.ItemGroupService.SaveItemGroup:input_type -> item.SaveItemGroupReq
	6,  // 13: item.ItemGroupService.DeleteItemGroup:input_type -> item.DeleteItemGroupReq
	10, // 14: item.ItemGroupService.SaveAttributeGroup:input_type -> item.SaveAttributeGroupReq
	11, // 15: item.ItemGroupService.DeleteAttributeGroup:input_type -> item.DeleteAttributeGroupReq
	15, // 16: item.ItemGroupService.SaveAddonGroup:input_type -> item.SaveAddonGroupReq
	17, // 17: item.ItemGroupService.GetItemGroupList:output_type -> erp.ResponseInfo
	17, // 18: item.ItemGroupService.GetItemGroup:output_type -> erp.ResponseInfo
	17, // 19: item.ItemGroupService.SaveItemGroup:output_type -> erp.ResponseInfo
	17, // 20: item.ItemGroupService.DeleteItemGroup:output_type -> erp.ResponseInfo
	17, // 21: item.ItemGroupService.SaveAttributeGroup:output_type -> erp.ResponseInfo
	17, // 22: item.ItemGroupService.DeleteAttributeGroup:output_type -> erp.ResponseInfo
	17, // 23: item.ItemGroupService.SaveAddonGroup:output_type -> erp.ResponseInfo
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_item_item_group_proto_init() }
func file_item_item_group_proto_init() {
	if File_item_item_group_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_item_item_group_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemGroupListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemGroupListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemGroupResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveItemGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveItemGroupResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteItemGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemGroupInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeGroupInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeItemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveAttributeGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAttributeGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveAttributeGroupResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddonGroupInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddonItemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveAddonGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_item_group_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveAddonGroupResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_item_item_group_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_item_item_group_proto_goTypes,
		DependencyIndexes: file_item_item_group_proto_depIdxs,
		MessageInfos:      file_item_item_group_proto_msgTypes,
	}.Build()
	File_item_item_group_proto = out.File
	file_item_item_group_proto_rawDesc = nil
	file_item_item_group_proto_goTypes = nil
	file_item_item_group_proto_depIdxs = nil
}
