// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: item/item.proto

package item

import (
	reflect "reflect"
	sync "sync"
	api "ttpos-bmp/app/ttpos-erp/api"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemGroup int32

const (
	ItemGroup_Others      ItemGroup = 0 // 其他
	ItemGroup_RawMaterial ItemGroup = 1 // 原材料
	ItemGroup_Products    ItemGroup = 2 // 商品
	ItemGroup_Package     ItemGroup = 3 // 套餐
)

// Enum value maps for ItemGroup.
var (
	ItemGroup_name = map[int32]string{
		0: "Others",
		1: "RawMaterial",
		2: "Products",
		3: "Package",
	}
	ItemGroup_value = map[string]int32{
		"Others":      0,
		"RawMaterial": 1,
		"Products":    2,
		"Package":     3,
	}
)

func (x ItemGroup) Enum() *ItemGroup {
	p := new(ItemGroup)
	*p = x
	return p
}

func (x ItemGroup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemGroup) Descriptor() protoreflect.EnumDescriptor {
	return file_item_item_proto_enumTypes[0].Descriptor()
}

func (ItemGroup) Type() protoreflect.EnumType {
	return &file_item_item_proto_enumTypes[0]
}

func (x ItemGroup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemGroup.Descriptor instead.
func (ItemGroup) EnumDescriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{0}
}

type GetItemListReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ItemGroup       ItemGroup              `protobuf:"varint,1,opt,name=item_group,json=itemGroup,proto3,enum=item.ItemGroup" json:"item_group,omitempty" dc:"物品分组，可选  Products 商品/Raw Material 原材料/Package 套餐"` // 物品分组，可选  Products 商品/Raw Material 原材料/Package 套餐
	ItemName        string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty" dc:"商品名称模糊查询，可选，如: %商品名称%"`                                                    // 商品名称模糊查询，可选，如: %商品名称%
	Branch          string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                                                                                      // 分支名称，可选
	CompanyAbbr     string                 `protobuf:"bytes,4,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司简称，可选"`                                                         // 公司简称，可选
	ItemCode        string                 `protobuf:"bytes,5,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty" dc:"物品编码，可选"`                                                                  // 物品编码，可选
	ItemCodePrefix  string                 `protobuf:"bytes,6,opt,name=item_code_prefix,json=itemCodePrefix,proto3" json:"item_code_prefix,omitempty" dc:"物品编码前缀，可选"`                                            // 物品编码前缀，可选
	ContainDisabled bool                   `protobuf:"varint,7,opt,name=contain_disabled,json=containDisabled,proto3" json:"contain_disabled,omitempty" dc:"是否包含禁用状态，可选，默认只取有效"`                                 // 是否包含禁用状态，可选，默认只取有效
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetItemListReq) Reset() {
	*x = GetItemListReq{}
	mi := &file_item_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemListReq) ProtoMessage() {}

func (x *GetItemListReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemListReq.ProtoReflect.Descriptor instead.
func (*GetItemListReq) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{0}
}

func (x *GetItemListReq) GetItemGroup() ItemGroup {
	if x != nil {
		return x.ItemGroup
	}
	return ItemGroup_Others
}

func (x *GetItemListReq) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *GetItemListReq) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetItemListReq) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *GetItemListReq) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *GetItemListReq) GetItemCodePrefix() string {
	if x != nil {
		return x.ItemCodePrefix
	}
	return ""
}

func (x *GetItemListReq) GetContainDisabled() bool {
	if x != nil {
		return x.ContainDisabled
	}
	return false
}

type GetItemListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemList      []*ItemInfo            `protobuf:"bytes,1,rep,name=item_list,json=itemList,proto3" json:"item_list,omitempty" dc:"物品列表"` // 物品列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemListResp) Reset() {
	*x = GetItemListResp{}
	mi := &file_item_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemListResp) ProtoMessage() {}

func (x *GetItemListResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemListResp.ProtoReflect.Descriptor instead.
func (*GetItemListResp) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemListResp) GetItemList() []*ItemInfo {
	if x != nil {
		return x.ItemList
	}
	return nil
}

type ItemInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ItemName          string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty" dc:"物品名称，必填"`                                                                 // 物品名称，必填
	ItemGroup         ItemGroup              `protobuf:"varint,2,opt,name=item_group,json=itemGroup,proto3,enum=item.ItemGroup" json:"item_group,omitempty" dc:"物品分组，必填 Products 商品/Raw Material 原材料/Package 套餐"` // 物品分组，必填 Products 商品/Raw Material 原材料/Package 套餐
	StockUom          string                 `protobuf:"bytes,3,opt,name=stock_uom,json=stockUom,proto3" json:"stock_uom,omitempty" dc:"库存单位，必填 ttpos 传英文过来"`                                                     // 库存单位，必填 ttpos 传英文过来
	ItemCode          string                 `protobuf:"bytes,4,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty" dc:"物品编码，可选"`                                                                 // 物品编码，可选
	ValuationRate     float64                `protobuf:"fixed64,5,opt,name=valuation_rate,json=valuationRate,proto3" json:"valuation_rate,omitempty" dc:"估值率，必填"`                                                 // 估值率，必填
	Barcode           string                 `protobuf:"bytes,6,opt,name=barcode,proto3" json:"barcode,omitempty" dc:"条码，可选"`                                                                                     // 条码，可选
	OpeningStock      float64                `protobuf:"fixed64,7,opt,name=opening_stock,json=openingStock,proto3" json:"opening_stock,omitempty" dc:"期初库存，可选"`                                                   // 期初库存，可选
	IsStockItem       bool                   `protobuf:"varint,8,opt,name=is_stock_item,json=isStockItem,proto3" json:"is_stock_item,omitempty" dc:"是否库存物品，可选"`                                                   // 是否库存物品，可选
	TemplateItemCode  string                 `protobuf:"bytes,9,opt,name=template_item_code,json=templateItemCode,proto3" json:"template_item_code,omitempty" dc:"模版物品编码，可选， 多规格商品时必填，传原始物品编码"`                   // 模版物品编码，可选， 多规格商品时必填，传原始物品编码
	Branch            string                 `protobuf:"bytes,10,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                                                                                    // 分支名称，可选
	CompanyAbbr       string                 `protobuf:"bytes,11,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司简称，可选"`                                                       // 公司简称，可选
	Company           string                 `protobuf:"bytes,12,opt,name=company,proto3" json:"company,omitempty" dc:"公司名称，可选"`                                                                                  // 公司名称，可选
	ItemSpecification string                 `protobuf:"bytes,13,opt,name=item_specification,json=itemSpecification,proto3" json:"item_specification,omitempty" dc:"物品规格，可选 ttpos 传英文过来 多规格商品时必填"`                // 物品规格，可选 ttpos 传英文过来 多规格商品时必填
	Uoms              []*UomDetail           `protobuf:"bytes,14,rep,name=uoms,proto3" json:"uoms,omitempty" dc:"单位列表，可选"`                                                                                        // 单位列表，可选
	Disabled          bool                   `protobuf:"varint,15,opt,name=disabled,proto3" json:"disabled,omitempty" dc:"是否禁用，可选"`                                                                               // 是否禁用，可选
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	mi := &file_item_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{2}
}

func (x *ItemInfo) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ItemInfo) GetItemGroup() ItemGroup {
	if x != nil {
		return x.ItemGroup
	}
	return ItemGroup_Others
}

func (x *ItemInfo) GetStockUom() string {
	if x != nil {
		return x.StockUom
	}
	return ""
}

func (x *ItemInfo) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *ItemInfo) GetValuationRate() float64 {
	if x != nil {
		return x.ValuationRate
	}
	return 0
}

func (x *ItemInfo) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *ItemInfo) GetOpeningStock() float64 {
	if x != nil {
		return x.OpeningStock
	}
	return 0
}

func (x *ItemInfo) GetIsStockItem() bool {
	if x != nil {
		return x.IsStockItem
	}
	return false
}

func (x *ItemInfo) GetTemplateItemCode() string {
	if x != nil {
		return x.TemplateItemCode
	}
	return ""
}

func (x *ItemInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ItemInfo) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *ItemInfo) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *ItemInfo) GetItemSpecification() string {
	if x != nil {
		return x.ItemSpecification
	}
	return ""
}

func (x *ItemInfo) GetUoms() []*UomDetail {
	if x != nil {
		return x.Uoms
	}
	return nil
}

func (x *ItemInfo) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type UomDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uom              string                 `protobuf:"bytes,1,opt,name=uom,proto3" json:"uom,omitempty" dc:"单位名称，必填"`                                                          // 单位名称，必填
	ConversionFactor float64                `protobuf:"fixed64,2,opt,name=conversion_factor,json=conversionFactor,proto3" json:"conversion_factor,omitempty" dc:"转换比率，相对于基准单位"` // 转换比率，相对于基准单位
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UomDetail) Reset() {
	*x = UomDetail{}
	mi := &file_item_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UomDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UomDetail) ProtoMessage() {}

func (x *UomDetail) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UomDetail.ProtoReflect.Descriptor instead.
func (*UomDetail) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{3}
}

func (x *UomDetail) GetUom() string {
	if x != nil {
		return x.Uom
	}
	return ""
}

func (x *UomDetail) GetConversionFactor() float64 {
	if x != nil {
		return x.ConversionFactor
	}
	return 0
}

type GetUomListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                              // 分支名称，可选
	CompanyAbbr   string                 `protobuf:"bytes,2,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司简称，可选"` // 公司简称，可选
	UomName       string                 `protobuf:"bytes,3,opt,name=uom_name,json=uomName,proto3" json:"uom_name,omitempty" dc:"单位名称，可选"`             // 单位名称，可选
	AliasName     string                 `protobuf:"bytes,4,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty" dc:"单位别名，可选"`       // 单位别名，可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUomListReq) Reset() {
	*x = GetUomListReq{}
	mi := &file_item_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUomListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUomListReq) ProtoMessage() {}

func (x *GetUomListReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUomListReq.ProtoReflect.Descriptor instead.
func (*GetUomListReq) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{4}
}

func (x *GetUomListReq) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetUomListReq) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *GetUomListReq) GetUomName() string {
	if x != nil {
		return x.UomName
	}
	return ""
}

func (x *GetUomListReq) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

type GetUomListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UomList       []*UomInfo             `protobuf:"bytes,1,rep,name=uom_list,json=uomList,proto3" json:"uom_list,omitempty" dc:"单位列表"` //单位列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUomListResp) Reset() {
	*x = GetUomListResp{}
	mi := &file_item_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUomListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUomListResp) ProtoMessage() {}

func (x *GetUomListResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUomListResp.ProtoReflect.Descriptor instead.
func (*GetUomListResp) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{5}
}

func (x *GetUomListResp) GetUomList() []*UomInfo {
	if x != nil {
		return x.UomList
	}
	return nil
}

type UomInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UomName           string                 `protobuf:"bytes,1,opt,name=uom_name,json=uomName,proto3" json:"uom_name,omitempty" dc:"单位名称，必填"`                                    // 单位名称，必填
	Branch            string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                                                     // 分支名称，可选
	CompanyAbbr       string                 `protobuf:"bytes,3,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司简称，可选"`                        // 公司简称，可选
	Company           string                 `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty" dc:"公司名称，可选"`                                                   // 公司名称，可选
	AliasName         string                 `protobuf:"bytes,5,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty" dc:"单位别名，可选"`                              // 单位别名，可选
	MustBeWholeNumber bool                   `protobuf:"varint,6,opt,name=must_be_whole_number,json=mustBeWholeNumber,proto3" json:"must_be_whole_number,omitempty" dc:"是否必须为整数"` // 是否必须为整数
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UomInfo) Reset() {
	*x = UomInfo{}
	mi := &file_item_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UomInfo) ProtoMessage() {}

func (x *UomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UomInfo.ProtoReflect.Descriptor instead.
func (*UomInfo) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{6}
}

func (x *UomInfo) GetUomName() string {
	if x != nil {
		return x.UomName
	}
	return ""
}

func (x *UomInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *UomInfo) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *UomInfo) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *UomInfo) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

func (x *UomInfo) GetMustBeWholeNumber() bool {
	if x != nil {
		return x.MustBeWholeNumber
	}
	return false
}

type GetAttributeListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                                    // 分支名称，可选
	CompanyAbbr   string                 `protobuf:"bytes,2,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司简称，可选"`       // 公司简称，可选
	AttributeName string                 `protobuf:"bytes,3,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty" dc:"属性名称，可选"` // 属性名称，可选
	AliasName     string                 `protobuf:"bytes,4,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty" dc:"属性别名，可选"`             // 属性别名，可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributeListReq) Reset() {
	*x = GetAttributeListReq{}
	mi := &file_item_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeListReq) ProtoMessage() {}

func (x *GetAttributeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeListReq.ProtoReflect.Descriptor instead.
func (*GetAttributeListReq) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{7}
}

func (x *GetAttributeListReq) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetAttributeListReq) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *GetAttributeListReq) GetAttributeName() string {
	if x != nil {
		return x.AttributeName
	}
	return ""
}

func (x *GetAttributeListReq) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

type AttributeInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AttributeName      string                 `protobuf:"bytes,1,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty" dc:"属性名称，必填"`                // 属性名称，必填
	Branch             string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，可选"`                                                   // 分支名称，可选
	Company            string                 `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty" dc:"公司名称，可选"`                                                 // 公司名称，可选
	CompanyAbbr        string                 `protobuf:"bytes,4,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司简称，可选"`                      // 公司简称，可选
	AliasName          string                 `protobuf:"bytes,5,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty" dc:"属性别名，可选"`                            // 属性别名，可选
	AttributeValueList []*AttributeValueInfo  `protobuf:"bytes,6,rep,name=attribute_value_list,json=attributeValueList,proto3" json:"attribute_value_list,omitempty" dc:"属性值列表"` // 属性值列表
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AttributeInfo) Reset() {
	*x = AttributeInfo{}
	mi := &file_item_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeInfo) ProtoMessage() {}

func (x *AttributeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeInfo.ProtoReflect.Descriptor instead.
func (*AttributeInfo) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{8}
}

func (x *AttributeInfo) GetAttributeName() string {
	if x != nil {
		return x.AttributeName
	}
	return ""
}

func (x *AttributeInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *AttributeInfo) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *AttributeInfo) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *AttributeInfo) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

func (x *AttributeInfo) GetAttributeValueList() []*AttributeValueInfo {
	if x != nil {
		return x.AttributeValueList
	}
	return nil
}

type AttributeValueInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AttributeValue string                 `protobuf:"bytes,1,opt,name=attribute_value,json=attributeValue,proto3" json:"attribute_value,omitempty" dc:"属性值，必填"` // 属性值，必填
	Abbr           string                 `protobuf:"bytes,2,opt,name=abbr,proto3" json:"abbr,omitempty" dc:"属性缩写，必填"`                                          // 属性缩写，必填
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AttributeValueInfo) Reset() {
	*x = AttributeValueInfo{}
	mi := &file_item_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValueInfo) ProtoMessage() {}

func (x *AttributeValueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValueInfo.ProtoReflect.Descriptor instead.
func (*AttributeValueInfo) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{9}
}

func (x *AttributeValueInfo) GetAttributeValue() string {
	if x != nil {
		return x.AttributeValue
	}
	return ""
}

func (x *AttributeValueInfo) GetAbbr() string {
	if x != nil {
		return x.Abbr
	}
	return ""
}

type GetAttributeListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttributeList []*AttributeInfo       `protobuf:"bytes,1,rep,name=attribute_list,json=attributeList,proto3" json:"attribute_list,omitempty" dc:"属性列表"` // 属性列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributeListResp) Reset() {
	*x = GetAttributeListResp{}
	mi := &file_item_item_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeListResp) ProtoMessage() {}

func (x *GetAttributeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeListResp.ProtoReflect.Descriptor instead.
func (*GetAttributeListResp) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{10}
}

func (x *GetAttributeListResp) GetAttributeList() []*AttributeInfo {
	if x != nil {
		return x.AttributeList
	}
	return nil
}

type ItemStock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemCode      string                 `protobuf:"bytes,1,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty" dc:"物品编码，"`                         // 物品编码，
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty" dc:"物品名称，"`                         // 物品名称，
	ItemGroup     ItemGroup              `protobuf:"varint,3,opt,name=item_group,json=itemGroup,proto3,enum=item.ItemGroup" json:"item_group,omitempty" dc:"物品分组，"` // 物品分组，
	Warehouse     string                 `protobuf:"bytes,4,opt,name=warehouse,proto3" json:"warehouse,omitempty" dc:"仓库名称，"`                                       // 仓库名称，
	StockUom      string                 `protobuf:"bytes,5,opt,name=stock_uom,json=stockUom,proto3" json:"stock_uom,omitempty" dc:"库存单位，"`                         // 库存单位，
	ActualQty     float64                `protobuf:"fixed64,6,opt,name=actual_qty,json=actualQty,proto3" json:"actual_qty,omitempty" dc:"实际库存数量"`                   // 实际库存数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemStock) Reset() {
	*x = ItemStock{}
	mi := &file_item_item_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStock) ProtoMessage() {}

func (x *ItemStock) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStock.ProtoReflect.Descriptor instead.
func (*ItemStock) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{11}
}

func (x *ItemStock) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *ItemStock) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ItemStock) GetItemGroup() ItemGroup {
	if x != nil {
		return x.ItemGroup
	}
	return ItemGroup_Others
}

func (x *ItemStock) GetWarehouse() string {
	if x != nil {
		return x.Warehouse
	}
	return ""
}

func (x *ItemStock) GetStockUom() string {
	if x != nil {
		return x.StockUom
	}
	return ""
}

func (x *ItemStock) GetActualQty() float64 {
	if x != nil {
		return x.ActualQty
	}
	return 0
}

type GetItemStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyAbbr   string                 `protobuf:"bytes,1,opt,name=company_abbr,json=companyAbbr,proto3" json:"company_abbr,omitempty" dc:"公司简称，必填"`                // 公司简称，必填
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty" dc:"分支名称，必填"`                                             // 分支名称，必填
	ItemCode      string                 `protobuf:"bytes,3,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty" dc:"物品编码，可选"`                         // 物品编码，可选
	ItemName      string                 `protobuf:"bytes,4,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty" dc:"物品名称，可选，模糊查询"`                    // 物品名称，可选，模糊查询
	ItemGroup     ItemGroup              `protobuf:"varint,5,opt,name=item_group,json=itemGroup,proto3,enum=item.ItemGroup" json:"item_group,omitempty" dc:"物品分组，可选"` // 物品分组，可选
	Warehouse     string                 `protobuf:"bytes,6,opt,name=warehouse,proto3" json:"warehouse,omitempty" dc:"仓库名称，可选"`                                       // 仓库名称，可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemStockReq) Reset() {
	*x = GetItemStockReq{}
	mi := &file_item_item_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemStockReq) ProtoMessage() {}

func (x *GetItemStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemStockReq.ProtoReflect.Descriptor instead.
func (*GetItemStockReq) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{12}
}

func (x *GetItemStockReq) GetCompanyAbbr() string {
	if x != nil {
		return x.CompanyAbbr
	}
	return ""
}

func (x *GetItemStockReq) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetItemStockReq) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *GetItemStockReq) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *GetItemStockReq) GetItemGroup() ItemGroup {
	if x != nil {
		return x.ItemGroup
	}
	return ItemGroup_Others
}

func (x *GetItemStockReq) GetWarehouse() string {
	if x != nil {
		return x.Warehouse
	}
	return ""
}

type GetItemStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemStockList []*ItemStock           `protobuf:"bytes,1,rep,name=item_stock_list,json=itemStockList,proto3" json:"item_stock_list,omitempty" dc:"物品库存列表"` // 物品库存列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemStockResp) Reset() {
	*x = GetItemStockResp{}
	mi := &file_item_item_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemStockResp) ProtoMessage() {}

func (x *GetItemStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemStockResp.ProtoReflect.Descriptor instead.
func (*GetItemStockResp) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{13}
}

func (x *GetItemStockResp) GetItemStockList() []*ItemStock {
	if x != nil {
		return x.ItemStockList
	}
	return nil
}

type BomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemCode      string                 `protobuf:"bytes,1,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty" dc:"商品编码，"`     // 商品编码，
	BomName       string                 `protobuf:"bytes,2,opt,name=bom_name,json=bomName,proto3" json:"bom_name,omitempty" dc:"商品名称，"`        // 商品名称，
	StockUom      string                 `protobuf:"bytes,4,opt,name=stock_uom,json=stockUom,proto3" json:"stock_uom,omitempty" dc:"库存单位，"`     // 库存单位，
	Quantity      float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty" dc:"数量，必填"`                   // 数量，必填
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty" dc:"是否激活，"`    // 是否激活，
	IsDefault     bool                   `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty" dc:"是否默认，"` // 是否默认，
	Items         []*BomItem             `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty" dc:"物品列表，"`                           // 物品列表，
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BomInfo) Reset() {
	*x = BomInfo{}
	mi := &file_item_item_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BomInfo) ProtoMessage() {}

func (x *BomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BomInfo.ProtoReflect.Descriptor instead.
func (*BomInfo) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{14}
}

func (x *BomInfo) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *BomInfo) GetBomName() string {
	if x != nil {
		return x.BomName
	}
	return ""
}

func (x *BomInfo) GetStockUom() string {
	if x != nil {
		return x.StockUom
	}
	return ""
}

func (x *BomInfo) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BomInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *BomInfo) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *BomInfo) GetItems() []*BomItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BomItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemCode      string                 `protobuf:"bytes,1,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty" dc:"物品编码，"` // 物品编码，
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty" dc:"物品名称，"` // 物品名称，
	Qty           float64                `protobuf:"fixed64,3,opt,name=qty,proto3" json:"qty,omitempty" dc:"物品数量，"`                         // 物品数量，
	Uom           string                 `protobuf:"bytes,4,opt,name=uom,proto3" json:"uom,omitempty" dc:"物品单位，"`                           // 物品单位，
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BomItem) Reset() {
	*x = BomItem{}
	mi := &file_item_item_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BomItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BomItem) ProtoMessage() {}

func (x *BomItem) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BomItem.ProtoReflect.Descriptor instead.
func (*BomItem) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{15}
}

func (x *BomItem) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *BomItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *BomItem) GetQty() float64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *BomItem) GetUom() string {
	if x != nil {
		return x.Uom
	}
	return ""
}

var File_item_item_proto protoreflect.FileDescriptor

const file_item_item_proto_rawDesc = "" +
	"\n" +
	"\x0fitem/item.proto\x12\x04item\x1a\terp.proto\"\x8a\x02\n" +
	"\x0eGetItemListReq\x12.\n" +
	"\n" +
	"item_group\x18\x01 \x01(\x0e2\x0f.item.ItemGroupR\titemGroup\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12!\n" +
	"\fcompany_abbr\x18\x04 \x01(\tR\vcompanyAbbr\x12\x1b\n" +
	"\titem_code\x18\x05 \x01(\tR\bitemCode\x12(\n" +
	"\x10item_code_prefix\x18\x06 \x01(\tR\x0eitemCodePrefix\x12)\n" +
	"\x10contain_disabled\x18\a \x01(\bR\x0fcontainDisabled\">\n" +
	"\x0fGetItemListResp\x12+\n" +
	"\titem_list\x18\x01 \x03(\v2\x0e.item.ItemInfoR\bitemList\"\x8e\x04\n" +
	"\bItemInfo\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12.\n" +
	"\n" +
	"item_group\x18\x02 \x01(\x0e2\x0f.item.ItemGroupR\titemGroup\x12\x1b\n" +
	"\tstock_uom\x18\x03 \x01(\tR\bstockUom\x12\x1b\n" +
	"\titem_code\x18\x04 \x01(\tR\bitemCode\x12%\n" +
	"\x0evaluation_rate\x18\x05 \x01(\x01R\rvaluationRate\x12\x18\n" +
	"\abarcode\x18\x06 \x01(\tR\abarcode\x12#\n" +
	"\ropening_stock\x18\a \x01(\x01R\fopeningStock\x12\"\n" +
	"\ris_stock_item\x18\b \x01(\bR\visStockItem\x12,\n" +
	"\x12template_item_code\x18\t \x01(\tR\x10templateItemCode\x12\x16\n" +
	"\x06branch\x18\n" +
	" \x01(\tR\x06branch\x12!\n" +
	"\fcompany_abbr\x18\v \x01(\tR\vcompanyAbbr\x12\x18\n" +
	"\acompany\x18\f \x01(\tR\acompany\x12-\n" +
	"\x12item_specification\x18\r \x01(\tR\x11itemSpecification\x12#\n" +
	"\x04uoms\x18\x0e \x03(\v2\x0f.item.UomDetailR\x04uoms\x12\x1a\n" +
	"\bdisabled\x18\x0f \x01(\bR\bdisabled\"J\n" +
	"\tUomDetail\x12\x10\n" +
	"\x03uom\x18\x01 \x01(\tR\x03uom\x12+\n" +
	"\x11conversion_factor\x18\x02 \x01(\x01R\x10conversionFactor\"\x84\x01\n" +
	"\rGetUomListReq\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\x12!\n" +
	"\fcompany_abbr\x18\x02 \x01(\tR\vcompanyAbbr\x12\x19\n" +
	"\buom_name\x18\x03 \x01(\tR\auomName\x12\x1d\n" +
	"\n" +
	"alias_name\x18\x04 \x01(\tR\taliasName\":\n" +
	"\x0eGetUomListResp\x12(\n" +
	"\buom_list\x18\x01 \x03(\v2\r.item.UomInfoR\auomList\"\xc9\x01\n" +
	"\aUomInfo\x12\x19\n" +
	"\buom_name\x18\x01 \x01(\tR\auomName\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12!\n" +
	"\fcompany_abbr\x18\x03 \x01(\tR\vcompanyAbbr\x12\x18\n" +
	"\acompany\x18\x04 \x01(\tR\acompany\x12\x1d\n" +
	"\n" +
	"alias_name\x18\x05 \x01(\tR\taliasName\x12/\n" +
	"\x14must_be_whole_number\x18\x06 \x01(\bR\x11mustBeWholeNumber\"\x96\x01\n" +
	"\x13GetAttributeListReq\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\x12!\n" +
	"\fcompany_abbr\x18\x02 \x01(\tR\vcompanyAbbr\x12%\n" +
	"\x0eattribute_name\x18\x03 \x01(\tR\rattributeName\x12\x1d\n" +
	"\n" +
	"alias_name\x18\x04 \x01(\tR\taliasName\"\xf6\x01\n" +
	"\rAttributeInfo\x12%\n" +
	"\x0eattribute_name\x18\x01 \x01(\tR\rattributeName\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x18\n" +
	"\acompany\x18\x03 \x01(\tR\acompany\x12!\n" +
	"\fcompany_abbr\x18\x04 \x01(\tR\vcompanyAbbr\x12\x1d\n" +
	"\n" +
	"alias_name\x18\x05 \x01(\tR\taliasName\x12J\n" +
	"\x14attribute_value_list\x18\x06 \x03(\v2\x18.item.AttributeValueInfoR\x12attributeValueList\"Q\n" +
	"\x12AttributeValueInfo\x12'\n" +
	"\x0fattribute_value\x18\x01 \x01(\tR\x0eattributeValue\x12\x12\n" +
	"\x04abbr\x18\x02 \x01(\tR\x04abbr\"R\n" +
	"\x14GetAttributeListResp\x12:\n" +
	"\x0eattribute_list\x18\x01 \x03(\v2\x13.item.AttributeInfoR\rattributeList\"\xcf\x01\n" +
	"\tItemStock\x12\x1b\n" +
	"\titem_code\x18\x01 \x01(\tR\bitemCode\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12.\n" +
	"\n" +
	"item_group\x18\x03 \x01(\x0e2\x0f.item.ItemGroupR\titemGroup\x12\x1c\n" +
	"\twarehouse\x18\x04 \x01(\tR\twarehouse\x12\x1b\n" +
	"\tstock_uom\x18\x05 \x01(\tR\bstockUom\x12\x1d\n" +
	"\n" +
	"actual_qty\x18\x06 \x01(\x01R\tactualQty\"\xd4\x01\n" +
	"\x0fGetItemStockReq\x12!\n" +
	"\fcompany_abbr\x18\x01 \x01(\tR\vcompanyAbbr\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x1b\n" +
	"\titem_code\x18\x03 \x01(\tR\bitemCode\x12\x1b\n" +
	"\titem_name\x18\x04 \x01(\tR\bitemName\x12.\n" +
	"\n" +
	"item_group\x18\x05 \x01(\x0e2\x0f.item.ItemGroupR\titemGroup\x12\x1c\n" +
	"\twarehouse\x18\x06 \x01(\tR\twarehouse\"K\n" +
	"\x10GetItemStockResp\x127\n" +
	"\x0fitem_stock_list\x18\x01 \x03(\v2\x0f.item.ItemStockR\ritemStockList\"\xdb\x01\n" +
	"\aBomInfo\x12\x1b\n" +
	"\titem_code\x18\x01 \x01(\tR\bitemCode\x12\x19\n" +
	"\bbom_name\x18\x02 \x01(\tR\abomName\x12\x1b\n" +
	"\tstock_uom\x18\x04 \x01(\tR\bstockUom\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefault\x12#\n" +
	"\x05items\x18\b \x03(\v2\r.item.BomItemR\x05items\"g\n" +
	"\aBomItem\x12\x1b\n" +
	"\titem_code\x18\x01 \x01(\tR\bitemCode\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\x01R\x03qty\x12\x10\n" +
	"\x03uom\x18\x04 \x01(\tR\x03uom*C\n" +
	"\tItemGroup\x12\n" +
	"\n" +
	"\x06Others\x10\x00\x12\x0f\n" +
	"\vRawMaterial\x10\x01\x12\f\n" +
	"\bProducts\x10\x02\x12\v\n" +
	"\aPackage\x10\x032\x8c\x03\n" +
	"\vItemService\x126\n" +
	"\vGetItemList\x12\x14.item.GetItemListReq\x1a\x11.erp.ResponseInfo\x124\n" +
	"\n" +
	"GetUomList\x12\x13.item.GetUomListReq\x1a\x11.erp.ResponseInfo\x12+\n" +
	"\aSaveUom\x12\r.item.UomInfo\x1a\x11.erp.ResponseInfo\x12@\n" +
	"\x10GetAttributeList\x12\x19.item.GetAttributeListReq\x1a\x11.erp.ResponseInfo\x127\n" +
	"\rSaveAttribute\x12\x13.item.AttributeInfo\x1a\x11.erp.ResponseInfo\x12-\n" +
	"\bSaveItem\x12\x0e.item.ItemInfo\x1a\x11.erp.ResponseInfo\x128\n" +
	"\fGetItemStock\x12\x15.item.GetItemStockReq\x1a\x11.erp.ResponseInfoB\"Z ttpos-bmp/app/ttpos-erp/api/itemb\x06proto3"

var (
	file_item_item_proto_rawDescOnce sync.Once
	file_item_item_proto_rawDescData []byte
)

func file_item_item_proto_rawDescGZIP() []byte {
	file_item_item_proto_rawDescOnce.Do(func() {
		file_item_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_item_proto_rawDesc), len(file_item_item_proto_rawDesc)))
	})
	return file_item_item_proto_rawDescData
}

var file_item_item_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_item_item_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_item_item_proto_goTypes = []any{
	(ItemGroup)(0),               // 0: item.ItemGroup
	(*GetItemListReq)(nil),       // 1: item.GetItemListReq
	(*GetItemListResp)(nil),      // 2: item.GetItemListResp
	(*ItemInfo)(nil),             // 3: item.ItemInfo
	(*UomDetail)(nil),            // 4: item.UomDetail
	(*GetUomListReq)(nil),        // 5: item.GetUomListReq
	(*GetUomListResp)(nil),       // 6: item.GetUomListResp
	(*UomInfo)(nil),              // 7: item.UomInfo
	(*GetAttributeListReq)(nil),  // 8: item.GetAttributeListReq
	(*AttributeInfo)(nil),        // 9: item.AttributeInfo
	(*AttributeValueInfo)(nil),   // 10: item.AttributeValueInfo
	(*GetAttributeListResp)(nil), // 11: item.GetAttributeListResp
	(*ItemStock)(nil),            // 12: item.ItemStock
	(*GetItemStockReq)(nil),      // 13: item.GetItemStockReq
	(*GetItemStockResp)(nil),     // 14: item.GetItemStockResp
	(*BomInfo)(nil),              // 15: item.BomInfo
	(*BomItem)(nil),              // 16: item.BomItem
	(*api.ResponseInfo)(nil),     // 17: erp.ResponseInfo
}
var file_item_item_proto_depIdxs = []int32{
	0,  // 0: item.GetItemListReq.item_group:type_name -> item.ItemGroup
	3,  // 1: item.GetItemListResp.item_list:type_name -> item.ItemInfo
	0,  // 2: item.ItemInfo.item_group:type_name -> item.ItemGroup
	4,  // 3: item.ItemInfo.uoms:type_name -> item.UomDetail
	7,  // 4: item.GetUomListResp.uom_list:type_name -> item.UomInfo
	10, // 5: item.AttributeInfo.attribute_value_list:type_name -> item.AttributeValueInfo
	9,  // 6: item.GetAttributeListResp.attribute_list:type_name -> item.AttributeInfo
	0,  // 7: item.ItemStock.item_group:type_name -> item.ItemGroup
	0,  // 8: item.GetItemStockReq.item_group:type_name -> item.ItemGroup
	12, // 9: item.GetItemStockResp.item_stock_list:type_name -> item.ItemStock
	16, // 10: item.BomInfo.items:type_name -> item.BomItem
	1,  // 11: item.ItemService.GetItemList:input_type -> item.GetItemListReq
	5,  // 12: item.ItemService.GetUomList:input_type -> item.GetUomListReq
	7,  // 13: item.ItemService.SaveUom:input_type -> item.UomInfo
	8,  // 14: item.ItemService.GetAttributeList:input_type -> item.GetAttributeListReq
	9,  // 15: item.ItemService.SaveAttribute:input_type -> item.AttributeInfo
	3,  // 16: item.ItemService.SaveItem:input_type -> item.ItemInfo
	13, // 17: item.ItemService.GetItemStock:input_type -> item.GetItemStockReq
	17, // 18: item.ItemService.GetItemList:output_type -> erp.ResponseInfo
	17, // 19: item.ItemService.GetUomList:output_type -> erp.ResponseInfo
	17, // 20: item.ItemService.SaveUom:output_type -> erp.ResponseInfo
	17, // 21: item.ItemService.GetAttributeList:output_type -> erp.ResponseInfo
	17, // 22: item.ItemService.SaveAttribute:output_type -> erp.ResponseInfo
	17, // 23: item.ItemService.SaveItem:output_type -> erp.ResponseInfo
	17, // 24: item.ItemService.GetItemStock:output_type -> erp.ResponseInfo
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_item_item_proto_init() }
func file_item_item_proto_init() {
	if File_item_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_item_proto_rawDesc), len(file_item_item_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_item_item_proto_goTypes,
		DependencyIndexes: file_item_item_proto_depIdxs,
		EnumInfos:         file_item_item_proto_enumTypes,
		MessageInfos:      file_item_item_proto_msgTypes,
	}.Build()
	File_item_item_proto = out.File
	file_item_item_proto_goTypes = nil
	file_item_item_proto_depIdxs = nil
}
