# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":14011"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level : "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
  link: "mysql:$DB_USERNAME:$DB_PASSWORD@tcp($DB_HOST:$DB_PORT_OPEN)/saas"

grpc:
  name:            "ttpos-shop"
  address:            ":14012"
  logPath:          "./log"
  logStdout:        true
  errorLogEnabled:  true
  accessLogEnabled: true
  errorStack:       true

nacos:
  server:
    addresses: "$NACOS_SERVER_ADDRESSES"  # 多实例配置（格式：host1:port1,host2:port2,host3:port3），优先使用
    # 兼容旧配置（单实例）
    ip: $NACOS_SERVER_IP
    port: $NACOS_SERVER_PORT
  config:
    dataId: ttpos-shop.yaml
    group: DEFAULT_GROUP

# 调用链监控配置
otlp:
  enabled: false
  serviceName: "ttpos-erp"
  endpoint: "10.0.11.43:4318"
  path: "/v1/traces"