// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// companySettingDao is the data access object for the table ttpos_company_setting.
// You can define custom methods on it to extend its functionality as needed.
type companySettingDao struct {
	*internal.CompanySettingDao
}

var (
	// CompanySetting is a globally accessible object for table ttpos_company_setting operations.
	CompanySetting = companySettingDao{internal.NewCompanySettingDao()}
)

// Add your custom methods and functionality below.
