// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos/internal/dao/internal"
)

// lanPrinterScanDao is the data access object for the table ttpos_lan_printer_scan.
// You can define custom methods on it to extend its functionality as needed.
type lanPrinterScanDao struct {
	*internal.LanPrinterScanDao
}

var (
	// LanPrinterScan is a globally accessible object for table ttpos_lan_printer_scan operations.
	LanPrinterScan = lanPrinterScanDao{internal.NewLanPrinterScanDao()}
)

// Add your custom methods and functionality below.
