// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// memberRechargeOrderOperationLogDao is the data access object for the table ttpos_member_recharge_order_operation_log.
// You can define custom methods on it to extend its functionality as needed.
type memberRechargeOrderOperationLogDao struct {
	*internal.MemberRechargeOrderOperationLogDao
}

var (
	// MemberRechargeOrderOperationLog is a globally accessible object for table ttpos_member_recharge_order_operation_log operations.
	MemberRechargeOrderOperationLog = memberRechargeOrderOperationLogDao{internal.NewMemberRechargeOrderOperationLogDao()}
)

// Add your custom methods and functionality below.
