// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// printerTemplateDao is the data access object for the table ttpos_printer_template.
// You can define custom methods on it to extend its functionality as needed.
type printerTemplateDao struct {
	*internal.PrinterTemplateDao
}

var (
	// PrinterTemplate is a globally accessible object for table ttpos_printer_template operations.
	PrinterTemplate = printerTemplateDao{internal.NewPrinterTemplateDao()}
)

// Add your custom methods and functionality below.
