// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// productAttributeGroupDao is the data access object for the table ttpos_product_attribute_group.
// You can define custom methods on it to extend its functionality as needed.
type productAttributeGroupDao struct {
	*internal.ProductAttributeGroupDao
}

var (
	// ProductAttributeGroup is a globally accessible object for table ttpos_product_attribute_group operations.
	ProductAttributeGroup = productAttributeGroupDao{internal.NewProductAttributeGroupDao()}
)

// Add your custom methods and functionality below.
