// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// productMustPlanDao is the data access object for the table ttpos_product_must_plan.
// You can define custom methods on it to extend its functionality as needed.
type productMustPlanDao struct {
	*internal.ProductMustPlanDao
}

var (
	// ProductMustPlan is a globally accessible object for table ttpos_product_must_plan operations.
	ProductMustPlan = productMustPlanDao{internal.NewProductMustPlanDao()}
)

// Add your custom methods and functionality below.
