// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// productionOrderMaterialDao is the data access object for the table ttpos_production_order_material.
// You can define custom methods on it to extend its functionality as needed.
type productionOrderMaterialDao struct {
	*internal.ProductionOrderMaterialDao
}

var (
	// ProductionOrderMaterial is a globally accessible object for table ttpos_production_order_material operations.
	ProductionOrderMaterial = productionOrderMaterialDao{internal.NewProductionOrderMaterialDao()}
)

// Add your custom methods and functionality below.
