// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// productPrinterDao is the data access object for the table ttpos_product_printer.
// You can define custom methods on it to extend its functionality as needed.
type productPrinterDao struct {
	*internal.ProductPrinterDao
}

var (
	// ProductPrinter is a globally accessible object for table ttpos_product_printer operations.
	ProductPrinter = productPrinterDao{internal.NewProductPrinterDao()}
)

// Add your custom methods and functionality below.
