// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// purchaseFormDao is the data access object for the table ttpos_purchase_form.
// You can define custom methods on it to extend its functionality as needed.
type purchaseFormDao struct {
	*internal.PurchaseFormDao
}

var (
	// PurchaseForm is a globally accessible object for table ttpos_purchase_form operations.
	PurchaseForm = purchaseFormDao{internal.NewPurchaseFormDao()}
)

// Add your custom methods and functionality below.
