// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// relatedMaterialDao is the data access object for the table ttpos_related_material.
// You can define custom methods on it to extend its functionality as needed.
type relatedMaterialDao struct {
	*internal.RelatedMaterialDao
}

var (
	// RelatedMaterial is a globally accessible object for table ttpos_related_material operations.
	RelatedMaterial = relatedMaterialDao{internal.NewRelatedMaterialDao()}
)

// Add your custom methods and functionality below.
