// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// returnOrderAmountDao is the data access object for the table ttpos_return_order_amount.
// You can define custom methods on it to extend its functionality as needed.
type returnOrderAmountDao struct {
	*internal.ReturnOrderAmountDao
}

var (
	// ReturnOrderAmount is a globally accessible object for table ttpos_return_order_amount operations.
	ReturnOrderAmount = returnOrderAmountDao{internal.NewReturnOrderAmountDao()}
)

// Add your custom methods and functionality below.
