// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// saleOrderBuffetCustomerTypeDao is the data access object for the table ttpos_sale_order_buffet_customer_type.
// You can define custom methods on it to extend its functionality as needed.
type saleOrderBuffetCustomerTypeDao struct {
	*internal.SaleOrderBuffetCustomerTypeDao
}

var (
	// SaleOrderBuffetCustomerType is a globally accessible object for table ttpos_sale_order_buffet_customer_type operations.
	SaleOrderBuffetCustomerType = saleOrderBuffetCustomerTypeDao{internal.NewSaleOrderBuffetCustomerTypeDao()}
)

// Add your custom methods and functionality below.
