// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// saleOrderDao is the data access object for the table ttpos_sale_order.
// You can define custom methods on it to extend its functionality as needed.
type saleOrderDao struct {
	*internal.SaleOrderDao
}

var (
	// SaleOrder is a globally accessible object for table ttpos_sale_order operations.
	SaleOrder = saleOrderDao{internal.NewSaleOrderDao()}
)

// Add your custom methods and functionality below.
