// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// saleOrderOperationRecordDao is the data access object for the table ttpos_sale_order_operation_record.
// You can define custom methods on it to extend its functionality as needed.
type saleOrderOperationRecordDao struct {
	*internal.SaleOrderOperationRecordDao
}

var (
	// SaleOrderOperationRecord is a globally accessible object for table ttpos_sale_order_operation_record operations.
	SaleOrderOperationRecord = saleOrderOperationRecordDao{internal.NewSaleOrderOperationRecordDao()}
)

// Add your custom methods and functionality below.
