// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// statisticsMemberDao is the data access object for the table ttpos_statistics_member.
// You can define custom methods on it to extend its functionality as needed.
type statisticsMemberDao struct {
	*internal.StatisticsMemberDao
}

var (
	// StatisticsMember is a globally accessible object for table ttpos_statistics_member operations.
	StatisticsMember = statisticsMemberDao{internal.NewStatisticsMemberDao()}
)

// Add your custom methods and functionality below.
