// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// supplierDao is the data access object for the table ttpos_supplier.
// You can define custom methods on it to extend its functionality as needed.
type supplierDao struct {
	*internal.SupplierDao
}

var (
	// Supplier is a globally accessible object for table ttpos_supplier operations.
	Supplier = supplierDao{internal.NewSupplierDao()}
)

// Add your custom methods and functionality below.
