// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// warehouseMonthlyFormDao is the data access object for the table ttpos_warehouse_monthly_form.
// You can define custom methods on it to extend its functionality as needed.
type warehouseMonthlyFormDao struct {
	*internal.WarehouseMonthlyFormDao
}

var (
	// WarehouseMonthlyForm is a globally accessible object for table ttpos_warehouse_monthly_form operations.
	WarehouseMonthlyForm = warehouseMonthlyFormDao{internal.NewWarehouseMonthlyFormDao()}
)

// Add your custom methods and functionality below.
