// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-shop/internal/dao/internal"
)

// warehouseMonthlyProductBomFormDao is the data access object for the table ttpos_warehouse_monthly_product_bom_form.
// You can define custom methods on it to extend its functionality as needed.
type warehouseMonthlyProductBomFormDao struct {
	*internal.WarehouseMonthlyProductBomFormDao
}

var (
	// WarehouseMonthlyProductBomForm is a globally accessible object for table ttpos_warehouse_monthly_product_bom_form operations.
	WarehouseMonthlyProductBomForm = warehouseMonthlyProductBomFormDao{internal.NewWarehouseMonthlyProductBomFormDao()}
)

// Add your custom methods and functionality below.
