// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-erp/internal/dao/internal"
)

// receiveReturnPosInvoiceDao is the data access object for the table erp_receive_return_pos_invoice.
// You can define custom methods on it to extend its functionality as needed.
type receiveReturnPosInvoiceDao struct {
	*internal.ReceiveReturnPosInvoiceDao
}

var (
	// ReceiveReturnPosInvoice is a globally accessible object for table erp_receive_return_pos_invoice operations.
	ReceiveReturnPosInvoice = receiveReturnPosInvoiceDao{internal.NewReceiveReturnPosInvoiceDao()}
)

// Add your custom methods and functionality below.
