// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ttpos-bmp/app/ttpos-erp/internal/dao/internal"
)

// warehouseLogisticsDao is the data access object for the table erp_warehouse_logistics.
// You can define custom methods on it to extend its functionality as needed.
type warehouseLogisticsDao struct {
	*internal.WarehouseLogisticsDao
}

var (
	// WarehouseLogistics is a globally accessible object for table erp_warehouse_logistics operations.
	WarehouseLogistics = warehouseLogisticsDao{internal.NewWarehouseLogisticsDao()}
)

// Add your custom methods and functionality below.
