// Grab 服务 Protobuf 定义文件
// 用于定义 Grab 相关的 gRPC 服务接口和消息结构

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: grab/grab.proto

package grab

import (
	context "context"
	takeout "ttpos-bmp/app/ttpos-takeout/api/takeout"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Grab_CreateSelfServeJourney_FullMethodName = "/grab.Grab/CreateSelfServeJourney"
	Grab_GetShopProviderCfg_FullMethodName     = "/grab.Grab/GetShopProviderCfg"
	Grab_NotifyMenuUpdate_FullMethodName       = "/grab.Grab/NotifyMenuUpdate"
)

// GrabClient is the client API for Grab service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Grab 服务接口定义
// 提供 Grab 渠道相关的 gRPC 服务方法
type GrabClient interface {
	// 创建自助激活链接
	// 参数：provider_name（外卖渠道，如 grab、lineman）、shop_uuid（门店UUID）、request_id（追踪ID，可选）
	// 返回：统一的 ApiResponse 格式，包含自助激活链接信息
	CreateSelfServeJourney(ctx context.Context, in *CreateSelfServeJourneyReq, opts ...grpc.CallOption) (*takeout.ApiResponse, error)
	// 查询门店第三方配置
	// 参数：shop_uuid（门店UUID）、provider_name（第三方名称，可选，默认 grab）
	// 返回：统一的 ApiResponse 格式，包含门店集成状态、第三方商户ID、更新时间等
	GetShopProviderCfg(ctx context.Context, in *GetShopProviderCfgReq, opts ...grpc.CallOption) (*takeout.ApiResponse, error)
	// 通知菜单更新
	// 参数：merchant_id（第三方商户ID）
	// 返回：统一的 ApiResponse 格式，包含请求ID用于追踪同步状态
	NotifyMenuUpdate(ctx context.Context, in *NotifyMenuUpdateReq, opts ...grpc.CallOption) (*takeout.ApiResponse, error)
}

type grabClient struct {
	cc grpc.ClientConnInterface
}

func NewGrabClient(cc grpc.ClientConnInterface) GrabClient {
	return &grabClient{cc}
}

func (c *grabClient) CreateSelfServeJourney(ctx context.Context, in *CreateSelfServeJourneyReq, opts ...grpc.CallOption) (*takeout.ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(takeout.ApiResponse)
	err := c.cc.Invoke(ctx, Grab_CreateSelfServeJourney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabClient) GetShopProviderCfg(ctx context.Context, in *GetShopProviderCfgReq, opts ...grpc.CallOption) (*takeout.ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(takeout.ApiResponse)
	err := c.cc.Invoke(ctx, Grab_GetShopProviderCfg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabClient) NotifyMenuUpdate(ctx context.Context, in *NotifyMenuUpdateReq, opts ...grpc.CallOption) (*takeout.ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(takeout.ApiResponse)
	err := c.cc.Invoke(ctx, Grab_NotifyMenuUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrabServer is the server API for Grab service.
// All implementations must embed UnimplementedGrabServer
// for forward compatibility.
//
// Grab 服务接口定义
// 提供 Grab 渠道相关的 gRPC 服务方法
type GrabServer interface {
	// 创建自助激活链接
	// 参数：provider_name（外卖渠道，如 grab、lineman）、shop_uuid（门店UUID）、request_id（追踪ID，可选）
	// 返回：统一的 ApiResponse 格式，包含自助激活链接信息
	CreateSelfServeJourney(context.Context, *CreateSelfServeJourneyReq) (*takeout.ApiResponse, error)
	// 查询门店第三方配置
	// 参数：shop_uuid（门店UUID）、provider_name（第三方名称，可选，默认 grab）
	// 返回：统一的 ApiResponse 格式，包含门店集成状态、第三方商户ID、更新时间等
	GetShopProviderCfg(context.Context, *GetShopProviderCfgReq) (*takeout.ApiResponse, error)
	// 通知菜单更新
	// 参数：merchant_id（第三方商户ID）
	// 返回：统一的 ApiResponse 格式，包含请求ID用于追踪同步状态
	NotifyMenuUpdate(context.Context, *NotifyMenuUpdateReq) (*takeout.ApiResponse, error)
	mustEmbedUnimplementedGrabServer()
}

// UnimplementedGrabServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrabServer struct{}

func (UnimplementedGrabServer) CreateSelfServeJourney(context.Context, *CreateSelfServeJourneyReq) (*takeout.ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSelfServeJourney not implemented")
}
func (UnimplementedGrabServer) GetShopProviderCfg(context.Context, *GetShopProviderCfgReq) (*takeout.ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShopProviderCfg not implemented")
}
func (UnimplementedGrabServer) NotifyMenuUpdate(context.Context, *NotifyMenuUpdateReq) (*takeout.ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyMenuUpdate not implemented")
}
func (UnimplementedGrabServer) mustEmbedUnimplementedGrabServer() {}
func (UnimplementedGrabServer) testEmbeddedByValue()              {}

// UnsafeGrabServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrabServer will
// result in compilation errors.
type UnsafeGrabServer interface {
	mustEmbedUnimplementedGrabServer()
}

func RegisterGrabServer(s grpc.ServiceRegistrar, srv GrabServer) {
	// If the following call panics, it indicates UnimplementedGrabServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Grab_ServiceDesc, srv)
}

func _Grab_CreateSelfServeJourney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSelfServeJourneyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabServer).CreateSelfServeJourney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grab_CreateSelfServeJourney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabServer).CreateSelfServeJourney(ctx, req.(*CreateSelfServeJourneyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grab_GetShopProviderCfg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopProviderCfgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabServer).GetShopProviderCfg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grab_GetShopProviderCfg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabServer).GetShopProviderCfg(ctx, req.(*GetShopProviderCfgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grab_NotifyMenuUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyMenuUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabServer).NotifyMenuUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grab_NotifyMenuUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabServer).NotifyMenuUpdate(ctx, req.(*NotifyMenuUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Grab_ServiceDesc is the grpc.ServiceDesc for Grab service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grab_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grab.Grab",
	HandlerType: (*GrabServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSelfServeJourney",
			Handler:    _Grab_CreateSelfServeJourney_Handler,
		},
		{
			MethodName: "GetShopProviderCfg",
			Handler:    _Grab_GetShopProviderCfg_Handler,
		},
		{
			MethodName: "NotifyMenuUpdate",
			Handler:    _Grab_NotifyMenuUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grab/grab.proto",
}
