// Grab 服务 Protobuf 定义文件
// 用于定义 Grab 相关的 gRPC 服务接口和消息结构

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: grab/grab.proto

package grab

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Grab_CreateSelfServeJourney_FullMethodName = "/grab.Grab/CreateSelfServeJourney"
)

// GrabClient is the client API for Grab service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Grab 服务接口定义
// 提供 Grab 渠道相关的 gRPC 服务方法
type GrabClient interface {
	// 创建自助激活链接
	// 参数：provider_name（外卖渠道，如 grab、lineman）、shop_uuid（门店UUID）、request_id（追踪ID，可选）
	// 返回：provider_name、self_serve_url（自助点餐链接）、request_id（追踪ID）
	CreateSelfServeJourney(ctx context.Context, in *CreateSelfServeJourneyReq, opts ...grpc.CallOption) (*CreateSelfServeJourneyResp, error)
}

type grabClient struct {
	cc grpc.ClientConnInterface
}

func NewGrabClient(cc grpc.ClientConnInterface) GrabClient {
	return &grabClient{cc}
}

func (c *grabClient) CreateSelfServeJourney(ctx context.Context, in *CreateSelfServeJourneyReq, opts ...grpc.CallOption) (*CreateSelfServeJourneyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSelfServeJourneyResp)
	err := c.cc.Invoke(ctx, Grab_CreateSelfServeJourney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrabServer is the server API for Grab service.
// All implementations must embed UnimplementedGrabServer
// for forward compatibility
//
// Grab 服务接口定义
// 提供 Grab 渠道相关的 gRPC 服务方法
type GrabServer interface {
	// 创建自助激活链接
	// 参数：provider_name（外卖渠道，如 grab、lineman）、shop_uuid（门店UUID）、request_id（追踪ID，可选）
	// 返回：provider_name、self_serve_url（自助点餐链接）、request_id（追踪ID）
	CreateSelfServeJourney(context.Context, *CreateSelfServeJourneyReq) (*CreateSelfServeJourneyResp, error)
	mustEmbedUnimplementedGrabServer()
}

// UnimplementedGrabServer must be embedded to have forward compatible implementations.
type UnimplementedGrabServer struct {
}

func (UnimplementedGrabServer) CreateSelfServeJourney(context.Context, *CreateSelfServeJourneyReq) (*CreateSelfServeJourneyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSelfServeJourney not implemented")
}
func (UnimplementedGrabServer) mustEmbedUnimplementedGrabServer() {}

// UnsafeGrabServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrabServer will
// result in compilation errors.
type UnsafeGrabServer interface {
	mustEmbedUnimplementedGrabServer()
}

func RegisterGrabServer(s grpc.ServiceRegistrar, srv GrabServer) {
	s.RegisterService(&Grab_ServiceDesc, srv)
}

func _Grab_CreateSelfServeJourney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSelfServeJourneyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabServer).CreateSelfServeJourney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grab_CreateSelfServeJourney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabServer).CreateSelfServeJourney(ctx, req.(*CreateSelfServeJourneyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Grab_ServiceDesc is the grpc.ServiceDesc for Grab service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grab_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grab.Grab",
	HandlerType: (*GrabServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSelfServeJourney",
			Handler:    _Grab_CreateSelfServeJourney_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grab/grab.proto",
}
