/*
 * 厨显项目
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package req

// KitchenSetting - 保持厨显设置
type KitchenSetting struct {

	// 顾客呼叫提醒
	CustomerCallReminder bool `json:"customerCallReminder"`

	// 来菜提醒
	FoodReminder bool `json:"foodReminder"`

	// 字体大小
	FontSize int32 `json:"fontSize"`

	// 机器备注
	Remark string `json:"remark"`

	// 商品打印档口
	ProductPrint int32 `json:"productPrint"`
}
