FROM node:20-slim AS build
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN corepack prepare pnpm

#使用国内镜像
RUN pnpm i -g nrm
RUN nrm use taobao
RUN npx update-browserslist-db@latest

WORKDIR /app
ADD views .

WORKDIR /app/admin
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install  --frozen-lockfile
RUN pnpm run build


WORKDIR /app/shop
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install  --frozen-lockfile
RUN  pnpm run build


FROM nginx:alpine
ADD public /var/www/public
WORKDIR /var/www/public
COPY --from=build /app/admin/admin ./admin
COPY --from=build /app/shop/dist ./shop
