// =================================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SaleOrderProduct is the golang structure for table sale_order_product.
type SaleOrderProduct struct {
	OpenMemberDiscount     int     `json:"openMemberDiscount"     orm:"open_member_discount"      description:"是否开启会员折扣, 0-否 1-是。添加商品时记录下状态不受后台改变，结账时检查是否改变"`                                                                                         // 是否开启会员折扣, 0-否 1-是。添加商品时记录下状态不受后台改变，结账时检查是否改变
	Id                     uint    `json:"id"                     orm:"id"                        description:"自增ID"`                                                                                                                                 // 自增ID
	Uuid                   uint64  `json:"uuid"                   orm:"uuid"                      description:"销售订单商品ID"`                                                                                                                             // 销售订单商品ID
	Name                   string  `json:"name"                   orm:"name"                      description:"商品名称"`                                                                                                                                 // 商品名称
	FlavorName             string  `json:"flavorName"             orm:"flavor_name"               description:"规格名称"`                                                                                                                                 // 规格名称
	Sign                   string  `json:"sign"                   orm:"sign"                      description:"商品签名,规格、属性、加料、是否改价、是否赠菜、送厨批次、销售价相同的商品签名相同,用于取消拆单时合并商品"`                                                                                // 商品签名,规格、属性、加料、是否改价、是否赠菜、送厨批次、销售价相同的商品签名相同,用于取消拆单时合并商品
	MultiLanguageNameUuid  uint64  `json:"multiLanguageNameUuid"  orm:"multi_language_name_uuid"  description:"多语言名称ID"`                                                                                                                              // 多语言名称ID
	Num                    int     `json:"num"                    orm:"num"                       description:"商品数量。不能减为0，当数量为1再减时，标记删除"`                                                                                                             // 商品数量。不能减为0，当数量为1再减时，标记删除
	ImageFileUuid          uint64  `json:"imageFileUuid"          orm:"image_file_uuid"           description:"商品图片ID"`                                                                                                                               // 商品图片ID
	FlavorPrice            float64 `json:"flavorPrice"            orm:"flavor_price"              description:"规格原价（单商品）,仅某规格商品的原价"`                                                                                                                  // 规格原价（单商品）,仅某规格商品的原价
	SaucePrice             float64 `json:"saucePrice"             orm:"sauce_price"               description:"小料价（单商品）,所有小料的价格之和"`                                                                                                                   // 小料价（单商品）,所有小料的价格之和
	ProductPrice           float64 `json:"productPrice"           orm:"product_price"             description:"原始单价（单商品）,规格原价+小料价"`                                                                                                                   // 原始单价（单商品）,规格原价+小料价
	ChangePriceTime        uint    `json:"changePriceTime"        orm:"change_price_time"         description:"改价时间(时间戳),用于判断是否改价和不同时间改价的商品不合并"`                                                                                                      // 改价时间(时间戳),用于判断是否改价和不同时间改价的商品不合并
	IsBuffet               int     `json:"isBuffet"               orm:"is_buffet"                 description:"是否为自助餐商品,0-否 1-是. 如果是自助餐商品，则sale_price为0"`                                                                                             // 是否为自助餐商品,0-否 1-是. 如果是自助餐商品，则sale_price为0
	SalePrice              float64 `json:"salePrice"              orm:"sale_price"                description:"销售价（单商品，折前价）,当自定义价格时，销售价=自定义价格,否则销售价=原始单价"`                                                                                            // 销售价（单商品，折前价）,当自定义价格时，销售价=自定义价格,否则销售价=原始单价
	SalePriceNoTax         float64 `json:"salePriceNoTax"         orm:"sale_price_no_tax"         description:"销售价,未含税价格（折前）"`                                                                                                                        // 销售价,未含税价格（折前）
	TaxRate                float64 `json:"taxRate"                orm:"tax_rate"                  description:"税率,单位%.加购时记录税率,结账时再重新核算"`                                                                                                              // 税率,单位%.加购时记录税率,结账时再重新核算
	MemberDiscountRate     float64 `json:"memberDiscountRate"     orm:"member_discount_rate"      description:"会员折扣率(0-100%)"`                                                                                                                        // 会员折扣率(0-100%)
	MemberCardDiscountRate float64 `json:"memberCardDiscountRate" orm:"member_card_discount_rate" description:"会员卡折扣率(0-100%)"`                                                                                                                       // 会员卡折扣率(0-100%)
	CustomDiscountRate     float64 `json:"customDiscountRate"     orm:"custom_discount_rate"      description:"自定义折扣率(0-100%)"`                                                                                                                       // 自定义折扣率(0-100%)
	MemberDiscountPrice    float64 `json:"memberDiscountPrice"    orm:"member_discount_price"     description:"会员折扣后的价格（单商品）=销售价*会员折扣率*会员卡折扣率"`                                                                                                       // 会员折扣后的价格（单商品）=销售价*会员折扣率*会员卡折扣率
	Price                  float64 `json:"price"                  orm:"price"                     description:"最终单价(单商品，会员、会员卡和优惠折扣后，折后价)。销售价*折扣率"`                                                                                                   // 最终单价(单商品，会员、会员卡和优惠折扣后，折后价)。销售价*折扣率
	ServiceTaxFee          float64 `json:"serviceTaxFee"          orm:"service_tax_fee"           description:"服务费税费（单商品）,0-不收取税费；收取时，服务费税费=服务费*税率"`                                                                                                  // 服务费税费（单商品）,0-不收取税费；收取时，服务费税费=服务费*税率
	TaxFee                 float64 `json:"taxFee"                 orm:"tax_fee"                   description:"商品税费（单商品）。商品已含税时，税费=规格原价*(1-1/(1+税率))；商品未含税时，税费=原始单价*税率"`                                                                              // 商品税费（单商品）。商品已含税时，税费=规格原价*(1-1/(1+税率))；商品未含税时，税费=原始单价*税率
	ServiceFee             float64 `json:"serviceFee"             orm:"service_fee"               description:"服务费（单商品）,0-固定服务费 大于0-按比例收服务费；商品已含税时，服务费=(最终单价-商品税费)*服务费比例；商品未含税时，服务费=最终单价*服务费比例"`                                                      // 服务费（单商品）,0-固定服务费 大于0-按比例收服务费；商品已含税时，服务费=(最终单价-商品税费)*服务费比例；商品未含税时，服务费=最终单价*服务费比例
	TotalPrice             float64 `json:"totalPrice"             orm:"total_price"               description:"应收金额(单商品)。商品已含税时，应收金额(单商品)=(最终单价-商品税费)+服务费+总税费；商品未含税时，应收金额(单商品)=最终单价+服务费+总税费"`                                                         // 应收金额(单商品)。商品已含税时，应收金额(单商品)=(最终单价-商品税费)+服务费+总税费；商品未含税时，应收金额(单商品)=最终单价+服务费+总税费
	OriginTotalPrice       float64 `json:"originTotalPrice"       orm:"origin_total_price"        description:"应收金额(单商品)。商品已含税时，应收金额(单商品)=(销售价-商品税费)+服务费+总税费；商品未含税时，应收金额(单商品)=销售价+服务费+总税费"`                                                           // 应收金额(单商品)。商品已含税时，应收金额(单商品)=(销售价-商品税费)+服务费+总税费；商品未含税时，应收金额(单商品)=销售价+服务费+总税费
	DiscountFee            float64 `json:"discountFee"            orm:"discount_fee"              description:"打折金额（单商品）=销售价-最终单价。校验：打折金额=会员折扣金额+自定义折扣金额"`                                                                                            // 打折金额（单商品）=销售价-最终单价。校验：打折金额=会员折扣金额+自定义折扣金额
	MemberDiscountFee      float64 `json:"memberDiscountFee"      orm:"member_discount_fee"       description:"会员折扣金额（单商品）=销售价*（1-会员折扣率*会员卡折扣率）"`                                                                                                     // 会员折扣金额（单商品）=销售价*（1-会员折扣率*会员卡折扣率）
	CustomDiscountFee      float64 `json:"customDiscountFee"      orm:"custom_discount_fee"       description:"自定义折扣金额（单商品）。自定义折扣金额（单商品）=会员折扣后的价格（单商品）*(1-自定义折扣率) 。校验：自定义折扣金额（单商品）=销售价 - 最终单价（单商品）-会员折扣金额（单商品）；注意，不能这样算，自定义折扣金额（单商品）=销售价*(1-自定义折扣率)"` // 自定义折扣金额（单商品）。自定义折扣金额（单商品）=会员折扣后的价格（单商品）*(1-自定义折扣率) 。校验：自定义折扣金额（单商品）=销售价 - 最终单价（单商品）-会员折扣金额（单商品）；注意，不能这样算，自定义折扣金额（单商品）=销售价*(1-自定义折扣率)
	Status                 int     `json:"status"                 orm:"status"                    description:"状态, 0-未送厨 1-已送厨"`                                                                                                                      // 状态, 0-未送厨 1-已送厨
	IsRequire              int     `json:"isRequire"              orm:"is_require"                description:"是否必点商品 0-否 1-是。用于在前端显示必点图标"`                                                                                                           // 是否必点商品 0-否 1-是。用于在前端显示必点图标
	DeductStockType        int     `json:"deductStockType"        orm:"deduct_stock_type"         description:"库存计算方式,0-下单减库存 1-付款减库存。加购商品时记录，不受后台影响，用于减少查询次数"`                                                                                       // 库存计算方式,0-下单减库存 1-付款减库存。加购商品时记录，不受后台影响，用于减少查询次数
	DeductStockTime        uint    `json:"deductStockTime"        orm:"deduct_stock_time"         description:"减库存的时间(时间戳)，0-未减库存。标记是否已减库存，用于取消订单时恢复库存、避免重复减库存、避免漏减库存"`                                                                               // 减库存的时间(时间戳)，0-未减库存。标记是否已减库存，用于取消订单时恢复库存、避免重复减库存、避免漏减库存
	Remark                 string  `json:"remark"                 orm:"remark"                    description:"备注，顾客对商品的备注信息"`                                                                                                                        // 备注，顾客对商品的备注信息
	GiftTime               uint    `json:"giftTime"               orm:"gift_time"                 description:"赠菜时间(时间戳),用于判断是否赠菜和不同时间赠送的商品不合并"`                                                                                                      // 赠菜时间(时间戳),用于判断是否赠菜和不同时间赠送的商品不合并
	CancelTime             uint    `json:"cancelTime"             orm:"cancel_time"               description:"退菜时间(时间戳)"`                                                                                                                            // 退菜时间(时间戳)
	GiftReason             string  `json:"giftReason"             orm:"gift_reason"               description:"赠菜原因"`                                                                                                                                 // 赠菜原因
	CancelReason           string  `json:"cancelReason"           orm:"cancel_reason"             description:"退菜原因"`                                                                                                                                 // 退菜原因
	ProductionOrderUuid    uint64  `json:"productionOrderUuid"    orm:"production_order_uuid"     description:"生产订单ID"`                                                                                                                               // 生产订单ID
	ProductPackageUuid     uint64  `json:"productPackageUuid"     orm:"product_package_uuid"      description:"商品包ID"`                                                                                                                                // 商品包ID
	SaleBillUuid           uint64  `json:"saleBillUuid"           orm:"sale_bill_uuid"            description:"销售账单ID"`                                                                                                                               // 销售账单ID
	SaleOrderUuid          uint64  `json:"saleOrderUuid"          orm:"sale_order_uuid"           description:"销售订单ID"`                                                                                                                               // 销售订单ID
	MustPlanUuid           uint64  `json:"mustPlanUuid"           orm:"must_plan_uuid"            description:"必点方案ID,产品要求用这种方式标注各个必点"`                                                                                                               // 必点方案ID,产品要求用这种方式标注各个必点
	DeskUuid               uint64  `json:"deskUuid"               orm:"desk_uuid"                 description:"桌台ID, 默认为0是本台，大于0为合并过来的桌台"`                                                                                                            // 桌台ID, 默认为0是本台，大于0为合并过来的桌台
	H5OrderUuid            uint64  `json:"h5OrderUuid"            orm:"h5_order_uuid"             description:"扫码订单ID，用于关联扫码订单，用于判断是否为扫码订单商品"`                                                                                                        // 扫码订单ID，用于关联扫码订单，用于判断是否为扫码订单商品
	H5OrderProductUuid     uint64  `json:"h5OrderProductUuid"     orm:"h5_order_product_uuid"     description:"h5订单商品ID，用于关联h5订单商品，用于判断是否为h5订单商品"`                                                                                                    // h5订单商品ID，用于关联h5订单商品，用于判断是否为h5订单商品
	IsAcceptOrder          int     `json:"isAcceptOrder"          orm:"is_accept_order"           description:"是否已接单, 0-否 1-是。订单商品默认已接单，h5订单商品只有下单并接单后才改为已接单"`                                                                                        // 是否已接单, 0-否 1-是。订单商品默认已接单，h5订单商品只有下单并接单后才改为已接单
	SendKitchenTime        uint    `json:"sendKitchenTime"        orm:"send_kitchen_time"         description:"送厨时间(时间戳)"`                                                                                                                            // 送厨时间(时间戳)
	CreateTime             uint    `json:"createTime"             orm:"create_time"               description:"创建时间(时间戳)"`                                                                                                                            // 创建时间(时间戳)
	UpdateTime             uint    `json:"updateTime"             orm:"update_time"               description:"更新时间(时间戳)"`                                                                                                                            // 更新时间(时间戳)
	DeleteTime             uint    `json:"deleteTime"             orm:"delete_time"               description:"删除时间(时间戳)"`                                                                                                                            // 删除时间(时间戳)
}
