// =================================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SaleOrder is the golang structure for table sale_order.
type SaleOrder struct {
	Id                     uint    `json:"id"                     orm:"id"                        description:"自增ID"`                                                                                                          // 自增ID
	Uuid                   int64   `json:"uuid"                   orm:"uuid"                      description:"销售订单ID"`                                                                                                        // 销售订单ID
	OrderNo                string  `json:"orderNo"                orm:"order_no"                  description:"订单编号"`                                                                                                          // 订单编号
	Status                 int     `json:"status"                 orm:"status"                    description:"订单状态, 0-未结账 1-已结账"`                                                                                             // 订单状态, 0-未结账 1-已结账
	MemberDiscountFee      float64 `json:"memberDiscountFee"      orm:"member_discount_fee"       description:"总会员折扣金额。总会员折扣金额=(订单商品.会员折扣金额)之和"`                                                                               // 总会员折扣金额。总会员折扣金额=(订单商品.会员折扣金额)之和
	CustomDiscountFee      float64 `json:"customDiscountFee"      orm:"custom_discount_fee"       description:"总自定义折扣金额。总自定义折扣金额=(订单商品.自定义折扣金额)之和"`                                                                            // 总自定义折扣金额。总自定义折扣金额=(订单商品.自定义折扣金额)之和
	ZeroFee                float64 `json:"zeroFee"                orm:"zero_fee"                  description:"优惠折扣抹零金额。"`                                                                                                     // 优惠折扣抹零金额。
	ProductAmount          float64 `json:"productAmount"          orm:"product_amount"            description:"商品金额，订单商品的最终单价(折后价)之和。商品已含税时，该金额包括了税费。当商品未含税时，该金额不包括税费"`                                                        // 商品金额，订单商品的最终单价(折后价)之和。商品已含税时，该金额包括了税费。当商品未含税时，该金额不包括税费
	ProductOriginalAmount  float64 `json:"productOriginalAmount"  orm:"product_original_amount"   description:"原始商品金额(折前价)。 商品原始金额=订单商品的销售价(折前价)之和。"`                                                                          // 原始商品金额(折前价)。 商品原始金额=订单商品的销售价(折前价)之和。
	ServiceFee             float64 `json:"serviceFee"             orm:"service_fee"               description:"服务费固定服务费时，服务费=固定服务费；按比例收服务费时，服务费=(订单商品.总服务费)之和"`                                                                // 服务费固定服务费时，服务费=固定服务费；按比例收服务费时，服务费=(订单商品.总服务费)之和
	TaxFee                 float64 `json:"taxFee"                 orm:"tax_fee"                   description:"税费。税费=(订单商品.总税费)之和"`                                                                                            // 税费。税费=(订单商品.总税费)之和
	Amount                 float64 `json:"amount"                 orm:"amount"                    description:"应收金额。商品未含税时，总金额=商品金额+服务费+税费。商品已含税时，总金额=商品金额（含商品消费税）+服务费+税费（只有服务费税）"`                                            // 应收金额。商品未含税时，总金额=商品金额+服务费+税费。商品已含税时，总金额=商品金额（含商品消费税）+服务费+税费（只有服务费税）
	OriginAmount           float64 `json:"originAmount"           orm:"origin_amount"             description:"原始应收金额。原始应收金额=商品金额+服务费+消费税。商品未含税时，原始应收金额=商品金额+服务费+消费税（商品消费税税费+服务费税费）。商品已含税时，原始应收金额=商品金额（包含商品消费税税费）+服务费+服务费税费。"` // 原始应收金额。原始应收金额=商品金额+服务费+消费税。商品未含税时，原始应收金额=商品金额+服务费+消费税（商品消费税税费+服务费税费）。商品已含税时，原始应收金额=商品金额（包含商品消费税税费）+服务费+服务费税费。
	IsFree                 int     `json:"isFree"                 orm:"is_free"                   description:"是否免单, 0-否 1-是"`                                                                                                 // 是否免单, 0-否 1-是
	FreeReason             string  `json:"freeReason"             orm:"free_reason"               description:"免单原因"`                                                                                                          // 免单原因
	MemberDiscountRate     float64 `json:"memberDiscountRate"     orm:"member_discount_rate"      description:"会员折扣率(0-100%)，默认100%，取值范围0-1，如折扣率为10%，则取值为0.1"`                                                                 // 会员折扣率(0-100%)，默认100%，取值范围0-1，如折扣率为10%，则取值为0.1
	MemberCardDiscountRate float64 `json:"memberCardDiscountRate" orm:"member_card_discount_rate" description:"会员卡折扣率(0-100%)，默认100%，取值范围0-1，如折扣率为10%，则取值为0.1"`                                                                // 会员卡折扣率(0-100%)，默认100%，取值范围0-1，如折扣率为10%，则取值为0.1
	CustomDiscountRate     float64 `json:"customDiscountRate"     orm:"custom_discount_rate"      description:"自定义折扣率(0-100%)，默认100%，取值范围0-1，如折扣率为10%，则取值为0.1"`                                                                // 自定义折扣率(0-100%)，默认100%，取值范围0-1，如折扣率为10%，则取值为0.1
	CustomAmount           float64 `json:"customAmount"           orm:"custom_amount"             description:"整单改价金额。改价后，应收金额=整单改价金额，前端优先显示改价后的金额，改价金额不能为负数。当为-1时，表示不改价，显示amount改收金额"`                                        // 整单改价金额。改价后，应收金额=整单改价金额，前端优先显示改价后的金额，改价金额不能为负数。当为-1时，表示不改价，显示amount改收金额
	ZeroRule               int     `json:"zeroRule"               orm:"zero_rule"                 description:"优惠折扣抹零, 0-实款实收 1-抹分 2-抹角 3-四舍五入保留一位小数 4-四舍五入保留整数"`                                                              // 优惠折扣抹零, 0-实款实收 1-抹分 2-抹角 3-四舍五入保留一位小数 4-四舍五入保留整数
	ZeroCheckoutRule       int     `json:"zeroCheckoutRule"       orm:"zero_checkout_rule"        description:"结账抹零, 0-实款实收 1-抹分 2-抹角 3-抹元"`                                                                                   // 结账抹零, 0-实款实收 1-抹分 2-抹角 3-抹元
	PaymentAmount          float64 `json:"paymentAmount"          orm:"payment_amount"            description:"已支付金额,关联付款单的支付金额之和。"`                                                                                           // 已支付金额,关联付款单的支付金额之和。
	ChangeAmount           float64 `json:"changeAmount"           orm:"change_amount"             description:"找零金额,结账完成后才记录"`                                                                                                 // 找零金额,结账完成后才记录
	ZeroCheckoutFee        float64 `json:"zeroCheckoutFee"        orm:"zero_checkout_fee"         description:"结账抹零金额。"`                                                                                                       // 结账抹零金额。
	FinalPrice             float64 `json:"finalPrice"             orm:"final_price"               description:"最终应收金额。最终应收金额=应收金额+手续费-结账抹零金额"`                                                                                 // 最终应收金额。最终应收金额=应收金额+手续费-结账抹零金额
	PaymentCommissionFee   float64 `json:"paymentCommissionFee"   orm:"payment_commission_fee"    description:"支付手续费,关联付款单的支付手续费之和"`                                                                                           // 支付手续费,关联付款单的支付手续费之和
	GiftAmount             float64 `json:"giftAmount"             orm:"gift_amount"               description:"赠菜金额,(销售订单赠菜商品.总最终单价)之和"`                                                                                       // 赠菜金额,(销售订单赠菜商品.总最终单价)之和
	GiftPoints             float64 `json:"giftPoints"             orm:"gift_points"               description:"赠送积分. 赠送积分=应收金额amount*积分赠送比例."`                                                                                 // 赠送积分. 赠送积分=应收金额amount*积分赠送比例.
	GiftPointsRate         float64 `json:"giftPointsRate"         orm:"gift_points_rate"          description:"赠送积分比例. 取值范围0-1。结账后记录，不受后台改变"`                                                                                  // 赠送积分比例. 取值范围0-1。结账后记录，不受后台改变
	MemberBalance          float64 `json:"memberBalance"          orm:"member_balance"            description:"会员余额.会员消费本单后剩余的余额"`                                                                                             // 会员余额.会员消费本单后剩余的余额
	CashierName            string  `json:"cashierName"            orm:"cashier_name"              description:"收银员名称"`                                                                                                         // 收银员名称
	ConsumerUuid           int64   `json:"consumerUuid"           orm:"consumer_uuid"             description:"消费者ID"`                                                                                                         // 消费者ID
	CashierUuid            int64   `json:"cashierUuid"            orm:"cashier_uuid"              description:"收银员ID"`                                                                                                         // 收银员ID
	SaleBillUuid           int64   `json:"saleBillUuid"           orm:"sale_bill_uuid"            description:"销售账单ID"`                                                                                                        // 销售账单ID
	FinishTime             uint    `json:"finishTime"             orm:"finish_time"               description:"完成时间(时间戳),结账时间"`                                                                                                // 完成时间(时间戳),结账时间
	CreateTime             uint    `json:"createTime"             orm:"create_time"               description:"创建时间(时间戳)"`                                                                                                     // 创建时间(时间戳)
	UpdateTime             uint    `json:"updateTime"             orm:"update_time"               description:"更新时间(时间戳)"`                                                                                                     // 更新时间(时间戳)
	DeleteTime             uint    `json:"deleteTime"             orm:"delete_time"               description:"删除时间(时间戳)"`                                                                                                     // 删除时间(时间戳)
}
