// Shop 服务 Protobuf 定义文件
// 用于定义 Shop 相关的 gRPC 服务接口和消息结构

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: shop/shop.proto

package shop

import (
	context "context"
	takeout "ttpos-bmp/app/ttpos-takeout/api/takeout"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Shop_ActivateShop_FullMethodName       = "/shop.Shop/ActivateShop"
	Shop_GetShopProviderCfg_FullMethodName = "/shop.Shop/GetShopProviderCfg"
)

// ShopClient is the client API for Shop service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Shop 服务接口定义
// 提供门店管理相关的 gRPC 服务方法
type ShopClient interface {
	// 激活门店外卖渠道
	// 参数：provider_name（外卖渠道）、shop_uuid（门店UUID）、request_id（追踪ID，可选）
	// 返回：统一的 ApiResponse 格式，包含激活结果和配置信息
	ActivateShop(ctx context.Context, in *ActivateShopReq, opts ...grpc.CallOption) (*takeout.ApiResponse, error)
	// 查询门店第三方配置
	// 参数：shop_uuid（门店UUID）、provider_name（第三方名称，可选，为空时返回所有渠道配置）
	// 返回：统一的 ApiResponse 格式，包含门店集成状态、第三方商户ID、更新时间等
	GetShopProviderCfg(ctx context.Context, in *GetShopProviderCfgReq, opts ...grpc.CallOption) (*takeout.ApiResponse, error)
}

type shopClient struct {
	cc grpc.ClientConnInterface
}

func NewShopClient(cc grpc.ClientConnInterface) ShopClient {
	return &shopClient{cc}
}

func (c *shopClient) ActivateShop(ctx context.Context, in *ActivateShopReq, opts ...grpc.CallOption) (*takeout.ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(takeout.ApiResponse)
	err := c.cc.Invoke(ctx, Shop_ActivateShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopClient) GetShopProviderCfg(ctx context.Context, in *GetShopProviderCfgReq, opts ...grpc.CallOption) (*takeout.ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(takeout.ApiResponse)
	err := c.cc.Invoke(ctx, Shop_GetShopProviderCfg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServer is the server API for Shop service.
// All implementations must embed UnimplementedShopServer
// for forward compatibility.
//
// Shop 服务接口定义
// 提供门店管理相关的 gRPC 服务方法
type ShopServer interface {
	// 激活门店外卖渠道
	// 参数：provider_name（外卖渠道）、shop_uuid（门店UUID）、request_id（追踪ID，可选）
	// 返回：统一的 ApiResponse 格式，包含激活结果和配置信息
	ActivateShop(context.Context, *ActivateShopReq) (*takeout.ApiResponse, error)
	// 查询门店第三方配置
	// 参数：shop_uuid（门店UUID）、provider_name（第三方名称，可选，为空时返回所有渠道配置）
	// 返回：统一的 ApiResponse 格式，包含门店集成状态、第三方商户ID、更新时间等
	GetShopProviderCfg(context.Context, *GetShopProviderCfgReq) (*takeout.ApiResponse, error)
	mustEmbedUnimplementedShopServer()
}

// UnimplementedShopServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShopServer struct{}

func (UnimplementedShopServer) ActivateShop(context.Context, *ActivateShopReq) (*takeout.ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateShop not implemented")
}
func (UnimplementedShopServer) GetShopProviderCfg(context.Context, *GetShopProviderCfgReq) (*takeout.ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShopProviderCfg not implemented")
}
func (UnimplementedShopServer) mustEmbedUnimplementedShopServer() {}
func (UnimplementedShopServer) testEmbeddedByValue()              {}

// UnsafeShopServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopServer will
// result in compilation errors.
type UnsafeShopServer interface {
	mustEmbedUnimplementedShopServer()
}

func RegisterShopServer(s grpc.ServiceRegistrar, srv ShopServer) {
	// If the following call panics, it indicates UnimplementedShopServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Shop_ServiceDesc, srv)
}

func _Shop_ActivateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateShopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServer).ActivateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shop_ActivateShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServer).ActivateShop(ctx, req.(*ActivateShopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shop_GetShopProviderCfg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopProviderCfgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServer).GetShopProviderCfg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shop_GetShopProviderCfg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServer).GetShopProviderCfg(ctx, req.(*GetShopProviderCfgReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Shop_ServiceDesc is the grpc.ServiceDesc for Shop service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shop_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shop.Shop",
	HandlerType: (*ShopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActivateShop",
			Handler:    _Shop_ActivateShop_Handler,
		},
		{
			MethodName: "GetShopProviderCfg",
			Handler:    _Shop_GetShopProviderCfg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop/shop.proto",
}
