[program:think-queue-print]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www
command=php ./think queue:work --queue "print" --quiet
numprocs=15
autostart=true
autorestart=true
startretries=3
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/docker/php/log/queue-print.log