[program:php]
directory=/var/www
command=/var/docker/php/supervisor/job.sh
numprocs=1
autostart=true
autorestart=true
startretries=3
user=www-data
redirect_stderr=false
stdout_logfile=/var/docker/php/log/job.log


