package erp

// Supplier 结构体，表示供应商信息
type Supplier struct {
	Name                                               string                  `json:"name,omitempty"`                                                     // 名称
	Owner                                              string                  `json:"owner,omitempty"`                                                    // 拥有者
	Creation                                           string                  `json:"creation,omitempty"`                                                 // 创建时间
	Modified                                           string                  `json:"modified,omitempty"`                                                 // 修改时间
	ModifiedBy                                         string                  `json:"modified_by,omitempty"`                                              // 修改人
	Docstatus                                          int                     `json:"docstatus,omitempty"`                                                // 单据状态
	Idx                                                int                     `json:"idx,omitempty"`                                                      // 索引
	NamingSeries                                       string                  `json:"naming_series,omitempty"`                                            // 编码规则
	SupplierName                                       string                  `json:"supplier_name,omitempty"`                                            // 供应商名称
	Country                                            string                  `json:"country,omitempty"`                                                  // 国家
	SupplierType                                       string                  `json:"supplier_type,omitempty"`                                            // 供应商类型
	IsTransporter                                      int                     `json:"is_transporter,omitempty"`                                           // 是否承运商
	IsInternalSupplier                                 int                     `json:"is_internal_supplier,omitempty"`                                     // 是否内部供应商
	RepresentsCompany                                  string                  `json:"represents_company,omitempty"`                                       // 代表公司
	Language                                           string                  `json:"language,omitempty"`                                                 // 语言
	AllowPurchaseInvoiceCreationWithoutPurchaseOrder   int                     `json:"allow_purchase_invoice_creation_without_purchase_order,omitempty"`   // 允许无采购订单创建采购发票
	AllowPurchaseInvoiceCreationWithoutPurchaseReceipt int                     `json:"allow_purchase_invoice_creation_without_purchase_receipt,omitempty"` // 允许无收货单创建采购发票
	IsFrozen                                           int                     `json:"is_frozen,omitempty"`                                                // 是否冻结
	Disabled                                           int                     `json:"disabled,omitempty"`                                                 // 是否禁用
	WarnRfqs                                           int                     `json:"warn_rfqs,omitempty"`                                                // 询价单警告
	WarnPos                                            int                     `json:"warn_pos,omitempty"`                                                 // 采购订单警告
	PreventRfqs                                        int                     `json:"prevent_rfqs,omitempty"`                                             // 阻止询价单
	PreventPos                                         int                     `json:"prevent_pos,omitempty"`                                              // 阻止采购订单
	OnHold                                             int                     `json:"on_hold,omitempty"`                                                  // 是否暂停
	HoldType                                           string                  `json:"hold_type,omitempty"`                                                // 暂停类型
	Doctype                                            string                  `json:"doctype,omitempty"`                                                  // 单据类型
	Accounts                                           []interface{}           `json:"accounts,omitempty"`                                                 // 账户信息
	PortalUsers                                        []interface{}           `json:"portal_users,omitempty"`                                             // 门户用户
	Companies                                          []AllowedToTransactWith `json:"companies,omitempty"`                                                // 允许交易的公司
}

// AllowedToTransactWith 结构体，表示允许交易的公司
type AllowedToTransactWith struct {
	Name        string `json:"name,omitempty"`        // 名称
	Owner       string `json:"owner,omitempty"`       // 拥有者
	Creation    string `json:"creation,omitempty"`    // 创建时间
	Modified    string `json:"modified,omitempty"`    // 修改时间
	ModifiedBy  string `json:"modified_by,omitempty"` // 修改人
	Docstatus   int    `json:"docstatus,omitempty"`   // 单据状态
	Idx         int    `json:"idx,omitempty"`         // 索引
	Company     string `json:"company,omitempty"`     // 公司
	Parent      string `json:"parent,omitempty"`      // 父级
	Parentfield string `json:"parentfield,omitempty"` // 父级字段
	Parenttype  string `json:"parenttype,omitempty"`  // 父级类型
	Doctype     string `json:"doctype,omitempty"`     // 单据类型
}

// PaymentSchedule 结构体，表示付款计划
type PaymentSchedule struct {
	Name              string  `json:"name,omitempty"`                // 名称
	Owner             string  `json:"owner,omitempty"`               // 拥有者
	Creation          string  `json:"creation,omitempty"`            // 创建时间
	Modified          string  `json:"modified,omitempty"`            // 修改时间
	ModifiedBy        string  `json:"modified_by,omitempty"`         // 修改人
	Docstatus         int     `json:"docstatus,omitempty"`           // 单据状态
	Idx               int     `json:"idx,omitempty"`                 // 索引
	DueDate           string  `json:"due_date,omitempty"`            // 到期日期
	InvoicePortion    float64 `json:"invoice_portion,omitempty"`     // 发票比例
	Discount          float64 `json:"discount,omitempty"`            // 折扣
	PaymentAmount     float64 `json:"payment_amount,omitempty"`      // 付款金额
	Outstanding       float64 `json:"outstanding,omitempty"`         // 未付金额
	PaidAmount        float64 `json:"paid_amount,omitempty"`         // 已付金额
	DiscountedAmount  float64 `json:"discounted_amount,omitempty"`   // 折扣金额
	BasePaymentAmount float64 `json:"base_payment_amount,omitempty"` // 基础付款金额
	BaseOutstanding   float64 `json:"base_outstanding,omitempty"`    // 基础未付金额
	BasePaidAmount    float64 `json:"base_paid_amount,omitempty"`    // 基础已付金额
	Parent            string  `json:"parent,omitempty"`              // 父级
	Parentfield       string  `json:"parentfield,omitempty"`         // 父级字段
	Parenttype        string  `json:"parenttype,omitempty"`          // 父级类型
	Doctype           string  `json:"doctype,omitempty"`             // 单据类型
}

// PurchaseOrderItem 结构体，表示采购订单项目
type PurchaseOrderItem struct {
	Name                      string  `json:"name,omitempty"`                        // 名称
	Owner                     string  `json:"owner,omitempty"`                       // 拥有者
	Creation                  string  `json:"creation,omitempty"`                    // 创建时间
	Modified                  string  `json:"modified,omitempty"`                    // 修改时间
	ModifiedBy                string  `json:"modified_by,omitempty"`                 // 修改人
	Docstatus                 int     `json:"docstatus,omitempty"`                   // 单据状态
	Idx                       int     `json:"idx,omitempty"`                         // 索引
	FgItemQty                 float64 `json:"fg_item_qty,omitempty"`                 // 成品项目数量
	ItemCode                  string  `json:"item_code,omitempty"`                   // 项目编码
	ItemName                  string  `json:"item_name,omitempty"`                   // 项目名称
	ScheduleDate              string  `json:"schedule_date,omitempty"`               // 计划日期
	ItemGroup                 string  `json:"item_group,omitempty"`                  // 项目组
	Description               string  `json:"description,omitempty"`                 // 描述
	Image                     string  `json:"image,omitempty"`                       // 图片
	Qty                       float64 `json:"qty,omitempty"`                         // 数量
	StockUom                  string  `json:"stock_uom,omitempty"`                   // 库存单位
	SubcontractedQuantity     float64 `json:"subcontracted_quantity,omitempty"`      // 分包数量
	Uom                       string  `json:"uom,omitempty"`                         // 单位
	ConversionFactor          float64 `json:"conversion_factor,omitempty"`           // 转换因子
	StockQty                  float64 `json:"stock_qty,omitempty"`                   // 库存数量
	PriceListRate             float64 `json:"price_list_rate,omitempty"`             // 价目表价格
	LastPurchaseRate          float64 `json:"last_purchase_rate,omitempty"`          // 最后采购价格
	BasePriceListRate         float64 `json:"base_price_list_rate,omitempty"`        // 基础价目表价格
	MarginType                string  `json:"margin_type,omitempty"`                 // 利润率类型
	MarginRateOrAmount        float64 `json:"margin_rate_or_amount,omitempty"`       // 利润率或金额
	RateWithMargin            float64 `json:"rate_with_margin,omitempty"`            // 含利润率价格
	DiscountPercentage        float64 `json:"discount_percentage,omitempty"`         // 折扣百分比
	DiscountAmount            float64 `json:"discount_amount,omitempty"`             // 折扣金额
	DistributedDiscountAmount float64 `json:"distributed_discount_amount,omitempty"` // 分配折扣金额
	BaseRateWithMargin        float64 `json:"base_rate_with_margin,omitempty"`       // 基础含利润率价格
	Rate                      float64 `json:"rate,omitempty"`                        // 价格
	Amount                    float64 `json:"amount,omitempty"`                      // 金额
	BaseRate                  float64 `json:"base_rate,omitempty"`                   // 基础价格
	BaseAmount                float64 `json:"base_amount,omitempty"`                 // 基础金额
	StockUomRate              float64 `json:"stock_uom_rate,omitempty"`              // 库存单位价格
	IsFreeItem                int     `json:"is_free_item,omitempty"`                // 是否免费项目
	ApplyTds                  int     `json:"apply_tds,omitempty"`                   // 应用TDS
	NetRate                   float64 `json:"net_rate,omitempty"`                    // 净价格
	NetAmount                 float64 `json:"net_amount,omitempty"`                  // 净金额
	BaseNetRate               float64 `json:"base_net_rate,omitempty"`               // 基础净价格
	BaseNetAmount             float64 `json:"base_net_amount,omitempty"`             // 基础净金额
	Warehouse                 string  `json:"warehouse,omitempty"`                   // 仓库
	ActualQty                 float64 `json:"actual_qty,omitempty"`                  // 实际数量
	CompanyTotalStock         float64 `json:"company_total_stock,omitempty"`         // 公司总库存
	MaterialRequest           string  `json:"material_request,omitempty"`            // 物料请求
	MaterialRequestItem       string  `json:"material_request_item,omitempty"`       // 物料请求项目
	DeliveredBySupplier       int     `json:"delivered_by_supplier,omitempty"`       // 供应商交付
	AgainstBlanketOrder       int     `json:"against_blanket_order,omitempty"`       // 针对总括订单
	BlanketOrderRate          float64 `json:"blanket_order_rate,omitempty"`          // 总括订单价格
	ReceivedQty               float64 `json:"received_qty,omitempty"`                // 已收数量
	ReturnedQty               float64 `json:"returned_qty,omitempty"`                // 退回数量
	BilledAmt                 float64 `json:"billed_amt,omitempty"`                  // 已开票金额
	ExpenseAccount            string  `json:"expense_account,omitempty"`             // 费用账户
	IncludeExplodedItems      int     `json:"include_exploded_items,omitempty"`      // 包含分解项目
	WeightPerUnit             float64 `json:"weight_per_unit,omitempty"`             // 单位重量
	TotalWeight               float64 `json:"total_weight,omitempty"`                // 总重量
	CostCenter                string  `json:"cost_center,omitempty"`                 // 成本中心
	IsFixedAsset              int     `json:"is_fixed_asset,omitempty"`              // 是否固定资产
	ItemTaxRate               string  `json:"item_tax_rate,omitempty"`               // 项目税率
	PageBreak                 int     `json:"page_break,omitempty"`                  // 分页符
	Parent                    string  `json:"parent,omitempty"`                      // 父级
	Parentfield               string  `json:"parentfield,omitempty"`                 // 父级字段
	Parenttype                string  `json:"parenttype,omitempty"`                  // 父级类型
	Doctype                   string  `json:"doctype,omitempty"`                     // 单据类型
}

// PurchaseOrder 结构体，表示采购订单
type PurchaseOrder struct {
	Name                         string              `json:"name,omitempty"`                            // 名称
	Owner                        string              `json:"owner,omitempty"`                           // 拥有者
	Creation                     string              `json:"creation,omitempty"`                        // 创建时间
	Modified                     string              `json:"modified,omitempty"`                        // 修改时间
	ModifiedBy                   string              `json:"modified_by,omitempty"`                     // 修改人
	Docstatus                    int                 `json:"docstatus,omitempty"`                       // 单据状态
	Idx                          int                 `json:"idx,omitempty"`                             // 索引
	Title                        string              `json:"title,omitempty"`                           // 标题
	NamingSeries                 string              `json:"naming_series,omitempty"`                   // 编码规则
	Supplier                     string              `json:"supplier,omitempty"`                        // 供应商
	SupplierName                 string              `json:"supplier_name,omitempty"`                   // 供应商名称
	TransactionDate              string              `json:"transaction_date,omitempty"`                // 交易日期
	ScheduleDate                 string              `json:"schedule_date,omitempty"`                   // 计划日期
	Company                      string              `json:"company,omitempty"`                         // 公司
	ApplyTds                     int                 `json:"apply_tds,omitempty"`                       // 应用TDS
	IsSubcontracted              int                 `json:"is_subcontracted,omitempty"`                // 是否分包
	HasUnitPriceItems            int                 `json:"has_unit_price_items,omitempty"`            // 是否有单位价格项目
	Currency                     string              `json:"currency,omitempty"`                        // 货币
	ConversionRate               float64             `json:"conversion_rate,omitempty"`                 // 转换汇率
	BuyingPriceList              string              `json:"buying_price_list,omitempty"`               // 采购价目表
	PriceListCurrency            string              `json:"price_list_currency,omitempty"`             // 价目表货币
	PlcConversionRate            float64             `json:"plc_conversion_rate,omitempty"`             // PLC转换汇率
	IgnorePricingRule            int                 `json:"ignore_pricing_rule,omitempty"`             // 忽略定价规则
	SetWarehouse                 string              `json:"set_warehouse,omitempty"`                   // 设置仓库
	TotalQty                     float64             `json:"total_qty,omitempty"`                       // 总数量
	TotalNetWeight               float64             `json:"total_net_weight,omitempty"`                // 总净重
	BaseTotal                    float64             `json:"base_total,omitempty"`                      // 基础总额
	BaseNetTotal                 float64             `json:"base_net_total,omitempty"`                  // 基础净总额
	Total                        float64             `json:"total,omitempty"`                           // 总额
	NetTotal                     float64             `json:"net_total,omitempty"`                       // 净总额
	TaxWithholdingNetTotal       float64             `json:"tax_withholding_net_total,omitempty"`       // 代扣税净总额
	BaseTaxWithholdingNetTotal   float64             `json:"base_tax_withholding_net_total,omitempty"`  // 基础代扣税净总额
	TaxCategory                  string              `json:"tax_category,omitempty"`                    // 税类别
	BaseTaxesAndChargesAdded     float64             `json:"base_taxes_and_charges_added,omitempty"`    // 基础税费和费用增加
	BaseTaxesAndChargesDeducted  float64             `json:"base_taxes_and_charges_deducted,omitempty"` // 基础税费和费用扣除
	BaseTotalTaxesAndCharges     float64             `json:"base_total_taxes_and_charges,omitempty"`    // 基础税费和费用总额
	TaxesAndChargesAdded         float64             `json:"taxes_and_charges_added,omitempty"`         // 税费和费用增加
	TaxesAndChargesDeducted      float64             `json:"taxes_and_charges_deducted,omitempty"`      // 税费和费用扣除
	TotalTaxesAndCharges         float64             `json:"total_taxes_and_charges,omitempty"`         // 税费和费用总额
	BaseGrandTotal               float64             `json:"base_grand_total,omitempty"`                // 基础总金额
	BaseRoundingAdjustment       float64             `json:"base_rounding_adjustment,omitempty"`        // 基础舍入调整
	BaseInWords                  string              `json:"base_in_words,omitempty"`                   // 基础金额大写
	BaseRoundedTotal             float64             `json:"base_rounded_total,omitempty"`              // 基础舍入总额
	GrandTotal                   float64             `json:"grand_total,omitempty"`                     // 总金额
	RoundingAdjustment           float64             `json:"rounding_adjustment,omitempty"`             // 舍入调整
	RoundedTotal                 float64             `json:"rounded_total,omitempty"`                   // 舍入总额
	DisableRoundedTotal          int                 `json:"disable_rounded_total,omitempty"`           // 禁用舍入总额
	InWords                      string              `json:"in_words,omitempty"`                        // 金额大写
	AdvancePaid                  float64             `json:"advance_paid,omitempty"`                    // 预付款
	ApplyDiscountOn              string              `json:"apply_discount_on,omitempty"`               // 应用折扣于
	BaseDiscountAmount           float64             `json:"base_discount_amount,omitempty"`            // 基础折扣金额
	AdditionalDiscountPercentage float64             `json:"additional_discount_percentage,omitempty"`  // 额外折扣百分比
	DiscountAmount               float64             `json:"discount_amount,omitempty"`                 // 折扣金额
	ShippingAddress              string              `json:"shipping_address,omitempty"`                // 送货地址
	ShippingAddressDisplay       string              `json:"shipping_address_display,omitempty"`        // 送货地址显示
	BillingAddress               string              `json:"billing_address,omitempty"`                 // 账单地址
	BillingAddressDisplay        string              `json:"billing_address_display,omitempty"`         // 账单地址显示
	Status                       string              `json:"status,omitempty"`                          // 状态
	PerBilled                    float64             `json:"per_billed,omitempty"`                      // 已开票百分比
	PerReceived                  float64             `json:"per_received,omitempty"`                    // 已收货百分比
	GroupSameItems               int                 `json:"group_same_items,omitempty"`                // 分组相同项目
	Language                     string              `json:"language,omitempty"`                        // 语言
	IsInternalSupplier           int                 `json:"is_internal_supplier,omitempty"`            // 是否内部供应商
	RepresentsCompany            string              `json:"represents_company,omitempty"`              // 代表公司
	PartyAccountCurrency         string              `json:"party_account_currency,omitempty"`          // 对方账户货币
	IsOldSubcontractingFlow      int                 `json:"is_old_subcontracting_flow,omitempty"`      // 是否旧分包流程
	Doctype                      string              `json:"doctype,omitempty"`                         // 单据类型
	PricingRules                 []interface{}       `json:"pricing_rules,omitempty"`                   // 定价规则
	SuppliedItems                []interface{}       `json:"supplied_items,omitempty"`                  // 供应项目
	PaymentSchedule              []PaymentSchedule   `json:"payment_schedule,omitempty"`                // 付款计划
	Items                        []PurchaseOrderItem `json:"items,omitempty"`                           // 项目
	Taxes                        []interface{}       `json:"taxes,omitempty"`                           // 税费
}
