# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":14031"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level : "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
  link: "mysql:root:$DB_ROOT_PASSWORD@tcp($DB_HOST:$DB_PORT_OPEN)/takeout"

grpc:
  name:            "ttpos-manager"
  address:            ":14032"
  logPath:          "./log"
  logStdout:        true
  errorLogEnabled:  true
  accessLogEnabled: true
  errorStack:       true

nacos:
  server:
    ip: localhost
    port: 8848
  config:
    dataId: ttpos-bmp.takeout.yaml
    group: DEFAULT_GROUP