package constant

import (
	"ttpos-server-go/app/dto"
)

// Country 国家信息
type Country struct {
	Code        string             // 国家编码（ISO 3166-1 alpha-2）
	LocaleNames dto.LocaleResponse // 多语言国家名称
}

// GetLocaleNames 获取多语言名称
func (c *Country) GetLocaleNames() dto.LocaleResponse {
	return c.LocaleNames
}

// 国家列表（部分国家，后续补充完整197个国家）
var countries = []Country{
	{
		Code: "CN",
		LocaleNames: dto.LocaleResponse{
			ZH:   "中国",
			ZHTW: "中國",
			EN:   "China",
			JA:   "中国",
			KO:   "중국",
			MY:   "တရုတ်",
			TH:   "จีน",
			TR:   "Çin",
			SV:   "Kina",
		},
	},
	{
		Code: "US",
		LocaleNames: dto.LocaleResponse{
			ZH:   "美国",
			ZHTW: "美國",
			EN:   "United States",
			JA:   "アメリカ合衆国",
			KO:   "미국",
			MY:   "အမေရိကန်",
			TH:   "สหรัฐอเมริกา",
			TR:   "Amerika Birleşik Devletleri",
			SV:   "USA",
		},
	},
	{
		Code: "TH",
		LocaleNames: dto.LocaleResponse{
			ZH:   "泰国",
			ZHTW: "泰國",
			EN:   "Thailand",
			JA:   "タイ",
			KO:   "태국",
			MY:   "ထိုင်း",
			TH:   "ประเทศไทย",
			TR:   "Tayland",
			SV:   "Thailand",
		},
	},
	{
		Code: "JP",
		LocaleNames: dto.LocaleResponse{
			ZH:   "日本",
			ZHTW: "日本",
			EN:   "Japan",
			JA:   "日本",
			KO:   "일본",
			MY:   "ဂျပန်",
			TH:   "ญี่ปุ่น",
			TR:   "Japonya",
			SV:   "Japan",
		},
	},
	{
		Code: "KR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "韩国",
			ZHTW: "韓國",
			EN:   "South Korea",
			JA:   "韓国",
			KO:   "대한민국",
			MY:   "တောင်ကိုရီးယား",
			TH:   "เกาหลีใต้",
			TR:   "Güney Kore",
			SV:   "Sydkorea",
		},
	},
	{
		Code: "MY",
		LocaleNames: dto.LocaleResponse{
			ZH:   "马来西亚",
			ZHTW: "馬來西亞",
			EN:   "Malaysia",
			JA:   "マレーシア",
			KO:   "말레이시아",
			MY:   "မလေးရှား",
			TH:   "มาเลเซีย",
			TR:   "Malezya",
			SV:   "Malaysia",
		},
	},
	{
		Code: "SG",
		LocaleNames: dto.LocaleResponse{
			ZH:   "新加坡",
			ZHTW: "新加坡",
			EN:   "Singapore",
			JA:   "シンガポール",
			KO:   "싱가포르",
			MY:   "စင်ကာပူ",
			TH:   "สิงคโปร์",
			TR:   "Singapur",
			SV:   "Singapore",
		},
	},
	{
		Code: "ID",
		LocaleNames: dto.LocaleResponse{
			ZH:   "印度尼西亚",
			ZHTW: "印尼",
			EN:   "Indonesia",
			JA:   "インドネシア",
			KO:   "인도네시아",
			MY:   "အင်ဒိုနီးရှား",
			TH:   "อินโดนีเซีย",
			TR:   "Endonezya",
			SV:   "Indonesien",
		},
	},
	{
		Code: "PH",
		LocaleNames: dto.LocaleResponse{
			ZH:   "菲律宾",
			ZHTW: "菲律賓",
			EN:   "Philippines",
			JA:   "フィリピン",
			KO:   "필리핀",
			MY:   "ဖိလစ်ပိုင်",
			TH:   "ฟิลิปปินส์",
			TR:   "Filipinler",
			SV:   "Filippinerna",
		},
	},
	{
		Code: "VN",
		LocaleNames: dto.LocaleResponse{
			ZH:   "越南",
			ZHTW: "越南",
			EN:   "Vietnam",
			JA:   "ベトナム",
			KO:   "베트남",
			MY:   "ဗီယက်နမ်",
			TH:   "เวียดนาม",
			TR:   "Vietnam",
			SV:   "Vietnam",
		},
	},
	{
		Code: "IN",
		LocaleNames: dto.LocaleResponse{
			ZH:   "印度",
			ZHTW: "印度",
			EN:   "India",
			JA:   "インド",
			KO:   "인도",
			MY:   "အိန္ဒိယ",
			TH:   "อินเดีย",
			TR:   "Hindistan",
			SV:   "Indien",
		},
	},
	{
		Code: "GB",
		LocaleNames: dto.LocaleResponse{
			ZH:   "英国",
			ZHTW: "英國",
			EN:   "United Kingdom",
			JA:   "イギリス",
			KO:   "영국",
			MY:   "ယူနိုက်တက်ကင်းဒမ်း",
			TH:   "สหราชอาณาจักร",
			TR:   "Birleşik Krallık",
			SV:   "Storbritannien",
		},
	},
	{
		Code: "FR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "法国",
			ZHTW: "法國",
			EN:   "France",
			JA:   "フランス",
			KO:   "프랑스",
			MY:   "ပြင်သစ်",
			TH:   "ฝรั่งเศส",
			TR:   "Fransa",
			SV:   "Frankrike",
		},
	},
	{
		Code: "DE",
		LocaleNames: dto.LocaleResponse{
			ZH:   "德国",
			ZHTW: "德國",
			EN:   "Germany",
			JA:   "ドイツ",
			KO:   "독일",
			MY:   "ဂျာမနီ",
			TH:   "เยอรมนี",
			TR:   "Almanya",
			SV:   "Tyskland",
		},
	},
	{
		Code: "IT",
		LocaleNames: dto.LocaleResponse{
			ZH:   "意大利",
			ZHTW: "義大利",
			EN:   "Italy",
			JA:   "イタリア",
			KO:   "이탈리아",
			MY:   "အီတလီ",
			TH:   "อิตาลี",
			TR:   "İtalya",
			SV:   "Italien",
		},
	},
	{
		Code: "ES",
		LocaleNames: dto.LocaleResponse{
			ZH:   "西班牙",
			ZHTW: "西班牙",
			EN:   "Spain",
			JA:   "スペイン",
			KO:   "스페인",
			MY:   "စပိန်",
			TH:   "สเปน",
			TR:   "İspanya",
			SV:   "Spanien",
		},
	},
	{
		Code: "RU",
		LocaleNames: dto.LocaleResponse{
			ZH:   "俄罗斯",
			ZHTW: "俄羅斯",
			EN:   "Russia",
			JA:   "ロシア",
			KO:   "러시아",
			MY:   "ရုရှား",
			TH:   "รัสเซีย",
			TR:   "Rusya",
			SV:   "Ryssland",
		},
	},
	{
		Code: "CA",
		LocaleNames: dto.LocaleResponse{
			ZH:   "加拿大",
			ZHTW: "加拿大",
			EN:   "Canada",
			JA:   "カナダ",
			KO:   "캐나다",
			MY:   "ကနေဒါ",
			TH:   "แคนาดา",
			TR:   "Kanada",
			SV:   "Kanada",
		},
	},
	{
		Code: "AU",
		LocaleNames: dto.LocaleResponse{
			ZH:   "澳大利亚",
			ZHTW: "澳洲",
			EN:   "Australia",
			JA:   "オーストラリア",
			KO:   "호주",
			MY:   "ဩစတြေးလျ",
			TH:   "ออสเตรเลีย",
			TR:   "Avustralya",
			SV:   "Australien",
		},
	},
	{
		Code: "NZ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "新西兰",
			ZHTW: "紐西蘭",
			EN:   "New Zealand",
			JA:   "ニュージーランド",
			KO:   "뉴질랜드",
			MY:   "နယူးဇီလန်",
			TH:   "นิวซีแลนด์",
			TR:   "Yeni Zelanda",
			SV:   "Nya Zeeland",
		},
	},
	{
		Code: "BR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "巴西",
			ZHTW: "巴西",
			EN:   "Brazil",
			JA:   "ブラジル",
			KO:   "브라질",
			MY:   "ဘရာဇီး",
			TH:   "บราซิล",
			TR:   "Brezilya",
			SV:   "Brasilien",
		},
	},
	{
		Code: "MX",
		LocaleNames: dto.LocaleResponse{
			ZH:   "墨西哥",
			ZHTW: "墨西哥",
			EN:   "Mexico",
			JA:   "メキシコ",
			KO:   "멕시코",
			MY:   "မက္ကဆီကို",
			TH:   "เม็กซิโก",
			TR:   "Meksika",
			SV:   "Mexiko",
		},
	},
	{
		Code: "AR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "阿根廷",
			ZHTW: "阿根廷",
			EN:   "Argentina",
			JA:   "アルゼンチン",
			KO:   "아르헨티나",
			MY:   "အာဂျင်တီးနား",
			TH:   "อาร์เจนตินา",
			TR:   "Arjantin",
			SV:   "Argentina",
		},
	},
	{
		Code: "TR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "土耳其",
			ZHTW: "土耳其",
			EN:   "Turkey",
			JA:   "トルコ",
			KO:   "터키",
			MY:   "တူရကီ",
			TH:   "ตุรกี",
			TR:   "Türkiye",
			SV:   "Turkiet",
		},
	},
	{
		Code: "SA",
		LocaleNames: dto.LocaleResponse{
			ZH:   "沙特阿拉伯",
			ZHTW: "沙烏地阿拉伯",
			EN:   "Saudi Arabia",
			JA:   "サウジアラビア",
			KO:   "사우디아라비아",
			MY:   "ဆော်ဒီအာရေဗျ",
			TH:   "ซาอุดีอาระเบีย",
			TR:   "Suudi Arabistan",
			SV:   "Saudiarabien",
		},
	},
	{
		Code: "AE",
		LocaleNames: dto.LocaleResponse{
			ZH:   "阿联酋",
			ZHTW: "阿拉伯聯合大公國",
			EN:   "United Arab Emirates",
			JA:   "アラブ首長国連邦",
			KO:   "아랍에미리트",
			MY:   "ယူအေအီး",
			TH:   "สหรัฐอาหรับเอมิเรตส์",
			TR:   "Birleşik Arap Emirlikleri",
			SV:   "Förenade Arabemiraten",
		},
	},
	{
		Code: "EG",
		LocaleNames: dto.LocaleResponse{
			ZH:   "埃及",
			ZHTW: "埃及",
			EN:   "Egypt",
			JA:   "エジプト",
			KO:   "이집트",
			MY:   "အီဂျစ်",
			TH:   "อียิปต์",
			TR:   "Mısır",
			SV:   "Egypten",
		},
	},
	{
		Code: "ZA",
		LocaleNames: dto.LocaleResponse{
			ZH:   "南非",
			ZHTW: "南非",
			EN:   "South Africa",
			JA:   "南アフリカ",
			KO:   "남아프리카 공화국",
			MY:   "တောင်အာဖရိက",
			TH:   "แอฟริกาใต้",
			TR:   "Güney Afrika",
			SV:   "Sydafrika",
		},
	},
	{
		Code: "NG",
		LocaleNames: dto.LocaleResponse{
			ZH:   "尼日利亚",
			ZHTW: "奈及利亞",
			EN:   "Nigeria",
			JA:   "ナイジェリア",
			KO:   "나이지리아",
			MY:   "နိုင်ဂျီးရီးယား",
			TH:   "ไนจีเรีย",
			TR:   "Nijerya",
			SV:   "Nigeria",
		},
	},
	{
		Code: "KE",
		LocaleNames: dto.LocaleResponse{
			ZH:   "肯尼亚",
			ZHTW: "肯亞",
			EN:   "Kenya",
			JA:   "ケニア",
			KO:   "케냐",
			MY:   "ကင်ညာ",
			TH:   "เคนยา",
			TR:   "Kenya",
			SV:   "Kenya",
		},
	},
	{
		Code: "HK",
		LocaleNames: dto.LocaleResponse{
			ZH:   "香港",
			ZHTW: "香港",
			EN:   "Hong Kong",
			JA:   "香港",
			KO:   "홍콩",
			MY:   "ဟောင်ကောင်",
			TH:   "ฮ่องกง",
			TR:   "Hong Kong",
			SV:   "Hongkong",
		},
	},
	{
		Code: "TW",
		LocaleNames: dto.LocaleResponse{
			ZH:   "台湾",
			ZHTW: "台灣",
			EN:   "Taiwan",
			JA:   "台湾",
			KO:   "대만",
			MY:   "ထိုင်ဝမ်",
			TH:   "ไต้หวัน",
			TR:   "Tayvan",
			SV:   "Taiwan",
		},
	},
	{
		Code: "MO",
		LocaleNames: dto.LocaleResponse{
			ZH:   "澳门",
			ZHTW: "澳門",
			EN:   "Macau",
			JA:   "マカオ",
			KO:   "마카오",
			MY:   "မကာအို",
			TH:   "มาเก๊า",
			TR:   "Makao",
			SV:   "Macao",
		},
	},
	{
		Code: "AF",
		LocaleNames: dto.LocaleResponse{
			ZH:   "阿富汗",
			ZHTW: "阿富汗",
			EN:   "Afghanistan",
			JA:   "アフガニスタン",
			KO:   "아프가니스탄",
			MY:   "အာဖဂန်နစ္စတန်",
			TH:   "อัฟกานิสถาน",
			TR:   "Afganistan",
			SV:   "Afghanistan",
		},
	},
	{
		Code: "AL",
		LocaleNames: dto.LocaleResponse{
			ZH:   "阿尔巴尼亚",
			ZHTW: "阿爾巴尼亞",
			EN:   "Albania",
			JA:   "アルバニア",
			KO:   "알바니아",
			MY:   "အယ်လ်ဘေးနီးယား",
			TH:   "แอลเบเนีย",
			TR:   "Arnavutluk",
			SV:   "Albanien",
		},
	},
	{
		Code: "DZ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "阿尔及利亚",
			ZHTW: "阿爾及利亞",
			EN:   "Algeria",
			JA:   "アルジェリア",
			KO:   "알제리",
			MY:   "အယ်လ်ဂျီးရီးယား",
			TH:   "แอลจีเรีย",
			TR:   "Cezayir",
			SV:   "Algeriet",
		},
	},
	{
		Code: "AD",
		LocaleNames: dto.LocaleResponse{
			ZH:   "安道尔",
			ZHTW: "安道爾",
			EN:   "Andorra",
			JA:   "アンドラ",
			KO:   "안도라",
			MY:   "အန်ဒိုရာ",
			TH:   "อันดอร์รา",
			TR:   "Andorra",
			SV:   "Andorra",
		},
	},
	{
		Code: "AO",
		LocaleNames: dto.LocaleResponse{
			ZH:   "安哥拉",
			ZHTW: "安哥拉",
			EN:   "Angola",
			JA:   "アンゴラ",
			KO:   "앙골라",
			MY:   "အန်ဂိုလာ",
			TH:   "แองโกลา",
			TR:   "Angola",
			SV:   "Angola",
		},
	},
	{
		Code: "AG",
		LocaleNames: dto.LocaleResponse{
			ZH:   "安提瓜和巴布达",
			ZHTW: "安地卡及巴布達",
			EN:   "Antigua and Barbuda",
			JA:   "アンティグア・バーブーダ",
			KO:   "앤티가 바부다",
			MY:   "အန်တီဂွါနှင့်ဘာဘူဒါ",
			TH:   "แอนติกาและบาร์บูดา",
			TR:   "Antigua ve Barbuda",
			SV:   "Antigua och Barbuda",
		},
	},
	{
		Code: "AM",
		LocaleNames: dto.LocaleResponse{
			ZH:   "亚美尼亚",
			ZHTW: "亞美尼亞",
			EN:   "Armenia",
			JA:   "アルメニア",
			KO:   "아르메니아",
			MY:   "အာမေးနီးယား",
			TH:   "อาร์เมเนีย",
			TR:   "Ermenistan",
			SV:   "Armenien",
		},
	},
	{
		Code: "AT",
		LocaleNames: dto.LocaleResponse{
			ZH:   "奥地利",
			ZHTW: "奧地利",
			EN:   "Austria",
			JA:   "オーストリア",
			KO:   "오스트리아",
			MY:   "ဩစတြီးယား",
			TH:   "ออสเตรีย",
			TR:   "Avusturya",
			SV:   "Österrike",
		},
	},
	{
		Code: "AZ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "阿塞拜疆",
			ZHTW: "亞塞拜然",
			EN:   "Azerbaijan",
			JA:   "アゼルバイジャン",
			KO:   "아제르바이잔",
			MY:   "အဇာဘိုင်ဂျန်",
			TH:   "อาเซอร์ไบจาน",
			TR:   "Azerbaycan",
			SV:   "Azerbajdzjan",
		},
	},
	{
		Code: "BS",
		LocaleNames: dto.LocaleResponse{
			ZH:   "巴哈马",
			ZHTW: "巴哈馬",
			EN:   "Bahamas",
			JA:   "バハマ",
			KO:   "바하마",
			MY:   "ဘဟားမား",
			TH:   "บาฮามาส",
			TR:   "Bahamalar",
			SV:   "Bahamas",
		},
	},
	{
		Code: "BH",
		LocaleNames: dto.LocaleResponse{
			ZH:   "巴林",
			ZHTW: "巴林",
			EN:   "Bahrain",
			JA:   "バーレーン",
			KO:   "바레인",
			MY:   "ဘာရိန်း",
			TH:   "บาห์เรน",
			TR:   "Bahreyn",
			SV:   "Bahrain",
		},
	},
	{
		Code: "BD",
		LocaleNames: dto.LocaleResponse{
			ZH:   "孟加拉国",
			ZHTW: "孟加拉",
			EN:   "Bangladesh",
			JA:   "バングラデシュ",
			KO:   "방글라데시",
			MY:   "ဘင်္ဂလားဒေ့ရှ်",
			TH:   "บังกลาเทศ",
			TR:   "Bangladeş",
			SV:   "Bangladesh",
		},
	},
	{
		Code: "BB",
		LocaleNames: dto.LocaleResponse{
			ZH:   "巴巴多斯",
			ZHTW: "巴貝多",
			EN:   "Barbados",
			JA:   "バルバドス",
			KO:   "바베이도스",
			MY:   "ဘာဘေးဒိုးစ်",
			TH:   "บาร์เบโดส",
			TR:   "Barbados",
			SV:   "Barbados",
		},
	},
	{
		Code: "BY",
		LocaleNames: dto.LocaleResponse{
			ZH:   "白俄罗斯",
			ZHTW: "白俄羅斯",
			EN:   "Belarus",
			JA:   "ベラルーシ",
			KO:   "벨라루스",
			MY:   "ဘီလာရုစ်",
			TH:   "เบลารุส",
			TR:   "Belarus",
			SV:   "Vitryssland",
		},
	},
	{
		Code: "BE",
		LocaleNames: dto.LocaleResponse{
			ZH:   "比利时",
			ZHTW: "比利時",
			EN:   "Belgium",
			JA:   "ベルギー",
			KO:   "벨기에",
			MY:   "ဘယ်လ်ဂျီယမ်",
			TH:   "เบลเยียม",
			TR:   "Belçika",
			SV:   "Belgien",
		},
	},
	{
		Code: "BZ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "伯利兹",
			ZHTW: "貝里斯",
			EN:   "Belize",
			JA:   "ベリーズ",
			KO:   "벨리즈",
			MY:   "ဘလိဇ်",
			TH:   "เบลize",
			TR:   "Belize",
			SV:   "Belize",
		},
	},
	{
		Code: "BJ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "贝宁",
			ZHTW: "貝南",
			EN:   "Benin",
			JA:   "ベナン",
			KO:   "베냉",
			MY:   "ဘီနင်",
			TH:   "เบนิน",
			TR:   "Benin",
			SV:   "Benin",
		},
	},
	{
		Code: "BT",
		LocaleNames: dto.LocaleResponse{
			ZH:   "不丹",
			ZHTW: "不丹",
			EN:   "Bhutan",
			JA:   "ブータン",
			KO:   "부탄",
			MY:   "ဘူတန်",
			TH:   "ภูฏาน",
			TR:   "Bhutan",
			SV:   "Bhutan",
		},
	},
	{
		Code: "BO",
		LocaleNames: dto.LocaleResponse{
			ZH:   "玻利维亚",
			ZHTW: "玻利維亞",
			EN:   "Bolivia",
			JA:   "ボリビア",
			KO:   "볼리비아",
			MY:   "ဘိုလီးဗီးယား",
			TH:   "โบลิเวีย",
			TR:   "Bolivya",
			SV:   "Bolivia",
		},
	},
	{
		Code: "BA",
		LocaleNames: dto.LocaleResponse{
			ZH:   "波黑",
			ZHTW: "波士尼亞與赫塞哥維納",
			EN:   "Bosnia and Herzegovina",
			JA:   "ボスニア・ヘルツェゴビナ",
			KO:   "보스니아 헤르체고비나",
			MY:   "ဘော့စနီးယားနှင့်ဟာဇီဂိုဗီးနား",
			TH:   "บอสเนียและเฮอร์เซโกวีนา",
			TR:   "Bosna ve Hersek",
			SV:   "Bosnien och Hercegovina",
		},
	},
	{
		Code: "BW",
		LocaleNames: dto.LocaleResponse{
			ZH:   "博茨瓦纳",
			ZHTW: "波札那",
			EN:   "Botswana",
			JA:   "ボツワナ",
			KO:   "보츠와나",
			MY:   "ဘော့ဆွာနာ",
			TH:   "บอตสวานา",
			TR:   "Botsvana",
			SV:   "Botswana",
		},
	},
	{
		Code: "BN",
		LocaleNames: dto.LocaleResponse{
			ZH:   "文莱",
			ZHTW: "汶萊",
			EN:   "Brunei",
			JA:   "ブルネイ",
			KO:   "브루나이",
			MY:   "ဘရူနိုင်း",
			TH:   "บรูไน",
			TR:   "Brunei",
			SV:   "Brunei",
		},
	},
	{
		Code: "BG",
		LocaleNames: dto.LocaleResponse{
			ZH:   "保加利亚",
			ZHTW: "保加利亞",
			EN:   "Bulgaria",
			JA:   "ブルガリア",
			KO:   "불가리아",
			MY:   "ဘူလ်ဂေးရီးယား",
			TH:   "บัลแกเรีย",
			TR:   "Bulgaristan",
			SV:   "Bulgarien",
		},
	},
	{
		Code: "BF",
		LocaleNames: dto.LocaleResponse{
			ZH:   "布基纳法索",
			ZHTW: "布吉納法索",
			EN:   "Burkina Faso",
			JA:   "ブルキナファソ",
			KO:   "부르키나파소",
			MY:   "ဘာကီနာဖာဆို",
			TH:   "บูร์กินาฟาโซ",
			TR:   "Burkina Faso",
			SV:   "Burkina Faso",
		},
	},
	{
		Code: "BI",
		LocaleNames: dto.LocaleResponse{
			ZH:   "布隆迪",
			ZHTW: "蒲隆地",
			EN:   "Burundi",
			JA:   "ブルンジ",
			KO:   "부룬디",
			MY:   "ဘူရွန်ဒီ",
			TH:   "บุรุนดี",
			TR:   "Burundi",
			SV:   "Burundi",
		},
	},
	{
		Code: "CV",
		LocaleNames: dto.LocaleResponse{
			ZH:   "佛得角",
			ZHTW: "維德角",
			EN:   "Cape Verde",
			JA:   "カーボベルデ",
			KO:   "카보베르데",
			MY:   "ကိတ်ဗာဒီ",
			TH:   "เคปเวิร์ด",
			TR:   "Yeşil Burun",
			SV:   "Kap Verde",
		},
	},
	{
		Code: "KH",
		LocaleNames: dto.LocaleResponse{
			ZH:   "柬埔寨",
			ZHTW: "柬埔寨",
			EN:   "Cambodia",
			JA:   "カンボジア",
			KO:   "캄보디아",
			MY:   "ကမ္ဘောဒီးယား",
			TH:   "กัมพูชา",
			TR:   "Kamboçya",
			SV:   "Kambodja",
		},
	},
	{
		Code: "CM",
		LocaleNames: dto.LocaleResponse{
			ZH:   "喀麦隆",
			ZHTW: "喀麥隆",
			EN:   "Cameroon",
			JA:   "カメルーン",
			KO:   "카메룬",
			MY:   "ကင်မရွန်း",
			TH:   "แคเมอรูน",
			TR:   "Kamerun",
			SV:   "Kamerun",
		},
	},
	{
		Code: "CF",
		LocaleNames: dto.LocaleResponse{
			ZH:   "中非",
			ZHTW: "中非",
			EN:   "Central African Republic",
			JA:   "中央アフリカ",
			KO:   "중앙아프리카 공화국",
			MY:   "ဗဟိုအာဖရိကသမ္မတနိုင်ငံ",
			TH:   "สาธารณรัฐแอฟริกากลาง",
			TR:   "Orta Afrika Cumhuriyeti",
			SV:   "Centralafrikanska republiken",
		},
	},
	{
		Code: "TD",
		LocaleNames: dto.LocaleResponse{
			ZH:   "乍得",
			ZHTW: "查德",
			EN:   "Chad",
			JA:   "チャド",
			KO:   "차드",
			MY:   "ချဒ်",
			TH:   "ชาด",
			TR:   "Çad",
			SV:   "Tchad",
		},
	},
	{
		Code: "CL",
		LocaleNames: dto.LocaleResponse{
			ZH:   "智利",
			ZHTW: "智利",
			EN:   "Chile",
			JA:   "チリ",
			KO:   "칠레",
			MY:   "ချီလီ",
			TH:   "ชิลี",
			TR:   "Şili",
			SV:   "Chile",
		},
	},
	{
		Code: "CO",
		LocaleNames: dto.LocaleResponse{
			ZH:   "哥伦比亚",
			ZHTW: "哥倫比亞",
			EN:   "Colombia",
			JA:   "コロンビア",
			KO:   "콜롬비아",
			MY:   "ကိုလံဘီယာ",
			TH:   "โคลอมเบีย",
			TR:   "Kolombiya",
			SV:   "Colombia",
		},
	},
	{
		Code: "KM",
		LocaleNames: dto.LocaleResponse{
			ZH:   "科摩罗",
			ZHTW: "葛摩",
			EN:   "Comoros",
			JA:   "コモロ",
			KO:   "코모로",
			MY:   "ကိုမိုရို",
			TH:   "คอโมโรส",
			TR:   "Komorlar",
			SV:   "Komorerna",
		},
	},
	{
		Code: "CG",
		LocaleNames: dto.LocaleResponse{
			ZH:   "刚果",
			ZHTW: "剛果",
			EN:   "Congo",
			JA:   "コンゴ",
			KO:   "콩고",
			MY:   "ကွန်ဂို",
			TH:   "คองโก",
			TR:   "Kongo",
			SV:   "Kongo",
		},
	},
	{
		Code: "CD",
		LocaleNames: dto.LocaleResponse{
			ZH:   "刚果民主共和国",
			ZHTW: "剛果民主共和國",
			EN:   "Democratic Republic of the Congo",
			JA:   "コンゴ民主共和国",
			KO:   "콩고 민주 공화국",
			MY:   "ကွန်ဂိုဒီမိုကရက်တစ်သမ္မတနိုင်ငံ",
			TH:   "สาธารณรัฐประชาธิปไตยคองโก",
			TR:   "Kongo Demokratik Cumhuriyeti",
			SV:   "Kongo-Kinshasa",
		},
	},
	{
		Code: "CR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "哥斯达黎加",
			ZHTW: "哥斯大黎加",
			EN:   "Costa Rica",
			JA:   "コスタリカ",
			KO:   "코스타리카",
			MY:   "ကိုစတာရီကာ",
			TH:   "คอสตาริกา",
			TR:   "Kosta Rika",
			SV:   "Costa Rica",
		},
	},
	{
		Code: "CI",
		LocaleNames: dto.LocaleResponse{
			ZH:   "科特迪瓦",
			ZHTW: "象牙海岸",
			EN:   "Côte d'Ivoire",
			JA:   "コートジボワール",
			KO:   "코트디부아르",
			MY:   "ကိုတီဒီဗွာ",
			TH:   "โกตดิวัวร์",
			TR:   "Fildişi Sahili",
			SV:   "Elfenbenskusten",
		},
	},
	{
		Code: "HR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "克罗地亚",
			ZHTW: "克羅埃西亞",
			EN:   "Croatia",
			JA:   "クロアチア",
			KO:   "크로아티아",
			MY:   "ခရိုအေးရှား",
			TH:   "โครเอเชีย",
			TR:   "Hırvatistan",
			SV:   "Kroatien",
		},
	},
	{
		Code: "CU",
		LocaleNames: dto.LocaleResponse{
			ZH:   "古巴",
			ZHTW: "古巴",
			EN:   "Cuba",
			JA:   "キューバ",
			KO:   "쿠바",
			MY:   "ကျူးဘား",
			TH:   "คิวบา",
			TR:   "Küba",
			SV:   "Kuba",
		},
	},
	{
		Code: "CY",
		LocaleNames: dto.LocaleResponse{
			ZH:   "塞浦路斯",
			ZHTW: "賽普勒斯",
			EN:   "Cyprus",
			JA:   "キプロス",
			KO:   "키프로스",
			MY:   "ဆိုက်ပရပ်စ်",
			TH:   "ไซปรัส",
			TR:   "Kıbrıs",
			SV:   "Cypern",
		},
	},
	{
		Code: "CZ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "捷克",
			ZHTW: "捷克",
			EN:   "Czech Republic",
			JA:   "チェコ",
			KO:   "체코",
			MY:   "ချက်ခ်",
			TH:   "เช็กเกีย",
			TR:   "Çek Cumhuriyeti",
			SV:   "Tjeckien",
		},
	},
	{
		Code: "DK",
		LocaleNames: dto.LocaleResponse{
			ZH:   "丹麦",
			ZHTW: "丹麥",
			EN:   "Denmark",
			JA:   "デンマーク",
			KO:   "덴마크",
			MY:   "ဒိန်းမတ်",
			TH:   "เดนมาร์ก",
			TR:   "Danimarka",
			SV:   "Danmark",
		},
	},
	{
		Code: "DJ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "吉布提",
			ZHTW: "吉布地",
			EN:   "Djibouti",
			JA:   "ジブチ",
			KO:   "지부티",
			MY:   "ဂျီဘူတီ",
			TH:   "จิบูตี",
			TR:   "Cibuti",
			SV:   "Djibouti",
		},
	},
	{
		Code: "DM",
		LocaleNames: dto.LocaleResponse{
			ZH:   "多米尼克",
			ZHTW: "多米尼克",
			EN:   "Dominica",
			JA:   "ドミニカ",
			KO:   "도미니카",
			MY:   "ဒိုမီနီကာ",
			TH:   "โดมินิกา",
			TR:   "Dominika",
			SV:   "Dominica",
		},
	},
	{
		Code: "DO",
		LocaleNames: dto.LocaleResponse{
			ZH:   "多米尼加",
			ZHTW: "多明尼加",
			EN:   "Dominican Republic",
			JA:   "ドミニカ共和国",
			KO:   "도미니카 공화국",
			MY:   "ဒိုမီနီကန်သမ္မတနိုင်ငံ",
			TH:   "สาธารณรัฐโดมินิกัน",
			TR:   "Dominik Cumhuriyeti",
			SV:   "Dominikanska republiken",
		},
	},
	{
		Code: "EC",
		LocaleNames: dto.LocaleResponse{
			ZH:   "厄瓜多尔",
			ZHTW: "厄瓜多",
			EN:   "Ecuador",
			JA:   "エクアドル",
			KO:   "에콰도르",
			MY:   "အီကွေဒေါ",
			TH:   "เอกวาดอร์",
			TR:   "Ekvador",
			SV:   "Ecuador",
		},
	},
	{
		Code: "EE",
		LocaleNames: dto.LocaleResponse{
			ZH:   "爱沙尼亚",
			ZHTW: "愛沙尼亞",
			EN:   "Estonia",
			JA:   "エストニア",
			KO:   "에스토니아",
			MY:   "အက်စ်တိုးနီးယား",
			TH:   "เอสโตเนีย",
			TR:   "Estonya",
			SV:   "Estland",
		},
	},
	{
		Code: "SZ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "斯威士兰",
			ZHTW: "史瓦濟蘭",
			EN:   "Eswatini",
			JA:   "エスワティニ",
			KO:   "에스와티니",
			MY:   "အက်စ်ဝါတီနီ",
			TH:   "เอสวาตินี",
			TR:   "Esvati",
			SV:   "Eswatini",
		},
	},
	{
		Code: "ET",
		LocaleNames: dto.LocaleResponse{
			ZH:   "埃塞俄比亚",
			ZHTW: "衣索比亞",
			EN:   "Ethiopia",
			JA:   "エチオピア",
			KO:   "에티오피아",
			MY:   "အီသီယိုးပီးယား",
			TH:   "เอธิโอเปีย",
			TR:   "Etiyopya",
			SV:   "Etiopien",
		},
	},
	{
		Code: "FJ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "斐济",
			ZHTW: "斐濟",
			EN:   "Fiji",
			JA:   "フィジー",
			KO:   "피지",
			MY:   "ဖီဂျီ",
			TH:   "ฟิจิ",
			TR:   "Fiji",
			SV:   "Fiji",
		},
	},
	{
		Code: "FI",
		LocaleNames: dto.LocaleResponse{
			ZH:   "芬兰",
			ZHTW: "芬蘭",
			EN:   "Finland",
			JA:   "フィンランド",
			KO:   "핀란드",
			MY:   "ဖင်လန်",
			TH:   "ฟินแลนด์",
			TR:   "Finlandiya",
			SV:   "Finland",
		},
	},
	{
		Code: "GA",
		LocaleNames: dto.LocaleResponse{
			ZH:   "加蓬",
			ZHTW: "加彭",
			EN:   "Gabon",
			JA:   "ガボン",
			KO:   "가봉",
			MY:   "ဂါဘွန်",
			TH:   "กาบอง",
			TR:   "Gabon",
			SV:   "Gabon",
		},
	},
	{
		Code: "GM",
		LocaleNames: dto.LocaleResponse{
			ZH:   "冈比亚",
			ZHTW: "甘比亞",
			EN:   "Gambia",
			JA:   "ガンビア",
			KO:   "감비아",
			MY:   "ဂမ်ဘီယာ",
			TH:   "แกมเบีย",
			TR:   "Gambiya",
			SV:   "Gambia",
		},
	},
	{
		Code: "GE",
		LocaleNames: dto.LocaleResponse{
			ZH:   "格鲁吉亚",
			ZHTW: "喬治亞",
			EN:   "Georgia",
			JA:   "ジョージア",
			KO:   "조지아",
			MY:   "ဂျော်ဂျီယာ",
			TH:   "จอร์เจีย",
			TR:   "Gürcistan",
			SV:   "Georgien",
		},
	},
	{
		Code: "GH",
		LocaleNames: dto.LocaleResponse{
			ZH:   "加纳",
			ZHTW: "迦納",
			EN:   "Ghana",
			JA:   "ガーナ",
			KO:   "가나",
			MY:   "ဂါနာ",
			TH:   "กานา",
			TR:   "Gana",
			SV:   "Ghana",
		},
	},
	{
		Code: "GR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "希腊",
			ZHTW: "希臘",
			EN:   "Greece",
			JA:   "ギリシャ",
			KO:   "그리스",
			MY:   "ဂရိ",
			TH:   "กรีซ",
			TR:   "Yunanistan",
			SV:   "Grekland",
		},
	},
	{
		Code: "GD",
		LocaleNames: dto.LocaleResponse{
			ZH:   "格林纳达",
			ZHTW: "格瑞那達",
			EN:   "Grenada",
			JA:   "グレナダ",
			KO:   "그레나다",
			MY:   "ဂရီနာဒါ",
			TH:   "เกรเนดา",
			TR:   "Grenada",
			SV:   "Grenada",
		},
	},
	{
		Code: "GT",
		LocaleNames: dto.LocaleResponse{
			ZH:   "危地马拉",
			ZHTW: "瓜地馬拉",
			EN:   "Guatemala",
			JA:   "グアテマラ",
			KO:   "과테말라",
			MY:   "ဂွာတီမာလာ",
			TH:   "กัวเตมาลา",
			TR:   "Guatemala",
			SV:   "Guatemala",
		},
	},
	{
		Code: "GN",
		LocaleNames: dto.LocaleResponse{
			ZH:   "几内亚",
			ZHTW: "幾內亞",
			EN:   "Guinea",
			JA:   "ギニア",
			KO:   "기니",
			MY:   "ဂီနီ",
			TH:   "กินี",
			TR:   "Gine",
			SV:   "Guinea",
		},
	},
	{
		Code: "GW",
		LocaleNames: dto.LocaleResponse{
			ZH:   "几内亚比绍",
			ZHTW: "幾內亞比索",
			EN:   "Guinea-Bissau",
			JA:   "ギニアビサウ",
			KO:   "기니비사우",
			MY:   "ဂီနီ-ဘီစော",
			TH:   "กินี-บิสเซา",
			TR:   "Gine-Bissau",
			SV:   "Guinea-Bissau",
		},
	},
	{
		Code: "GY",
		LocaleNames: dto.LocaleResponse{
			ZH:   "圭亚那",
			ZHTW: "蓋亞那",
			EN:   "Guyana",
			JA:   "ガイアナ",
			KO:   "가이아나",
			MY:   "ဂိုင်ယာနာ",
			TH:   "กายอานา",
			TR:   "Guyana",
			SV:   "Guyana",
		},
	},
	{
		Code: "HT",
		LocaleNames: dto.LocaleResponse{
			ZH:   "海地",
			ZHTW: "海地",
			EN:   "Haiti",
			JA:   "ハイチ",
			KO:   "아이티",
			MY:   "ဟေတီ",
			TH:   "เฮติ",
			TR:   "Haiti",
			SV:   "Haiti",
		},
	},
	{
		Code: "HN",
		LocaleNames: dto.LocaleResponse{
			ZH:   "洪都拉斯",
			ZHTW: "宏都拉斯",
			EN:   "Honduras",
			JA:   "ホンジュラス",
			KO:   "온두라스",
			MY:   "ဟွန်ဒူးရပ်စ်",
			TH:   "ฮอนดูรัส",
			TR:   "Honduras",
			SV:   "Honduras",
		},
	},
	{
		Code: "HU",
		LocaleNames: dto.LocaleResponse{
			ZH:   "匈牙利",
			ZHTW: "匈牙利",
			EN:   "Hungary",
			JA:   "ハンガリー",
			KO:   "헝가리",
			MY:   "ဟန်ဂေရီ",
			TH:   "ฮังการี",
			TR:   "Macaristan",
			SV:   "Ungern",
		},
	},
	{
		Code: "IS",
		LocaleNames: dto.LocaleResponse{
			ZH:   "冰岛",
			ZHTW: "冰島",
			EN:   "Iceland",
			JA:   "アイスランド",
			KO:   "아이슬란드",
			MY:   "အိုက်စလန်",
			TH:   "ไอซ์แลนด์",
			TR:   "İzlanda",
			SV:   "Island",
		},
	},
	{
		Code: "IR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "伊朗",
			ZHTW: "伊朗",
			EN:   "Iran",
			JA:   "イラン",
			KO:   "이란",
			MY:   "အီရန်",
			TH:   "อิหร่าน",
			TR:   "İran",
			SV:   "Iran",
		},
	},
	{
		Code: "IQ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "伊拉克",
			ZHTW: "伊拉克",
			EN:   "Iraq",
			JA:   "イラク",
			KO:   "이라크",
			MY:   "အီရတ်",
			TH:   "อิรัก",
			TR:   "Irak",
			SV:   "Irak",
		},
	},
	{
		Code: "IE",
		LocaleNames: dto.LocaleResponse{
			ZH:   "爱尔兰",
			ZHTW: "愛爾蘭",
			EN:   "Ireland",
			JA:   "アイルランド",
			KO:   "아일랜드",
			MY:   "အိုင်ယာလန်",
			TH:   "ไอร์แลนด์",
			TR:   "İrlanda",
			SV:   "Irland",
		},
	},
	{
		Code: "IL",
		LocaleNames: dto.LocaleResponse{
			ZH:   "以色列",
			ZHTW: "以色列",
			EN:   "Israel",
			JA:   "イスラエル",
			KO:   "이스라엘",
			MY:   "အစ္စရေး",
			TH:   "อิสราเอล",
			TR:   "İsrail",
			SV:   "Israel",
		},
	},
	{
		Code: "JM",
		LocaleNames: dto.LocaleResponse{
			ZH:   "牙买加",
			ZHTW: "牙買加",
			EN:   "Jamaica",
			JA:   "ジャマイカ",
			KO:   "자메이카",
			MY:   "ဂျမေကာ",
			TH:   "จาเมกา",
			TR:   "Jamaika",
			SV:   "Jamaica",
		},
	},
	{
		Code: "JO",
		LocaleNames: dto.LocaleResponse{
			ZH:   "约旦",
			ZHTW: "約旦",
			EN:   "Jordan",
			JA:   "ヨルダン",
			KO:   "요르단",
			MY:   "ဂျော်ဒန်",
			TH:   "จอร์แดน",
			TR:   "Ürdün",
			SV:   "Jordanien",
		},
	},
	{
		Code: "KZ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "哈萨克斯坦",
			ZHTW: "哈薩克",
			EN:   "Kazakhstan",
			JA:   "カザフスタン",
			KO:   "카자흐스탄",
			MY:   "ခါဇက်စတန်",
			TH:   "คาซัคสถาน",
			TR:   "Kazakistan",
			SV:   "Kazakstan",
		},
	},
	{
		Code: "KI",
		LocaleNames: dto.LocaleResponse{
			ZH:   "基里巴斯",
			ZHTW: "吉里巴斯",
			EN:   "Kiribati",
			JA:   "キリバス",
			KO:   "키리바시",
			MY:   "ကီရီဘာတီ",
			TH:   "คิริบาส",
			TR:   "Kiribati",
			SV:   "Kiribati",
		},
	},
	{
		Code: "KW",
		LocaleNames: dto.LocaleResponse{
			ZH:   "科威特",
			ZHTW: "科威特",
			EN:   "Kuwait",
			JA:   "クウェート",
			KO:   "쿠웨이트",
			MY:   "ကူဝိတ်",
			TH:   "คูเวต",
			TR:   "Kuveyt",
			SV:   "Kuwait",
		},
	},
	{
		Code: "KG",
		LocaleNames: dto.LocaleResponse{
			ZH:   "吉尔吉斯斯坦",
			ZHTW: "吉爾吉斯",
			EN:   "Kyrgyzstan",
			JA:   "キルギス",
			KO:   "키르기스스탄",
			MY:   "ချာဂီဆတန်",
			TH:   "คีร์กีซสถาน",
			TR:   "Kırgızistan",
			SV:   "Kirgizistan",
		},
	},
	{
		Code: "LA",
		LocaleNames: dto.LocaleResponse{
			ZH:   "老挝",
			ZHTW: "寮國",
			EN:   "Laos",
			JA:   "ラオス",
			KO:   "라오스",
			MY:   "လာအို",
			TH:   "ลาว",
			TR:   "Laos",
			SV:   "Laos",
		},
	},
	{
		Code: "LV",
		LocaleNames: dto.LocaleResponse{
			ZH:   "拉脱维亚",
			ZHTW: "拉脫維亞",
			EN:   "Latvia",
			JA:   "ラトビア",
			KO:   "라트비아",
			MY:   "လတ်ဗီယာ",
			TH:   "ลัตเวีย",
			TR:   "Letonya",
			SV:   "Lettland",
		},
	},
	{
		Code: "LB",
		LocaleNames: dto.LocaleResponse{
			ZH:   "黎巴嫩",
			ZHTW: "黎巴嫩",
			EN:   "Lebanon",
			JA:   "レバノン",
			KO:   "레바논",
			MY:   "လက်ဘနွန်",
			TH:   "เลบานอน",
			TR:   "Lübnan",
			SV:   "Libanon",
		},
	},
	{
		Code: "LS",
		LocaleNames: dto.LocaleResponse{
			ZH:   "莱索托",
			ZHTW: "賴索托",
			EN:   "Lesotho",
			JA:   "レソト",
			KO:   "레소토",
			MY:   "လီဆိုသို",
			TH:   "เลโซโท",
			TR:   "Lesotho",
			SV:   "Lesotho",
		},
	},
	{
		Code: "LR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "利比里亚",
			ZHTW: "賴比瑞亞",
			EN:   "Liberia",
			JA:   "リベリア",
			KO:   "라이베리아",
			MY:   "လိုင်ဘေးရီးယား",
			TH:   "ไลบีเรีย",
			TR:   "Liberya",
			SV:   "Liberia",
		},
	},
	{
		Code: "LY",
		LocaleNames: dto.LocaleResponse{
			ZH:   "利比亚",
			ZHTW: "利比亞",
			EN:   "Libya",
			JA:   "リビア",
			KO:   "리비아",
			MY:   "လစ်ဗျာ",
			TH:   "ลิเบีย",
			TR:   "Libya",
			SV:   "Libyen",
		},
	},
	{
		Code: "LI",
		LocaleNames: dto.LocaleResponse{
			ZH:   "列支敦士登",
			ZHTW: "列支敦斯登",
			EN:   "Liechtenstein",
			JA:   "リヒテンシュタイン",
			KO:   "리히텐슈타인",
			MY:   "လစ်ချ်တန်စတိန်း",
			TH:   "ลิกเตนสไตน์",
			TR:   "Liechtenstein",
			SV:   "Liechtenstein",
		},
	},
	{
		Code: "LT",
		LocaleNames: dto.LocaleResponse{
			ZH:   "立陶宛",
			ZHTW: "立陶宛",
			EN:   "Lithuania",
			JA:   "リトアニア",
			KO:   "리투아니아",
			MY:   "လစ်သူရေးနီးယား",
			TH:   "ลิทัวเนีย",
			TR:   "Litvanya",
			SV:   "Litauen",
		},
	},
	{
		Code: "LU",
		LocaleNames: dto.LocaleResponse{
			ZH:   "卢森堡",
			ZHTW: "盧森堡",
			EN:   "Luxembourg",
			JA:   "ルクセンブルク",
			KO:   "룩셈부르크",
			MY:   "လူဇင်ဘာ့ဂ်",
			TH:   "ลักเซมเบิร์ก",
			TR:   "Lüksemburg",
			SV:   "Luxemburg",
		},
	},
	{
		Code: "MG",
		LocaleNames: dto.LocaleResponse{
			ZH:   "马达加斯加",
			ZHTW: "馬達加斯加",
			EN:   "Madagascar",
			JA:   "マダガスカル",
			KO:   "마다가스카르",
			MY:   "မဒါဂတ်စကာ",
			TH:   "มาดากัสการ์",
			TR:   "Madagaskar",
			SV:   "Madagaskar",
		},
	},
	{
		Code: "MW",
		LocaleNames: dto.LocaleResponse{
			ZH:   "马拉维",
			ZHTW: "馬拉威",
			EN:   "Malawi",
			JA:   "マラウイ",
			KO:   "말라위",
			MY:   "မလာဝီ",
			TH:   "มาลาวี",
			TR:   "Malavi",
			SV:   "Malawi",
		},
	},
	{
		Code: "MV",
		LocaleNames: dto.LocaleResponse{
			ZH:   "马尔代夫",
			ZHTW: "馬爾地夫",
			EN:   "Maldives",
			JA:   "モルディブ",
			KO:   "몰디브",
			MY:   "မော်လဒိုက်",
			TH:   "มัลดีฟส์",
			TR:   "Maldivler",
			SV:   "Maldiverna",
		},
	},
	{
		Code: "ML",
		LocaleNames: dto.LocaleResponse{
			ZH:   "马里",
			ZHTW: "馬利",
			EN:   "Mali",
			JA:   "マリ",
			KO:   "말리",
			MY:   "မာလီ",
			TH:   "มาลี",
			TR:   "Mali",
			SV:   "Mali",
		},
	},
	{
		Code: "MT",
		LocaleNames: dto.LocaleResponse{
			ZH:   "马耳他",
			ZHTW: "馬爾他",
			EN:   "Malta",
			JA:   "マルタ",
			KO:   "몰타",
			MY:   "မော်လတာ",
			TH:   "มอลตา",
			TR:   "Malta",
			SV:   "Malta",
		},
	},
	{
		Code: "MH",
		LocaleNames: dto.LocaleResponse{
			ZH:   "马绍尔群岛",
			ZHTW: "馬紹爾群島",
			EN:   "Marshall Islands",
			JA:   "マーシャル諸島",
			KO:   "마셜 제도",
			MY:   "မာရှယ်ကျွန်းစု",
			TH:   "หมู่เกาะมาร์แชลล์",
			TR:   "Marshall Adaları",
			SV:   "Marshallöarna",
		},
	},
	{
		Code: "MR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "毛里塔尼亚",
			ZHTW: "茅利塔尼亞",
			EN:   "Mauritania",
			JA:   "モーリタニア",
			KO:   "모리타니아",
			MY:   "မော်ရီတေးနီးယား",
			TH:   "มอริเตเนีย",
			TR:   "Moritanya",
			SV:   "Mauretanien",
		},
	},
	{
		Code: "MU",
		LocaleNames: dto.LocaleResponse{
			ZH:   "毛里求斯",
			ZHTW: "模里西斯",
			EN:   "Mauritius",
			JA:   "モーリシャス",
			KO:   "모리셔스",
			MY:   "မော်ရီရှပ်စ်",
			TH:   "มอริเชียส",
			TR:   "Mauritius",
			SV:   "Mauritius",
		},
	},
	{
		Code: "FM",
		LocaleNames: dto.LocaleResponse{
			ZH:   "密克罗尼西亚",
			ZHTW: "密克羅尼西亞",
			EN:   "Micronesia",
			JA:   "ミクロネシア",
			KO:   "미크로네시아",
			MY:   "မိုက်ခရိုနီးရှား",
			TH:   "ไมโครนีเซีย",
			TR:   "Mikronezya",
			SV:   "Mikronesien",
		},
	},
	{
		Code: "MD",
		LocaleNames: dto.LocaleResponse{
			ZH:   "摩尔多瓦",
			ZHTW: "摩爾多瓦",
			EN:   "Moldova",
			JA:   "モルドバ",
			KO:   "몰도바",
			MY:   "မော်လ်ဒိုဗာ",
			TH:   "มอลโดวา",
			TR:   "Moldova",
			SV:   "Moldavien",
		},
	},
	{
		Code: "MC",
		LocaleNames: dto.LocaleResponse{
			ZH:   "摩纳哥",
			ZHTW: "摩納哥",
			EN:   "Monaco",
			JA:   "モナコ",
			KO:   "모나코",
			MY:   "မိုနာကို",
			TH:   "โมนาโก",
			TR:   "Monako",
			SV:   "Monaco",
		},
	},
	{
		Code: "MN",
		LocaleNames: dto.LocaleResponse{
			ZH:   "蒙古",
			ZHTW: "蒙古",
			EN:   "Mongolia",
			JA:   "モンゴル",
			KO:   "몽골",
			MY:   "မွန်ဂိုလီးယား",
			TH:   "มองโกเลีย",
			TR:   "Moğolistan",
			SV:   "Mongoliet",
		},
	},
	{
		Code: "ME",
		LocaleNames: dto.LocaleResponse{
			ZH:   "黑山",
			ZHTW: "蒙特內哥羅",
			EN:   "Montenegro",
			JA:   "モンテネグロ",
			KO:   "몬테네그로",
			MY:   "မွန်တီနီဂရို",
			TH:   "มอนเตเนโกร",
			TR:   "Karadağ",
			SV:   "Montenegro",
		},
	},
	{
		Code: "MA",
		LocaleNames: dto.LocaleResponse{
			ZH:   "摩洛哥",
			ZHTW: "摩洛哥",
			EN:   "Morocco",
			JA:   "モロッコ",
			KO:   "모로코",
			MY:   "မော်ရိုကို",
			TH:   "โมร็อกโก",
			TR:   "Fas",
			SV:   "Marocko",
		},
	},
	{
		Code: "MZ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "莫桑比克",
			ZHTW: "莫三比克",
			EN:   "Mozambique",
			JA:   "モザンビーク",
			KO:   "모잠비크",
			MY:   "မိုဇမ်ဘီက်",
			TH:   "โมซัมบิก",
			TR:   "Mozambik",
			SV:   "Moçambique",
		},
	},
	{
		Code: "MM",
		LocaleNames: dto.LocaleResponse{
			ZH:   "缅甸",
			ZHTW: "緬甸",
			EN:   "Myanmar",
			JA:   "ミャンマー",
			KO:   "미얀마",
			MY:   "မြန်မာ",
			TH:   "พม่า",
			TR:   "Myanmar",
			SV:   "Myanmar",
		},
	},
	{
		Code: "NA",
		LocaleNames: dto.LocaleResponse{
			ZH:   "纳米比亚",
			ZHTW: "納米比亞",
			EN:   "Namibia",
			JA:   "ナミビア",
			KO:   "나미비아",
			MY:   "နမီးဘီးယား",
			TH:   "นามิเบีย",
			TR:   "Namibya",
			SV:   "Namibia",
		},
	},
	{
		Code: "NR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "瑙鲁",
			ZHTW: "諾魯",
			EN:   "Nauru",
			JA:   "ナウル",
			KO:   "나우루",
			MY:   "နာအူရူ",
			TH:   "นาอูรู",
			TR:   "Nauru",
			SV:   "Nauru",
		},
	},
	{
		Code: "NP",
		LocaleNames: dto.LocaleResponse{
			ZH:   "尼泊尔",
			ZHTW: "尼泊爾",
			EN:   "Nepal",
			JA:   "ネパール",
			KO:   "네팔",
			MY:   "နီပေါ",
			TH:   "เนปาล",
			TR:   "Nepal",
			SV:   "Nepal",
		},
	},
	{
		Code: "NL",
		LocaleNames: dto.LocaleResponse{
			ZH:   "荷兰",
			ZHTW: "荷蘭",
			EN:   "Netherlands",
			JA:   "オランダ",
			KO:   "네덜란드",
			MY:   "နယ်သာလန်",
			TH:   "เนเธอร์แลนด์",
			TR:   "Hollanda",
			SV:   "Nederländerna",
		},
	},
	{
		Code: "NI",
		LocaleNames: dto.LocaleResponse{
			ZH:   "尼加拉瓜",
			ZHTW: "尼加拉瓜",
			EN:   "Nicaragua",
			JA:   "ニカラグア",
			KO:   "니카라과",
			MY:   "နီကာရာဂွါ",
			TH:   "นิการากัว",
			TR:   "Nikaragua",
			SV:   "Nicaragua",
		},
	},
	{
		Code: "NE",
		LocaleNames: dto.LocaleResponse{
			ZH:   "尼日尔",
			ZHTW: "尼日",
			EN:   "Niger",
			JA:   "ニジェール",
			KO:   "니제르",
			MY:   "နိုင်ဂျာ",
			TH:   "ไนเจอร์",
			TR:   "Nijer",
			SV:   "Niger",
		},
	},
	{
		Code: "NO",
		LocaleNames: dto.LocaleResponse{
			ZH:   "挪威",
			ZHTW: "挪威",
			EN:   "Norway",
			JA:   "ノルウェー",
			KO:   "노르웨이",
			MY:   "နော်ဝေ",
			TH:   "นอร์เวย์",
			TR:   "Norveç",
			SV:   "Norge",
		},
	},
	{
		Code: "OM",
		LocaleNames: dto.LocaleResponse{
			ZH:   "阿曼",
			ZHTW: "阿曼",
			EN:   "Oman",
			JA:   "オマーン",
			KO:   "오만",
			MY:   "အိုမန်",
			TH:   "โอมาน",
			TR:   "Umman",
			SV:   "Oman",
		},
	},
	{
		Code: "PK",
		LocaleNames: dto.LocaleResponse{
			ZH:   "巴基斯坦",
			ZHTW: "巴基斯坦",
			EN:   "Pakistan",
			JA:   "パキスタン",
			KO:   "파키스탄",
			MY:   "ပါကစ္စတန်",
			TH:   "ปากีสถาน",
			TR:   "Pakistan",
			SV:   "Pakistan",
		},
	},
	{
		Code: "PW",
		LocaleNames: dto.LocaleResponse{
			ZH:   "帕劳",
			ZHTW: "帛琉",
			EN:   "Palau",
			JA:   "パラオ",
			KO:   "팔라우",
			MY:   "ပလာအို",
			TH:   "ปาเลา",
			TR:   "Palau",
			SV:   "Palau",
		},
	},
	{
		Code: "PS",
		LocaleNames: dto.LocaleResponse{
			ZH:   "巴勒斯坦",
			ZHTW: "巴勒斯坦",
			EN:   "Palestine",
			JA:   "パレスチナ",
			KO:   "팔레스타인",
			MY:   "ပါလက်စတိုင်း",
			TH:   "ปาเลสไตน์",
			TR:   "Filistin",
			SV:   "Palestina",
		},
	},
	{
		Code: "PA",
		LocaleNames: dto.LocaleResponse{
			ZH:   "巴拿马",
			ZHTW: "巴拿馬",
			EN:   "Panama",
			JA:   "パナマ",
			KO:   "파나마",
			MY:   "ပနားမား",
			TH:   "ปานามา",
			TR:   "Panama",
			SV:   "Panama",
		},
	},
	{
		Code: "PG",
		LocaleNames: dto.LocaleResponse{
			ZH:   "巴布亚新几内亚",
			ZHTW: "巴布亞紐幾內亞",
			EN:   "Papua New Guinea",
			JA:   "パプアニューギニア",
			KO:   "파푸아뉴기니",
			MY:   "ပါပူအာနယူးဂီနီ",
			TH:   "ปาปัวนิวกินี",
			TR:   "Papua Yeni Gine",
			SV:   "Papua Nya Guinea",
		},
	},
	{
		Code: "PY",
		LocaleNames: dto.LocaleResponse{
			ZH:   "巴拉圭",
			ZHTW: "巴拉圭",
			EN:   "Paraguay",
			JA:   "パラグアイ",
			KO:   "파라과이",
			MY:   "ပါရာဂွေး",
			TH:   "ปารากวัย",
			TR:   "Paraguay",
			SV:   "Paraguay",
		},
	},
	{
		Code: "PE",
		LocaleNames: dto.LocaleResponse{
			ZH:   "秘鲁",
			ZHTW: "秘魯",
			EN:   "Peru",
			JA:   "ペルー",
			KO:   "페루",
			MY:   "ပီရူး",
			TH:   "เปรู",
			TR:   "Peru",
			SV:   "Peru",
		},
	},
	{
		Code: "PL",
		LocaleNames: dto.LocaleResponse{
			ZH:   "波兰",
			ZHTW: "波蘭",
			EN:   "Poland",
			JA:   "ポーランド",
			KO:   "폴란드",
			MY:   "ပိုလန်",
			TH:   "โปแลนด์",
			TR:   "Polonya",
			SV:   "Polen",
		},
	},
	{
		Code: "PT",
		LocaleNames: dto.LocaleResponse{
			ZH:   "葡萄牙",
			ZHTW: "葡萄牙",
			EN:   "Portugal",
			JA:   "ポルトガル",
			KO:   "포르투갈",
			MY:   "ပေါ်တူဂီ",
			TH:   "โปรตุเกส",
			TR:   "Portekiz",
			SV:   "Portugal",
		},
	},
	{
		Code: "QA",
		LocaleNames: dto.LocaleResponse{
			ZH:   "卡塔尔",
			ZHTW: "卡達",
			EN:   "Qatar",
			JA:   "カタール",
			KO:   "카타르",
			MY:   "ကာတာ",
			TH:   "กาตาร์",
			TR:   "Katar",
			SV:   "Qatar",
		},
	},
	{
		Code: "RO",
		LocaleNames: dto.LocaleResponse{
			ZH:   "罗马尼亚",
			ZHTW: "羅馬尼亞",
			EN:   "Romania",
			JA:   "ルーマニア",
			KO:   "루마니아",
			MY:   "ရိုမေးနီးယား",
			TH:   "โรมาเนีย",
			TR:   "Romanya",
			SV:   "Rumänien",
		},
	},
	{
		Code: "RW",
		LocaleNames: dto.LocaleResponse{
			ZH:   "卢旺达",
			ZHTW: "盧安達",
			EN:   "Rwanda",
			JA:   "ルワンダ",
			KO:   "르완다",
			MY:   "ရဝမ်ဒါ",
			TH:   "รวันดา",
			TR:   "Ruanda",
			SV:   "Rwanda",
		},
	},
	{
		Code: "KN",
		LocaleNames: dto.LocaleResponse{
			ZH:   "圣基茨和尼维斯",
			ZHTW: "聖克里斯多福及尼維斯",
			EN:   "Saint Kitts and Nevis",
			JA:   "セントクリストファー・ネーヴィス",
			KO:   "세인트키츠 네비스",
			MY:   "စိန့်ကစ်နှင့်နီဗစ်",
			TH:   "เซนต์คิตส์และเนวิส",
			TR:   "Saint Kitts ve Nevis",
			SV:   "Saint Kitts och Nevis",
		},
	},
	{
		Code: "LC",
		LocaleNames: dto.LocaleResponse{
			ZH:   "圣卢西亚",
			ZHTW: "聖露西亞",
			EN:   "Saint Lucia",
			JA:   "セントルシア",
			KO:   "세인트루시아",
			MY:   "စိန့်လူစီယာ",
			TH:   "เซนต์ลูเซีย",
			TR:   "Saint Lucia",
			SV:   "Saint Lucia",
		},
	},
	{
		Code: "VC",
		LocaleNames: dto.LocaleResponse{
			ZH:   "圣文森特和格林纳丁斯",
			ZHTW: "聖文森及格瑞那丁",
			EN:   "Saint Vincent and the Grenadines",
			JA:   "セントビンセント・グレナディーン",
			KO:   "세인트빈센트 그레나딘",
			MY:   "စိန့်ဗင်းဆင့်နှင့်ဂရီနာဒင်းစ်",
			TH:   "เซนต์วินเซนต์และเกรนาดีนส์",
			TR:   "Saint Vincent ve Grenadinler",
			SV:   "Saint Vincent och Grenadinerna",
		},
	},
	{
		Code: "WS",
		LocaleNames: dto.LocaleResponse{
			ZH:   "萨摩亚",
			ZHTW: "薩摩亞",
			EN:   "Samoa",
			JA:   "サモア",
			KO:   "사모아",
			MY:   "ဆမိုအာ",
			TH:   "ซามัว",
			TR:   "Samoa",
			SV:   "Samoa",
		},
	},
	{
		Code: "SM",
		LocaleNames: dto.LocaleResponse{
			ZH:   "圣马力诺",
			ZHTW: "聖馬利諾",
			EN:   "San Marino",
			JA:   "サンマリノ",
			KO:   "산마리노",
			MY:   "ဆန်မာရီနို",
			TH:   "ซานมารีโน",
			TR:   "San Marino",
			SV:   "San Marino",
		},
	},
	{
		Code: "ST",
		LocaleNames: dto.LocaleResponse{
			ZH:   "圣多美和普林西比",
			ZHTW: "聖多美普林西比",
			EN:   "São Tomé and Príncipe",
			JA:   "サントメ・プリンシペ",
			KO:   "상투메 프린시페",
			MY:   "ဆောင်တူမေးနှင့်ပရင်စီပီ",
			TH:   "เซาตูเมและปรินซิปี",
			TR:   "São Tomé ve Príncipe",
			SV:   "São Tomé och Príncipe",
		},
	},
	{
		Code: "SN",
		LocaleNames: dto.LocaleResponse{
			ZH:   "塞内加尔",
			ZHTW: "塞內加爾",
			EN:   "Senegal",
			JA:   "セネガル",
			KO:   "세네갈",
			MY:   "ဆီနီဂေါ",
			TH:   "เซเนกัล",
			TR:   "Senegal",
			SV:   "Senegal",
		},
	},
	{
		Code: "RS",
		LocaleNames: dto.LocaleResponse{
			ZH:   "塞尔维亚",
			ZHTW: "塞爾維亞",
			EN:   "Serbia",
			JA:   "セルビア",
			KO:   "세르비아",
			MY:   "ဆားဘီးယား",
			TH:   "เซอร์เบีย",
			TR:   "Sırbistan",
			SV:   "Serbien",
		},
	},
	{
		Code: "SC",
		LocaleNames: dto.LocaleResponse{
			ZH:   "塞舌尔",
			ZHTW: "塞席爾",
			EN:   "Seychelles",
			JA:   "セーシェル",
			KO:   "세이셸",
			MY:   "ဆေးရှဲ",
			TH:   "เซเชลส์",
			TR:   "Seyşeller",
			SV:   "Seychellerna",
		},
	},
	{
		Code: "SL",
		LocaleNames: dto.LocaleResponse{
			ZH:   "塞拉利昂",
			ZHTW: "獅子山",
			EN:   "Sierra Leone",
			JA:   "シエラレオネ",
			KO:   "시에라리온",
			MY:   "ဆီယာရာလီယွန်း",
			TH:   "เซียร์ราลีโอน",
			TR:   "Sierra Leone",
			SV:   "Sierra Leone",
		},
	},
	{
		Code: "SK",
		LocaleNames: dto.LocaleResponse{
			ZH:   "斯洛伐克",
			ZHTW: "斯洛伐克",
			EN:   "Slovakia",
			JA:   "スロバキア",
			KO:   "슬로바키아",
			MY:   "ဆလိုဗက်ကီးယား",
			TH:   "สโลวาเกีย",
			TR:   "Slovakya",
			SV:   "Slovakien",
		},
	},
	{
		Code: "SI",
		LocaleNames: dto.LocaleResponse{
			ZH:   "斯洛文尼亚",
			ZHTW: "斯洛維尼亞",
			EN:   "Slovenia",
			JA:   "スロベニア",
			KO:   "슬로베니아",
			MY:   "ဆလိုဗေးနီးယား",
			TH:   "สโลวีเนีย",
			TR:   "Slovenya",
			SV:   "Slovenien",
		},
	},
	{
		Code: "SB",
		LocaleNames: dto.LocaleResponse{
			ZH:   "所罗门群岛",
			ZHTW: "索羅門群島",
			EN:   "Solomon Islands",
			JA:   "ソロモン諸島",
			KO:   "솔로몬 제도",
			MY:   "ဆော်လမွန်ကျွန်းစု",
			TH:   "หมู่เกาะโซโลมอน",
			TR:   "Solomon Adaları",
			SV:   "Salomonöarna",
		},
	},
	{
		Code: "SO",
		LocaleNames: dto.LocaleResponse{
			ZH:   "索马里",
			ZHTW: "索馬利亞",
			EN:   "Somalia",
			JA:   "ソマリア",
			KO:   "소말리아",
			MY:   "ဆိုမာလီယာ",
			TH:   "โซมาเลีย",
			TR:   "Somali",
			SV:   "Somalia",
		},
	},
	{
		Code: "SS",
		LocaleNames: dto.LocaleResponse{
			ZH:   "南苏丹",
			ZHTW: "南蘇丹",
			EN:   "South Sudan",
			JA:   "南スーダン",
			KO:   "남수단",
			MY:   "တောင်ဆူဒန်",
			TH:   "เซาท์ซูดาน",
			TR:   "Güney Sudan",
			SV:   "Sydsudan",
		},
	},
	{
		Code: "LK",
		LocaleNames: dto.LocaleResponse{
			ZH:   "斯里兰卡",
			ZHTW: "斯里蘭卡",
			EN:   "Sri Lanka",
			JA:   "スリランカ",
			KO:   "스리랑카",
			MY:   "သီရိလင်္ကာ",
			TH:   "ศรีลังกา",
			TR:   "Sri Lanka",
			SV:   "Sri Lanka",
		},
	},
	{
		Code: "SD",
		LocaleNames: dto.LocaleResponse{
			ZH:   "苏丹",
			ZHTW: "蘇丹",
			EN:   "Sudan",
			JA:   "スーダン",
			KO:   "수단",
			MY:   "ဆူဒန်",
			TH:   "ซูดาน",
			TR:   "Sudan",
			SV:   "Sudan",
		},
	},
	{
		Code: "SR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "苏里南",
			ZHTW: "蘇利南",
			EN:   "Suriname",
			JA:   "スリナム",
			KO:   "수리남",
			MY:   "ဆူရီနမ်",
			TH:   "ซูรินาเม",
			TR:   "Surinam",
			SV:   "Surinam",
		},
	},
	{
		Code: "SE",
		LocaleNames: dto.LocaleResponse{
			ZH:   "瑞典",
			ZHTW: "瑞典",
			EN:   "Sweden",
			JA:   "スウェーデン",
			KO:   "스웨덴",
			MY:   "ဆွီဒင်",
			TH:   "สวีเดน",
			TR:   "İsveç",
			SV:   "Sverige",
		},
	},
	{
		Code: "CH",
		LocaleNames: dto.LocaleResponse{
			ZH:   "瑞士",
			ZHTW: "瑞士",
			EN:   "Switzerland",
			JA:   "スイス",
			KO:   "스위스",
			MY:   "ဆွစ်ဇာလန်",
			TH:   "สวิตเซอร์แลนด์",
			TR:   "İsviçre",
			SV:   "Schweiz",
		},
	},
	{
		Code: "SY",
		LocaleNames: dto.LocaleResponse{
			ZH:   "叙利亚",
			ZHTW: "敘利亞",
			EN:   "Syria",
			JA:   "シリア",
			KO:   "시리아",
			MY:   "ဆီးရီးယား",
			TH:   "ซีเรีย",
			TR:   "Suriye",
			SV:   "Syrien",
		},
	},
	{
		Code: "TJ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "塔吉克斯坦",
			ZHTW: "塔吉克",
			EN:   "Tajikistan",
			JA:   "タジキスタン",
			KO:   "타지키스탄",
			MY:   "တာဂျီကစ္စတန်",
			TH:   "ทาจิกิสถาน",
			TR:   "Tacikistan",
			SV:   "Tadzjikistan",
		},
	},
	{
		Code: "TZ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "坦桑尼亚",
			ZHTW: "坦尚尼亞",
			EN:   "Tanzania",
			JA:   "タンザニア",
			KO:   "탄자니아",
			MY:   "တန်ဇန်းနီးယား",
			TH:   "แทนซาเนีย",
			TR:   "Tanzanya",
			SV:   "Tanzania",
		},
	},
	{
		Code: "TL",
		LocaleNames: dto.LocaleResponse{
			ZH:   "东帝汶",
			ZHTW: "東帝汶",
			EN:   "Timor-Leste",
			JA:   "東ティモール",
			KO:   "동티모르",
			MY:   "အရှေ့တီမော",
			TH:   "ติมอร์-เลสเต",
			TR:   "Doğu Timor",
			SV:   "Östtimor",
		},
	},
	{
		Code: "TG",
		LocaleNames: dto.LocaleResponse{
			ZH:   "多哥",
			ZHTW: "多哥",
			EN:   "Togo",
			JA:   "トーゴ",
			KO:   "토고",
			MY:   "တိုဂို",
			TH:   "โตโก",
			TR:   "Togo",
			SV:   "Togo",
		},
	},
	{
		Code: "TO",
		LocaleNames: dto.LocaleResponse{
			ZH:   "汤加",
			ZHTW: "東加",
			EN:   "Tonga",
			JA:   "トンガ",
			KO:   "통가",
			MY:   "တွန်ဂါ",
			TH:   "ตองกา",
			TR:   "Tonga",
			SV:   "Tonga",
		},
	},
	{
		Code: "TT",
		LocaleNames: dto.LocaleResponse{
			ZH:   "特立尼达和多巴哥",
			ZHTW: "千里達及托巴哥",
			EN:   "Trinidad and Tobago",
			JA:   "トリニダード・トバゴ",
			KO:   "트리니다드 토바고",
			MY:   "ထရီနီဒက်နှင့်တိုဘာဂို",
			TH:   "ตรินิแดดและโตเบโก",
			TR:   "Trinidad ve Tobago",
			SV:   "Trinidad och Tobago",
		},
	},
	{
		Code: "TN",
		LocaleNames: dto.LocaleResponse{
			ZH:   "突尼斯",
			ZHTW: "突尼西亞",
			EN:   "Tunisia",
			JA:   "チュニジア",
			KO:   "튀니지",
			MY:   "တူနီးရှား",
			TH:   "ตูนิเซีย",
			TR:   "Tunus",
			SV:   "Tunisien",
		},
	},
	{
		Code: "TM",
		LocaleNames: dto.LocaleResponse{
			ZH:   "土库曼斯坦",
			ZHTW: "土庫曼",
			EN:   "Turkmenistan",
			JA:   "トルクメニスタン",
			KO:   "투르크메니스탄",
			MY:   "တာ့ခ်မင်နစ္စတန်",
			TH:   "เติร์กเมนิสถาน",
			TR:   "Türkmenistan",
			SV:   "Turkmenistan",
		},
	},
	{
		Code: "TV",
		LocaleNames: dto.LocaleResponse{
			ZH:   "图瓦卢",
			ZHTW: "吐瓦魯",
			EN:   "Tuvalu",
			JA:   "ツバル",
			KO:   "투발루",
			MY:   "တူဗာလူ",
			TH:   "ตูวาลู",
			TR:   "Tuvalu",
			SV:   "Tuvalu",
		},
	},
	{
		Code: "UG",
		LocaleNames: dto.LocaleResponse{
			ZH:   "乌干达",
			ZHTW: "烏干達",
			EN:   "Uganda",
			JA:   "ウガンダ",
			KO:   "우간다",
			MY:   "ဥဂန်ဒါ",
			TH:   "ยูกันดา",
			TR:   "Uganda",
			SV:   "Uganda",
		},
	},
	{
		Code: "UA",
		LocaleNames: dto.LocaleResponse{
			ZH:   "乌克兰",
			ZHTW: "烏克蘭",
			EN:   "Ukraine",
			JA:   "ウクライナ",
			KO:   "우크라이나",
			MY:   "ယူကရိန်း",
			TH:   "ยูเครน",
			TR:   "Ukrayna",
			SV:   "Ukraina",
		},
	},
	{
		Code: "UY",
		LocaleNames: dto.LocaleResponse{
			ZH:   "乌拉圭",
			ZHTW: "烏拉圭",
			EN:   "Uruguay",
			JA:   "ウルグアイ",
			KO:   "우루과이",
			MY:   "ဥရုဂွေး",
			TH:   "อุรุกวัย",
			TR:   "Uruguay",
			SV:   "Uruguay",
		},
	},
	{
		Code: "UZ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "乌兹别克斯坦",
			ZHTW: "烏茲別克",
			EN:   "Uzbekistan",
			JA:   "ウズベキスタン",
			KO:   "우즈베키스탄",
			MY:   "ဥဇဘက်ကစ္စတန်",
			TH:   "อุซเบกิสถาน",
			TR:   "Özbekistan",
			SV:   "Uzbekistan",
		},
	},
	{
		Code: "VU",
		LocaleNames: dto.LocaleResponse{
			ZH:   "瓦努阿图",
			ZHTW: "萬那杜",
			EN:   "Vanuatu",
			JA:   "バヌアツ",
			KO:   "바누아투",
			MY:   "ဗာနူအာတူ",
			TH:   "วานูอาตู",
			TR:   "Vanuatu",
			SV:   "Vanuatu",
		},
	},
	{
		Code: "VA",
		LocaleNames: dto.LocaleResponse{
			ZH:   "梵蒂冈",
			ZHTW: "梵蒂岡",
			EN:   "Vatican City",
			JA:   "バチカン",
			KO:   "바티칸",
			MY:   "ဗာတီကန်",
			TH:   "นครวาติกัน",
			TR:   "Vatikan",
			SV:   "Vatikanen",
		},
	},
	{
		Code: "VE",
		LocaleNames: dto.LocaleResponse{
			ZH:   "委内瑞拉",
			ZHTW: "委內瑞拉",
			EN:   "Venezuela",
			JA:   "ベネズエラ",
			KO:   "베네수엘라",
			MY:   "ဗင်နီဇွဲလာ",
			TH:   "เวเนซุเอลา",
			TR:   "Venezuela",
			SV:   "Venezuela",
		},
	},
	{
		Code: "YE",
		LocaleNames: dto.LocaleResponse{
			ZH:   "也门",
			ZHTW: "葉門",
			EN:   "Yemen",
			JA:   "イエメン",
			KO:   "예멘",
			MY:   "ယီမင်",
			TH:   "เยเมน",
			TR:   "Yemen",
			SV:   "Jemen",
		},
	},
	{
		Code: "ZM",
		LocaleNames: dto.LocaleResponse{
			ZH:   "赞比亚",
			ZHTW: "尚比亞",
			EN:   "Zambia",
			JA:   "ザンビア",
			KO:   "잠비아",
			MY:   "ဇမ်ဘီယာ",
			TH:   "แซมเบีย",
			TR:   "Zambiya",
			SV:   "Zambia",
		},
	},
	{
		Code: "ZW",
		LocaleNames: dto.LocaleResponse{
			ZH:   "津巴布韦",
			ZHTW: "辛巴威",
			EN:   "Zimbabwe",
			JA:   "ジンバブエ",
			KO:   "짐바브웨",
			MY:   "ဇင်ဘာဘွေ",
			TH:   "ซิมบับเว",
			TR:   "Zimbabve",
			SV:   "Zimbabwe",
		},
	},
}

// GetAllCountries 获取所有国家列表
func GetAllCountries() []Country {
	return countries
}

// GetCountryByCode 根据编码获取国家信息
func GetCountryByCode(code string) *Country {
	for i := range countries {
		if countries[i].Code == code {
			return &countries[i]
		}
	}
	return nil
}
