package constant

import (
	"ttpos-server-go/app/dto"
)

// Country 国家信息
type Country struct {
	Code        string             // 国家编码（ISO 3166-1 alpha-2）
	LocaleNames dto.LocaleResponse // 多语言国家名称
}

// GetLocaleNames 获取多语言名称
func (c *Country) GetLocaleNames() dto.LocaleResponse {
	return c.LocaleNames
}

// 国家列表（部分国家，后续补充完整197个国家）
var countries = []Country{
	{
		Code: "CN",
		LocaleNames: dto.LocaleResponse{
			ZH:   "中国",
			ZHTW: "中國",
			EN:   "China",
			JA:   "中国",
			KO:   "중국",
			MY:   "တရုတ်",
			TH:   "จีน",
			TR:   "Çin",
			SV:   "Kina",
		},
	},
	{
		Code: "US",
		LocaleNames: dto.LocaleResponse{
			ZH:   "美国",
			ZHTW: "美國",
			EN:   "United States",
			JA:   "アメリカ合衆国",
			KO:   "미국",
			MY:   "အမေရိကန်",
			TH:   "สหรัฐอเมริกา",
			TR:   "Amerika Birleşik Devletleri",
			SV:   "USA",
		},
	},
	{
		Code: "TH",
		LocaleNames: dto.LocaleResponse{
			ZH:   "泰国",
			ZHTW: "泰國",
			EN:   "Thailand",
			JA:   "タイ",
			KO:   "태국",
			MY:   "ထိုင်း",
			TH:   "ประเทศไทย",
			TR:   "Tayland",
			SV:   "Thailand",
		},
	},
	{
		Code: "JP",
		LocaleNames: dto.LocaleResponse{
			ZH:   "日本",
			ZHTW: "日本",
			EN:   "Japan",
			JA:   "日本",
			KO:   "일본",
			MY:   "ဂျပန်",
			TH:   "ญี่ปุ่น",
			TR:   "Japonya",
			SV:   "Japan",
		},
	},
	{
		Code: "KR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "韩国",
			ZHTW: "韓國",
			EN:   "South Korea",
			JA:   "韓国",
			KO:   "대한민국",
			MY:   "တောင်ကိုရီးယား",
			TH:   "เกาหลีใต้",
			TR:   "Güney Kore",
			SV:   "Sydkorea",
		},
	},
	{
		Code: "MY",
		LocaleNames: dto.LocaleResponse{
			ZH:   "马来西亚",
			ZHTW: "馬來西亞",
			EN:   "Malaysia",
			JA:   "マレーシア",
			KO:   "말레이시아",
			MY:   "မလေးရှား",
			TH:   "มาเลเซีย",
			TR:   "Malezya",
			SV:   "Malaysia",
		},
	},
	{
		Code: "SG",
		LocaleNames: dto.LocaleResponse{
			ZH:   "新加坡",
			ZHTW: "新加坡",
			EN:   "Singapore",
			JA:   "シンガポール",
			KO:   "싱가포르",
			MY:   "စင်ကာပူ",
			TH:   "สิงคโปร์",
			TR:   "Singapur",
			SV:   "Singapore",
		},
	},
	{
		Code: "ID",
		LocaleNames: dto.LocaleResponse{
			ZH:   "印度尼西亚",
			ZHTW: "印尼",
			EN:   "Indonesia",
			JA:   "インドネシア",
			KO:   "인도네시아",
			MY:   "အင်ဒိုနီးရှား",
			TH:   "อินโดนีเซีย",
			TR:   "Endonezya",
			SV:   "Indonesien",
		},
	},
	{
		Code: "PH",
		LocaleNames: dto.LocaleResponse{
			ZH:   "菲律宾",
			ZHTW: "菲律賓",
			EN:   "Philippines",
			JA:   "フィリピン",
			KO:   "필리핀",
			MY:   "ဖိလစ်ပိုင်",
			TH:   "ฟิลิปปินส์",
			TR:   "Filipinler",
			SV:   "Filippinerna",
		},
	},
	{
		Code: "VN",
		LocaleNames: dto.LocaleResponse{
			ZH:   "越南",
			ZHTW: "越南",
			EN:   "Vietnam",
			JA:   "ベトナム",
			KO:   "베트남",
			MY:   "ဗီယက်နမ်",
			TH:   "เวียดนาม",
			TR:   "Vietnam",
			SV:   "Vietnam",
		},
	},
	{
		Code: "IN",
		LocaleNames: dto.LocaleResponse{
			ZH:   "印度",
			ZHTW: "印度",
			EN:   "India",
			JA:   "インド",
			KO:   "인도",
			MY:   "အိန္ဒိယ",
			TH:   "อินเดีย",
			TR:   "Hindistan",
			SV:   "Indien",
		},
	},
	{
		Code: "GB",
		LocaleNames: dto.LocaleResponse{
			ZH:   "英国",
			ZHTW: "英國",
			EN:   "United Kingdom",
			JA:   "イギリス",
			KO:   "영국",
			MY:   "ယူနိုက်တက်ကင်းဒမ်း",
			TH:   "สหราชอาณาจักร",
			TR:   "Birleşik Krallık",
			SV:   "Storbritannien",
		},
	},
	{
		Code: "FR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "法国",
			ZHTW: "法國",
			EN:   "France",
			JA:   "フランス",
			KO:   "프랑스",
			MY:   "ပြင်သစ်",
			TH:   "ฝรั่งเศส",
			TR:   "Fransa",
			SV:   "Frankrike",
		},
	},
	{
		Code: "DE",
		LocaleNames: dto.LocaleResponse{
			ZH:   "德国",
			ZHTW: "德國",
			EN:   "Germany",
			JA:   "ドイツ",
			KO:   "독일",
			MY:   "ဂျာမနီ",
			TH:   "เยอรมนี",
			TR:   "Almanya",
			SV:   "Tyskland",
		},
	},
	{
		Code: "IT",
		LocaleNames: dto.LocaleResponse{
			ZH:   "意大利",
			ZHTW: "義大利",
			EN:   "Italy",
			JA:   "イタリア",
			KO:   "이탈리아",
			MY:   "အီတလီ",
			TH:   "อิตาลี",
			TR:   "İtalya",
			SV:   "Italien",
		},
	},
	{
		Code: "ES",
		LocaleNames: dto.LocaleResponse{
			ZH:   "西班牙",
			ZHTW: "西班牙",
			EN:   "Spain",
			JA:   "スペイン",
			KO:   "스페인",
			MY:   "စပိန်",
			TH:   "สเปน",
			TR:   "İspanya",
			SV:   "Spanien",
		},
	},
	{
		Code: "RU",
		LocaleNames: dto.LocaleResponse{
			ZH:   "俄罗斯",
			ZHTW: "俄羅斯",
			EN:   "Russia",
			JA:   "ロシア",
			KO:   "러시아",
			MY:   "ရုရှား",
			TH:   "รัสเซีย",
			TR:   "Rusya",
			SV:   "Ryssland",
		},
	},
	{
		Code: "CA",
		LocaleNames: dto.LocaleResponse{
			ZH:   "加拿大",
			ZHTW: "加拿大",
			EN:   "Canada",
			JA:   "カナダ",
			KO:   "캐나다",
			MY:   "ကနေဒါ",
			TH:   "แคนาดา",
			TR:   "Kanada",
			SV:   "Kanada",
		},
	},
	{
		Code: "AU",
		LocaleNames: dto.LocaleResponse{
			ZH:   "澳大利亚",
			ZHTW: "澳洲",
			EN:   "Australia",
			JA:   "オーストラリア",
			KO:   "호주",
			MY:   "ဩစတြေးလျ",
			TH:   "ออสเตรเลีย",
			TR:   "Avustralya",
			SV:   "Australien",
		},
	},
	{
		Code: "NZ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "新西兰",
			ZHTW: "紐西蘭",
			EN:   "New Zealand",
			JA:   "ニュージーランド",
			KO:   "뉴질랜드",
			MY:   "နယူးဇီလန်",
			TH:   "นิวซีแลนด์",
			TR:   "Yeni Zelanda",
			SV:   "Nya Zeeland",
		},
	},
	{
		Code: "BR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "巴西",
			ZHTW: "巴西",
			EN:   "Brazil",
			JA:   "ブラジル",
			KO:   "브라질",
			MY:   "ဘရာဇီး",
			TH:   "บราซิล",
			TR:   "Brezilya",
			SV:   "Brasilien",
		},
	},
	{
		Code: "MX",
		LocaleNames: dto.LocaleResponse{
			ZH:   "墨西哥",
			ZHTW: "墨西哥",
			EN:   "Mexico",
			JA:   "メキシコ",
			KO:   "멕시코",
			MY:   "မက္ကဆီကို",
			TH:   "เม็กซิโก",
			TR:   "Meksika",
			SV:   "Mexiko",
		},
	},
	{
		Code: "AR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "阿根廷",
			ZHTW: "阿根廷",
			EN:   "Argentina",
			JA:   "アルゼンチン",
			KO:   "아르헨티나",
			MY:   "အာဂျင်တီးနား",
			TH:   "อาร์เจนตินา",
			TR:   "Arjantin",
			SV:   "Argentina",
		},
	},
	{
		Code: "TR",
		LocaleNames: dto.LocaleResponse{
			ZH:   "土耳其",
			ZHTW: "土耳其",
			EN:   "Turkey",
			JA:   "トルコ",
			KO:   "터키",
			MY:   "တူရကီ",
			TH:   "ตุรกี",
			TR:   "Türkiye",
			SV:   "Turkiet",
		},
	},
	{
		Code: "SA",
		LocaleNames: dto.LocaleResponse{
			ZH:   "沙特阿拉伯",
			ZHTW: "沙烏地阿拉伯",
			EN:   "Saudi Arabia",
			JA:   "サウジアラビア",
			KO:   "사우디아라비아",
			MY:   "ဆော်ဒီအာရေဗျ",
			TH:   "ซาอุดีอาระเบีย",
			TR:   "Suudi Arabistan",
			SV:   "Saudiarabien",
		},
	},
	{
		Code: "AE",
		LocaleNames: dto.LocaleResponse{
			ZH:   "阿联酋",
			ZHTW: "阿拉伯聯合大公國",
			EN:   "United Arab Emirates",
			JA:   "アラブ首長国連邦",
			KO:   "아랍에미리트",
			MY:   "ယူအေအီး",
			TH:   "สหรัฐอาหรับเอมิเรตส์",
			TR:   "Birleşik Arap Emirlikleri",
			SV:   "Förenade Arabemiraten",
		},
	},
	{
		Code: "EG",
		LocaleNames: dto.LocaleResponse{
			ZH:   "埃及",
			ZHTW: "埃及",
			EN:   "Egypt",
			JA:   "エジプト",
			KO:   "이집트",
			MY:   "အီဂျစ်",
			TH:   "อียิปต์",
			TR:   "Mısır",
			SV:   "Egypten",
		},
	},
	{
		Code: "ZA",
		LocaleNames: dto.LocaleResponse{
			ZH:   "南非",
			ZHTW: "南非",
			EN:   "South Africa",
			JA:   "南アフリカ",
			KO:   "남아프리카 공화국",
			MY:   "တောင်အာဖရိက",
			TH:   "แอฟริกาใต้",
			TR:   "Güney Afrika",
			SV:   "Sydafrika",
		},
	},
	{
		Code: "NG",
		LocaleNames: dto.LocaleResponse{
			ZH:   "尼日利亚",
			ZHTW: "奈及利亞",
			EN:   "Nigeria",
			JA:   "ナイジェリア",
			KO:   "나이지리아",
			MY:   "နိုင်ဂျီးရီးယား",
			TH:   "ไนจีเรีย",
			TR:   "Nijerya",
			SV:   "Nigeria",
		},
	},
	{
		Code: "KE",
		LocaleNames: dto.LocaleResponse{
			ZH:   "肯尼亚",
			ZHTW: "肯亞",
			EN:   "Kenya",
			JA:   "ケニア",
			KO:   "케냐",
			MY:   "ကင်ညာ",
			TH:   "เคนยา",
			TR:   "Kenya",
			SV:   "Kenya",
		},
	},
	{
		Code: "HK",
		LocaleNames: dto.LocaleResponse{
			ZH:   "香港",
			ZHTW: "香港",
			EN:   "Hong Kong",
			JA:   "香港",
			KO:   "홍콩",
			MY:   "ဟောင်ကောင်",
			TH:   "ฮ่องกง",
			TR:   "Hong Kong",
			SV:   "Hongkong",
		},
	},
	{
		Code: "TW",
		LocaleNames: dto.LocaleResponse{
			ZH:   "台湾",
			ZHTW: "台灣",
			EN:   "Taiwan",
			JA:   "台湾",
			KO:   "대만",
			MY:   "ထိုင်ဝမ်",
			TH:   "ไต้หวัน",
			TR:   "Tayvan",
			SV:   "Taiwan",
		},
	},
	{
		Code: "MO",
		LocaleNames: dto.LocaleResponse{
			ZH:   "澳门",
			ZHTW: "澳門",
			EN:   "Macau",
			JA:   "マカオ",
			KO:   "마카오",
			MY:   "မကာအို",
			TH:   "มาเก๊า",
			TR:   "Makao",
			SV:   "Macao",
		},
	},
	{
		Code: "AF",
		LocaleNames: dto.LocaleResponse{
			ZH:   "阿富汗",
			ZHTW: "阿富汗",
			EN:   "Afghanistan",
			JA:   "アフガニスタン",
			KO:   "아프가니스탄",
			MY:   "အာဖဂန်နစ္စတန်",
			TH:   "อัฟกานิสถาน",
			TR:   "Afganistan",
			SV:   "Afghanistan",
		},
	},
	{
		Code: "AL",
		LocaleNames: dto.LocaleResponse{
			ZH:   "阿尔巴尼亚",
			ZHTW: "阿爾巴尼亞",
			EN:   "Albania",
			JA:   "アルバニア",
			KO:   "알바니아",
			MY:   "အယ်လ်ဘေးနီးယား",
			TH:   "แอลเบเนีย",
			TR:   "Arnavutluk",
			SV:   "Albanien",
		},
	},
	{
		Code: "DZ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "阿尔及利亚",
			ZHTW: "阿爾及利亞",
			EN:   "Algeria",
			JA:   "アルジェリア",
			KO:   "알제리",
			MY:   "အယ်လ်ဂျီးရီးယား",
			TH:   "แอลจีเรีย",
			TR:   "Cezayir",
			SV:   "Algeriet",
		},
	},
	{
		Code: "AD",
		LocaleNames: dto.LocaleResponse{
			ZH:   "安道尔",
			ZHTW: "安道爾",
			EN:   "Andorra",
			JA:   "アンドラ",
			KO:   "안도라",
			MY:   "အန်ဒိုရာ",
			TH:   "อันดอร์รา",
			TR:   "Andorra",
			SV:   "Andorra",
		},
	},
	{
		Code: "AO",
		LocaleNames: dto.LocaleResponse{
			ZH:   "安哥拉",
			ZHTW: "安哥拉",
			EN:   "Angola",
			JA:   "アンゴラ",
			KO:   "앙골라",
			MY:   "အန်ဂိုလာ",
			TH:   "แองโกลา",
			TR:   "Angola",
			SV:   "Angola",
		},
	},
	{
		Code: "AG",
		LocaleNames: dto.LocaleResponse{
			ZH:   "安提瓜和巴布达",
			ZHTW: "安地卡及巴布達",
			EN:   "Antigua and Barbuda",
			JA:   "アンティグア・バーブーダ",
			KO:   "앤티가 바부다",
			MY:   "အန်တီဂွါနှင့်ဘာဘူဒါ",
			TH:   "แอนติกาและบาร์บูดา",
			TR:   "Antigua ve Barbuda",
			SV:   "Antigua och Barbuda",
		},
	},
	{
		Code: "AM",
		LocaleNames: dto.LocaleResponse{
			ZH:   "亚美尼亚",
			ZHTW: "亞美尼亞",
			EN:   "Armenia",
			JA:   "アルメニア",
			KO:   "아르메니아",
			MY:   "အာမေးနီးယား",
			TH:   "อาร์เมเนีย",
			TR:   "Ermenistan",
			SV:   "Armenien",
		},
	},
	{
		Code: "AT",
		LocaleNames: dto.LocaleResponse{
			ZH:   "奥地利",
			ZHTW: "奧地利",
			EN:   "Austria",
			JA:   "オーストリア",
			KO:   "오스트리아",
			MY:   "ဩစတြီးယား",
			TH:   "ออสเตรีย",
			TR:   "Avusturya",
			SV:   "Österrike",
		},
	},
	{
		Code: "AZ",
		LocaleNames: dto.LocaleResponse{
			ZH:   "阿塞拜疆",
			ZHTW: "亞塞拜然",
			EN:   "Azerbaijan",
			JA:   "アゼルバイジャン",
			KO:   "아제르바이잔",
			MY:   "အဇာဘိုင်ဂျန်",
			TH:   "อาเซอร์ไบจาน",
			TR:   "Azerbaycan",
			SV:   "Azerbajdzjan",
		},
	},
	{
		Code: "BS",
		LocaleNames: dto.LocaleResponse{
			ZH:   "巴哈马",
			ZHTW: "巴哈馬",
			EN:   "Bahamas",
			JA:   "バハマ",
			KO:   "바하마",
			MY:   "ဘဟားမား",
			TH:   "บาฮามาส",
			TR:   "Bahamalar",
			SV:   "Bahamas",
		},
	},
	{
		Code: "BH",
		LocaleNames: dto.LocaleResponse{
			ZH:   "巴林",
			ZHTW: "巴林",
			EN:   "Bahrain",
			JA:   "バーレーン",
			KO:   "바레인",
			MY:   "ဘာရိန်း",
			TH:   "บาห์เรน",
			TR:   "Bahreyn",
			SV:   "Bahrain",
		},
	},
	{
		Code: "BD",
		LocaleNames: dto.LocaleResponse{
			ZH:   "孟加拉国",
			ZHTW: "孟加拉",
			EN:   "Bangladesh",
			JA:   "バングラデシュ",
			KO:   "방글라데시",
			MY:   "ဘင်္ဂလားဒေ့ရှ်",
			TH:   "บังกลาเทศ",
			TR:   "Bangladeş",
			SV:   "Bangladesh",
		},
	},
	{
		Code: "BB",
		LocaleNames: dto.LocaleResponse{
			ZH:   "巴巴多斯",
			ZHTW: "巴貝多",
			EN:   "Barbados",
			JA:   "バルバドス",
			KO:   "바베이도스",
			MY:   "ဘာဘေးဒိုးစ်",
			TH:   "บาร์เบโดส",
			TR:   "Barbados",
			SV:   "Barbados",
		},
	},
	{
		Code: "BY",
		LocaleNames: dto.LocaleResponse{
			ZH:   "白俄罗斯",
			ZHTW: "白俄羅斯",
			EN:   "Belarus",
			JA:   "ベラルーシ",
			KO:   "벨라루스",
			MY:   "ဘီလာရုစ်",
			TH:   "เบลารุส",
			TR:   "Belarus",
			SV:   "Vitryssland",
		},
	},
}

// GetAllCountries 获取所有国家列表
func GetAllCountries() []Country {
	return countries
}

// GetCountryByCode 根据编码获取国家信息
func GetCountryByCode(code string) *Country {
	for i := range countries {
		if countries[i].Code == code {
			return &countries[i]
		}
	}
	return nil
}
