// WebSocket 服务 Protobuf 定义文件
// 用于定义 WebSocket 消息推送相关的 gRPC 服务接口和消息结构

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: websocket/websocket.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebSocket_PushMessage_FullMethodName        = "/websocket.WebSocket/PushMessage"
	WebSocket_GetConnectionStats_FullMethodName = "/websocket.WebSocket/GetConnectionStats"
	WebSocket_CheckDeviceOnline_FullMethodName  = "/websocket.WebSocket/CheckDeviceOnline"
	WebSocket_CloseConnection_FullMethodName    = "/websocket.WebSocket/CloseConnection"
)

// WebSocketClient is the client API for WebSocket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WebSocket 服务接口定义
// 提供 WebSocket 连接管理和消息推送相关的 gRPC 服务方法
type WebSocketClient interface {
	// 推送消息到客户端
	// 根据条件筛选连接并推送消息
	// 参数：推送消息请求参数
	// 返回：推送结果
	PushMessage(ctx context.Context, in *PushMessageReq, opts ...grpc.CallOption) (*PushMessageResp, error)
	// 获取连接统计信息
	// 返回当前所有 WebSocket 连接的统计数据
	// 参数：空请求
	// 返回：连接统计信息
	GetConnectionStats(ctx context.Context, in *GetConnectionStatsReq, opts ...grpc.CallOption) (*GetConnectionStatsResp, error)
	// 检查设备是否在线
	// 根据公司UUID和设备ID检查设备是否在线
	// 参数：设备信息
	// 返回：在线状态
	CheckDeviceOnline(ctx context.Context, in *CheckDeviceOnlineReq, opts ...grpc.CallOption) (*CheckDeviceOnlineResp, error)
	// 关闭指定连接
	// 根据条件关闭 WebSocket 连接
	// 参数：关闭连接请求
	// 返回：关闭结果
	CloseConnection(ctx context.Context, in *CloseConnectionReq, opts ...grpc.CallOption) (*CloseConnectionResp, error)
}

type webSocketClient struct {
	cc grpc.ClientConnInterface
}

func NewWebSocketClient(cc grpc.ClientConnInterface) WebSocketClient {
	return &webSocketClient{cc}
}

func (c *webSocketClient) PushMessage(ctx context.Context, in *PushMessageReq, opts ...grpc.CallOption) (*PushMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushMessageResp)
	err := c.cc.Invoke(ctx, WebSocket_PushMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webSocketClient) GetConnectionStats(ctx context.Context, in *GetConnectionStatsReq, opts ...grpc.CallOption) (*GetConnectionStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectionStatsResp)
	err := c.cc.Invoke(ctx, WebSocket_GetConnectionStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webSocketClient) CheckDeviceOnline(ctx context.Context, in *CheckDeviceOnlineReq, opts ...grpc.CallOption) (*CheckDeviceOnlineResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckDeviceOnlineResp)
	err := c.cc.Invoke(ctx, WebSocket_CheckDeviceOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webSocketClient) CloseConnection(ctx context.Context, in *CloseConnectionReq, opts ...grpc.CallOption) (*CloseConnectionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseConnectionResp)
	err := c.cc.Invoke(ctx, WebSocket_CloseConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebSocketServer is the server API for WebSocket service.
// All implementations must embed UnimplementedWebSocketServer
// for forward compatibility.
//
// WebSocket 服务接口定义
// 提供 WebSocket 连接管理和消息推送相关的 gRPC 服务方法
type WebSocketServer interface {
	// 推送消息到客户端
	// 根据条件筛选连接并推送消息
	// 参数：推送消息请求参数
	// 返回：推送结果
	PushMessage(context.Context, *PushMessageReq) (*PushMessageResp, error)
	// 获取连接统计信息
	// 返回当前所有 WebSocket 连接的统计数据
	// 参数：空请求
	// 返回：连接统计信息
	GetConnectionStats(context.Context, *GetConnectionStatsReq) (*GetConnectionStatsResp, error)
	// 检查设备是否在线
	// 根据公司UUID和设备ID检查设备是否在线
	// 参数：设备信息
	// 返回：在线状态
	CheckDeviceOnline(context.Context, *CheckDeviceOnlineReq) (*CheckDeviceOnlineResp, error)
	// 关闭指定连接
	// 根据条件关闭 WebSocket 连接
	// 参数：关闭连接请求
	// 返回：关闭结果
	CloseConnection(context.Context, *CloseConnectionReq) (*CloseConnectionResp, error)
	mustEmbedUnimplementedWebSocketServer()
}

// UnimplementedWebSocketServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebSocketServer struct{}

func (UnimplementedWebSocketServer) PushMessage(context.Context, *PushMessageReq) (*PushMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushMessage not implemented")
}
func (UnimplementedWebSocketServer) GetConnectionStats(context.Context, *GetConnectionStatsReq) (*GetConnectionStatsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnectionStats not implemented")
}
func (UnimplementedWebSocketServer) CheckDeviceOnline(context.Context, *CheckDeviceOnlineReq) (*CheckDeviceOnlineResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckDeviceOnline not implemented")
}
func (UnimplementedWebSocketServer) CloseConnection(context.Context, *CloseConnectionReq) (*CloseConnectionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseConnection not implemented")
}
func (UnimplementedWebSocketServer) mustEmbedUnimplementedWebSocketServer() {}
func (UnimplementedWebSocketServer) testEmbeddedByValue()                   {}

// UnsafeWebSocketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebSocketServer will
// result in compilation errors.
type UnsafeWebSocketServer interface {
	mustEmbedUnimplementedWebSocketServer()
}

func RegisterWebSocketServer(s grpc.ServiceRegistrar, srv WebSocketServer) {
	// If the following call pancis, it indicates UnimplementedWebSocketServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebSocket_ServiceDesc, srv)
}

func _WebSocket_PushMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebSocketServer).PushMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebSocket_PushMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebSocketServer).PushMessage(ctx, req.(*PushMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebSocket_GetConnectionStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebSocketServer).GetConnectionStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebSocket_GetConnectionStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebSocketServer).GetConnectionStats(ctx, req.(*GetConnectionStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebSocket_CheckDeviceOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDeviceOnlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebSocketServer).CheckDeviceOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebSocket_CheckDeviceOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebSocketServer).CheckDeviceOnline(ctx, req.(*CheckDeviceOnlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebSocket_CloseConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseConnectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebSocketServer).CloseConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebSocket_CloseConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebSocketServer).CloseConnection(ctx, req.(*CloseConnectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WebSocket_ServiceDesc is the grpc.ServiceDesc for WebSocket service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebSocket_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "websocket.WebSocket",
	HandlerType: (*WebSocketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushMessage",
			Handler:    _WebSocket_PushMessage_Handler,
		},
		{
			MethodName: "GetConnectionStats",
			Handler:    _WebSocket_GetConnectionStats_Handler,
		},
		{
			MethodName: "CheckDeviceOnline",
			Handler:    _WebSocket_CheckDeviceOnline_Handler,
		},
		{
			MethodName: "CloseConnection",
			Handler:    _WebSocket_CloseConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "websocket/websocket.proto",
}
