syntax = "proto3";
import "erp.proto" ;
package item;

// Go 包路径配置，指定生成的 Go 代码存放位置
option go_package = "ttpos-bmp/app/ttpos-erp/api/item";

enum ItemGroup {
  Others = 0; // 其他
  RawMaterial = 1; // 原材料
  Products = 2; // 商品
  Package = 3; // 套餐
  VirtualProduct = 4; // 虚拟产品
  PosAttribute =5 ; // pos 系统中特殊的item ，属性
  PosAddon = 6; // pos 系统中特殊的item ，加料
}

message GetItemListReq {
  ItemGroup item_group = 1; // 物品分组，可选  Products 商品/Raw Material 原材料/Package 套餐/Virtual Product 虚拟产品
  string item_name = 2; // 商品名称模糊查询，可选，如: %商品名称%
  string branch = 3; // 分支名称，可选
  string company_abbr = 4; // 公司简称，可选
  string sub_company_abbr = 5; // 门店公司简称，可选。 sub_company_abbr(门店公司简称) ,会过滤 item permission rule 下的物品，黑名单优先级高。
  string item_code = 6; // 物品编码，可选
  string item_code_prefix = 7; // 物品编码前缀，可选
  bool contain_disabled = 8; // 是否包含禁用状态，可选，默认只取有效
  string item_group_name = 9; // 物品分组名称，可选,  PosAttribute 属性/PosAddon 加料 时必填
  string variant_of = 10; // 变体物品编码，可选。 多规格商品时填。
}

message GetItemListResp {
  repeated ItemInfo item_list = 1; // 物品列表
}

message ItemInfo {
  string item_name = 1; // 物品名称，必填
  ItemGroup item_group = 2; // 物品分组，必填 Products 商品/Raw Material 原材料/Package 套餐/Virtual Product 虚拟产品 / PosAttribute 属性/PosAddon 加料
  string stock_uom = 3; // 库存单位，必填 ttpos 传英文过来
  string item_code = 4; // 物品编码，可选
  double valuation_rate = 5; // 估值率，必填
  string barcode = 6; // 条码，可选
  double opening_stock = 7; // 期初库存，可选
  bool is_stock_item = 8; // 是否库存物品，可选
  string template_item_code = 9; // 模版物品编码，可选， 多规格商品时必填，传原始物品编码
  string branch = 10; // 分支名称，可选
  string company_abbr = 11; // 公司简称，可选
  string company = 12; // 公司名称，可选
  string item_specification = 13; // 物品规格，可选 ttpos 传过来 多规格商品时必填。 映射到erp上是 item attribute, 这个是产品！设计！的特性！
  repeated UomDetail uoms = 14; // 单位列表，可选
  bool disabled = 15; // 是否禁用，可选
  string classification = 16; // 分类，可选
  string classification_code = 17; // 分类编码，可选
  string internal_code = 18; // 内部编码，可选
  bool not_for_sale = 19; //是否禁售，可选
  string purchase_uom = 20; // 默认采购单位，可选
  bool has_variants = 21; // 是否包含变体参数，可选。 多规格商品时必填。
  repeated ItemAttribute attributes = 22; // 变体参数列表，可选。 多规格商品时必填。
  string item_group_name = 23; // 物品分组名称，可选,  PosAttribute 属性/PosAddon 加料 时必填
}

message ItemAttribute {
  string attribute_name = 1; //属性名称
  string attribute_value = 2; //属性值
  string item_internal_code = 3; // 变体物品内部编码，可选。 创建时才有值更新到有规格商品的内部编码
  string item_code = 4; // 多规格物品编码，可选。 调用新增接口才有返回值
}

message UomDetail {
  string uom = 1; // 单位名称，必填
  double conversion_factor = 2; // 转换比率，相对于基准单位
}

message GetUomListReq {
  string branch = 1; // 分支名称，可选
  string company_abbr = 2; // 公司简称，可选
  string uom_name = 3; // 单位名称，可选
  string alias_name = 4; // 单位别名，可选
  string sub_company_abbr = 5; // 门店公司简称，可选。 sub_company_abbr(门店公司简称) ,会过滤  permission rule 下的物品，黑名单优先级高。
}


message GetUomListResp {
  repeated UomInfo uom_list = 1; //单位列表
}

message GetUomReq {
  string uom_name = 1; // 单位名称，必填
}

message GetUomResp {
  UomInfo uom_info = 1; // 单位信息
}

message UomInfo {
  string uom_name = 1; // 单位名称，必填
  string branch = 2; // 分支名称，可选
  string company_abbr = 3; // 公司简称，可选
  string company = 4; // 公司名称，可选
  string alias_name = 5; // 单位别名，可选
  bool must_be_whole_number = 6; // 是否必须为整数
}


message GetAttributeListReq {
  string branch = 1; // 分支名称，可选
  string company_abbr = 2; // 公司简称，可选
  string attribute_name = 3; // 属性名称，可选
  string alias_name = 4; // 属性别名，可选
  string sub_company_abbr = 5; // 门店公司简称，可选。  sub_company_abbr(门店公司简称) ,会过滤  permission rule 下的物品，黑名单优先级高。
}

message AttributeInfo {
  string attribute_name = 1; // 属性名称，必填
  string branch = 2; // 分支名称，可选
  string company = 3; // 公司名称，可选
  string company_abbr = 4; // 公司简称，可选
  string alias_name = 5; // 属性别名，可选
  repeated AttributeValueInfo attribute_value_list = 6; // 属性值列表,可选
}

message AttributeValueInfo {
  string attribute_value = 1; // 属性值，必填
  string abbr = 3; // 属性缩写，必填
}

message GetAttributeListResp {
  repeated AttributeInfo attribute_list = 1; // 属性列表
}

message ItemStock {
  string item_code = 1;      // 物品编码，
  string item_name = 2;      // 物品名称，
  ItemGroup item_group = 3;     // 物品分组，
  string warehouse = 4;      // 仓库名称，
  string stock_uom = 5;      // 库存单位，
  double actual_qty = 6;      // 实际库存数量
  double projected_qty =7 ;  //预估库存
  double reserved_qty_for_pos = 8 ; //销售保留
}


message GetItemStockReq {
  string company_abbr = 1;      // 公司简称，必填
  string branch = 2;      // 分支名称，必填
  string item_code = 3;      // 物品编码，可选
  string item_name = 4;      // 物品名称，可选，模糊查询
  ItemGroup item_group = 5;     // 物品分组，可选
  string warehouse = 6;      // 仓库名称，可选. 不传的话会取 默认名称的仓库库存 (根据公司和分支名取)
}

message GetItemStockResp {
  repeated ItemStock item_stock_list = 1; // 物品库存列表
}

message GetItemReq {
  string item_code = 1; // 物品编码，必填
  string company_abbr = 2; // 公司简称，可选
  string branch = 3; // 分支名称，可选
}

message GetItemResp {
  ItemInfo item_info = 1; // 物品信息
}

message BomInfo {
  string item_code = 1;      // 商品编码，
  string bom_name = 2;      // 商品名称，
  string stock_uom = 4;      // 库存单位，
  double quantity = 5;      // 数量，必填
  bool is_active = 6;      // 是否激活，
  bool is_default = 7;      // 是否默认，
  repeated BomItem items = 8;      // 物品列表，
}

message BomItem {
  string item_code = 1;      // 物品编码，
  string item_name = 2;      // 物品名称，
  double qty = 3;      // 物品数量，
  string uom = 4;      // 物品单位，
}

// Pos 系统中特殊的item ，如 属性/加料
message PosSpecItem {
  string item_name = 1; // 物品名称，必填
  string item_code = 2; // 物品编码，可选，修改时传，必填
  string template_item_code = 3; // 模版物品编码，可选
  string branch = 4; // 分支名称，可选
  string company_abbr = 5; // 公司简称，可选
  bool disabled = 6; // 是否禁用，可选
  string internal_code = 7; // 内部编码，可选
  bool not_for_sale = 8; //是否禁售，可选
  string item_group_name =9; //分组名称
}

message SavePosAttributeReq {
    PosSpecItem item = 1; //属性值， 必填
}

message SavePosAttributeResp{
  ItemInfo item_info = 1; // 物品信息
}

message SavePosAddonReq {
  PosSpecItem item = 1; //属性值， 必填
}

message SavePosAddonResp{
  ItemInfo item_info = 1; // 物品信息
}


message DeleteUomReq {
  string uom =1 ;// 单位名称，必填
}

message DeleteUomResp {
  string uom = 1 ; // 单位名称
}


message DeleteItemReq {
  string item_code = 1; //物品编码，必填
}


message DeleteItemResp {
  string item_code = 1; //物品编码，必填
}


service ItemService {
  // 获取物品列表
  // 输入条件如果未包含company 则会返回全量数据，如需要只显示无company 约束的数据，需要自行过滤结果中 company 为空的数据
  // 参数：查询条件
  // 返回：物品列表，最大9999
  rpc GetItemList(item.GetItemListReq) returns (erp.ResponseInfo);

  // 获取单位列表
  // 输入条件如果未包含company 则会返回全量数据，如需要只显示无company 约束的数据，需要自行过滤结果中 company 为空的数据
  // 参数：查询条件
  // 返回：单位列表
  rpc GetUomList(item.GetUomListReq) returns (erp.ResponseInfo);

  // 根据单位名称获取单个单位信息
  // 参数：单位名称
  // 返回：单位详细信息
  rpc GetUom(item.GetUomReq) returns (erp.ResponseInfo);

  // 添加单位
  // 参数：单位信息
  // 返回：添加结果
  rpc SaveUom(item.UomInfo) returns (erp.ResponseInfo);

  //删除单位
  //
  rpc DeleteUom(item.DeleteUomReq) returns (erp.ResponseInfo);

  // 获取属性列表
  // 参数：查询条件
  // 返回：属性列表和分页信息
  rpc GetAttributeList(item.GetAttributeListReq) returns (erp.ResponseInfo);

  // 添加属性
  // 参数：属性信息
  // 返回：添加结果
  rpc SaveAttribute(item.AttributeInfo) returns (erp.ResponseInfo);

  // 添加商品
  // 参数：商品信息
  // 返回：添加结果 TTPOS 端调用成功后后更新 item_code 到商品/物品信息中
  rpc SaveItem(item.ItemInfo) returns (erp.ResponseInfo);

  // 获取商品库存
  // 参数：查询条件
  // 返回：商品库存列表
  rpc GetItemStock(item.GetItemStockReq) returns (erp.ResponseInfo);

  // 根据物品编码获取单个物品信息
  // 参数：物品编码和可选的公司、分支信息
  // 返回：物品详细信息
  rpc GetItem(item.GetItemReq) returns (erp.ResponseInfo);

  // 删除物品
  // 参数：商品信息
  rpc DeleteItem(item.DeleteItemReq) returns (erp.ResponseInfo);

  // 保存 pos 系统中特殊的item ，如 属性/加料
  rpc SavePosAttribute(item.SavePosAttributeReq) returns (erp.ResponseInfo);

  // 保存 pos 系统中特殊的item ，如 加料
  rpc SavePosAddon(item.SavePosAddonReq) returns (erp.ResponseInfo);
}