syntax = "proto3";

import "erp.proto";

package item;

// Go 包路径配置
option go_package = "ttpos-bmp/app/ttpos-erp/api/item";


message UpdateProductReq {
  string item_code = 1; // 物品编码，必填
  bool not_for_sale = 2; //是否禁售，可选
  string internal_code = 3 ; //内部编码, 可选
  bool disabled =4 ; //是否禁用，可选
  repeated ProductAttribute attributes = 5; //更新规格值
}


message ProductAttribute {
    string attribute = 1; //属性名称, 必填
    string attribute_value = 2; //属性值, 必填
}

message UpdateProductResp {
  string item_code = 1; // 物品编码，必填
  bool not_for_sale = 2; //是否禁售，可选
  string internal_code = 3 ; //内部编码, 可选
  bool disabled =4 ; //是否禁用，可选
  repeated ProductAttribute attributes = 5; //规格值
}


service ProductService {
  // 设置物品是否禁售
  // 参数：物品编码和是否禁售标志
  // 返回：设置结果
  rpc UpdateProduct(UpdateProductReq) returns (erp.ResponseInfo);
}
