// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: manager/admin_user_role.proto

package manager

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminUserRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"自增ID"`                      // 自增ID
	AdminUserId   int32                  `protobuf:"varint,2,opt,name=AdminUserId,proto3" json:"AdminUserId,omitempty" dc:"超管用户ID"`  // 超管用户ID
	RoleId        int32                  `protobuf:"varint,3,opt,name=RoleId,proto3" json:"RoleId,omitempty" dc:"角色ID"`              // 角色ID
	CreateTime    int32                  `protobuf:"varint,4,opt,name=CreateTime,proto3" json:"CreateTime,omitempty" dc:"创建时间（时间戳）"` // 创建时间（时间戳）
	UpdateTime    int32                  `protobuf:"varint,5,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty" dc:"更新时间（时间戳）"` // 更新时间（时间戳）
	DeleteTime    int32                  `protobuf:"varint,6,opt,name=DeleteTime,proto3" json:"DeleteTime,omitempty" dc:"删除时间（时间戳）"` // 删除时间（时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserRole) Reset() {
	*x = AdminUserRole{}
	mi := &file_manager_admin_user_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserRole) ProtoMessage() {}

func (x *AdminUserRole) ProtoReflect() protoreflect.Message {
	mi := &file_manager_admin_user_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserRole.ProtoReflect.Descriptor instead.
func (*AdminUserRole) Descriptor() ([]byte, []int) {
	return file_manager_admin_user_role_proto_rawDescGZIP(), []int{0}
}

func (x *AdminUserRole) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUserRole) GetAdminUserId() int32 {
	if x != nil {
		return x.AdminUserId
	}
	return 0
}

func (x *AdminUserRole) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AdminUserRole) GetCreateTime() int32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *AdminUserRole) GetUpdateTime() int32 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *AdminUserRole) GetDeleteTime() int32 {
	if x != nil {
		return x.DeleteTime
	}
	return 0
}

var File_manager_admin_user_role_proto protoreflect.FileDescriptor

const file_manager_admin_user_role_proto_rawDesc = "" +
	"\n" +
	"\x1dmanager/admin_user_role.proto\x12\amanager\"\xb9\x01\n" +
	"\rAdminUserRole\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\rR\x02Id\x12 \n" +
	"\vAdminUserId\x18\x02 \x01(\x05R\vAdminUserId\x12\x16\n" +
	"\x06RoleId\x18\x03 \x01(\x05R\x06RoleId\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\x04 \x01(\x05R\n" +
	"CreateTime\x12\x1e\n" +
	"\n" +
	"UpdateTime\x18\x05 \x01(\x05R\n" +
	"UpdateTime\x12\x1e\n" +
	"\n" +
	"DeleteTime\x18\x06 \x01(\x05R\n" +
	"DeleteTimeB)Z'ttpos-bmp/app/ttpos-manager/api/managerb\x06proto3"

var (
	file_manager_admin_user_role_proto_rawDescOnce sync.Once
	file_manager_admin_user_role_proto_rawDescData []byte
)

func file_manager_admin_user_role_proto_rawDescGZIP() []byte {
	file_manager_admin_user_role_proto_rawDescOnce.Do(func() {
		file_manager_admin_user_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_admin_user_role_proto_rawDesc), len(file_manager_admin_user_role_proto_rawDesc)))
	})
	return file_manager_admin_user_role_proto_rawDescData
}

var file_manager_admin_user_role_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_manager_admin_user_role_proto_goTypes = []any{
	(*AdminUserRole)(nil), // 0: manager.AdminUserRole
}
var file_manager_admin_user_role_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_manager_admin_user_role_proto_init() }
func file_manager_admin_user_role_proto_init() {
	if File_manager_admin_user_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_admin_user_role_proto_rawDesc), len(file_manager_admin_user_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manager_admin_user_role_proto_goTypes,
		DependencyIndexes: file_manager_admin_user_role_proto_depIdxs,
		MessageInfos:      file_manager_admin_user_role_proto_msgTypes,
	}.Build()
	File_manager_admin_user_role_proto = out.File
	file_manager_admin_user_role_proto_goTypes = nil
	file_manager_admin_user_role_proto_depIdxs = nil
}
