// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: manager/client_version.proto

package manager

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientVersion struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"自增ID"`                                 // 自增ID
	Type           int32                  `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty" dc:"类型： 1收银端,2平板端,3厨显端,4商家后台端,5点餐助手端"` // 类型： 1收银端,2平板端,3厨显端,4商家后台端,5点餐助手端
	Brand          int32                  `protobuf:"varint,3,opt,name=Brand,proto3" json:"Brand,omitempty" dc:"品牌"`                             // 品牌
	IsPublish      int32                  `protobuf:"varint,4,opt,name=IsPublish,proto3" json:"IsPublish,omitempty" dc:"是否发布 0-否 1-是"`           // 是否发布 0-否 1-是
	Md5Hash        string                 `protobuf:"bytes,5,opt,name=Md5Hash,proto3" json:"Md5Hash,omitempty" dc:"谷歌云 md5-hash 值"`              // 谷歌云 md5-hash 值
	DownloadNum    int32                  `protobuf:"varint,6,opt,name=DownloadNum,proto3" json:"DownloadNum,omitempty" dc:"下载数量"`               // 下载数量
	VersionNumber  string                 `protobuf:"bytes,7,opt,name=VersionNumber,proto3" json:"VersionNumber,omitempty" dc:"版本号"`             // 版本号
	VersionName    string                 `protobuf:"bytes,8,opt,name=VersionName,proto3" json:"VersionName,omitempty" dc:"版本名称"`                // 版本名称
	ApkVersionCode string                 `protobuf:"bytes,9,opt,name=ApkVersionCode,proto3" json:"ApkVersionCode,omitempty" dc:"Apk版本code"`     // Apk版本code
	ApkData        string                 `protobuf:"bytes,10,opt,name=ApkData,proto3" json:"ApkData,omitempty" dc:"apk数据"`                      // apk数据
	ForcedUpdate   int32                  `protobuf:"varint,11,opt,name=ForcedUpdate,proto3" json:"ForcedUpdate,omitempty" dc:"强制更新 0否 1是"`      // 强制更新 0否 1是
	PackageUrl     string                 `protobuf:"bytes,12,opt,name=PackageUrl,proto3" json:"PackageUrl,omitempty" dc:"包地址"`                  // 包地址
	OriginalName   string                 `protobuf:"bytes,13,opt,name=OriginalName,proto3" json:"OriginalName,omitempty" dc:"文件原名称"`            // 文件原名称
	UpdateLog      string                 `protobuf:"bytes,14,opt,name=UpdateLog,proto3" json:"UpdateLog,omitempty" dc:"更新日志"`                   // 更新日志
	CreateTime     int32                  `protobuf:"varint,15,opt,name=CreateTime,proto3" json:"CreateTime,omitempty" dc:"创建时间（时间戳）"`           // 创建时间（时间戳）
	UpdateTime     int32                  `protobuf:"varint,16,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty" dc:"更新时间（时间戳）"`           // 更新时间（时间戳）
	DeleteTime     int32                  `protobuf:"varint,17,opt,name=DeleteTime,proto3" json:"DeleteTime,omitempty" dc:"删除时间（时间戳）"`           // 删除时间（时间戳）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientVersion) Reset() {
	*x = ClientVersion{}
	mi := &file_manager_client_version_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientVersion) ProtoMessage() {}

func (x *ClientVersion) ProtoReflect() protoreflect.Message {
	mi := &file_manager_client_version_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientVersion.ProtoReflect.Descriptor instead.
func (*ClientVersion) Descriptor() ([]byte, []int) {
	return file_manager_client_version_proto_rawDescGZIP(), []int{0}
}

func (x *ClientVersion) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientVersion) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ClientVersion) GetBrand() int32 {
	if x != nil {
		return x.Brand
	}
	return 0
}

func (x *ClientVersion) GetIsPublish() int32 {
	if x != nil {
		return x.IsPublish
	}
	return 0
}

func (x *ClientVersion) GetMd5Hash() string {
	if x != nil {
		return x.Md5Hash
	}
	return ""
}

func (x *ClientVersion) GetDownloadNum() int32 {
	if x != nil {
		return x.DownloadNum
	}
	return 0
}

func (x *ClientVersion) GetVersionNumber() string {
	if x != nil {
		return x.VersionNumber
	}
	return ""
}

func (x *ClientVersion) GetVersionName() string {
	if x != nil {
		return x.VersionName
	}
	return ""
}

func (x *ClientVersion) GetApkVersionCode() string {
	if x != nil {
		return x.ApkVersionCode
	}
	return ""
}

func (x *ClientVersion) GetApkData() string {
	if x != nil {
		return x.ApkData
	}
	return ""
}

func (x *ClientVersion) GetForcedUpdate() int32 {
	if x != nil {
		return x.ForcedUpdate
	}
	return 0
}

func (x *ClientVersion) GetPackageUrl() string {
	if x != nil {
		return x.PackageUrl
	}
	return ""
}

func (x *ClientVersion) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *ClientVersion) GetUpdateLog() string {
	if x != nil {
		return x.UpdateLog
	}
	return ""
}

func (x *ClientVersion) GetCreateTime() int32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ClientVersion) GetUpdateTime() int32 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *ClientVersion) GetDeleteTime() int32 {
	if x != nil {
		return x.DeleteTime
	}
	return 0
}

var File_manager_client_version_proto protoreflect.FileDescriptor

const file_manager_client_version_proto_rawDesc = "" +
	"\n" +
	"\x1cmanager/client_version.proto\x12\amanager\"\x93\x04\n" +
	"\rClientVersion\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\rR\x02Id\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\x05R\x04Type\x12\x14\n" +
	"\x05Brand\x18\x03 \x01(\x05R\x05Brand\x12\x1c\n" +
	"\tIsPublish\x18\x04 \x01(\x05R\tIsPublish\x12\x18\n" +
	"\aMd5Hash\x18\x05 \x01(\tR\aMd5Hash\x12 \n" +
	"\vDownloadNum\x18\x06 \x01(\x05R\vDownloadNum\x12$\n" +
	"\rVersionNumber\x18\a \x01(\tR\rVersionNumber\x12 \n" +
	"\vVersionName\x18\b \x01(\tR\vVersionName\x12&\n" +
	"\x0eApkVersionCode\x18\t \x01(\tR\x0eApkVersionCode\x12\x18\n" +
	"\aApkData\x18\n" +
	" \x01(\tR\aApkData\x12\"\n" +
	"\fForcedUpdate\x18\v \x01(\x05R\fForcedUpdate\x12\x1e\n" +
	"\n" +
	"PackageUrl\x18\f \x01(\tR\n" +
	"PackageUrl\x12\"\n" +
	"\fOriginalName\x18\r \x01(\tR\fOriginalName\x12\x1c\n" +
	"\tUpdateLog\x18\x0e \x01(\tR\tUpdateLog\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\x0f \x01(\x05R\n" +
	"CreateTime\x12\x1e\n" +
	"\n" +
	"UpdateTime\x18\x10 \x01(\x05R\n" +
	"UpdateTime\x12\x1e\n" +
	"\n" +
	"DeleteTime\x18\x11 \x01(\x05R\n" +
	"DeleteTimeB)Z'ttpos-bmp/app/ttpos-manager/api/managerb\x06proto3"

var (
	file_manager_client_version_proto_rawDescOnce sync.Once
	file_manager_client_version_proto_rawDescData []byte
)

func file_manager_client_version_proto_rawDescGZIP() []byte {
	file_manager_client_version_proto_rawDescOnce.Do(func() {
		file_manager_client_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_client_version_proto_rawDesc), len(file_manager_client_version_proto_rawDesc)))
	})
	return file_manager_client_version_proto_rawDescData
}

var file_manager_client_version_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_manager_client_version_proto_goTypes = []any{
	(*ClientVersion)(nil), // 0: manager.ClientVersion
}
var file_manager_client_version_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_manager_client_version_proto_init() }
func file_manager_client_version_proto_init() {
	if File_manager_client_version_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_client_version_proto_rawDesc), len(file_manager_client_version_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manager_client_version_proto_goTypes,
		DependencyIndexes: file_manager_client_version_proto_depIdxs,
		MessageInfos:      file_manager_client_version_proto_msgTypes,
	}.Build()
	File_manager_client_version_proto = out.File
	file_manager_client_version_proto_goTypes = nil
	file_manager_client_version_proto_depIdxs = nil
}
