// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: manager/migrations.proto

package manager

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Migrations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`            //
	MigrationName string                 `protobuf:"bytes,2,opt,name=MigrationName,proto3" json:"MigrationName,omitempty"` //
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`         //
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=EndTime,proto3" json:"EndTime,omitempty"`             //
	Breakpoint    int32                  `protobuf:"varint,5,opt,name=Breakpoint,proto3" json:"Breakpoint,omitempty"`      //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migrations) Reset() {
	*x = Migrations{}
	mi := &file_manager_migrations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migrations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migrations) ProtoMessage() {}

func (x *Migrations) ProtoReflect() protoreflect.Message {
	mi := &file_manager_migrations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migrations.ProtoReflect.Descriptor instead.
func (*Migrations) Descriptor() ([]byte, []int) {
	return file_manager_migrations_proto_rawDescGZIP(), []int{0}
}

func (x *Migrations) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Migrations) GetMigrationName() string {
	if x != nil {
		return x.MigrationName
	}
	return ""
}

func (x *Migrations) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Migrations) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Migrations) GetBreakpoint() int32 {
	if x != nil {
		return x.Breakpoint
	}
	return 0
}

var File_manager_migrations_proto protoreflect.FileDescriptor

const file_manager_migrations_proto_rawDesc = "" +
	"\n" +
	"\x18manager/migrations.proto\x12\amanager\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x01\n" +
	"\n" +
	"Migrations\x12\x18\n" +
	"\aVersion\x18\x01 \x01(\x03R\aVersion\x12$\n" +
	"\rMigrationName\x18\x02 \x01(\tR\rMigrationName\x128\n" +
	"\tStartTime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tStartTime\x124\n" +
	"\aEndTime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aEndTime\x12\x1e\n" +
	"\n" +
	"Breakpoint\x18\x05 \x01(\x05R\n" +
	"BreakpointB)Z'ttpos-bmp/app/ttpos-manager/api/managerb\x06proto3"

var (
	file_manager_migrations_proto_rawDescOnce sync.Once
	file_manager_migrations_proto_rawDescData []byte
)

func file_manager_migrations_proto_rawDescGZIP() []byte {
	file_manager_migrations_proto_rawDescOnce.Do(func() {
		file_manager_migrations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_migrations_proto_rawDesc), len(file_manager_migrations_proto_rawDesc)))
	})
	return file_manager_migrations_proto_rawDescData
}

var file_manager_migrations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_manager_migrations_proto_goTypes = []any{
	(*Migrations)(nil),            // 0: manager.Migrations
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_manager_migrations_proto_depIdxs = []int32{
	1, // 0: manager.Migrations.StartTime:type_name -> google.protobuf.Timestamp
	1, // 1: manager.Migrations.EndTime:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_manager_migrations_proto_init() }
func file_manager_migrations_proto_init() {
	if File_manager_migrations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_migrations_proto_rawDesc), len(file_manager_migrations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manager_migrations_proto_goTypes,
		DependencyIndexes: file_manager_migrations_proto_depIdxs,
		MessageInfos:      file_manager_migrations_proto_msgTypes,
	}.Build()
	File_manager_migrations_proto = out.File
	file_manager_migrations_proto_goTypes = nil
	file_manager_migrations_proto_depIdxs = nil
}
