// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: manager/upload_group.proto

package manager

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint32                 `protobuf:"varint,1,opt,name=GroupId,proto3" json:"GroupId,omitempty" dc:"自增ID"`            // 自增ID
	GroupType     string                 `protobuf:"bytes,2,opt,name=GroupType,proto3" json:"GroupType,omitempty" dc:"文件类型"`         // 文件类型
	GroupName     string                 `protobuf:"bytes,3,opt,name=GroupName,proto3" json:"GroupName,omitempty" dc:"分类名称"`         // 分类名称
	Sort          uint32                 `protobuf:"varint,4,opt,name=Sort,proto3" json:"Sort,omitempty" dc:"分类排序(数字越小越靠前)"`         // 分类排序(数字越小越靠前)
	CreateTime    int32                  `protobuf:"varint,5,opt,name=CreateTime,proto3" json:"CreateTime,omitempty" dc:"创建时间（时间戳）"` // 创建时间（时间戳）
	UpdateTime    int32                  `protobuf:"varint,6,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty" dc:"更新时间（时间戳）"` // 更新时间（时间戳）
	DeleteTime    int32                  `protobuf:"varint,7,opt,name=DeleteTime,proto3" json:"DeleteTime,omitempty" dc:"删除时间（时间戳）"` // 删除时间（时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadGroup) Reset() {
	*x = UploadGroup{}
	mi := &file_manager_upload_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadGroup) ProtoMessage() {}

func (x *UploadGroup) ProtoReflect() protoreflect.Message {
	mi := &file_manager_upload_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadGroup.ProtoReflect.Descriptor instead.
func (*UploadGroup) Descriptor() ([]byte, []int) {
	return file_manager_upload_group_proto_rawDescGZIP(), []int{0}
}

func (x *UploadGroup) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UploadGroup) GetGroupType() string {
	if x != nil {
		return x.GroupType
	}
	return ""
}

func (x *UploadGroup) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *UploadGroup) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UploadGroup) GetCreateTime() int32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UploadGroup) GetUpdateTime() int32 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *UploadGroup) GetDeleteTime() int32 {
	if x != nil {
		return x.DeleteTime
	}
	return 0
}

var File_manager_upload_group_proto protoreflect.FileDescriptor

const file_manager_upload_group_proto_rawDesc = "" +
	"\n" +
	"\x1amanager/upload_group.proto\x12\amanager\"\xd7\x01\n" +
	"\vUploadGroup\x12\x18\n" +
	"\aGroupId\x18\x01 \x01(\rR\aGroupId\x12\x1c\n" +
	"\tGroupType\x18\x02 \x01(\tR\tGroupType\x12\x1c\n" +
	"\tGroupName\x18\x03 \x01(\tR\tGroupName\x12\x12\n" +
	"\x04Sort\x18\x04 \x01(\rR\x04Sort\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\x05 \x01(\x05R\n" +
	"CreateTime\x12\x1e\n" +
	"\n" +
	"UpdateTime\x18\x06 \x01(\x05R\n" +
	"UpdateTime\x12\x1e\n" +
	"\n" +
	"DeleteTime\x18\a \x01(\x05R\n" +
	"DeleteTimeB)Z'ttpos-bmp/app/ttpos-manager/api/managerb\x06proto3"

var (
	file_manager_upload_group_proto_rawDescOnce sync.Once
	file_manager_upload_group_proto_rawDescData []byte
)

func file_manager_upload_group_proto_rawDescGZIP() []byte {
	file_manager_upload_group_proto_rawDescOnce.Do(func() {
		file_manager_upload_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_upload_group_proto_rawDesc), len(file_manager_upload_group_proto_rawDesc)))
	})
	return file_manager_upload_group_proto_rawDescData
}

var file_manager_upload_group_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_manager_upload_group_proto_goTypes = []any{
	(*UploadGroup)(nil), // 0: manager.UploadGroup
}
var file_manager_upload_group_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_manager_upload_group_proto_init() }
func file_manager_upload_group_proto_init() {
	if File_manager_upload_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_upload_group_proto_rawDesc), len(file_manager_upload_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manager_upload_group_proto_goTypes,
		DependencyIndexes: file_manager_upload_group_proto_depIdxs,
		MessageInfos:      file_manager_upload_group_proto_msgTypes,
	}.Build()
	File_manager_upload_group_proto = out.File
	file_manager_upload_group_proto_goTypes = nil
	file_manager_upload_group_proto_depIdxs = nil
}
